### ISSUE TITLE
Avformat producer AV sync

### ISSUE THREAD

**Issue by matiaspl** [mltframework/mlt#100]
There's a problem with keeping A+V synchronization on long running live input streams. My input is a multicast UDP MPEG-TS from a decent source (satelite ingest for a big iptv provider, my server is in the same facility). Over 15h video is 1 minute ahead of audio (it's perfectly in sync at the start). On the other hand just playing the stream using ffplay or doing a live transcode with the same version of ffmpeg used for building melt is in perfect sync.

**Comment by ddennedy** [comment]
There is not enough information. What is your version? What is your OS? What are you running in melt (command line)? What is some basic information about "UDP MPEG-TS" stream such as codecs, frame rate, etc.? Why do you use melt instead of ffmpeg?

**Comment by matiaspl** [comment]
melt 0.9.9 (git from 14.02.2016), ffmpeg N-78419-g4099e4a, Ubuntu 14.04 LTS. I'm using command line melt as a signal generator - I want to acheive constant framerate regardless of input stream being on or off. Something like a digital telecine or a video mixer/switcher if you like. 

The workflow: 
- source stream: H264 MP@ML 720p50, MP2 audio 48 kHz UDP multicast
- two tracks: color producer on the bottom track, avformat on top
- avformat producer options: reconnect=1, stimeout=1000000
- raw video+audio output in MKV container piped to ffmpeg for multi bitrate encoding with RTMP delivery

Currently I'm experimenting with additional err_detect and fps=25 filter graph options on input.

**Comment by matiaspl** [comment]
Additional info - I'm using atsc_720p_25 profile. This seems very important, because the melt's frame dropping mechanism is likely to be the source of the problem. Adding -graph=fps=25 keeps the AV sync - no problems after 14 hours. I have now a new a problem with video jitter. Apparently the 50 -> 25 fps conversion using fps avfilter doesn't drop every second frame but does something more evil. Even though the current outcome is more than acceptable. I'll get back to you after my 48hrs test completes. It might be worth mentioning this solution in the wiki.
