### ISSUE TITLE
Frozen frames during playback and render

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#1023]
There is a regression in playback of some Mpeg files, which causes some frozen frames on playback and on render.

We traced down the problem to this commit by @Tjoppen :
https://github.com/mltframework/mlt/commit/c868d5eef34e61cbbc61e43e5f7177e5b1f8b

Issue was reported in this bug report : 
https://bugs.kde.org/show_bug.cgi?id=492692
and we reproduced it locally. 

Reverting this commit fixes the issue and playback is smooth again.
I am not really familiar enough with avformat internals to propose a fix, but 
am willing to help in any possible way.

Thanks

**Comment by ddennedy** [comment]
Fixed in  a6b862589e28
