### ISSUE TITLE
fail to build swig/ruby should be easy to fix , though .

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#104]
```
Building ruby...OK
make[2]: Entering directory '/builddir/build/BUILD/mlt-6.0.0/src/swig/ruby'
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -m64 -o mlt_wrap.o -c mlt_wrap.cxx
mlt_wrap.cxx:2001:23: fatal error: mlt++/Mlt.h: No such file or directory
compilation terminated.

```

Looks to me easy to fix, include should be -I ..

**Comment by ddennedy** [comment]
It does include -I../.. for me. In src/swig/ruby/build, it looks like $CFLAGS should be $CXXFLAGS. Does changing it to that work for you? My version of Ruby mkmf requires using CFLAGS, not CXXFLAGS. I found a Ruby bug related to this:
https://bugs.ruby-lang.org/issues/6504

So, to cover different versions, we need to set both:
```
$CFLAGS = $CFLAGS.to_s + " -I../.. " + (ENV.has_key?('CXXFLAGS')? ENV['CXXFLAGS'] : '')
$CXXFLAGS = $CXXFLAGS.to_s + " -I../.. " + (ENV.has_key?('CXXFLAGS')? ENV['CXXFLAGS'] : '')

```
I changed "+=" to "= ... .to_s" to fix a bug that NilClass does not support += when the var does not exist. Can you test this change with your version, please?

**Comment by sergiomb2** [comment]
In Linux Fedora version 22 and 23, we have ruby-2.2.4  and I remember that starting fail with ruby 2.0
In src/swig/ruby/build 
`+$CXXFLAGS += " -I../.. " + (ENV.has_key?('CXXFLAGS')? ENV['CXXFLAGS'] : '')`
fixed my build

**Comment by sergiomb2** [comment]
I test the commit and works well, 
Thanks .
