### ISSUE TITLE
When I add the movit filter to the.mlt file,melt crashes

### ISSUE THREAD

**Issue by liubailin2017** [mltframework/mlt#1042]
This tracker is for defects only! For feature requests, you can submit a pull
request with the changes.

If you’re reporting a defect, make it as detailed as possible, and include both your operating system and MLT versions (e.g. `macOS 10.16; MLT v7.4.0`).
When I add the movit filter to the.mlt file,melt crash. 
melt 1.mlt  -filter movit.blur -consumer sdl2
1.mlt:
<?xml version="1.0" standalone="no"?>
<mlt LC_NUMERIC="C" version="7.25.0" title="Shotcut version 24.10.14" producer="main_bin">
  <profile description="PAL 4:3 DV or DVD" width="1080" height="1920" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="9" display_aspect_den="16" frame_rate_num="30" frame_rate_den="1" colorspace="709"/>
  <playlist id="main_bin">
    <property name="xml_retain">1</property>
  </playlist>
  <producer id="black" in="00:00:00.000" out="00:00:03.133">
    <property name="length">00:00:03.167</property>
    <property name="eof">pause</property>
    <property name="resource">0</property>
    <property name="aspect_ratio">1</property>
    <property name="mlt_service">color</property>
    <property name="mlt_image_format">rgba</property>
    <property name="set.test_audio">0</property>
  </producer>
  <playlist id="background">
    <entry producer="black" in="00:00:00.000" out="00:00:03.133"/>
  </playlist>
  <chain id="chain0" out="00:00:03.133">
    <property name="length">00:00:03.167</property>
    <property name="eof">pause</property>
    <property name="resource">b.mp4</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="meta.media.nb_streams">2</property>
    <property name="meta.media.0.stream.type">video</property>
    <property name="meta.media.0.stream.frame_rate">30</property>
    <property name="meta.media.0.stream.sample_aspect_ratio">1</property>
    <property name="meta.media.0.codec.width">1260</property>
    <property name="meta.media.0.codec.height">702</property>
    <property name="meta.media.0.codec.rotate">0</property>
    <property name="meta.media.0.codec.pix_fmt">yuv420p</property>
    <property name="meta.media.0.codec.sample_aspect_ratio">0</property>
    <property name="meta.media.0.codec.colorspace">709</property>
    <property name="meta.media.0.codec.name">h264</property>
    <property name="meta.media.0.codec.long_name">H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10</property>
    <property name="meta.media.0.codec.bit_rate">1082104</property>
    <property name="meta.attr.0.stream.handler_name.markup">VideoHandler</property>
    <property name="meta.attr.0.stream.vendor_id.markup">[0][0][0][0]</property>
    <property name="meta.media.1.stream.type">audio</property>
    <property name="meta.media.1.codec.sample_fmt">fltp</property>
    <property name="meta.media.1.codec.sample_rate">48000</property>
    <property name="meta.media.1.codec.channels">2</property>
    <property name="meta.media.1.codec.layout">stereo</property>
    <property name="meta.media.1.codec.name">aac</property>
    <property name="meta.media.1.codec.long_name">AAC (Advanced Audio Coding)</property>
    <property name="meta.media.1.codec.bit_rate">2307</property>
    <property name="meta.attr.1.stream.handler_name.markup">SoundHandler</property>
    <property name="meta.attr.1.stream.vendor_id.markup">[0][0][0][0]</property>
    <property name="meta.attr.major_brand.markup">isom</property>
    <property name="meta.attr.minor_version.markup">512</property>
    <property name="meta.attr.compatible_brands.markup">isomiso2avc1mp41</property>
    <property name="meta.attr.encoder.markup">Lavf58.20.100</property>
    <property name="seekable">1</property>
    <property name="meta.media.sample_aspect_num">1</property>
    <property name="meta.media.sample_aspect_den">1</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="creation_time">2024-07-16T05:54:55</property>
    <property name="vstream">0</property>
    <property name="meta.media.frame_rate_num">30</property>
    <property name="meta.media.frame_rate_den">1</property>
    <property name="meta.media.colorspace">709</property>
    <property name="meta.media.color_trc">2</property>
    <property name="meta.media.has_b_frames">0</property>
    <property name="meta.media.width">1260</property>
    <property name="meta.media.height">702</property>
    <property name="meta.media.aspect_ratio">1</property>
    <property name="meta.media.color_range">mpeg</property>
    <property name="astream">0</property>
    <property name="shotcut:skipConvert">0</property>
    <property name="shotcut:hash">7967aadb1ed288f064fb23523e5298a4</property>
    <property name="ignore_points">0</property>
    <property name="meta.media.top_field_first">0</property>
    <property name="meta.media.progressive">1</property>
    <property name="shotcut:caption">b.mp4</property>
    <property name="xml">was here</property>
  </chain>
  <playlist id="playlist0">
    <property name="shotcut:video">1</property>
    <property name="shotcut:name">V1</property>
    <entry producer="chain0" in="00:00:00.000" out="00:00:03.133"/>
  </playlist>
  <tractor id="tractor0" title="Shotcut version 24.10.14" in="00:00:00.000" out="00:00:03.133">
    <property name="shotcut">1</property>
    <property name="shotcut:projectAudioChannels">2</property>
    <property name="shotcut:projectFolder">0</property>
    <property name="shotcut:skipConvert">0</property>
    <track producer="background"/>
    <track producer="playlist0"/>
    <transition id="transition0">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition1">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">movit.overlay</property>
      <property name="disable">1</property>
    </transition>
  </tractor>
</mlt>

**Comment by ddennedy** [comment]
This is a known limitation at this time: a OpenGL Movit filter attached to a `mlt_tractor` does not work. When it does not crash, it produces garbage video. If you use Shotcut with Settings > GPU Effects turned on, then when you select Timeline > Output and try to add a filter, it hides all of the GPU filters.
