### ISSUE TITLE
Build with explicit --enable-movit diverts kdenlive render to screen

### ISSUE THREAD

**Issue by lukefromdc** [mltframework/mlt#105]
Since at least Summer 2015, any build of MLT where  --enable-movit is used in configuration and Kdenlive is run with Movit enabled diverts Kdenlive rendering from the output file to a window on the screen. Rendering ends when playback ends with a zero byte file.

On the other hand, allowing MLT to autodetect a properly installed Movit install works fine, all the Movit effects will work in kdenlive, and rendering is to the output file with all Movit effects having worked.

This is some kind of issue in the build system where autodetection of Movit does one thing, and explicit specification does something else, something that does not work right at least for Kdenlive.
This is very confusing, no documentation can be found online, I only found this out by accident when disabling VDPAU support (which I used to use) for a test build and accidently also disabling explicit Movit detection. Took until tonight to know what I had really done.

**Comment by ddennedy** [comment]
--enable-movit is ignored by the configure script. I have seen that before in some instructions on the web, but there is nothing in MLT that does anything with that.

**Comment by lukefromdc** [comment]
I just found that in building today using version 6.1.0 this is in fact the case-
now the output is being diverted unconditionally to the screen if Movit is
enabled, will open a new issue for that.  For now I will try to work out what
was happening before with versions 0.9.8 and 0.9.9 and see if I can come 
up with a fix.

**Comment by lukefromdc** [comment]
I just found that disabling all the GPL 3 modules produced a build that enabled
movit with kdenlive and renders to a proper file, I will try to find out which module
is the culprit here. Wonder if this has something to do with VDPAU, which I am
not explicitly enabling but is on my system with all development files so ffmpeg
can build against it. Sorry about the noise, but there is a total lack of documentation
on this anywhere, it took me months to first get kdenlive to work with Movit.

Thanks for answering so quickly and getting me off  a false trail.

**Comment by ddennedy** [comment]
VDPAU integration in MLT must be explicitly enabled, and it actually fails to build against latest versions of FFmpeg. So, it has been removed from the configure script and is no longer supported.
Shotcut official binary builds integrate Movit, MLT from git master, and enables the gpl3 modules; but it does not exhibit this problem. If a screen appears when rendering, then I suspect the qglsl and/or avformat consumers are not available. Both are needed to render with Movit. Run `melt -query consumers` to see which consumers you have.

**Comment by lukefromdc** [comment]
https://github.com/mltframework/mlt/issues/106 describes the results of tonight's test: if GPLv3 is enabled, --avformat-no-vdpau must also be used, at least if VDPAU is on the system. VDPAU is supported on my ffmpeg version (2.8.2) and works fine in MPV. 

This seems to be a documentation issue only, as the code works with the right options, in fact works with kdenlive's default of only enabling GPL and not GPLv3. I don't know what is happening when the latter is enabled, maybe broken VDPAU support is breaking avformat?

**Comment by lukefromdc** [comment]
- qglsl did not show up when building with 
`./configure --prefix=/usr --enable-gpl --enable-gpl3 --disable-qt`
When I had KDE4 installed that --disable-qt was needed to prevent both QT4 and QT5 from loading and causing a segfault.

When building with 
`./configure --prefix=/usr --enable-gpl --enable-gpl3`
it worked fine, so maybe with KDE4 going away we are done with this?
