### ISSUE TITLE
Filter timwarp's audio effects is different at breakpoint melt version v7.25.0 from Shotcut release

### ISSUE THREAD

**Issue by myme5261314** [mltframework/mlt#1052]
Here's an example.
Source video is `demo5.mp4`

https://github.com/user-attachments/assets/be2876a7-3db0-478a-8871-d43d38b19df5

Run this command on melt v7.28.0
```bash
melt -track -producer timewarp:5.0:avformat:demo5.mp4 warp_pitch=1 -consumer avformat:linux_demo5_5.0.mp4
```
Here's the result of `linux_demo5_5.0.mp4` (abnormal audio effects)

https://github.com/user-attachments/assets/b15a9f0a-983b-483e-beae-189637a457f0

Run this command on melt v7.25.0 from Shotcut release.
```bash
melt -track -producer timewarp:5.0:avformat:demo5.mp4 warp_pitch=1 -consumer avformat:scut_demo5_5.0.mp4
```
Here's the resut of `scut_demo5_5.0.mp4` (proper normal audio effects)

https://github.com/user-attachments/assets/2c1dfa59-8ed9-4f57-82e8-226804127873

We verified these hints:
1. v7.24.0 and v7.25.0 produces normal audio effects.
2. v7.26.0 and v7.28.0 produces abnormal audio effects.
3. Larger accelerate ratio of timewarp will cause more severe audio effects difference between these versions.

Will you help fix this bug?

**Comment by bmatherly** [comment]
Both of your videos sound "bad" to me. I am not sure why you think one is "proper normal".

Maybe the difference in sound matches a release where we updated the Rubber Band pitch compensation library that we use. I did not check the specific history.

When I run your command, melt gives me the following output:

```
RubberBand: R3Stretcher: WARNING: Unsupported sample rate: 240000
RubberBand: R3Stretcher: Maximum rate is: 192000
```

It appears that a 5x speed up is too much for the pitch library to compensate. As a workaround, you could run the command on your file 2 times, but at 2.5x speed each time for a final total of 5x.

I do not plan to make any changes to try to make the pitch compensation sound better/different at 5x speed.
