### ISSUE TITLE
Melt doesn't seem to respect a given "in frame" on speed adjustments

### ISSUE THREAD

**Issue by apetrynet** [mltframework/mlt#117]
Hi! Please excuse me for double posting this issue. Not sure which one of sourceforge or github's tracker is active. (if not both?)

I'm trying to write an automated system for previewing video clips in a timeline. It works just fine for regular speed video, but I have isssues when using video played back at other speeds. Melt doesn't seem to respect the in frame given in the xml.
I found [this](https://sourceforge.net/p/mlt/bugs/136/) issue, but it doesn't apply to my case as I need to trim away a handle and begin at frame 15. With a speedup of 4 it begins at frame 60 of the file.
I also confirmed the same behavior when doing the same speedup in OpenShot. Both in the program and when using an exported mlt xml.
I've tried timewarp and framebuffer producers both yielding the same result. Here is an example of how I do the speedup:

```
<producer id="ms160_conform_plate_main_v001_ClientSDComp_photojpeg.mov">
  <property name="mlt_service">framebuffer</property>
  <property name="resource">/mnt/data/ms160_conform_plate_main_v001_ClientSDComp_photojpeg.mov?4.0</property>
</producer>
<playlist id="video1">
  <blank length="25"/>
  <entry in="15" out="50" producer="ms160_conform_plate_main_v001_ClientSDComp_photojpeg.mov"/>
</playlist>

```
Am I doing this wrong or is this a bug?
Versions: 0.7.7 (ubuntu12.04) and 6.0.0 (ubuntu 16.04)

Thanks,
-Daniel

**Comment by ddennedy** [comment]
I have not looked into this too deeply, but OpenShot is not a good tool for learning MLT. You are better off using Shotcut or Kdenlive, which are made by MLT developers. You must either specify an in and out on the producer representing the entire duration, or add a length property to the producer that is at least as long as the entry's out + 1 (length = out + 1).

**Comment by apetrynet** [comment]
Hey, Dan!
With your input I managed to figure it out!
I had to set the desired start frame in the producer's "in" attribute and set in="0" in the entry tag.
```
<producer id="ms160_conform_plate_main_v001_ClientSDComp_photojpeg.mov" in="15" out="120">
    <property name="mlt_service">framebuffer</property>
    <property name="resource">/my/path/ms160_conform_plate_main_v001_ClientSDComp_photojpeg.mov?4.0</property>
  </producer>
  <playlist id="video1">
    <blank length="25"/>
    <entry in="0" out="50" producer="ms160_conform_plate_main_v001_ClientSDComp_photojpeg.mov"/>
    <blank length="25"/>
  </playlist>
```

Thank you!

**Comment by poloking** [comment]
I know this is closed. But trying to find a way to help kdenlive do keyframable speed effects. It's a key feature missing from most of the opensource video editors. 

Am I right in thinking the above could be adapted to make that work?

**Comment by ddennedy** [comment]
> Am I right in thinking the above could be adapted to make that work?

The only proper way to support keyframes for speed is to modify src/modules/core/producer_timewarp.c.

The kludgy way to do it is to make a playlist with a bunch of items whose speeds are different and completely manage that playlist outside of MLT.
