### ISSUE TITLE
Build Error on Slackware64 14.2

### ISSUE THREAD

**Issue by slackhead** [mltframework/mlt#118]
I get this error building 6.2.0:

producer_avformat.c: In function ‘producer_get_audio’:
producer_avformat.c:2224:17: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘request_channels’
    codec_context->request_channels = self->audio_index == INT_MAX ? codec_context->channels : *channels;

Would this be connected with ffmpeg version by any chance? I have 3.1.1

**Comment by ddennedy** [comment]
We do nightly builds against FFmpeg git master. So, I think your ffmpeg build config has something to remove a deprecated API that we are still using. Run `ffmpeg -version` at command line to print out the build configuration.

**Comment by slackhead** [comment]
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.0 (GCC)
configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/man --disable-debug --enable-shared --disable-static --enable-pthreads --enable-libtheora --enable-libvorbis --enable-gpl --enable-version3 --enable-postproc --enable-swscale --enable-x11grab --enable-avfilter --enable-gnutls --enable-libcdio --arch=x86_64 --enable-libmp3lame --enable-libfaac --enable-libxvid --enable-libx264 --enable-nonfree --enable-libvpx
libavutil      55. 28.100 / 55. 28.100
libavcodec     57. 48.101 / 57. 48.101
libavformat    57. 41.100 / 57. 41.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 47.100 /  6. 47.100
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  1.100 /  2.  1.100
libpostproc    54.  0.100 / 54.  0.100

**Comment by ddennedy** [comment]
You are not using MLT 6.2.0 because we no longer use AVCodecContext.request_channels.
https://github.com/mltframework/mlt/blob/v6.2.0/src/modules/avformat/producer_avformat.c#L2224

This was fixed a while ago:
https://github.com/mltframework/mlt/commit/6b79e7c79ae67b56284ccca16cde3cac9f2587b6

**Comment by slackhead** [comment]
Oh. I had two source archives and may have got them mixed up when I copied the error. Sorry about that. I have attached an error.log so perhaps you can tell me the problem?
[error.txt](https://github.com/mltframework/mlt/files/372516/error.txt)

Configure options:
                                                                          
./configure \ 
  --disable-debug \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --qimage-libdir=${QT4DIR}/qt/lib \
  --qimage-includedir=${QT4DIR}/qt/include \
  --enable-gpl \ 
  --luma-compress \
  --enable-motion-est \
   --swig-languages="perl php python ruby tcl" \
  --build=$ARCH-slackware-linux

Thanks for your help.

**Comment by bmatherly** [comment]
All your build errors are in vdpau.c. To get it to compile, you could add this to your MLT configuration:
`--avformat-no-vdpau`
Or you would have to dig deeper to find the root cause.

P.S. https://www.mltframework.org/bin/view/MLT/OnlineSupport

**Comment by ddennedy** [comment]
The vdpau option defaults false for a long time now (since Mar 27, 2011) and requires an explicit option to enable it, which is not specified in the configure line above. In fact, that option is no longer supported and was removed from the configure --help output for the latest release. Are you still using really old sources: 0.6.2 instead of 6.2.0? If not, then how did that get turned on? Did you simply extract new sources over the top of old sources and run make?

**Comment by slackhead** [comment]
Sorry, it was a PEBKAC. Works fine now.
