### ISSUE TITLE
'asm' operand has impossible constraints  

### ISSUE THREAD

**Issue by alonepig** [mltframework/mlt#120]
some error show when i make mlt source， i use msys2

./configure --prefix=/home/lsj/build --enable-gpl --disable-decklink --disable-kdenlive --disable-gtk2 --disable-jackrack --disable-frei0r --disable-linsys --disable-opengl --disable-plus --disable-qt --disable-sox --disable-swfdec --disable-vid.stab --disable-resample

make install

cc -c -I../.. -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I../../win32  -o composite_line_yuv_sse2_simple.o composite_line_yuv_sse2_simple.c
composite_line_yuv_sse2_simple.c: In function 'composite_line_yuv_sse2_simple':
composite_line_yuv_sse2_simple.c:113:5: error: 'asm' operand has impossible constraints
     __asm__ volatile
     ^~~~~~~
{standard input}: Assembler messages:
{standard input}:110: Error: bad register name `%xmm9'
{standard input}:111: Error: bad register name `%xmm10'
{standard input}:130: Error: bad register name `%xmm8'
{standard input}:132: Error: bad register name `%xmm8'
{standard input}:134: Error: bad register name `%xmm8'
{standard input}:136: Error: bad register name `%xmm8'
{standard input}:139: Error: bad register name `%xmm8'

**Comment by ryno1234** [comment]
I'm getting this same error. What was your solution?

**Comment by I-am-ET** [comment]
I'm getting this same error. What was your solution?
