### ISSUE TITLE
php 7 support ?

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#125]
Hi, next Fedora version (F25) got php 7.0 , and php module doesn't build , any plans for php 7 ? 

Thanks

**Comment by ddennedy** [comment]
It depends on SWIG, which generates the code. See https://github.com/swig/swig/issues/571

**Comment by sergiomb2** [comment]
Fedora 25 had update swig to 3.0.11 which claims that have php7 support , but mlt still not compile with php7 I added 

`sed -i 's|-php5|-php7|g' src/swig/php/build `

but finish with : 

Building php...../../mlt++/MltProfile.h:65: Warning 314: 'list' is a PHP keyword, renaming to 'c_list' ../../mlt++/MltFrame.h:43: Warning 509: Overloaded method Mlt::Frame::Frame(Mlt::Frame const &) effectively ignored, ../../mlt++/MltFrame.h:42: Warning 509: as it is shadowed by Mlt::Frame::Frame(Mlt::Frame &). ../../mlt++/MltFrame.h:45: Warning 503: Can't wrap 'operator =' unless renamed to a valid identifier. ../../mlt++/MltGeometry.h:62: Warning 509: Overloaded method Mlt::Geometry::fetch(Mlt::GeometryItem *,float) effectively ignored, ../../mlt++/MltGeometry.h:61: Warning 509: as it is shadowed by Mlt::Geometry::fetch(Mlt::GeometryItem &,float). ../../mlt++/MltGeometry.h:65: Warning 509: Overloaded method Mlt::Geometry::insert(Mlt::GeometryItem *) effectively ignored, ../../mlt++/MltGeometry.h:64: Warning 509: as it is shadowed by Mlt::Geometry::insert(Mlt::GeometryItem &). ../../mlt++/MltGeometry.h:71: Warning 509: Overloaded method Mlt::Geometry::next_key(Mlt::GeometryItem *,int) effectively ignored, ../../mlt++/MltGeometry.h:70: Warning 509: as it is shadowed by Mlt::Geometry::next_key(Mlt::GeometryItem &,int). ../../mlt++/MltGeometry.h:73: Warning 509: Overloaded method Mlt::Geometry::prev_key(Mlt::GeometryItem *,int) effectively ignored, ../../mlt++/MltGeometry.h:72: Warning 509: as it is shadowed by Mlt::Geometry::prev_key(Mlt::GeometryItem &,int). ../../mlt++/MltProducer.h:48: Warning 509: Overloaded method Mlt::Producer::Producer(Mlt::Producer *) effectively ignored, ../../mlt++/MltProducer.h:47: Warning 509: as it is shadowed by Mlt::Producer::Producer(Mlt::Producer &). ../../mlt++/MltPlaylist.h:104: Warning 509: Overloaded method Mlt::Playlist::insert_at(int,Mlt::Producer &) effectively ignored, ../../mlt++/MltPlaylist.h:103: Warning 509: as it is shadowed by Mlt::Playlist::insert_at(int,Mlt::Producer *). ../../mlt++/MltPlaylist.h:103: Warning 509: Overloaded method Mlt::Playlist::insert_at(int,Mlt::Producer *,int) effectively ignored, ../../mlt++/MltPlaylist.h:104: Warning 509: as it is shadowed by Mlt::Playlist::insert_at(int,Mlt::Producer &,int). ../../mlt++/MltTractor.h:62: Warning 509: Overloaded method Mlt::Tractor::plant_transition(Mlt::Transition *) effectively ignored, ../../mlt++/MltTractor.h:61: Warning 509: as it is shadowed by Mlt::Tractor::plant_transition(Mlt::Transition &). ../../mlt++/MltTractor.h:61: Warning 509: Overloaded method Mlt::Tractor::plant_transition(Mlt::Transition &,int) effectively ignored, ../../mlt++/MltTractor.h:62: Warning 509: as it is shadowed by Mlt::Tractor::plant_transition(Mlt::Transition *,int). ../../mlt++/MltTractor.h:62: Warning 509: Overloaded method Mlt::Tractor::plant_transition(Mlt::Transition *,int,int) effectively ignored, ../../mlt++/MltTractor.h:61: Warning 509: as it is shadowed by Mlt::Tractor::plant_transition(Mlt::Transition &,int,int). ../../mlt++/MltTractor.h:64: Warning 509: Overloaded method Mlt::Tractor::plant_filter(Mlt::Filter *) effectively ignored, ../../mlt++/MltTractor.h:63: Warning 509: as it is shadowed by Mlt::Tractor::plant_filter(Mlt::Filter &). ../../mlt++/MltTractor.h:63: Warning 509: Overloaded method Mlt::Tractor::plant_filter(Mlt::Filter &,int) effectively ignored, ../../mlt++/MltTractor.h:64: Warning 509: as it is shadowed by Mlt::Tractor::plant_filter(Mlt::Filter *,int). ../../mlt++/MltAnimation.h:42: Warning 503: Can't wrap 'operator =' unless renamed to a valid identifier. g++: error: mlt_wrap.cpp: No such file or directory g++: fatal error: no input files compilation terminated. g++: error: mlt_wrap.o: No such file or directory
Makefile:5: recipe for target 'all' failed
make[1]: Leaving directory '/builddir/build/BUILD/mlt-6.4.1/src/swig'

**Comment by ddennedy** [comment]
Ignore the warnings and just look at the error. Obviously, it not longer writes a mlt_wrap.cpp file. What file does this version of SWIG write? Look yourself; it should be obvious. Then, try changing src/swig/php/build to compile the correct file. You will also need to change the link line.

**Comment by sergiomb2** [comment]
good tip thanks this make it work : 
```
%if 0%{fedora} >= 25
sed -i 's|-php5|-php7|g' src/swig/php/build
sed -i 's|mlt_wrap.cpp|mlt_wrap.cxx|g' src/swig/php/build
%endif
```
