### ISSUE TITLE
How to make a video of a audio and image file

### ISSUE THREAD

**Issue by davidhedlund** [mltframework/mlt#126]
I want to generate video.ogg that display cover.png the whole time audio.ogg is played.

Se this for example: https://www.youtube.com/watch?v=7AKsW57QkJE

How can I do that?

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by ddennedy** [comment]
Use a video editor instead of a development framework.

**Comment by davidhedlund** [comment]
@ddennedy openshot utilize melt.
