### ISSUE TITLE
Rendering webgl to video on a headless server with mlt ?

### ISSUE THREAD

**Issue by misterfresh** [mltframework/mlt#138]
I watched with great interest the video tutorial of shotcut about rendering webgl to video : 

https://www.youtube.com/watch?v=xs3bv1TzkYw

I understand that shotcut is just a GUI on top of the MLT framework. Is it possible to run MLT on a headless server to generate videos from webgl scripts ?

**Comment by ddennedy** [comment]
Yes, on Linux, using xvfb. If your headless server does not have a hardware GPU, then you need to setup llvmpipe, and it will be slow. We only use this tracker for bug; use stackoverflow.com with "mlt" tag for general Q&A.

**Comment by misterfresh** [comment]
Thanks, will try that and will post on stackoverflow if I need further troubleshooting.
