### ISSUE TITLE
webvfx

### ISSUE THREAD

**Issue by awright424** [mltframework/mlt#144]
How can I use webvfx with the current stable version of mlt? I initially was able to use webvfx with melt quite easily around the time when melt was version 0.9.6 or so I believe. I have been banging my head against a wall trying to get it to work with the current version. What would you guys recommend I do? I need to do something very simple which is generate a slideshow from images with the pan animation. Overlay some html/css elements and render to a video file. This is something I had working before so I am not sure what has changed between then and now.

**Comment by awright424** [comment]
downloading shotcut from the wbesite seems to have webvfx built already. I prefer kdenlive as they have the slideshow producer which makes things much easier.

**Comment by ddennedy** [comment]
This is not a bug. You can use melt that comes with Shotcut at Shotcut/Shotcut.app/melt.
