### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by awright424** [mltframework/mlt#145]
I have been trying to find a good example of using javascript with webvfx and mlt. Shotcut itself seems to crash and segfault when doing the simplest things and kdenlive has no webvfx built in. What is the easiest way for me to add webvfx to a mlt produced by kdenlive then? If I could see working examples of how javacript works that would be helpful. The tutorials that you guys have on youtube did not much to clarify on using html and javascript.

**Comment by ddennedy** [comment]
You really expect to get much help after being so insulting? Did you even bother following any of the documentation links on the MLT website? Yes, it is documented, listed in the documentation section, and includes examples.

**Comment by awright424** [comment]
I am very much aware of melt and think its great. I have actually been trying to get my company to adpot it for a project. But you seem to be a little butt hurt about a question.
