### ISSUE TITLE
Python bindings for MLT seem to be broken

### ISSUE THREAD

**Issue by jliljebl** [mltframework/mlt#150]
I've been getting reports that starting Flowblade with late versions
of MLT seems to be broken.

The message people are getting is:

ERROR: </path/to/>_mlt.so: undefined symbol: _ZNK3Mlt7Profile8is_validEv

First I thought that it was a question of KDEnlive PPA installing
incompatible MLT in system, but now I tried building Flowblade with
your script from https://www.mltframework.org/docs/buildscripts/ and
I'm getting the same error.

Archlinux also broke after they rolled 6.4 out, 6.2 seems to work.

The cause commit is very likely:

https://github.com/mltframework/mlt/commit/8b6aa7331c63064210b855ac5340931cfc6f339f

as that was pushed between 6.2 and 6.4.

Are Python bindings for Flowblade currently broken for 6.4 and
repository? Do the SWIG definitions need some updating to fix this? If
so, would it be possible for you to fix this and roll out a bug fix
release for 6.4?

I sent this message to mlt-devel mailing list too, we can continue handling this there or here, as you choose.

**Comment by jliljebl** [comment]
I just looked at the mlt.py file created by running script from https://www.mltframework.org/docs/buildscripts/ and the "is_valid" thing is right there in the class Profile(_object)::

    def is_valid(self):
        return _mlt.Profile_is_valid(self)

So SWIG definitions is not the issue because the method is generated. Just as I thought, adding new methods should only require recreating the bindings. 

What else could it be? I can spend time to look for answers if that is of help here.

**Comment by jliljebl** [comment]
I installed Flowblade with  script from https://www.mltframework.org/docs/buildscripts/  to clean a just installed Ubuntu 16.10 running in Virtualbox that had no MLT related programs/libs installed (or anything else, it was just stuff from install .iso - and got the error: 

ERROR: /home/janne/flowblade/20161115/flowblade-trunk/_mlt.so: undefined symbol: _ZNK3Mlt7Profile8is_validEv

so mlt.py has is_Valid but _mlt.so does not, and this is not related to having conflicting versions of MLT installed.

**Comment by ddennedy** [comment]
mlt++.vers is missing " MLTPP_0.9.8;" at the end of the last line. Yes, I can make a 6.4.1 version for this.

**Comment by ddennedy** [comment]
I do not yet understand the reason for the problem.

**Comment by jliljebl** [comment]
I added a line 334 to script build-flowblade.sh:

  REVISIONS[1]="33e56f8560bf225239247dbb6df22cfba660a2d5"

to build MLT with checkouts of different commits to make sure where breakage happens.

Problem is indeed where it was assumed to be:

Commit https://github.com/mltframework/mlt/commit/abdf1d4a8c83269c74a43f7fd1568aeab038cc8b before adding is_valid is GOOD for Python bindings.

Commit https://github.com/mltframework/mlt/commit/1949dcfcce401144a5ffee66ebf20964a9151db5 after adding is_valid() does not compile and gives syntax error:
/usr/bin/ld:mlt++.vers:524: syntax error in VERSION script

Commit https://github.com/mltframework/mlt/commit/33e56f8560bf225239247dbb6df22cfba660a2d5 that fixes the syntax error and compiles is BAD for Python bindings.

**Comment by ddennedy** [comment]
I wonder if removing the #ifdef block here fixes it:
https://github.com/mltframework/mlt/blob/master/src/mlt%2B%2B/MltProfile.h#L26

**Comment by jliljebl** [comment]
It's worth a try, other .h files in mlt++ module don't seem to have it. If you push a patch for that in your master I can easily run build-flowblade.sh and see if it helps.

**Comment by jliljebl** [comment]
I realized that I can change the source repository for MLT in build-flowblade.sh script, I'm now trying to do this "remove ifdef block from Mlt.Profile" using my own MLT fork, let's see if it works.

**Comment by jliljebl** [comment]
I did this commit https://github.com/jliljebl/mlt/commit/c6a653fb44eb45d06b1110ad5d809071287aac34 , and pulled from my own MLT fork, but unfortunately it didn't work, and I still get the same error.

I'll recheck tomorrow that MLT was really from my repo, but I think so, I changed line 306 in build-flowblade.sh to:

  REPOLOCS[1]="git://github.com/jliljebl/mlt.git"

**Comment by jliljebl** [comment]
Thanks for fixing this quickly.
