### ISSUE TITLE
Build fails when using recently released ffmpeg-3.0 with  --avformat-vdpau option

### ISSUE THREAD

**Issue by nic96** [mltframework/mlt#151]
When using the --avformat-vdpau option with a recent version of ffmpeg-3.0 the build fails with the following errors:

`vdpau.c: In function ‘vdpau_get_buffer’:
vdpau.c:162:9: error: ‘AVFrame {aka struct AVFrame}’ has no member named ‘type’
    frame->type = FF_BUFFER_TYPE_USER;
         ^~
vdpau.c:162:18: error: ‘FF_BUFFER_TYPE_USER’ undeclared (first use in this function)
    frame->type = FF_BUFFER_TYPE_USER;
                  ^~~~~~~~~~~~~~~~~~~
vdpau.c:162:18: note: each undeclared identifier is reported only once for each function it appears in
vdpau.c:165:14: error: ‘AVFrame {aka struct AVFrame}’ has no member named ‘reference’
    if ( frame->reference )
              ^~`

**Comment by ddennedy** [comment]
Compiling with vdpau is no longer supported: https://github.com/mltframework/mlt/commit/bb58611e43cd60875d871ededabf656761dc75d4
