### ISSUE TITLE
Intermittent failure to set color_trc in consumer_multi

### ISSUE THREAD

**Issue by ochilan** [mltframework/mlt#153]
I'm observing a problem in MLT (which ultimately showed when using shotcut in my case) which was quite hard to track down since it appears to be nondeterministic (possibly due to threading but I'm not completely sure yet).

In my case, the problem arises when processing a MLT XML exported by shotcut containing a short video clip (MP4 in my case) while GPU processing is active. The symptom is that the colors of the resulting video are sometimes correct and sometimes not, pretty much randomly. Note that it is **not** required to use shotcut to start the actual processing – processing the exported XML using melt directly also causes the problem.

The MLT XML exported this way uses a `movit.overlay service`. This in turn causes MLT to use `filter_movit_convert` and ultimately a `consumer_multi` where the core of the problem appears to be.

The first thing I noticed while debugging the processing chain (which explains the problem with the colors) is that the `getGammaCurve(mlt_properties properties)` function in `filter_movit_convert.cpp` – in my case – sometimes returns `GAMMA_REC_601` (numerical value 2) and sometimes `GAMMA_sRGB` which is the fallback value if the `consumer_color_trc` property of the `properties` parameter is not set.

Digging deeper, the `consumer_color_trc` property is set from the consumer property `color_trc` in `mlt_consumer_get_frame(mlt_consumer self)`. However, at this point the `color_trc` property is _sometimes_ missing. So where is the consumer's `color_trc` property set?

In the `consumer_thread` functor of `consumer_multi`, the consumer's properties are retrieved and subsequently updated using the `foreach_consumer_update` function. Before the `foreach_consumer_update` call, the properties do not contain the `color_trc` property, after the call they sometimes do. Indeed, the `foreach_consumer_update` function contains a loop which explicitly forwards the `color_trc` attribute to nested consumers, as far as I understand.

This however seems to fail randomly such that the resulting properties sometimes contain the `color_trc` property and sometimes not. At this point I couldn't figure out what the underlying problem is, maybe someone who knows the code better than me has an idea? Otherwise I'll try to dig further.

**Comment by ddennedy** [comment]
> However, at this point the `color_trc` property is sometimes missing. So where is the consumer's `color_trc` property set?

It is typically set by the user of the consumer. For example, Shotcut sets its in GPU mode based on Settings > Gamma. However, the avformat consumer also sets it from its `colorspace` property if `color_trc` is not set. The `colorspace` property is defaulted from the mlt_profile, and the user of the consumer can override it by setting the `colorspace` property. So, I think when using the avformat consumer, it should always be set.,

However, the avformat consumer does not set `color_trc` until its `consumer_thread` is started by `mlt_consumer_start()`.

> Indeed, the `foreach_consumer_update` function contains a loop which explicitly forwards the `color_trc` attribute to nested consumers, as far as I understand.

The other way around: `consumer_multi.c : foreach_consumer_update()` copies properties from a nested consumer (e.g., avformat) to itself, which is typically connected to a producer such as a tractor.  `consumer_multi` set its `color_trc` from avformat's `color_tr`, and `mlt_consumer` and `mlt_tractor` are propagating it onto each frame as `consumer_color_trc`.

`consumer_avformat.c : consumer_start()` will return before it gets too far along into its `consumer_thread()` since `pthread_create()` is asynchronous. Then, it is possible for `consumer_multi consumer_thread()` to call `foreach_consumer_update()` before avformat calls `color_trc_from_colorspace()` from its `consumer_thread` - this is a race condition. Does this change fix it?

```
--- src/modules/avformat/consumer_avformat.c
+++ src/modules/avformat/consumer_avformat.c
@@ -368,6 +368,11 @@ static int consumer_start( mlt_consumer consumer )
 		if ( mlt_properties_get( properties, "ar" ) )
 			mlt_properties_set_int( properties, "frequency", mlt_properties_get_int( properties, "ar" ) );
 
+		// Because Movit only reads this on the first frame,
+		// we must do this after properties have been set but before first frame request.
+		if ( !mlt_properties_get( properties, "color_trc") )
+			color_trc_from_colorspace( properties );
+
 		// Assign the thread to properties
 		mlt_properties_set_data( properties, "thread", thread, sizeof( pthread_t ), free, NULL );
 
@@ -1295,11 +1300,6 @@ static void *consumer_thread( void *arg )
 		}
 	}
 
-	// Because Movit only reads this on the first frame,
-	// we must do this after properties have been set but before first frame request.
-	if ( !mlt_properties_get( properties, "color_trc") )
-		color_trc_from_colorspace( properties );
-
 	// Add audio and video streams
 	if ( video_codec_id != AV_CODEC_ID_NONE )
 	{
```

**Comment by ochilan** [comment]
Thank you for the quick response.

The change seems to fix the race condition at least. It is always a bit hard to tell in such cases, but multiple runs seem to yield the same result now. However, it is the result with the wrong colors in the resulting video, but maybe this is to be expected as it is now? I'm using BT.601 source material and 601 color space in shotcut, but the `color_trc` property is now (consistently) unset in the consumer's propertries (instead of being set from the colorspace I guess).

I have to admit, the color space conversions confuse me, but what I can tell is that it is now consistent but wrong in my setting. The result was correct before whenever the `color_trc` was (with some luck) set to BT601 (whenever `color_trc_from_colorspace` was called early enough?).

**Comment by ochilan** [comment]
I should add: I'm using source material in BT601 color space with _full_ color range since this seemed to work best with GPU processing so far (but the results now turned out to be inconsistent after all, so I'm not sure anymore). When _not_ using GPU processing in shotcut, the resulting colors actually look fine. So maybe this (now consistent) difference in color when using or not using GPU processing possibly is a separate issue. I'm also not sure where the distinction between full or partial color range in the source material comes into play. If it helps, I could provide sample material with color test images in MP4s with different formats and some info which combinations work or don't work for me. That said, the situation is further complicated due to the fact that different video players show colors differently, and the settings of the video players (e.g. using GPU acceleration for colorspace conversions) also change the way colors look. :\ So far, mplayer seemed to be the most consistent, but like I said, I'm really confused by the colorspace conversions.

**Comment by ddennedy** [comment]
> I'm using BT.601 source material and 601 color space in shotcut, but the color_trc property is now (consistently) unset in the consumer's propertries (instead of being set from the colorspace I guess).

I am not reproducing that. After this change, by adding some logging, I now consistently see `color_trc` picked up from the nested avformat consumer in consumer_multi.c and property `consumer_color_trc` consistently set in filter_movit_convert.cpp.

> I'm using source material in BT601 color space with full color range

I want to leave full range out of this for now; this is about color_trc. For full range, you also need to set color_range on the consumer: 200bc5a. I will leave it at that for now.

**Comment by ddennedy** [comment]
Reopen if you can provide more info/steps about how to reproduce color_trc not getting set.

**Comment by ochilan** [comment]
Nevermind, I think it was my fault that I didn't see the color_trc being set now. I will re-check tomorrow, but I'm pretty sure it will work fine. Sorry for the confusion and thank you.
