### ISSUE TITLE
[BUG?] glibc: double free or corruption

### ISSUE THREAD

**Issue by iglosiggio** [mltframework/mlt#155]
I'm currently working on a basic stopmotion application and planned using mlt (currently using melt commandline) for rendering the videos, but when i generated a big example ~1000 photos it just crashed saying that melt intended to do a double free.

```
alumno@huayra:~/conectar/github/huayra-stopmotion$ time melt test.mlt -consumer avformat:lossless.mp4 properties=/lossless/H.264
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
*** Error in `melt': double free or corruption (!prev): 0x000000004c155c00 ***
Abortado

real	1m39.704s
user	0m35.884s
sys	0m2.892s
``` 

~Based on the time it took to excecute i think it at least loaded all the photos (or crashed trying to load the last ones)~ **looking at the debug output seems like it failed reading the last ones**

## Attachments

* [test.mlt](https://github.com/mltframework/mlt/files/649657/test.mltxml.txt): my test file, the photos are ~1.4GB
* [melt.strace.txt](https://github.com/mltframework/mlt/files/649698/melt.strace.txt) an strace output w/o the `read` syscall (those are like ~33Mb more on this file)
* [melt.debug](https://github.com/mltframework/mlt/files/649713/melt.debug.txt) an stderr output with the `-debug` flag

**Comment by ddennedy** [comment]
This (a separate producer for each image) is not a good way to do image sequences in mlt because that requires a separate mlt_producer object in memory for each frame. You should do something like "folder/.all.png" or "prefix-%04d.png" as documented here: https://www.mltframework.org/plugins/ProducerPixbuf/

**Comment by iglosiggio** [comment]
Thanks! I will try it today.

Do you think the error is caused by the memory restrictions of my computer?

**Comment by iglosiggio** [comment]
@ddennedy: I tried it now and melt doesn't crash (but skips a lot of frames when displaying on the default sdl output).

Wouldn't be great to have this advise on the avformat producer? I didn't think that the gdk-pixbuf and qtimage had those functionalities.

Anyways thanks for the help!

**Comment by ddennedy** [comment]
I know MLT does not have robust out-of-memory handling, which is partly why this is not closed. The other is that my Linux workstation got really hosed up last night and unresponsive for hours when trying to test this with a folder of ~27000 images. Which, prevented me to continue to debug a memory issue with a smaller subset. :-)

If you do not specify a producer, it does not always use the avformat producer. In fact, for most image files that have a known filename extension, it can use pixbuf or qimage. Thus, it is not necessarily obvious to note something about those two producers in the page for avformat. avformat as well can [read image sequences](https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence#Making_a_video_from_an_Image_Sequence) using something similar as a scanf pattern. However, avformat is lower priority than pixbuf and qimage for files with known, popular, image filename extensions. You can preface the filename specification with "avformat:" to designate a producer and try it as well.

> skips a lot of frames when displaying on the default sdl output

Yes, it does, particularly with PNG, which is slow. TGA is fast by comparison. Consumer sdl by default does video frame-dropping to try to simulate real time. You can set real_time=-1 on the consumer to turn that off.

**Comment by iglosiggio** [comment]
Thanks a lot for the responses! You cleared many of my doubts with mlt.

**Comment by ddennedy** [comment]
I am glad I continued to look into this deeper. It revealed a hard-coded array size deep in the framework code that effectively limited playlists to 1000 items. I had to make it dynamically resize. The previously described image sequence support avoids the issue by not creating bloated playlists.
