### ISSUE TITLE
Melt is not robust to malformed input file

### ISSUE THREAD

**Issue by alcinos** [mltframework/mlt#165]
I've came accross several instances of melt xmi files that cause an outright segfault or cause a 100% usage of the cpu for infinite amount of time.

This can be a concern, especially if one tries to playback files that come from an untrusted source.
It can also hint at some deficiency in the parsing process that may affects even regular users.

One such example can be found here : https://gist.github.com/alcinos/905f3134941dabd1c34009064563d502. It causes a segfault at parsing time due to a weird xml property.
The crash happens for me on a call to strdup, but preliminary inspection with valgrind seems to show that memory corruption happen during the xml phase.

I have a few more samples like this, triggering different bugs, let me know if you want me to post them.

**Comment by ddennedy** [comment]
No longer reproduces and instead shows errors like:
```
[producer_xml] parse fatal: Specification mandates value for attribute f
	row: 3	col: 190
[producer_xml] parse fatal: attributes construct error
	row: 3	col: 190
[producer_xml] parse fatal: error parsing attribute name
	row: 3	col: 190
[producer_xml] parse fatal: attributes construct error
	row: 3	col: 190
[producer_xml] parse fatal: xmlParseStartTag: problem parsing attributes
	row: 3	col: 190
[producer_xml] parse fatal: Couldn't find end of Start Tag profile line 3
	row: 3	col: 190
Failed to load "test.mlt"
```
