### ISSUE TITLE
cutting video in real time

### ISSUE THREAD

**Issue by hery84** [mltframework/mlt#167]
It's possible to cut a video while it's being updated?

example:

BlackMagic (input) > melt or Shotcut (export file) > file.mp4

can i cut file.mp4 while the file is being recorded without stopping export?

melt file.mp4 in=30 out=90 

Thx.

**Comment by ddennedy** [comment]
No.
P.S. We only use this Github Issues for bug tracking, not general Q&A. Use the mailing list or StackOverflow for that.
