### ISSUE TITLE
in XML image sequence does not show after 14999 is reached

### ISSUE THREAD

**Issue by markmal** [mltframework/mlt#168]
Example: there are 2864 png files from frm_000000.png to frm_002863.png

XML file that fails - tst-bad.mlt file is
```
<?xml version="1.0" ?>
<mlt>
	<playlist id="Track 1">
		<producer id="p" in="0" length="42960" novdpau="1" out="42959" ttl="15">
			<property name="resource">frm_%06d.png</property>
		</producer>
	</playlist>
</mlt>

```
shows only till frame 14999. After that it shows last image, in this case it is frm_000999.png. Which image will be last depends on ttl value

However XML file without playlist shows full sequence:
tst-good.mlt file is
```
<?xml version="1.0" ?>
<mlt>
		<producer id="p" in="0" length="42960" novdpau="1" out="42959" ttl="15">
			<property name="resource">frm_%06d.png</property>
		</producer>
</mlt>
```
Also, simple command line shows full sequence:
melt -verbose tue3/frm_%06d.png ttl=15 length=42960 novdpau=1 out=42959 in=0

Problem is that XML is generated by another software I cannot modify its structure.

**Comment by ddennedy** [comment]
With these changes you no longer need to supply length and out values if the frame count is > 14999 and you want to use the intrinsic duration computed from the image sequence and MLT ttl property value.

**Comment by markmal** [comment]
Thank you!
