### ISSUE TITLE
HTTP HLS input stream

### ISSUE THREAD

**Issue by miketolkachev** [mltframework/mlt#170]
Hi Dan,
I tried set HLS stream as source
Producer *mProducer =  new Producer(*mProfile, "avformat:http://www.server.com/stream.m3u8");
but i nothing happend.
How i can get http stream?

**Comment by ddennedy** [comment]
If you are using a version after Oct. 30 you are affected by a regression that I just fixed in commit d25ba846d68f2d80a0d3d5a3bd48639784c8f48c
