### ISSUE TITLE
Debian : MLT 0.9.2-2 and Qt 5

### ISSUE THREAD

**Issue by iliasibn** [mltframework/mlt#171]
Hi, 
I'm actually working on BuildOnMe from Dan with MLT and OpenGL and since I updated my Qt from 4 to 5 the function mlt_factory_init() create a segmentation fault. 
Also I had to use some Qt5 OpenGL functions so I can't use use qt 4.8 Compiler anymore. 
I tried to put a Directory in mlt_factory_init("/tmp/project") for exemple, but when i try to manipulate video I still have an error. 
Debian will not upgrade to MLT 6 until Debian 9 so please, help me :)

**Comment by ddennedy** [comment]
We only Github issues for tracking defects, not as a discussion forum. Use the mailing list or stackoverfow for general help. It is well-known basic rule that you cannot use both Qt4 and Qt5 in the same process. That means you need to stick with Qt4 or you need to make your own build of MLT against Qt5.
