### ISSUE TITLE
Multicore

### ISSUE THREAD

**Issue by RapFan89** [mltframework/mlt#179]
Hi there, i need to apply the charcoal effect to a bunch of videos, so here's my bash command:

`melt -filter charcoal in.mp4 -consumer avformat:out.mp4`

but it takes to much time to render it.

I've looked for a way to improve/force the all my core's cpu. So i've tried with `threads=6` parameter, but the time to do render it's the same. Opening htop to view the CPU usage i've noted that only 1 cpu is at 100%, the remaining are free for almost the time.

I've tried with a GUI software like Shotcut, and the result is impressive, the program is able to take at advantage of the full cpu resources. I've looked inside the mlt that shoutcat generated and the thread value is set to 0 (which means self determining mode).  Trying that number on my command seems to not affect nothing.

Can you help me?

OS OpenSUSE 42.2 Kernel 4.4.36-8-defaultl with nouveau
melt installed version 6.2.0
the melt installed inside Shoutcut package 6.5.0

**Comment by ddennedy** [comment]
Add "real_time=-3" after "-consumer" on your command line.
