### ISSUE TITLE
Build MLT with Movit

### ISSUE THREAD

**Issue by grio** [mltframework/mlt#187]
Hi
I have download the lastest source of Movit, build and install it.
I have download the lastest sources of MLT, configure it by
./configure --prefix=/usr --enable-gpl --enable-gpl3 --enable-opengl
build and install.
But I have nothing about movit in /usr/bin/mlt-melt -query consumers
---
consumers:
  - xgl
  - sdi
  - rtaudio
  - cbrts
  - qglsl
  - sdl
  - sdl_audio
  - sdl_preview
  - sdl_still
  - avformat
  - xml
  - decklink
  - multi
  - null
  - blipflash
...
How to check is the MLT can use movit or not?
What is the right parameters for ./configure?
Can someone to explain to me step by step how to make Kdenlive working with GPU?

**Comment by ddennedy** [comment]
Movit provides filters and transitions. So, query for transitions since that list is shorter. Movit effects have a "movit." prefix. No special configure options.

**Comment by grio** [comment]
Yes, thank you **ddennedy**! By **/usr/bin/mlt-melt -query** the movit filters and transitions is detected )
Btw, I have check the GPU box in Kdenlive settings, but not feel the render speed up yet. I suppose this only works in additional video effects, not just a render, isn't it?
