### ISSUE TITLE
OpenGL filters: make install broken

### ISSUE THREAD

**Issue by darix** [mltframework/mlt#203]
I just did the quick and dirty workaround for now. But maybe someone can properly integrate the makefile into the normal build system.

```
Index: mlt-6.4.1/src/modules/opengl/Makefile
===================================================================
--- mlt-6.4.1.orig/src/modules/opengl/Makefile
+++ mlt-6.4.1/src/modules/opengl/Makefile
@@ -68,9 +68,9 @@ clean:
                rm -f $(OBJS) $(TARGET) $(CPPOBJS)
 
 install: all
-       install -m 755 $(TARGET) "$(DESTDIR)$(libdir)/mlt"
-       install -d "$(DESTDIR)$(datadir)/mlt/opengl"
-       install -m 644 *.yml "$(DESTDIR)$(datadir)/mlt/opengl"
+       install -m 755 $(TARGET) "$(DESTDIR)$(libdir)/mlt-6"
+       install -d "$(DESTDIR)$(datadir)/mlt-6/opengl"
+       install -m 644 *.yml "$(DESTDIR)$(datadir)/mlt-6/opengl"
 
 ifneq ($(wildcard .depend),)
 include .depend
```

**Comment by ddennedy** [comment]
That is incorrect and distribution-dependent. Also, it appears that you are installing over the top of a system package, which is really bad.

**Comment by darix** [comment]
Incorrect. I *build* the system package. But so far the openSUSE package didn't have opengl support enabled and the build dies in "make install".

you create a symlink /usr/share/mlt here:

```
Makefile
33:     ln -s "$(moduledir)" "$(DESTDIR)$(unversionedmoduledir)"
38:     ln -s "$(mltdatadir)" "$(DESTDIR)$(unversionedmltdatadir)"
```

While src/modules/opengl/Makefile still assumes /usr/share/mlt to be a directory and tries to create it if it is missing. The install -d commandline dies with "already exists" as it isn't a directory. So when you changed the main Makefile to create the symlinks you didn't adapt the code for versioned directories in src/modules/opengl/Makefile. As such i would kindly ask to reopen this bug.

**Comment by ddennedy** [comment]
Ah, right I see the other modules use "$(DESTDIR)$(mltdatadir)". I just saw the "mlt-6" in your diff and passed.
