### ISSUE TITLE
Vertical slices playing yuv422p10le

### ISSUE THREAD

**Issue by ddennedy** [mltframework/mlt#206]
When I play the following clip with git master as of today, it appears as 3 vertical slices. Can you take a look @max-verem ?
http://www.mediafire.com/file/atzv7jj7b3uvj19/120fps_GoPro_HD3.mov

**Comment by max-verem** [comment]
i discovered it last weekend but planned to submit it in a factorizing of colorspace convertion....
fixes here: https://github.com/mltframework/mlt/pull/207
