### ISSUE TITLE
Melt6 segfaults immediately

### ISSUE THREAD

**Issue by lenscape** [mltframework/mlt#213]
This is a pretty new Opensuse Leap 42.2 set-up but Melt (Melt6) segfaults immediately, even if called with no args.

Opensuse Leap 42.2
libmlt6-6.2.0-1.3.x86_64
melt-6.2.0-1.3.x86_64

Oddly, if I run it in gdb, it runs OK and produces usage help.

```
dale@linux-9blt:~> melt6    
Segmentation fault (core dumped)
dale@linux-9blt:~> gdb melt6
GNU gdb (GDB; openSUSE Leap 42.2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from melt6...Reading symbols from /usr/lib/debug/usr/bin/melt6.debug...done.
done.
(gdb) run
Starting program: /usr/bin/melt6 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-3.7.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Usage: melt6 [options] [producer [name=value]* ]+
Options:
  -attach filter[:arg] [name=value]*       Attach a filter to the output
  -attach-cut filter[:arg] [name=value]*   Attach a filter to a cut
  -attach-track filter[:arg] [name=value]* Attach a filter to a track
  -attach-clip filter[:arg] [name=value]*  Attach a filter to a producer
  -audio-track | -hide-video               Add an audio-only track
  -blank frames                            Add blank silence to a track
  -consumer id[:arg] [name=value]*         Set the consumer (sink)
  -debug                                   Set the logging level to debug
  -filter filter[:arg] [name=value]*       Add a filter to the current track
  -getc                                    Get keyboard input using getc
  -group [name=value]*                     Apply properties repeatedly
  -help                                    Show this message
  -jack                                    Enable JACK transport synchronization
  -join clips                              Join multiple clips into one cut
  -mix length                              Add a mix between the last two cuts
  -mixer transition                        Add a transition to the mix
  -null-track | -hide-track                Add a hidden track
  -profile name                            Set the processing settings
  -progress                                Display progress along with position
  -remove                                  Remove the most recent cut
  -repeat times                            Repeat the last cut
  -query                                   List all of the registered services
  -query "consumers" | "consumer"=id       List consumers or show info about one
  -query "filters" | "filter"=id           List filters or show info about one
  -query "producers" | "producer"=id       List producers or show info about one
  -query "transitions" | "transition"=id   List transitions, show info about one
  -query "profiles" | "profile"=id         List profiles, show info about one
  -query "presets" | "preset"=id           List presets, show info about one
  -query "formats"                         List audio/video formats
  -query "audio_codecs"                    List audio codecs
  -query "video_codecs"                    List video codecs
  -serialise [filename]                    Write the commands to a text file
  -silent                                  Do not display position/transport
  -split relative-frame                    Split the last cut into two cuts
  -swap                                    Rearrange the last two cuts
  -track                                   Add a track
  -transition id[:arg] [name=value]*       Add a transition
  -verbose                                 Set the logging level to verbose
  -version                                 Show the version and copyright
  -video-track | -hide-audio               Add a video-only track
For more help: <http://www.mltframework.org/>
[Inferior 1 (process 8399) exited normally]
Missing separate debuginfos, use: zypper install fontconfig-debuginfo-2.11.1-2.2.x86_64 frei0r-plugins-debuginfo-1.4-8.1.x86_64 fribidi-debuginfo-0.19.2-15.5.x86_64 krb5-
etc... etc...
debuginfo-1.2.8-10.1.x86_64
(gdb) quit
dale@linux-9blt:~>
```
I'm not a developer so this strikes me as odd. How do you debug something that runs OK in the debugger but not by itself?

I am completely unable to work on videos at the moment, which is a bit of a problem!

Thanks for any help with this.

**Comment by walterav1984** [comment]
My guess is that you are trying to run a prebuild melt from the Opensuse repo's by looking at the version number 6.2.0-x, which might miss something? Could you try the 6.4.1 for thumbleweed perhaps, or contact the maintainer of the single click installers?

http://software.opensuse.org/package/melt

Other option is to build your own current git melt version?

https://github.com/mltframework/mlt-scripts/blob/master/build/build-melt.sh

**Comment by ddennedy** [comment]
This is probably a build-related problem. It could happen, for example, because frei0r is built to use OpenCV, which is built to use Qt 4, but the MLT qt module is built to use Qt 5. In the debugger try running with arg "-query" to make it do a little more and enumerate plugins. You can try to remove the MLT modules one at-a-time to see if there is a problematic one. They are usually in something like /usr/lib64/mlt/.

**Comment by lenscape** [comment]
Thank you for these pointers. That was very useful.
I removed all the modules in **/usr/lib64/mlt-6** and that cured the segfault. I then put them back one at a time until the problem returned. The culprit was **libmltfrei0r.so**. As long as I leave that out, we're OK. 
I assume this is linked to the _frei0r-plugins_ filter collection. Some sort of enabling module? It's part of the _libmlt6-modules_ package on Opensuse. I've tried a different version from the Packman repository but that fails in the same way.
I don't really know what to do next. I have a horrible feeling that me trying to build melt isn't likely to be easy - not being a developer.
I guess, as walterav1984 suggested, I should contact the Opensuse maintainers.
Many thanks for all the help.

**Comment by ddennedy** [comment]
Shotcut comes with a standalone (not installed), prebuilt melt. Just run the wrapper script inside of Shotcut.app instead of bin/melt directly. But also please report problem to opensuse.

**Comment by lenscape** [comment]
Many thanks, ddennedy. I reported it to OPensuse and someone quickly pointed out that I shouldn't have installed frei0r-modules. Apparently, they're pre-built into MELT 6?. Once that package was removed and a few things tidied up, everything is working. 
User error, I guess, but not sure how I could know.
I appreciate your help.

**Comment by ddennedy** [comment]
I am not sure what "frei0r-modules" is, but the MLT frei0r module is a bridge to the frei0r plugins. Some distros call the frei0r package "frei0r-plugins". In any case, some apps including melt will let you work without frei0r, but there is a lot of video processing functionality provided by these plugins. If you are using melt command line or you own custom XML, then you will know if you need frei0r because all of those effects start with "frei0r."

**Comment by lenscape** [comment]
My mistake. I meant: **frei0r-plugins**.
So it seems I'm working without those plugins and they're not built into MLT.
I'll go back to Opensuse...
Thanks.
