### ISSUE TITLE
setlocale causing very bad performance on windows

### ISSUE THREAD

**Issue by masuel** [mltframework/mlt#214]
See: https://forum.shotcut.org/t/performance-issues-in-windows/1097

When using shotcut on windows the performance was surprisingly (shockingly) bad. I found that is due to the fact that mlt is calling setlocale() multiple times per frame, and this is very slow on windows.

I made a quick hack to take out the call as it was not actually doing anything in my setup and the performance is now as expected. The patch is here:

https://gist.github.com/anonymous/f8c56bad8d3ba6b4fb66f802602eb308

The difference for my setup was between nearly every frame being late so the "force frame" out path being the only reason frames got displayed and never dropping frames.

This is just provided as a proof of issue not a suggested patch for inclusion, though I will be running with it until an alternative fix is available.

**Comment by ddennedy** [comment]
You should not need to remove all calls to setlocale() such as in mlt_factory_init(), mainly just those in mlt_property.c. We need to figure out if we can make an equivalent of strtod_l() for Windows and define it in src/win32.c.

**Comment by ddennedy** [comment]
This patch might be a clue:
https://code.videolan.org/mstorsjo/docker-buildbots/blob/9662343c537ea13bbb071abd47207b77dff6303b/vlc-winrt/toolchain-arm/patches/libcxx-0001.patch

For _strtod_l():
https://msdn.microsoft.com/en-us/library/kxsfc1ab.aspx

**Comment by ddennedy** [comment]
_strtod_l() and friends requires msvcr100.dll, which is not compatible with the msvcrt.dll used by runtime libs such as libstdc++ and liobgcc. So, I think for Windows we will just make mlt_properties and mlt_property not locale-specific. IOW, mlt_properties_set_lcnumeric() does nothing and the locale param to various mlt_property functions is noop and uses the thread's locale.

**Comment by ddennedy** [comment]
Can you please test the commit 29d0fc7 I made on a branch?

**Comment by masuel** [comment]
OK so that works. 

Running shotcut with mlt from this branch works well. The performance seems on a par with my hack from first glance.

I had some trouble testing it as when running melt.exe from this build it fails an assertion in for getting the audio samples.  Is a known issue? it seems 100% repeatable with all the mlt files that I have made so far from shotcut. If I find a cause I will open a separate issue. 

`
Program received signal SIGFPE, Arithmetic exception.
[Switching to Thread 3928.0x108c]
0x000000006a3dc84b in transition_get_audio (frame_a=0x445b10d0,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at transition_mix.c:166
166             samples_b = MIN( samples_b, MAX_SAMPLES * MAX_CHANNELS / channels_b );
(gdb) (gdb) (gdb) (gdb) bt
#0  0x000000006a3dc84b in transition_get_audio (frame_a=0x445b10d0,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at transition_mix.c:166
#1  0x0000000069ac28d2 in mlt_frame_get_audio (self=0x445b10d0,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at mlt_frame.c:782
#2  0x0000000069addae1 in producer_get_audio (self=0x445afea0,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at mlt_tractor.c:403
#3  0x0000000069ac28d2 in mlt_frame_get_audio (self=0x445afea0,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at mlt_frame.c:782
#4  0x0000000069addae1 in producer_get_audio (self=0x445aef40,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at mlt_tractor.c:403
#5  0x0000000069ac28d2 in mlt_frame_get_audio (self=0x445aef40,
    buffer=0x451afdf0, format=0x445a6710, frequency=0x445a677c,
    channels=0x445a6778, samples=0x451afdfc) at mlt_frame.c:782
#6  0x0000000069ad9322 in consumer_read_ahead_thread (arg=0x3933760)
    at mlt_consumer.c:814
#7  0x000000006494c37a in pthread_create_wrapper ()
   from C:\Projects\Shotcut\libwinpthread-1.dll
`

**Comment by ddennedy** [comment]
It is not a known issue. Does it repeat with melt.exe from a stock Shotcut build?
Are you using the default sdl consumer, something else specified with -consumer, or a consumer defined in the XML? The melt.exe built for Shotcut/Windows is made without support for SDL by defining CFLAGS -DMELT_NOSDL. This is to facilitate running melt as a background child process. As such, it is unsuitable to use as a command line MLT viewer. The idea is that you should use Shotcut to view MLT compositions.

**Comment by stykus666** [comment]
Hi, I know it might sound like a stupid question, and its been a while since you posted here, but could you explain how to use this patch? What should I do after I've downloaded it?
