### ISSUE TITLE
Kdenlive crashes upon adding a .wtv (Windows Media Center) file

### ISSUE THREAD

**Issue by bsilvern** [mltframework/mlt#220]
Kdenlive devs believe problem to be in melt.

Please see https://bugs.kde.org/show_bug.cgi?id=364833.

On Linux:
•	Kdenlive 16.12.2 & 17.07.0: crashes upon adding .wtv file
•	melt 6.5.0: Plays the test file OK.

On Windows:
•	Kdenlive 16.12.1: Clip loads with infinite multi-streams created.
•	melt 6.5.0 (supplied with Kdenlive): Crashes immediately. With other .wtv clips I've seen melt loop continuously over a few hundred ms section of the audio with black video.

Sample 2.5 minute video is [available here](https://www.dropbox.com/s/uew9fhuvfu7w4vd/kdenlive_multistream_bug.wtv?dl=0 ). (Please click "No thanks, continue to view").

**Comment by ddennedy** [comment]
The sample provided is working for me using Shotcut 17.03 on Windows, which uses MLT 6.5.0 git from March 2, 2017. I am not in a position to debug how it behaves in Kdenlive, but I can take another look at in gdb on Linux.

**Comment by ddennedy** [comment]
After several tries in Shotcut/Windows, I did reproduce the crash, and the crash report shows the same fail point as the first backtrace in the kdenlive bug report. It is not yet clear what the problem is.

**Comment by bsilvern** [comment]
Kdenlive bug report has been updated.
Thanks for the very prompt response, Dan!
