### ISSUE TITLE
Rendering video from kdenlive with GPU render enabled stuck on 99%

### ISSUE THREAD

**Issue by ekitru** [mltframework/mlt#227]
Currently this problem is reproduses for many users, rendering works, but unable to finish render.
https://forum.kde.org/viewtopic.php?f=272&t=125642&p=374677#p374677

**Comment by ddennedy** [comment]
All developers that use MLT need to contribute and support MLT. There are no longer dedicated MLT developers. As such, the Kdenlive devs will need to debug this.

**Comment by ekitru** [comment]
I see. 
Is is well known issue for other devs?

**Comment by DGxInfinitY** [comment]
A work around from what I can tell is to disable multicore rendering when using libmovit, this is a bug with libmovit as far as I can tell, it worked for me and after checking some of the documentation it clearly states: `Do not try to use parallel rendering threads with real_time > 1 or real_time < 1 at this time.`

**Comment by AV11D724** [comment]
I have similar problems(not just this one). This is data that i got from debugging with GDB.  It seems that MLT cannot access opencv libraries. 

`(gdb) run
Starting program: /usr/bin/kdenlive 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7fffde127700 (LWP 26831)]
[New Thread 0x7fffda810700 (LWP 26833)]
[New Thread 0x7fffd099d700 (LWP 26834)]
[New Thread 0x7fffcbfff700 (LWP 26835)]
[New Thread 0x7fffc892e700 (LWP 26838)]
[New Thread 0x7fffa01b2700 (LWP 26862)]
mlt_repository_init: failed to dlopen /usr/lib/mlt/libmltopencv.so
  (/usr/lib/mlt/libmltopencv.so: undefined symbol: _ZN2cv7Tracker4initERKNS_3MatERKNS_5Rect_IdEE)
[New Thread 0x7fff9a3fe700 (LWP 26932)]
[New Thread 0x7fff98ffd700 (LWP 26933)]
[New Thread 0x7fff93fff700 (LWP 26934)]
[New Thread 0x7fff91c3f700 (LWP 26937)]
[Thread 0x7fff91c3f700 (LWP 26937) exited]
[New Thread 0x7fff91c3f700 (LWP 26938)]
[New Thread 0x7fff9143e700 (LWP 26939)]
[New Thread 0x7fff909fa700 (LWP 26942)]
[New Thread 0x7fff87cec700 (LWP 26947)]
[New Thread 0x7fff872b8700 (LWP 26948)]
[New Thread 0x7fff84c5d700 (LWP 26956)]
[New Thread 0x7fff5a82b700 (LWP 26957)]
[New Thread 0x7fff58e60700 (LWP 26958)]
[Thread 0x7fff58e60700 (LWP 26958) exited]
[Thread 0x7fff91c3f700 (LWP 26938) exited]
[Thread 0x7fff5a82b700 (LWP 26957) exited]
[Thread 0x7fff87cec700 (LWP 26947) exited]
[New Thread 0x7fff87cec700 (LWP 27048)]
[Thread 0x7fff87cec700 (LWP 27048) exited]
[New Thread 0x7fff87cec700 (LWP 27049)]
[New Thread 0x7fff5a82b700 (LWP 27053)]
[New Thread 0x7fff91c3f700 (LWP 27055)]
[Thread 0x7fff87cec700 (LWP 27049) exited]
[Thread 0x7fff91c3f700 (LWP 27055) exited]
[New Thread 0x7fff91c3f700 (LWP 27058)]
[Thread 0x7fff91c3f700 (LWP 27058) exited]
[New Thread 0x7fff91c3f700 (LWP 27059)]
[Thread 0x7fff5a82b700 (LWP 27053) exited]
[New Thread 0x7fff5a82b700 (LWP 27060)]
[New Thread 0x7fff87cec700 (LWP 27061)]
[New Thread 0x7fff58e60700 (LWP 27062)]
[Thread 0x7fff58e60700 (LWP 27062) exited]
[Thread 0x7fff91c3f700 (LWP 27059) exited]
[Thread 0x7fff87cec700 (LWP 27061) exited]
[New Thread 0x7fff87cec700 (LWP 27090)]
[Thread 0x7fff87cec700 (LWP 27090) exited]
[New Thread 0x7fff87cec700 (LWP 27091)]
[Thread 0x7fff5a82b700 (LWP 27060) exited]
[New Thread 0x7fff5a82b700 (LWP 27092)]
[New Thread 0x7fff91c3f700 (LWP 27095)]
[New Thread 0x7fff58e60700 (LWP 27096)]
[Thread 0x7fff58e60700 (LWP 27096) exited]
[Thread 0x7fff87cec700 (LWP 27091) exited]
[Thread 0x7fff91c3f700 (LWP 27095) exited]
[New Thread 0x7fff91c3f700 (LWP 27155)]
[Thread 0x7fff91c3f700 (LWP 27155) exited]
[New Thread 0x7fff91c3f700 (LWP 27156)]
[Thread 0x7fff5a82b700 (LWP 27092) exited]
[New Thread 0x7fff5a82b700 (LWP 27157)]
kdenlive: resource_pool.cpp:577: GLuint movit::ResourcePool::create_vec2_vao(const std::set<int>&, GLuint): Assertion `vao_formats.count(key) == 0' failed.

Thread 36 "RenderThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff5a82b700 (LWP 27157)]
0x00007ffff037f8a0 in raise () from /lib/libc.so.6
`
