### ISSUE TITLE
Linux ProducerConsumer used for upscaling with different decklink profiles buffer overrun

### ISSUE THREAD

**Issue by walterav1984** [mltframework/mlt#230]
When looking for the syntax to upscale a live video feed from "dv_pal_wide" decklink producer to "atsc_720p_50" decklink consumer I found this plugin:

https://www.mltframework.org/plugins/ProducerConsumer/

My guess would be the following syntax, which works however with a lot of framedrops adding real_time=1 or preroll at different places in the command won't improve this:

`melt -profile atsc_720p50 -producer consumer:decklink profile=dv_pal_wide -consumer decklink #or sdl`

The hardware is capable of doing this since the Decklink SDI 4k is a full duplex card and running seperate melt playback/capture instances at the same time works with different profiles without a problem. 

For example if I run a single melt instance to capture the SDI dv_pal_wide and output it as a avformat:rtmp stream, than use a seperate melt instance which feeds on this rtmp stream and sends it to a decklink consumer with 720p profile its working fine without framedrop (however scaling looks like its droping a field).

OS ubuntu 16.04.2 amd64 kernel 4.4.0-72
Decklink drivers 10.8.4 / 10.8.6
Melt vesions 6.0.0 and Shotcut build 1704

**Comment by ddennedy** [comment]
You do not need to do anything but specify your profile. There is auto-normalization to handle differences in frame rate, resolution & aspect ratio, scan mode, field order, audio sample rate, and audio channels. Things not specified through the profile can be specified as consumer properties. You do not need to use the producer consumer. That can be used automatically if you load MLT XML that specifies a profile that is different than a profile you specify in the app.

**Comment by walterav1984** [comment]
Would this be the correct syntax, since it shows white frames and a warning "Profile is not compatible", funny it shows buffer underrun this time.

`melt -profile atsc_720p50 -producer consumer:decklink -consumer decklink #upscaling SD to HD`

**Comment by ddennedy** [comment]
Oh, sorry, I misread your original question and overlooked the decklink->decklink case. Only some special producers like avformat can adjust frame rate. The decklink producer does not, and neither does the ProducerConsumer. MLT does not really do what you are trying to do. Well, you might be able to figure out how to make it work using the MultiConsumer, which is able to do some frame rate conversions, but only output one consumer. However, I am not in the position of time availability to setup a scenario to work out the exact details.

**Comment by walterav1984** [comment]
You're indeed right about avformat which as a producer and consumer can go almost any formate/rate/resolution etc differing from the profile, however decklink to decklink is only working if profile is indeed the same for both consumer and format.

I was in the understanding that scaling/framerate/pixelformat/colourspace etc was always done by a separate processing engine between any producer consumer not related to a specific producer. 

Does this central/separate processing relate to what @max-verem referred to #199 a while ago?

**Comment by ddennedy** [comment]
"separate processing engine" is same as what I said about "auto-normalization", but I just revised it to remove frame rate as that is not included. That is one of the big omissions, but not a big deal for most use cases because avformat producer can handle it as well as some other producers do not really care so much about frame rate.
