### ISSUE TITLE
avformat threads arbitrarily limited to 16

### ISSUE THREAD

**Issue by slowriot** [mltframework/mlt#232]
According to the documentation, in avformat parameters, the max value of threads is 16:
![](https://i.imgur.com/fn5eDgW.png)

This sort of arbitrary limit is very unhelpful when running conversions on high-cpu-count machines; in this case I'm using a 56-core workstation.  There doesn't seem to be any valid reason for a thread limit here, so I suggest it be removed.

**Comment by bmatherly** [comment]
That parameter is provided by FFMpeg/Libav. We just parse it from the options and reflect it in our own metadata.

Here is where FFMpeg sets it:
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/pthread_internal.h#L26

Here is where we read it from FFMpeg
https://github.com/mltframework/mlt/blob/master/src/modules/avformat/factory.c#L214

In reality, its is a "recommended" limit by FFMpeg. I have seen situations where setting it higher can provide better performance. But that isn't always guaranteed - regardless of how many physical cores are in your machine.

Feel free to set it higher than 16. FFMpeg will probably output a warning:
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/pthread.c#L64
