### ISSUE TITLE
Feature request: Filter alphamerge like in Ffmpeg

### ISSUE THREAD

**Issue by andchir** [mltframework/mlt#237]
Ffmpeg have filter **[alphamerge](http://ffmpeg.org/ffmpeg-filters.html#alphamerge)**.
I have not found the posibility to apply the alpha mask (grayscale mask) in Melt. I tried to do it through the transaction and the mixers, but without success.
There is a possibility? If not please implement it. The mask can be video.

**Comment by ddennedy** [comment]
Feature requests are not accepted here.
