### ISSUE TITLE
Failed installation on ubuntu 64bit with sdl

### ISSUE THREAD

**Issue by smac89** [mltframework/mlt#239]
Running `make` produces the following errors:

> consumer_sdl.c: In function ‘consumer_get_dimensions’:
> consumer_sdl.c:919:10: error: ‘SDL_SysWMinfo {aka struct SDL_SysWMinfo}’ has no member named ‘subsystem’
>    if ( wm.subsystem == SDL_SYSWM_X11 )
>           ^
> consumer_sdl.c:919:24: error: ‘SDL_SYSWM_X11’ undeclared (first use in this function)
>    if ( wm.subsystem == SDL_SYSWM_X11 )
>                         ^~~~~~~~~~~~~
> consumer_sdl.c:919:24: note: each undeclared identifier is reported only once for each function it appears in
> consumer_sdl.c:922:4: error: unknown type name ‘Window’
>     Window window = wm.info.x11.window;
>     ^~~~~~
> consumer_sdl.c:922:22: error: ‘SDL_SysWMinfo {aka struct SDL_SysWMinfo}’ has no member named ‘info’
>     Window window = wm.info.x11.window;
>                       ^
> consumer_sdl.c:925:4: error: unknown type name ‘Display’
>     Display *display = wm.info.x11.display;
>     ^~~~~~~
> consumer_sdl.c:925:25: error: ‘SDL_SysWMinfo {aka struct SDL_SysWMinfo}’ has no member named ‘info’
>     Display *display = wm.info.x11.display;
>                          ^
> consumer_sdl.c:928:4: error: unknown type name ‘XWindowAttributes’
>     XWindowAttributes attr;
>     ^~~~~~~~~~~~~~~~~
> consumer_sdl.c:929:4: warning: implicit declaration of function ‘XGetWindowAttributes’ [-Wimplicit-function-declaration]
>     XGetWindowAttributes( display, window, &attr );
>     ^~~~~~~~~~~~~~~~~~~~
> consumer_sdl.c:932:28: error: request for member ‘width’ in something not a structure or union
>     changed = *width != attr.width || *height != attr.height;
>                             ^
> consumer_sdl.c:932:53: error: request for member ‘height’ in something not a structure or union
>     changed = *width != attr.width || *height != attr.height;
>                                                      ^
> consumer_sdl.c:935:17: error: request for member ‘width’ in something not a structure or union
>     *width = attr.width;
>                  ^
> consumer_sdl.c:936:18: error: request for member ‘height’ in something not a structure or union
>     *height = attr.height;

Is there a way to fix this? I have tried installing manually and via brew, but none of them have been able to help me install this library

**Comment by ddennedy** [comment]
There is brew for ubuntu now? This is probably due to you only having SDL2, but MLT is not yet compatible with SDL2 - as already mentioned in #112

**Comment by smac89** [comment]
Nvm, I found the issue. When I had initially tried to install with brew, brew installed sdl from `https://linuxbrew.bintray.com/bottles/sdl-1.2.15.x86_64_linux.bottle.3.tar.gz` and this was the cause of the problems.

I solved this by doing downloading the mlt source and then:

```bash
sudo apt install libsdl1.2-dev
./configure --prefix=$(brew --prefix)/Cellar/mlt/6.4.1 --disable-jackrack --disable-gtk2 --disable-swfdec --enable-gpl
make && make install
brew link mlt
```

Also yes there is brew for Linux here: http://linuxbrew.sh
