### ISSUE TITLE
How Can I use mlt with msvc

### ISSUE THREAD

**Issue by dlyili** [mltframework/mlt#241]
I use mingw to compile mlt ,this success, and I want to use this lib in my windows application(msvc),
this mean I need libmlt++ .lib or   libmlt++ .a , but I found no .lib or .a.
   I use msvc lib to create lib, the command like this: lib /machine:i386 /def:libmlt++.def ,this will create 
libmlt++.lib,  I link with this import lib , howerver, I got some link error, like this:

error LNK2019:  unresolved external symbol __declspec(dllimport) public: __thiscall Mlt::Profile::~Profile(void)

   thanks.

**Comment by ddennedy** [comment]
msvc is not supported. It may be possible, but no one on the team uses it and can help; so, you are on your own.
