### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!

### ISSUE THREAD

**Issue by aWangami** [mltframework/mlt#246]
```
➜  mlt melt video.mp4
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
|1=-10| |2= -5| |3= -2| |4= -1| |5=  0| |6=  1| |7=  2| |8=  5| |9= 10|
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
+---------------------------------------------------------------------+
|               H = back 1 minute,  L = forward 1 minute              |
|                 h = previous frame,  l = next frame                 |
|           g = start of clip, j = next clip, k = previous clip       |
|                0 = restart, q = quit, space = play                  |
+---------------------------------------------------------------------+
2017-07-26 14:29:25.903 melt[9323:3502618] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff86955e7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff9b540cad objc_exception_throw + 48
	2   AppKit                              0x00007fff84b788b1 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4471
	3   libSDL-1.2.0.dylib                  0x000000010ade2e12 QZ_PumpEvents + 337
	4   libSDL-1.2.0.dylib                  0x000000010adc17f9 SDL_PumpEvents + 35
	5   libSDL-1.2.0.dylib                  0x000000010adc182c SDL_PollEvent + 14
	6   libmltsdl.dylib                     0x0000000112237efe video_thread + 1759
	7   libsystem_pthread.dylib             0x00007fff9c03baab _pthread_body + 180
	8   libsystem_pthread.dylib             0x00007fff9c03b9f7 _pthread_body + 0
	9   libsystem_pthread.dylib             0x00007fff9c03b1fd thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    9323 abort      melt video.mp4
```

I install melt from homebrew `brew install mlt` and version is `6.4.1`

```
➜  mlt melt --version
melt 6.4.1
Copyright (C) 2002-2016 Meltytech, LLC
<http://www.mltframework.org/>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
➜  mlt
```

**Comment by anba8005** [comment]
I'm having same issue. Clearly SDL related .... MacOs 10.12.6

0   CoreFoundation                      0x00007fffd3c5c57b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffe8eb51da objc_exception_throw + 48
2   AppKit                              0x00007fffd1e47e82 -[NSApplication(NSEvent)_nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4480
3   libSDL-1.2.0.dylib                  0x000000010e051e12 QZ_PumpEvents + 337
4   libSDL-1.2.0.dylib                  0x000000010e0307f9 SDL_PumpEvents + 35
5   libSDL-1.2.0.dylib                  0x000000010e03082c SDL_PollEvent + 14
6   libmltsdl.dylib                     0x000000010fd2d916 video_thread + 550
7   libsystem_pthread.dylib             0x00007fffe99af93b _pthread_body + 180
8   libsystem_pthread.dylib             0x00007fffe99af887 _pthread_body + 0
9   libsystem_pthread.dylib             0x00007fffe99af08d thread_start + 13

**Comment by antiboredom** [comment]
Anyone have any thoughts about this? Having the same issue.

**Comment by siddharudh** [comment]
Facing exactly same issue.. macOS 10.12.6.. mlt 6.4.1 installed using brew

2017-08-27 11:44:32.270 melt[6294:121454] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7915957b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff8e3b21da objc_exception_throw + 48
	2   AppKit                              0x00007fff77344e82 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4480
	3   libSDL-1.2.0.dylib                  0x0000000104159e12 QZ_PumpEvents + 337
	4   libSDL-1.2.0.dylib                  0x00000001041387f9 SDL_PumpEvents + 35
	5   libSDL-1.2.0.dylib                  0x000000010413882c SDL_PollEvent + 14
	6   libmltsdl.dylib                     0x000000010b256efe video_thread + 1759
	7   libsystem_pthread.dylib             0x00007fff8eeac93b _pthread_body + 180
	8   libsystem_pthread.dylib             0x00007fff8eeac887 _pthread_body + 0
	9   libsystem_pthread.dylib             0x00007fff8eeac08d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by ddennedy** [comment]
I see this too with macports since last macOS upgrade or some other recent change. I noticed this error:

> objc[39984]: Class SDLTranslatorResponder is implemented in both /opt/local/lib/libSDL-1.2.0.dylib (0x1088fbb60) and /opt/local/lib/libSDL2-2.0.0.dylib (0x10d946818). One of the two will be used. Which one is undefined.

I know FFmpeg requires SDL2 now, and it pulled in that dependency. If I move libSDL2-2.0.0.dylib out of the way, then melt fails with

> mlt_repository_init: failed to dlopen /usr/local/lib/mlt/libmltavformat.dylib
  (dlopen(/usr/local/lib/mlt/libmltavformat.dylib, 2): Library not loaded: /opt/local/lib/libSDL2-2.0.0.dylib
  Referenced from: /opt/local/lib/libavcodec.57.dylib
  Reason: image not found)

So, yeah, just like for Qt, it is a bad idea to link different major versions of dependencies, and MLT needs to add support for SDL2 (or replace it with something else).

See also #112

**Comment by ddennedy** [comment]
I started working on a port to SDL2 today.

**Comment by ddennedy** [comment]
I can confirm that adding support for SDL2 resolves the issue, but also this issue may still occur with SDL 1.2 due to trying to process input events on other than the main thread as reported in the error. I could try to fix the older SDL 1.2 code, but I choose to move forward and require SDL2 and deprecate SDL 1.2 support.

**Comment by RJVB** [comment]
Has anyone tried catching and handling the exception "gracefully", out of curiosity?

**Comment by ddennedy** [comment]
The MLT code is C communicating with SDL, which is a C API. There is no exception handling capability here. The proper solution is to use the main thread, which I have in the SDL2 support.

**Comment by RJVB** [comment]
You're right of course about the proper solution, but AFAICS the exception is an ObjC one. It should have been trivial to add a little ObjC file to do the exception handling.

**Comment by eugeneware** [comment]
For others monitoring this thread who use homebrew, who'd like to get this fix in master and install the current version still using homebrew I created a little gist [here](https://gist.github.com/eugeneware/da0bf2520a10d9e016c682e971cb7f1b)

It bumps the version to 6.4.2, so you may wish to edit that to avoid conflicts with future versions.

To install (after downloading mlt.rb to your computer):
```
$ brew uninstall --force mlt
$ brew install ./mlt.rb
```
