### ISSUE TITLE
SDL1 and SDL2 broken in latest release

### ISSUE THREAD

**Issue by ddv2005** [mltframework/mlt#249]
Ubuntu 16.04 x64
SDL1 crashed on playing video with error:
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 724 requests (723 known processed) with 0 events remaining.

SDL2 with fullscreen=1 has no video

**Comment by ddv2005** [comment]
looks like SDL1 crashed because of 
echo "CFLAGS+=-fPIC `sdl-config --cflags`"
removal

**Comment by ddv2005** [comment]
looks like SDL1 crashed because of
echo "CFLAGS+=-fPIC sdl-config --cflags"
removal

**Comment by ddv2005** [comment]
SDL1 issue caused by unsafe multithreaded call of event_handling( producer, consumer ) in melt.c

**Comment by ddennedy** [comment]
I have a fix for SDL 1.2 pending commit while I am looking into SDL2 on Ubuntu. The SDL2 code was developed and tested so far on macOS, and there also fullscreen is not working.

**Comment by ddennedy** [comment]
The SDL 2 fix is going to take some time; so, I pushed the fix for SDL 1.2 in the meantime.

**Comment by ddv2005** [comment]
Thanks a lot

**Comment by ddennedy** [comment]
SDL 2 is working for me after the last commit b0b7dbb including fullscreen.
