### ISSUE TITLE
SDL Audio desync

### ISSUE THREAD

**Issue by ddv2005** [mltframework/mlt#250]
I found that on Ubuntu 16.04 melt have huge audio/video desync ( video about 100-200ms ahead of audio) on all H264/AAC videos. I have tested SDL1/SDL2 and both have an issue. Also I have tested ffplay with SDL2 and it play the same videos in sync.

**Comment by ddennedy** [comment]
Is the problem specific to videos with AAC? AAC codecs have an inherent delay that can be a source of problems. It can help to narrow down the problem by testing with uncompressed audio.

**Comment by ddv2005** [comment]
Ok I will test. But why ffplay works fine? It use the same library and the same SDL2 output.

**Comment by ddv2005** [comment]
I have tested and no change AAC or umcompressed audio. But I found that it happened only when I play 25fps video on 30/29.97/60/59.94 fps profile.

**Comment by ddv2005** [comment]
I have measured delay and it is exactly 200ms
