### ISSUE TITLE
How to solve height or width not divisible by 2 (1240x517)

### ISSUE THREAD

**Issue by rahuldeo2047** [mltframework/mlt#256]
`[libx264 @ 0x7fe07c0c79c0] height not divisible by 2 (1240x517)`
on
`melt file1.avi file2.avi file3.avi file4.avi -consumer avformat:fileOut.avi acodec=libmp3lame vcodec=libx264`
as ffmpeg has following option 
`-vf "scale=trunc(iw/2)*2:trunc(ih/2)*2"` with command

**Comment by ddennedy** [comment]
Use the -profile option. Use `melt -query profiles` to see a list of available profiles.
