### ISSUE TITLE
mlt_image_yuv420p recent changes...

### ISSUE THREAD

**Issue by max-verem** [mltframework/mlt#267]
latest commit to that function seems wrong to me:

https://github.com/mltframework/mlt/commit/dbc75eb5f958cb00718eb0d3aa137886e5fa2c93

could you review it?

**Comment by ddennedy** [comment]
Yeah, I read it as `planes[1] +` . But something is wrong in generate_test_image() that was causing a crash.

**Comment by ddennedy** [comment]
Thanks. I reverted that change and found the root cause of the crash I experienced to require change f583748.
