### ISSUE TITLE
Sound garbled when mono and stereo clips are used in same project

### ISSUE THREAD

**Issue by apienk** [mltframework/mlt#269]
**Steps to reproduce:**

1. Create a project containing clips with both stereo and mono audio.
2. Use `ac=1` to force mono output from AVFormat consumer.
3. Play the rendered file.

**Observed result:**
Audio of the stereo clips is heavily distorted while mono clips are OK.

**Expected result:**
Both types of audio clips are OK.

_Tested version: melt 6.5+git201704252005_

**Comment by ddennedy** [comment]
Reproduced with `melt mono.wav -track stereo.mp3 -transition mix -consumer avformat:test.wav ac=1`. Works OK without "-transition mix"
