### ISSUE TITLE
Multiple audio tracks issue

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#273]
Second track overwrites previous, should mix all audio tracks (audio in video + 1 and 2 soundtrack)
On 2.mp4 time (200-299) second track (music.mp3) disappears
![111111](https://user-images.githubusercontent.com/17032489/33287328-0af97292-d3c1-11e7-89d6-223c35fa9fb6.png)
```
melt
1.mp4" -mix 7 -mixer luma
"2.mp4" -mix 7 -mixer luma  
"3.mp4" -mix 7 -mixer luma 
-audio-track "music.mp3" out=300 -transition mix in=0 out=300 a_track=0 b_track=1  -filter volume level="0=0;95=0;100=-21;100=-21;195=-21;200=0"
-audio-track -blank 199 "2.mp3" -transition mix in=200  out=299 a_track=0 b_track=1 
```
Any fix or suggestion?

**Comment by ddennedy** [comment]
Did you try mocking this track and transition setup in a gui app such as Kdenlive, Flowblade, or Shotcut and viewing the XML result?
I have not tried running this yet, but one thing looks wrong is at the very end `a_track=0 b_track=1` should probably be `a_track=0 b_track=2`
