### ISSUE TITLE
How to keep alpha channel for png, webm

### ISSUE THREAD

**Issue by penguy** [mltframework/mlt#277]
I want to convert a png image and change size as blow

melt -producer avformat:Drawing.png -consumer avformat s=320x240 target=Drawing_out.png

But it doesn't work.

**Comment by ddennedy** [comment]
You need to specify a codec (.png alone will not do it) and pix_fmt. Choose one of:
  vcodec=png pix_fmt=rgba
  vcodec=targa pix_fmt=bgra
  vcodec=qtrle pix_fmt=argb
