### ISSUE TITLE
Failed to install mlt - osX High Sierra

### ISSUE THREAD

**Issue by benjaminlong** [mltframework/mlt#280]
Hello all, I am a newby with mlt.
I am trying to install mlt from source code, on osX High Sierra. 

I did:
```
git clone...
./ configure
make
```

Error I got:
```
consumer_gtk2.c:27:10: fatal error: 'gdk/gdkx.h' file not found
#include <gdk/gdkx.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [depend] Error 1
make[1]: *** [depend] Error 1
make: *** [all] Error 1
```

I did install gtk+ and gtk+3 using homebrew. I being stuck, and don't really know what to do...
I have gtk+ version `2.24.31` which doesn't seem to have the file `gdk/gdkx.h` in it's folder.
From this link: https://github.com/Homebrew/homebrew-core/issues/21826
It seems I need to enable x11 or Quartz support, but I haven't figured this out yet.

I also tried to install mlt using homebrew... it worked but when I test a simple command I got this error:
```
$ melt SampleVideo_720x480_5mb.mp4 
mlt_repository_init: failed to dlopen /usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltavformat.dylib
  (dlopen(/usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltavformat.dylib, 2): Symbol not found: _av_frame_set_color_range
  Referenced from: /usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltavformat.dylib
  Expected in: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
 in /usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltavformat.dylib)
Failed to load "SampleVideo_720x480_5mb.mp4"
[...]
```

What am I missing ?

**Comment by benjaminlong** [comment]
I found those Issues/Fixes:
- https://gist.github.com/zhiyzuo/a489ffdcc5da87f28f8589a55aa206dd
- https://gist.github.com/sebkopf/9405675

I succeeded to install **mlt** following those instructions:
```
$ brew uninstall cairo --ignore-dependencies
$ brew cask install xquartz 
$ brew install --with-x11 cairo
$ brew edit gtk+
```
Find where there is something like this and save it: Be sure gtk+ is uninstalled `brew uninstall gtk+ --ignore-dependencies`
```
def install
	args = [
    		"--disable-dependency-tracking",
			"--disable-silent-rules",
			"--prefix=#{prefix}",
			"--disable-glibtest",
			"--enable-introspection=yes",
			# "--disable-visibility",
			# "--with-gdktarget=quartz",
			"--with-gdktarget=x11",
			"--enable-x11-backend"
		   ]
```
```
$ brew install --build-from-source --verbose gtk+
```
After installation succeeds, add this to your `~/.bash_profile` file: `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig/gtk+-2.0.pc:/opt/X11/lib/pkgconfig`. Otherwise, gtk+ will not be recognized.

Then at mlt root dir... 
```
./reconfigure
make
make intsall
```
Worked like a charmed !

Now Im on this issue... https://github.com/mltframework/mlt/issues/246...

**Comment by ddennedy** [comment]
You could have also disabled the MLT gtk2 module on the configure step. It is not necessarily critical, and if you have the qt module, then it provides the same services and more.
