### ISSUE TITLE
Producer can not play video in windows

### ISSUE THREAD

**Issue by CovioGit** [mltframework/mlt#281]
Producer p1(profile, "noise");      // it is work

Producer p1(profile, "D:/1.wmv");      // it is not work
OS : Windows 7 64bit 
plaease help!~  thx very mush

**Comment by sway913** [comment]
You should specify the type of Producer  ,like avformat

**Comment by ddennedy** [comment]
There is a problem with your build of the avformat module that uses FFmpeg. It works in Shotcut on Windows: https://github.com/mltframework/shotcut/blob/master/src/mltcontroller.cpp#L108

Sorry, but build assistance is not provided. Here is a link to the Shotcut SDK that contains a working build of MLT and most modules for 64-bit Windows:
https://www.shotcut.org/notes/windowsdev/
