### ISSUE TITLE
ExecutablePath Path interception error

### ISSUE THREAD

**Issue by sway913** [mltframework/mlt#285]
at mlt_factory.c
When getting the current program path
char *appdir = dirname( path2 );
There will be an error when the “path2" string length is greater than 40
The bug of dirname function.

It can be replaced by this method
char *appdir = strdup( path2 );
strrchr( appdir, '\\')[0] = 0;

**Comment by ddennedy** [comment]
Please point it where this dirname() bug or shortcoming exists. Surely, it is not all implementations.

**Comment by sway913** [comment]
I see. I'll get the debug information out later.

**Comment by sway913** [comment]
Just look at the pictures. Must be present.
when I change path to "F:\Program Files (x86)\Shotcut1801中国欢迎您中国欢迎您中国欢迎您中国欢迎您中国欢迎您"
 will crash, I tracked it down to 2 characters less after calling the dirname() function.
![testpath](https://user-images.githubusercontent.com/9814915/34751660-e11a23e6-f5e8-11e7-9bf3-f114db1c1bff.gif)

**Comment by ddennedy** [comment]
Interesting. I do not reproduce it with "C:\Users\ddennedy\Desktop\Shotcut32-1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890". It might be a bug in mingw for some languages. Fortunately, this is the only place dirname() is used. Unfortunately, the code needs to work with both forward and back slashes, trailing slash, and no slash. Please review and test this change:
```
--- src/framework/mlt_factory.c
+++ src/framework/mlt_factory.c
@@ -89,12 +89,39 @@ static void mlt_factory_create_request( mlt_listener listener, mlt_properties ow
 static void mlt_factory_create_done( mlt_listener listener, mlt_properties owner, mlt_service self, void **args )
 {
 	if ( listener != NULL )
 		listener( owner, self, ( char * )args[ 0 ], ( char * )args[ 1 ], ( mlt_service )args[ 2 ] );
 }
 
+#if defined(_WIN32) || (defined(__APPLE__) && defined(RELOCATABLE))
+// Replacement for buggy dirname() on some systems.
+// https://github.com/mltframework/mlt/issues/285
+static char* mlt_dirname( char *path )
+{
+	if ( path && strlen( path ) )
+	{
+		char *dirsep = strrchr( path, '/' );
+		// Handle back slash on Windows.
+		if ( !dirsep )
+			dirsep = strrchr( path, '\\' );
+		// Handle trailing slash.
+		if ( dirsep == &path[ strlen( path ) - 1 ] )
+		{
+			dirsep[0] = '\0';
+			dirsep = strrchr( path, '/' );
+			if ( !dirsep )
+				dirsep = strrchr( path, '\\' );
+		}
+		// Truncate string at last directory separator.
+		if ( dirsep )
+			dirsep[0] = '\0';
+	}
+	return path;
+}
+#endif
+
 /** Construct the repository and factories.
  *
  * \param directory an optional full path to a directory containing the modules that overrides the default and
  * the MLT_REPOSITORY environment variable
  * \return the repository
  */
@@ -125,13 +152,13 @@ mlt_repository mlt_factory_init( const char *directory )
 		char path[1024];
 		uint32_t size = sizeof( path );
 		_NSGetExecutablePath( path, &size );
 #endif
 #if defined(_WIN32) || (defined(__APPLE__) && defined(RELOCATABLE))
 		char *path2 = strdup( path );
-		char *appdir = dirname( path2 );
+		char *appdir = mlt_dirname( path2 );
 		mlt_properties_set( global_properties, "MLT_APPDIR", appdir );
 		free( path2 );
 #endif
 	}
 
 	// Only initialise once
```

**Comment by sway913** [comment]
yes.
You this change  is work。
