### ISSUE TITLE
Build MLT failure to report errors when compiling frei0r.

### ISSUE THREAD

**Issue by leoxxw** [mltframework/mlt#286]
![image](https://user-images.githubusercontent.com/33110699/34815159-462d0b1a-f6eb-11e7-9521-eae4f5082cb2.png)
I followed your build steps, but with this problem, I tried to change the version of cmake, but it was still the problem.I guess it's an environment configuration problem, but I'm not sure which environment is wrong.May I ask for help?

**Comment by ddennedy** [comment]
The Windows build documentation is old and not maintained. Help with building is not provided here. This area is for reporting defects. Lastly, you are having a problem build frei0r and this is not the frei0r project.
