### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by Bleuzen** [mltframework/mlt#289]
I know, not a bug
but the problem is: Some Linux distros have a mlt package in their repo and it is from the latest 'release' version of MLT. Now let's say a rolling distro has the newest ffmpeg and kdenlive, but this very old MLT 6.4.1 release.

There are bugs when using this very old mlt version on a rolling distro (with newest ffmpeg and kdenlive),
for example that the kdenlive video preview uses only one thread to render.
This bug got already fixed, but after the 6.4.1 release. Distros that don't provide git packages still have this very old 6.4.1 version in their repo, so the bug is still there.
I know, I could use the Kdenlive app image, since this comes with MLT from git, but I think it would be better to use the distro's packages if possible. But it needs an update of MLT. There will be no package update, if there is no new MLT release.

So thats why I wanted to ask how the progress for the next release version is?

**Comment by ddennedy** [comment]
Over the weekend, I made a change to the SDL modules in preparation for a new release, which will be very soon - before end of the month.

**Comment by Bleuzen** [comment]
Great, thanks :D
