### ISSUE TITLE
OpenGL new features suggested

### ISSUE THREAD

**Issue by sway913** [mltframework/mlt#292]
Hello, I want to implement myself an opengl module to implement some of my own effects.
I know mlt movit module to achieve opengl rendering.
But some do not quite understand, all would like to ask next.

You first use "filter_glsl_manager" to call movit initialization and management.

use GlslManager::set_effect_input set video image.
use GlslManager::set_effect to let movit effect.
There are many, many details to deal with.
Also use "consumer_xgl" to export the video
movit finishes the drawing and returns the image.
https://github.com/ddennedy/movit

Finally, in fact, I want to say is:
If I wanted to implement a filter that was drawn using opengl, I'd draw a more complex 3D image of a character's skeleton than mine. How should I design the interface or structure.
I hope you can help out.
thank you!

**Comment by sway913** [comment]
My goal is to design an opengl module that provides a stable frame rate for expanding video editing.

**Comment by ddennedy** [comment]
This is not a bug report, and we do not take feature requests without a pull request.
For more information about using Movit OpenGL in MLT, see https://mltframework.org/docs/opengl/
See also WebGL filter examples that come with Shotcut (3D Text and Rutt -Etra-Izer filters). The WebVfx that powers that can also read Qt Quick QML including Qt 3D.
