### ISSUE TITLE
unknown type name locale_t when compiling with NDI SDK

### ISSUE THREAD

**Issue by jalowin** [mltframework/mlt#302]
Hello everybody

When I try to compile the git version, or 6.6.0 version I recevied this error

make[2]: se entra en el directorio '/home/ricardo/src/mlt/src/modules/ndi'
cc -fPIC -I../.. -Wno-deprecated -Wno-multichar -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -pthread -I/home/ricardo/Descargas/NDI_SDK_for_Linux/include    -c -o factory.o factory.c
In file included from ../../framework/mlt_animation.h:27:0,
                 from ../../framework/mlt.h:39,
                 from factory.h:23,
                 from factory.c:35:
../../framework/mlt_property.h:48:65: error: unknown type name ‘locale_t’
 extern int mlt_property_get_int( mlt_property self, double fps, locale_t );
                                                                 ^
../../framework/mlt_property.h:49:71: error: unknown type name ‘locale_t’
 extern double mlt_property_get_double( mlt_property self, double fps, locale_t );
                                                                       ^
../../framework/mlt_property.h:50:79: error: unknown type name ‘locale_t’
 extern mlt_position mlt_property_get_position( mlt_property self, double fps, locale_t );
                                                                               ^
../../framework/mlt_property.h:53:60: error: unknown type name ‘locale_t’
 extern char *mlt_property_get_string_l( mlt_property self, locale_t );
                                                            ^
../../framework/mlt_property.h:57:85: error: unknown type name ‘locale_t’
 extern char *mlt_property_get_time( mlt_property self, mlt_time_format, double fps, locale_t );
                                                                                     ^
../../framework/mlt_property.h:59:109: error: unknown type name ‘locale_t’
 extern int mlt_property_interpolate( mlt_property self, mlt_property points[], double progress, double fps, locale_t locale, mlt_keyframe_type i
                                                                                                             ^
../../framework/mlt_property.h:60:76: error: unknown type name ‘locale_t’
 extern double mlt_property_anim_get_double( mlt_property self, double fps, locale_t locale, int position, int length );
                                                                            ^
../../framework/mlt_property.h:61:70: error: unknown type name ‘locale_t’
 extern int mlt_property_anim_get_int( mlt_property self, double fps, locale_t locale, int position, int length );
                                                                      ^
../../framework/mlt_property.h:62:75: error: unknown type name ‘locale_t’
 extern char* mlt_property_anim_get_string( mlt_property self, double fps, locale_t locale, int position, int length );
                                                                           ^
../../framework/mlt_property.h:63:87: error: unknown type name ‘locale_t’
 extern int mlt_property_anim_set_double( mlt_property self, double value, double fps, locale_t locale, int position, int length, mlt_keyframe_ty
                                                                                       ^
../../framework/mlt_property.h:64:81: error: unknown type name ‘locale_t’
 extern int mlt_property_anim_set_int( mlt_property self, int value, double fps, locale_t locale, int position, int length, mlt_keyframe_type key
                                                                                 ^
../../framework/mlt_property.h:65:92: error: unknown type name ‘locale_t’
 extern int mlt_property_anim_set_string( mlt_property self, const char *value, double fps, locale_t locale, int position, int length );
                                                                                            ^
../../framework/mlt_property.h:69:59: error: unknown type name ‘locale_t’
 extern mlt_rect mlt_property_get_rect( mlt_property self, locale_t locale );
                                                           ^
../../framework/mlt_property.h:70:87: error: unknown type name ‘locale_t’
 extern int mlt_property_anim_set_rect( mlt_property self, mlt_rect value, double fps, locale_t locale, int position, int length, mlt_keyframe_ty
                                                                                       ^
../../framework/mlt_property.h:71:76: error: unknown type name ‘locale_t’
 extern mlt_rect mlt_property_anim_get_rect( mlt_property self, double fps, locale_t locale, int position, int length );
                                                                            ^
In file included from ../../framework/mlt.h:39:0,
                 from factory.h:23,
                 from factory.c:35:
../../framework/mlt_animation.h:41:94: error: unknown type name ‘locale_t’
 extern int mlt_animation_parse(mlt_animation self, const char *data, int length, double fps, locale_t locale );
                                                                                              ^
<integrado>: fallo en las instrucciones para el objetivo 'factory.o'
make[2]: *** [factory.o] Error 1
make[2]: se sale del directorio '/home/ricardo/src/mlt/src/modules/ndi'
Makefile:5: fallo en las instrucciones para el objetivo 'all'
make[1]: *** [all] Error 1
make[1]: se sale del directorio '/home/ricardo/src/mlt/src/modules'
Makefile:9: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 1

My configure line is this

./configure --prefix=/usr/local --enable-gpl --enable-gpl3 --disable-jackrack --swig-languages=python --ndi-sdk-include=/home/ricardo/Descargas/NDI_SDK_for_Linux/include --ndi-sdk-lib=/home/ricardo/Descargas/NDI_SDK_for_Linux/lib/x86_64-linux-gnu --disable-qt

 And my NDI SDK is this version
2017-10-09 @ r82134

Can somebody said me which are the problem?

Thanks for all

Best regards

**Comment by ddennedy** [comment]
What OS and version?
locale_t is provided by glibc. git master has a change to be compatible with musl libc: 5b2c9de. From that you can see it seems you have glibc without a locale_t defined in locale.h, which is strange.

**Comment by ddennedy** [comment]
Also, try building without NDI SDK and --disable-ndi to see if something in their SDK or our NDI module is having the problem.

**Comment by jalowin** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by jalowin** [comment]
Without ndi the software compile ok

**Comment by ddennedy** [comment]
Sorry, but I do not work with or support the NDI functionality, and you will have to see if another developer takes an interest.

**Comment by max-verem** [comment]
try please https://gist.github.com/max-verem/76b6617ad9154d37015abd2e81a936ed

**Comment by jalowin** [comment]
Ok, with this patch the system compile ok, thanks for all
Best regards

**Comment by ddennedy** [comment]
@max-verem Shall I apply that patch, or was that just a test?

**Comment by max-verem** [comment]
please commit
