### ISSUE TITLE
Expòrt H264 profile

### ISSUE THREAD

**Issue by jalowin** [mltframework/mlt#310]
![error_melt](https://user-images.githubusercontent.com/749160/37389213-b2c2721c-2763-11e8-8d86-eac28f91fbef.png)

Hello, when i try encode to h264 via libx264 I obtain this error when I try set the profile value to another value how main or high, by default is baseline

How can I change this value?

Thanks for all

Best regards

**Comment by jalowin** [comment]
Ok, thats all ok

for baseline => vpre=medium preset=medium vprofile=baseline coder=0 flags2=-wpred-dct8x8 wpredp=0 movflags=+faststart
for main => vpre=medium preset=medium vprofile=main flags2=-dct8x8 movflags=+faststart 
for high => vpre=medium preset=medium movflags=+faststart

Thanks for all

**Comment by ddennedy** [comment]
P.S. These messages are resolved in git master.
