### ISSUE TITLE
how to overlay a video on the other like a PiP(picture in picture)?

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [mltframework/mlt#314]
Hi, ddennedy, I have been learning your project recently. I used to use ffmpeg to process video and audio until I found this project, which brought me huge convenience. And now I want to use melt.exe to do something with video overlay. It's like overlay a video on the other, firstly I want to two videos to do overlay and maybe more later, How can I do this with melt.exe?

Thanks for all

Best regards

**Comment by ddennedy** [comment]
This not a bug. Only bug reports accepted here. Use stackoverflow.com for help. I am not available to provide education and user assistance. Use Shotcut to see how it is done and view the XML it creates.
