### ISSUE TITLE
Huge memory leaks during video rendering

### ISSUE THREAD

**Issue by mission712** [mltframework/mlt#316]
When trying to render a simple 7-minute long video with snippets from a few youtube videos and a still image, I exhaust my entire 16GB of RAM. The video is made with Kdenlive on a 1080p 29.97fps profile.
I attached the MLT file.
I tried to check with valgrind, which fails because:
```
VEX temporary storage exhausted.
Pool = TEMP,  start 0x598b2428 curr 0x59d5d440 end 0x59d76f67 (size 5000000)

vex: the `impossible' happened:
   VEX temporary storage exhausted.
Increase N_{TEMPORARY,PERMANENT}_BYTES and recompile.
vex storage: T total 4573614240 bytes allocated
vex storage: P total 640 bytes allocated

valgrind: the 'impossible' happened:
   LibVEX called failure_exit().
```
[mlt.zip](https://github.com/mltframework/mlt/files/1838657/mlt.zip)

Kdenlive version: 17.12.2
MLT version: 6.6.0

**Comment by mission712** [comment]
Downgrading to MLT 6.4.1 fixes this issue. Observing constant memory usage during render.

**Comment by ddennedy** [comment]
Unfortunately, I was not able to reproduce this by substituting my own media in the project file.  Using MLT v6.6.0 with real_time=-2 (two parallel processing threads to exercise it more), resident memory went up to 1.7 GiB. On git master (soon to be v6.8.0), it does not exceed 1.1 GiB (we made some changes to reduce memory footprint, but your problem sounds like a more specific bug).  On v6.4.1, it also went up to 1.7 GiB for me.
