### ISSUE TITLE
qimage and webvfx do not work together

### ISSUE THREAD

**Issue by coolwanglu** [mltframework/mlt#326]
To reproduce:
- Create two tracks
- In the first track, add an image
- In the second track, add a video, and apply a webvfx overlay.
- Use `melt` to render it

It seem that each track works by itself, but not together.
I wonder if there's some bug with Qt.

**Comment by ddennedy** [comment]
It works for me in Shotcut 18.06 on macOS. Be more specific in your steps to reproduce. Provide a full command line or XML.

**Comment by ddennedy** [comment]
Try using qmelt that comes with WebVfx as it initializes Qt on the main thread, which is what Qt and especially QtWebKit prefers. Shotcut uses qmelt for the export.

**Comment by ddennedy** [comment]
It still works for me in Shotcut on macOS when using Size and Position filters.
