### ISSUE TITLE
Mlt framework + SDL2 crash in Windows 7

### ISSUE THREAD

**Issue by dearshurik** [mltframework/mlt#330]
Dear gentlemans,
I have problem with Mlt framework + SDL2 in Windows OS (I use windows 7 (32 bit) and minGW w64 (32-bit) compiler).
My application crashed by function call
SDL_UpdateTexture( self->sdl_texture, NULL, planes[0], strides[0] );
The glEnable crash in calling stack.
The crash didn't apear if I set calling setup_sdl_video function to video_thread function. But after some time application didn't show video (audio is played). I saw a white window and application consumed 100% of processor.

The application is very simple:

// Project headers
#include <framework/mlt.h>
#include <SDL.h>

int main( int argc, char* argv[] )
{
    const char* filename = argv[ 1 ];
    SDL_Event event;

     mlt_factory_init( NULL );

    mlt_profile profile = mlt_profile_init( NULL );
    mlt_producer producer = mlt_factory_producer( profile, NULL, filename );

    mlt_profile_from_producer( profile, producer );
    mlt_consumer consumer = mlt_factory_consumer( profile, NULL, NULL );

    mlt_properties properties = mlt_consumer_properties( consumer );
    mlt_properties_set_int( properties, "real_time", 0 );

    mlt_consumer_connect( consumer, mlt_producer_service( producer ) );
    mlt_consumer_start( consumer );

    while(1)
    {
        while ( SDL_PollEvent( &event ))
        {
            switch ( event.type )
            {
                case SDL_KEYDOWN:
                {
                   
                    return 0;
                }
            }
        }
    }

    mlt_consumer_stop( consumer );
    mlt_consumer_connect( consumer, NULL );
    mlt_consumer_close( consumer );

    mlt_producer_close( producer );

    mlt_profile_close( profile );

    mlt_factory_close( );

    return 0;
}

**Comment by ddennedy** [comment]
Look at src/melt/melt.c for how to use MLT with SDL.
