### ISSUE TITLE
melt can't find profile file

### ISSUE THREAD

**Issue by CarlFK** [mltframework/mlt#332]
melt --version
melt 6.7.0
(from shotcut tarball)
 
highlights from below:

melt -verbose -pofile hdv_720_30p
+ export MLT_PROFILES_PATH=/home/carl/local/Shotcut/Shotcut.app/share/mlt/profiles
Failed to load "hdv_720_30p"

$ ls /home/carl/local/Shotcut/Shotcut.app/share/mlt/profiles/hdv_720_30p -l
-rw-r--r-- 1 carl carl 205 Mar  6 03:48 /home/carl/local/Shotcut/Shotcut.app/share/mlt/profiles/hdv_720_30p

carl@twist:~/src/veyepar/tests/melt/red_blue$ /home/carl/local/Shotcut/Shotcut.app/melt -verbose -pofile hdv_720_30p -video-track -producer noise

 + readlink -f /home/carl/local/Shotcut/Shotcut.app/melt
+ CURRENT_DIR=/home/carl/local/Shotcut/Shotcut.app/melt
+ dirname /home/carl/local/Shotcut/Shotcut.app/melt
+ INSTALL_DIR=/home/carl/local/Shotcut/Shotcut.app
+ export LD_LIBRARY_PATH=/home/carl/local/Shotcut/Shotcut.app/lib:
+ export MLT_REPOSITORY=/home/carl/local/Shotcut/Shotcut.app/lib/mlt
+ export MLT_DATA=/home/carl/local/Shotcut/Shotcut.app/share/mlt
+ export MLT_PROFILES_PATH=/home/carl/local/Shotcut/Shotcut.app/share/mlt/profiles
+ export FREI0R_PATH=/home/carl/local/Shotcut/Shotcut.app/lib/frei0r-1
+ export MLT_MOVIT_PATH=/home/carl/local/Shotcut/Shotcut.app/share/movit
+ export QT_PLUGIN_PATH=/home/carl/local/Shotcut/Shotcut.app/lib/qt5
+ export QML2_IMPORT_PATH=/home/carl/local/Shotcut/Shotcut.app/lib/qml
+ /home/carl/local/Shotcut/Shotcut.app/bin/melt -verbose -pofile hdv_720_30p -video-track -producer noise
/home/carl/local/Shotcut/Shotcut.app/bin/melt: /home/carl/local/Shotcut/Shotcut.app/lib/libxkbcommon.so.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0)
Failed to load "hdv_720_30p"
Failed to load "hdv_720_30p"
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
|1=-10| |2= -5| |3= -2| |4= -1| |5=  0| |6=  1| |7=  2| |8=  5| |9= 10|
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
+---------------------------------------------------------------------+
|               H = back 1 minute,  L = forward 1 minute              |
|                 h = previous frame,  l = next frame                 |
|           g = start of clip, j = next clip, k = previous clip       |
|                0 = restart, q = quit, space = play                  |
+---------------------------------------------------------------------+
Current Position:         37

Output window is 4:3

**Comment by ddennedy** [comment]
You misspelled profile command line option. As a result it is trying to load "hdv_720_30p" as a media file in the current directory and not finding it.
