### ISSUE TITLE
A 32bit melt.exe exited unexpectedly when dealing with global filter and high-resolution images simultaneously, while a 64bit melt doesn't.

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [mltframework/mlt#335]
I have installed both 32bit and 64bit Shotcut(version 17.02.01) on my Win10 64bit computer. So all my next test is using the melt.exe which Shotcut attached.
And I write my mlt file according to mlt-xml.txt and refer to Shotcut.
Here is my hand-written mlt file.

```xml
<?xml version='1.0' encoding='utf-8'?>
<mlt>
  <profile display_aspect_den="9" frame_rate_den="1" width="1920" sample_aspect_den="1" progressive="1" description="automatic" display_aspect_num="16" frame_rate_num="25" sample_aspect_num="1" colorspace="709" height="1080"/>
  <consumer real_time="-4" aspect="1.77778" ab="384k" preset="fast" movflags="+faststart" crf="21" threads="0" top_field_first="0" r="25" vcodec="libx264" width="1920" progressive="1" target="D:/xmlgenerator.mp4" ar="48000" height="1080" deinterlace_method="yadif" acodec="aac" mlt_service="avformat" rescale="bilinear" f="mp4" g="13" bf="2"/>
  <producer id="black" in="00:00:00.000" out="00:00:23.760">
    <property name="resource">black</property>
    <property name="mlt_service">color</property>
  </producer>
  <playlist id="background" autoclose="1">
    <entry producer="black" in="00:00:00.000" out="00:00:23.760"/>
  </playlist>
  <producer id="producer0" in="00:00:00.000" out="00:00:23.680">
    <property name="resource">D:/high-resolution.jpg</property>
    <property name="mlt_service">pixbuf</property>
  </producer>
  <playlist id="playlist0" autoclose="1">
    <entry producer="producer0" in="00:00:00.000" out="00:00:23.680"/>
  </playlist>
    <producer id="producer1" in="00:00:00.000" out="00:00:05.240">
    <property name="resource">D:/2.jpg</property>
    <property name="mlt_service">pixbuf</property>
  </producer>
  <playlist id="playlist1" autoclose="1">
    <blank length="00:00:04.160"/>
    <entry producer="producer1" in="00:00:00.000" out="00:00:05.240"/>
  </playlist>
  <producer id="producer2" in="00:00:00.000" out="00:03:42.640">
    <property name="resource">D:/Alex G - Butterflies.mp3</property>
    <property name="mlt_service">avformat</property>
  </producer>
  <playlist id="playlist2" autoclose="1">
    <entry producer="producer2" in="00:00:00.000" out="00:00:23.720"/>
  </playlist>
  <tractor id="tractor0" global_feed="1">
    <track producer="background"/>
    <track producer="playlist0"/>
	<track producer="playlist1"/>
    <track producer="playlist2" hide="video"/>
    <transition id="transition0">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition1">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">1</property>
    </transition>
    <transition id="transition2">
      <property name="a_track">0</property>
      <property name="b_track">2</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
	<transition id="transition1">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">0</property>
    </transition>
	<transition id="transition2">
      <property name="a_track">0</property>
      <property name="b_track">3</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
  </tractor>
  <tractor id="tractor1">
    <multitrack>
      <track producer="tractor0"/>
    </multitrack>
    <filter >
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="transition.cycle">0</property>
      <property name="transition.geometry">0=0.00%/0.00%:100.00%x100.00%;75=0.00%/-106.07%:206.07%x206.07%; 125=0.00%/-106.07%:206.07%x206.07%; 250=0.00%/-0.22%:100.22%x100.22%; 300=0.00%/-0.22%:100.22%x100.22%; 350=-31.34%/-31.64%:131.64%x131.64%; 450=0%/0%:100%x100%</property>
    </filter>
  </tractor>
</mlt>
```
It can be visualised in the traditional timeline widget as follows:

```
track0: [---------------------black-----------------------]  
track1: [----------------high-resolution.jpg ------------]  
track2: [---------------][2.jpg]
track3: [------------------music.mp3--------------------]
```
The high-resolution.jpg is 3877x2544, and its size is 846KB.
As you can see above, I employ another tractor and define a single track and apply an affine filter to do the zoom things.

So I type this command line and run it with a 32bit melt:
` .\melt.exe .\test.mlt -progress`

And I got this error.
 
![1525249745 1](https://user-images.githubusercontent.com/16981274/39513154-fce96a74-4e25-11e8-8dae-c545d4d3e0bf.jpg)

Actually when it crashed, my computer has more than 8G RAM available.
And then I did some comparsion tests.

```
1. I use a 64bit melt.exe to run the same mlt file and it works well.
2. I remove the global affine filter (delete the XML tag "tractor1") and run with a 32bit melt.exe, it works well.
3. I replace the high-resolution.jpg with a low-resolution() image and run with a 32bit melt.exe, it works well.
```

I don't know whether there is something wrong with my mlt file, but it works well with a 64bit melt.exe.
I also run it with the melt.exe which belong to the latest Shotcut, but it still crashed.

So what's the difference between a 32bit melt and a 64bit melt?
I would like to know if this is a bug and how to fix it.

**Comment by ddennedy** [comment]
Win32 programs can only use 2GB of RAM regardless of the amount of physical RAM. MLT already has a change in git master to use less memory especially when using the affine filter as you are. This will be in the next version of Shotcut due tomorrow or the next day.

**Comment by ddennedy** [comment]
Fixed in e426a4ed62c7f674db4498766d6928a9598a7ca9 and 71167e65b4ac126546b7524e406bd81f991c2abf

**Comment by HeartbreakSurvivor** [comment]
Ok, I will try to build the latest mlt on windows and test it. thanks for all.
Best regards

**Comment by HeartbreakSurvivor** [comment]
Hi, ddennedy. I know it may be improper to ask a question here, but I really get stuck and I need your help. It takes me several days to build an incomplete melt on windows with Mingw32. And I just can't wait to execute it with a windows console and I found it's a little bit weird with the melt.exe attach to Shotcut. First, when I start to run some melt command line and the melt.exe running in the background immediately while melt.exe in Shotcut(version 17.02.01) doesn't. Then I found what supposed to be displayed on the screen now were written to the files named stdout and stderr. I tried to find some configurtion and build options, but I failed. I also checked the code , it looks like nothing changed. 
So I want to know how to build a melt that can use blocking call and print output to console not a file.
Thanks in advance.
Best regards.

**Comment by ddennedy** [comment]
Console output broke when we integrated SDL2. The fix is a simple link flag `-mconsole` 
 as in e647ae3e7f74a663bfe87171383a4e6c6247311f

**Comment by HeartbreakSurvivor** [comment]
@ddennedy  hi, I have noticed your patch e647ae3. So I disable the SDL2 module use this:

`./configure -prefix=$HOME/build --disable-decklink --disable-rtaudio --enable-gpl --enable-gpl3 --disable-sdl --disable-sdl2 --enable-debug`

And I found the melt.exe indeed use blocking call, but only block, cause there is still nothing display on console, and the output is still writing to stderr.txt.

![image](https://user-images.githubusercontent.com/16981274/40225526-dd1dc3b4-5abb-11e8-999a-10af5dda7f08.png)

**Comment by ddennedy** [comment]
Disabling the sdl2 module has no affect on whether the melt executable in src/melt uses SDL or not. You did not say whether you made the change in your patch. If you want to build melt without SDL, then add "-DMELT_NOSDL" to CFLAGS.
