### ISSUE TITLE
I want to ask some questions about the playlist fps ,thank you

### ISSUE THREAD

**Issue by CovioGit** [mltframework/mlt#338]
my english is not good , so questions may be not enough clear ,forgive me 
my question is , if I create a playlist , and add two videos , one is 25fps , another one is 30fps. In that way,when playback, the  playlist  will be output video in 25fps ? OR 30fps ?  OR playback the first video is 25fps,and when playback the second video ,change to 30fps ?  
thank you very much

**Comment by ddennedy** [comment]
We only use Github for bug tracking. General discussion and questions should go to stackoverflow. To answer your question, it depends on the mlt_profile in use and any overriding properties on the consumer.
https://www.mltframework.org/docs/profiles/
https://www.mltframework.org/doxygen/structmlt__profile__s.html
https://www.mltframework.org/doxygen/properties.html
