### ISSUE TITLE
extremely fuzzy output when apply global affine filter to implement a  zoom effect with low-resolution videos.

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [mltframework/mlt#341]
Hi, I want to zoom in and zoom out my video clips smoothly, But unfortunately I have not been able to find any filters that can do this in Shotcut. So I turn to MLT for help and I found the [mlt_slideshow2](https://github.com/mltframework/mlt/blob/master/demo/mlt_slideshow2) in the mlt demo directory. Yes, The affine filter can do this, but you need to fill the "transition.geometry" property against the corresponding format by yourself in the command line.
The zoom animation effects must be applied to all the tracks. And fortunately I found the way how watermark filter to do this [here](https://github.com/mltframework/mlt/blob/master/docs/mlt-xml.txt), so I just borrowed form it.
And now I started to write my own mlt file to do this. Here is my timeline layout in Shotcut, But noticed that I didn't use Shotcut to do this, I just wanna show you the layout.
![timeline](https://user-images.githubusercontent.com/16981274/40462390-561f018a-5f42-11e8-9847-1c58d62c23f8.jpg)

And here is my own hand-written mlt file(buck_normal.mlt), some of it is borrowd from the mlt file which Shotcut generated.
 
```xml
<?xml version="1.0" encoding="utf-8"?>
<mlt LC_NUMERIC="en_US">
  <profile display_aspect_den="9" frame_rate_den="1" width="1920" sample_aspect_den="1" progressive="1" description="automatic" display_aspect_num="16" frame_rate_num="25" sample_aspect_num="1" colorspace="709" height="1080" />
  <consumer real_time="-4" ab="192k" aspect="1.77778" movflags="+faststart" threads="0" top_field_first="0" r="25" vcodec="libx264" width="1920" progressive="1" target="F:\Zoom\normal.mp4" ar="44100" height="1080" deinterlace_method="yadif" acodec="aac" mlt_service="avformat" rescale="bilinear" f="mp4" g="13" bf="2" preset="superfast" crf="22"/>
  <producer id="black" in="00:00:00.000" out="00:00:15.485">
    <property name="eof">pause</property>
    <property name="resource">black</property>
    <property name="mlt_service">color</property>
  </producer>
  <producer id="producer1" in="00:00:00.000" out="00:00:19.990">
    <property name="threads">1</property>
    <property name="resource">F:\Zoom\buck_20s.mp4</property>
    <property name="mlt_service">avformat</property>
  </producer>
  <producer id="producer2" in="00:00:00.000" out="00:33:20.000">
    <property name="aspect_ratio">1</property>
    <property name="resource">F:\Zoom\watermark.png</property>
    <property name="mlt_service">pixbuf</property>
    <filter id="filter0">
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="transition.geometry">29.68%/58.23%:46.81%x24.59%</property>
    </filter>
  </producer>
  <playlist id="background" autoclose="1">
    <entry producer="black" in="00:00:00.000" out="00:00:15.485" />
  </playlist>
  <playlist id="playlist1" autoclose="1">
    <entry producer="producer1" in="00:00:00.000" out="00:00:15.485" />
  </playlist>
  <playlist id="playlist2" autoclose="1">
    <entry producer="producer2" in="00:00:00.000" out="00:00:15.485" />
  </playlist>
  <tractor id="tractor0" global_feed="1">
    <track producer="background" />
    <track producer="playlist1" />
    <track producer="playlist2" />
    <transition id="transition0">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="version">0.9</property>
      <property name="disable">1</property>
    </transition>
    <transition id="transition1">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="version">0.9</property>
      <property name="disable">0</property>
    </transition>
    <transition id="transition2">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition3">
      <property name="a_track">0</property>
      <property name="b_track">2</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
  </tractor>
  <tractor id="tractor1">
    <track producer="tractor0"/>
    <filter id="filter1">
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="transition.cycle">0</property>
      <property name="transition.geometry">0=0.00%/0.00%:100.00%x100.00%;23=0.00%/0.00%:100.00%x100.00%;60=-65.03%/-96.05%:240.98%x240.98%;121=-65.03%/-96.05%:240.98%x240.98%;158=-14.84%/-3.21%:114.84%x114.84%;245=-14.84%/-3.21%:114.84%x114.84%;283=-3.04%/-2.88%:103.04%x103.04%;387=-3.04%/-2.88%:103.04%x103.04%;</property>
    </filter>
  </tractor>
</mlt>
```

And that works, the exported video has the zoomin/out effects. This is just amazing!
PS:  why Shotcut hasn't intergated this awesome function?

But don't get too confortable! Cause I found something weird thing happened when I replace the buck_20s.mp4 with a low-resolution 512x288 video named LOG-CG.mp4. In MLT, a low-resolution video will be stretch to fit the output video. So I must add a affine filter to adjust the geometry. In Shotcut its name is Size and Position. 
And here is the new timeline layout, as you say I just replaced the video on the V1.
![image](https://user-images.githubusercontent.com/16981274/40463773-a3c4c760-5f49-11e8-9961-1956a096975b.png)
Here is the new mlt file(weird.mlt), just add a affine filter to producer1, and there is no other difference from the previous mlt file.

```xml

<?xml version="1.0" encoding="utf-8"?>
<mlt LC_NUMERIC="en_US">
  <profile display_aspect_den="9" frame_rate_den="1" width="1920" sample_aspect_den="1" progressive="1" description="automatic" display_aspect_num="16" frame_rate_num="25" sample_aspect_num="1" colorspace="709" height="1080" />
  <consumer real_time="-4" ab="192k" aspect="1.77778" movflags="+faststart" threads="0" top_field_first="0" r="25" vcodec="libx264" width="1920" progressive="1" target="F:\Zoom\weird.mp4" ar="44100" height="1080" deinterlace_method="yadif" acodec="aac" mlt_service="avformat" rescale="bilinear" f="mp4" g="13" bf="2" preset="superfast" crf="22" />
  <producer id="black" in="00:00:00.000" out="00:00:15.549">
    <property name="eof">pause</property>
    <property name="resource">black</property>
    <property name="mlt_service">color</property>
  </producer>
  <producer id="producer1" in="00:00:00.000" out="00:01:49.945">
    <property name="threads">1</property>
    <property name="resource">F:\Zoom\LOL-CG.mp4</property>
    <property name="mlt_service">avformat</property>
    <filter id="filter0">
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="transition.geometry">30.00%/30.00%:40.00%x40.00%</property>
    </filter>
  </producer>
  <producer id="producer2" in="00:00:00.000" out="00:33:20.000">
    <property name="aspect_ratio">1</property>
    <property name="resource">F:\Zoom\watermark.png</property>
    <property name="mlt_service">pixbuf</property>
    <filter id="filter1">
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="transition.geometry">29.68%/58.23%:46.81%x24.59%</property>
    </filter>
  </producer>
  <playlist id="background" autoclose="1">
    <entry producer="black" in="00:00:00.000" out="00:00:15.549" />
  </playlist>
  <playlist id="playlist1" autoclose="1">
    <entry producer="producer1" in="00:00:00.000" out="00:00:15.549" />
  </playlist>
  <playlist id="playlist2" autoclose="1">
    <entry producer="producer2" in="00:00:00.000" out="00:00:15.485" />
  </playlist>
  <tractor id="tractor0" global_feed="1">
    <track producer="background" />
    <track producer="playlist1" />
    <track producer="playlist2" />
    <transition id="transition 10">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="version">0.9</property>
      <property name="disable">1</property>
    </transition>
    <transition id="transition 11">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="version">0.9</property>
      <property name="disable">0</property>
    </transition>
    <transition id="transition 12">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition 13">
      <property name="a_track">0</property>
      <property name="b_track">2</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
  </tractor>
  <tractor id="tractor1">
    <track producer="tractor0" />
    <filter id="filter2">
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="transition.cycle">0</property>
      <property name="transition.geometry">0=0.00%/0.00%:100.00%x100.00%;23=0.00%/0.00%:100.00%x100.00%;60=-65.03%/-96.05%:240.98%x240.98%;121=-65.03%/-96.05%:240.98%x240.98%;158=-14.84%/-3.21%:114.84%x114.84%;245=-14.84%/-3.21%:114.84%x114.84%;283=-3.04%/-2.88%:103.04%x103.04%;388=-3.04%/-2.88%:103.04%x103.04%;</property>
    </filter>
  </tractor>
</mlt>
```

And the output video "weird.mp4" is indeed has the zoom effects, but a little bit weird. It seems that the original video and the watermark.png were stretched overly and leads to the output images were extremely fuzzy(although the original video is not very clear as well).

So I decided to do the process in two steps.
First, I export the video(temp.mp4) without the zoom effects by remove the "tractor1" tag in the above mlt file, and save the temp mlt file with the name "temp.mlt".
Second, I write another mlt file(expected.mlt) to apply a affine filter to the temp.mp4, and export the video with the name "expected.mp4".

And the expected.mp4 has the normal zoom effects, and that's what I want. here is the comparison:
![image](https://user-images.githubusercontent.com/16981274/40470046-edcb47ce-5f64-11e8-8217-6eacde96b1de.png)

[here ](https://drive.google.com/drive/folders/13a3-cJLhzdZwI5sGpoPVW9Mtyll62RCg)is all the resource file that used and generated above.

And my question is why would the video generated by weird.mlt was so fuzzy, while the video generated by temp.mlt and expected.mlt wasn't? what's the difference between them? Is there a way to avoid this, I havd tried the properties described in transition_affine.yml, but I still can't figure it out.

Sorry for that long description, hope you can understand.

**Comment by ddennedy** [comment]
> I want to zoom in and zoom out my video clips smoothly, But unfortunately I have not been able to find any filters that can do this in Shotcut.

This is already implemented in the Size and Position filter:
https://www.youtube.com/watch?v=j9xb1Rzn2Sg

> PS: why Shotcut hasn't intergated this awesome function?

It has. https://www.shotcut.org/blog/new-release-1805/
I recommend you wait until version 18.06, however, as that was very buggy and more like a technology preview.

> And now I started to write my own mlt file to do this.

We are not available to help you troubleshoot hand-written MLT XML.

> why would the video generated by weird.mlt was so fuzzy, while the video generated by temp.mlt and expected.mlt wasn't?

The affine transition/filter requests the image in full resolution from upstream in the pipeline and to bypass the automatically applied filters to scale and pad to the project resolution. It has the information about the source clip's resolution and requests images from upstream at that resolution. When you use affine as a global filter, it does not have a specific clip against which to work. Maybe it is getting the resolution information of watermark.png and using that.
