### ISSUE TITLE
slideshow shows last image multiple times

### ISSUE THREAD

**Issue by awright424** [mltframework/mlt#344]
I am using mlt to create a slideshow with some transitions and it works fine. I have it doing this over a minute and notice that if there arent enough images the last image will be cycled versus it cycling through again. Is that an option that I missed?

**Comment by ddennedy** [comment]
This is not a bug report. This area is not for usage questions.

**Comment by ddennedy** [comment]
mlt_producer has a "eof" property documented [here](https://www.mltframework.org/doxygen/properties.html). It depends on which producer you apply this too, and whether it honors it. [This page](https://www.mltframework.org/doxygen/structmlt__producer__s.html) shows multitrack, playlist, and tractor are all producers as well. And search the [FAQ](https://www.mltframework.org/faq/) page for "loop."
