### ISSUE TITLE
avfilter.subtitles seems to ignore consumer position

### ISSUE THREAD

**Issue by luke-jr** [mltframework/mlt#345]
I'm trying to edit/censor a video with subtitles, like this:

```
<mlt>
	<producer id="movie">
		<property name="resource">video.mkv</property>
		<filter>
			<property name="mlt_service">avfilter.subtitles</property>
			<property name="av.filename">video.ssa</property>
		</filter>
	</producer>
	<playlist id="playlist">
		<entry producer="movie" in="0" out="10609"/>
		<entry producer="movie" in="10765" out="10994"/>
		<entry producer="movie" in="11374" out="12020"/>
		<entry producer="movie" in="12187" out="19889"/>
		<entry producer="movie" in="20069" out="34806"/>
	</playlist>
</mlt>
```

However, somehow the subtitles ignores the cut-points, and continues linearly, as if there are no cuts.

Using MLT 6.6.0 (latest available for Gentoo at this time)

**Comment by ddennedy** [comment]
The underlying avfilter does not get the MLT timing information. This might not be possible and unlikely to be looked at by me anytime soon, but I will leave it open for you or anyone else who wants to work on it. Just telling you to look for an alternate approach and don't wait for a fix.

**Comment by luke-jr** [comment]
Thanks... I would have expected each producer to produce a deterministic frame regardless of what its consumer is doing with it... :/

**Comment by richardpl** [comment]
What is actually missing in avfilter? What kind of info?

**Comment by ddennedy** [comment]
Nothing missing in libavfilter. MLT has various notions of time position. Most MLT filters use a time relative to the start of the filter. This avfilter bridge was setting AVFrame.pts to a value based on the position of a MLT frame within the playlist in this example. In any case, subtitles are obviously synchronized with the file to which they are mated and neither of the above makes sense. So, I changed the default for subtitles to use the time the source producer sets on the MLT frame.
