### ISSUE TITLE
MLT should not call XInitThreads

### ISSUE THREAD

**Issue by Celelibi** [mltframework/mlt#351]
If called at all, `XInitThreads` should be called before any Xlib function. But the way it is currently called make it happen in the middle of the execution (instead of during an initialization). And there is no easy way to make the application call `XInitThreads` without a direct dependency to Xlib. Which is unfortunate.

The function `XInitThreads` actually set global function pointers (to create/destroy/lock/unlock mutexes) which must stay consistent across the whole application life. What currently happens with the application flowblade is that a mutex is created before MLT calls `XInitThreads` (thus calling a dummy implementation that returns NULL), and it is locked after MLT has called `XInitThreads`. The actual locking functions gets a NULL pointer. Making the process crash.

**Comment by ddennedy** [comment]
There is no point to create a new issue with no patch!

**Comment by ddennedy** [comment]
oops, the other issue is in Flowblade project! sorry about that. I was confused because I received an e-mail from the other thread and had not noticed the repo.

**Comment by ddennedy** [comment]
Removing the call to `XInitThreads` did not fix Flowblade. I have to do more testing with Movit to see if there is a regression to remove it.
