### ISSUE TITLE
Getting a single frame while redirecting to memory makes consumer loop over same data

### ISSUE THREAD

**Issue by Victordmdb** [mltframework/mlt#352]
Not sure if this is normal behaviour, but by setting an avformat consumer with redirect to load the decoded data into memory, with speed set to 0, it continuously loops over the same frame.

The purpose is to request one frame at a time, therefore only sending the data for that one frame, then stop. Is that possible?

**Comment by ddennedy** [comment]
It is normal with speed set to 0. If you want something different you need to make your own consumer (can be in-app) that encapsulates avformat and drives it by fetching and sending frames. See the cbrts consumer for an example. What you are trying to do is a new and different use case for MLT, and you might even need to forgo using mlt_consumer (or inheriting from it).

**Comment by Victordmdb** [comment]
Alright I thought so. I've been looking at the cbrts code already since I was building a consumer with an mjpeg output. I'm forwarding the output through websocket to a client to decode with jsmpeg (js mjpeg lib). It's a super convoluted way to get frame by frame rendering work on the web. Do you have any other recommendations on how better to approach this?

**Comment by ddennedy** [comment]
Sorry, I do not have any experience with sending to a web browser from MLT directly or any suggestion.

**Comment by Victordmdb** [comment]
I might have a bug report. Within consumer_avformat.c, after the main consumer_thread while loop, if the loop was never entered (eg properties "running" was never set), the `enc_ctx->fifo` will not have been initialised and will cause a segfault at sample_fifo_used. My solution was to change `if ( enc_ctx->audio_st[0] ) for (;;)` on [line 2050](https://github.com/mltframework/mlt/blob/master/src/modules/avformat/consumer_avformat.c#L2050) to `if ( enc_ctx->fifo && enc_ctx->audio_st[0] ) for (;;)`.

I found this because for some reason `avcodec_open2` in `open_video` would change the property the passed `mlt_properties` object, putting "running" to 0.

**Comment by ddennedy** [comment]
Thanks, I added your check in 24ddae6d40b1b2eb4d5bc875f40a865278732338
There were some major changes to avformat consumer, and it would not surprise if cbrts became broken in the process. The main users of it (a few broadcasters) probably do not update their MLT much.

**Comment by Victordmdb** [comment]
Hi, I'm not sure if this is related to the above issue, but with the cbrts settings the video is played as fast as the system can handle it, disregarding the profile framerate. Speed is set to 1.0, and I've tested on multiple videos, where the pts is properly copied to the output frame. Is this normal behaviour, or am I missing something?

**Comment by ddennedy** [comment]
cbrts is designed for rate control via socket or whatever is consuming stdout. You can take a look at consumer_cbrts.c:write_udp(), which has some timing code in it. The avformat consumer attempts to simulate a rate control when the real_time property = 1, but I do not think that applies when using cbrts. And that setting may drop video frames trying to keep realtime and audio continuous, which you may not want (and probably screws with CBR MPEG2-TS compliance).
