### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by mwshubham** [mltframework/mlt#355]
Is there any integration doc/wiki or useful resources for mobile application developer where they can find the details to get started with MLT. I am working on FFMPEG from past few weeks. And for few complex transitions, I might require MLT framework. Can we integrate FFMpeg with MLT for a mobile application? or do we need to use MLT separately for our requirement?

Following application rely on MLT as well.
https://play.google.com/store/apps/details?id=com.goseet.MovieEditor
note: it uses FFmpeg and MLT under permission of LGPL.

Thanks,
Shubham A.

**Comment by ddennedy** [comment]
We do not have any information about how to build MLT for Android. You will have to figure it out yourself. If you do, then we appreciate if you would share it with us for the next person who needs it.

**Comment by wjhtinger** [comment]
> 
> 
> Is there any integration doc/wiki or useful resources for mobile application developer where they can find the details to get started with MLT. I am working on FFMPEG from past few weeks. And for few complex transitions, I might require MLT framework. Can we integrate FFMpeg with MLT for a mobile application? or do we need to use MLT separately for our requirement?
> 
> Following application rely on MLT as well.
> https://play.google.com/store/apps/details?id=com.goseet.MovieEditor
> note: it uses FFmpeg and MLT under permission of LGPL.
> 
> Thanks,
> Shubham A.

Do you success? Can you share something? 
Very thanks.

**Comment by mwshubham** [comment]
The product team asks us to go with FFMpeg. We were able to get the result using complex FFMpeg queries. The only con was the performance.
