### ISSUE TITLE
xkb_compose_table_unref, version V_0.5.0 not defined in libxkbcommon

### ISSUE THREAD

**Issue by CarlFK** [mltframework/mlt#356]
.mlt file plays ok in Shotcut, but after 1.5 hours of encoding it completed without error but the mp4 was 0 bytes.

I tried to encode with melt, it errored; 

 tried to play, same error: 

melt 6.9.0
from
shotcut-linux-x86_64-180702.tar.bz2

[An_Intuitive_Grasp_of_RegExs_in_Python.mlt.txt](https://github.com/mltframework/mlt/files/2246658/An_Intuitive_Grasp_of_RegExs_in_Python.mlt.txt)

carl@twist:~/Videos/veyepar/pyohio/pyohio_2018/custom$ melt An_Intuitive_Grasp_of_RegExs_in_Python.mlt 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/carl/local/Shotcut/Shotcut.app/bin/melt...done.
(gdb) r
Starting program: /home/carl/local/Shotcut/Shotcut.app/bin/melt An_Intuitive_Grasp_of_RegExs_in_Python.mlt
/home/carl/local/Shotcut/Shotcut.app/bin/melt: /home/carl/local/Shotcut/Shotcut.app/lib/libxkbcommon.so.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd8f7e700 (LWP 29881)]
[New Thread 0x7fffd1e7e700 (LWP 29882)]
[New Thread 0x7fffd167d700 (LWP 29883)]
[New Thread 0x7fffd0e7c700 (LWP 29884)]
[New Thread 0x7fffc3fff700 (LWP 29885)]
[New Thread 0x7fffc1410700 (LWP 29887)]
[New Thread 0x7fffc0c0f700 (LWP 29888)]
[Thread 0x7fffc1410700 (LWP 29887) exited]
[New Thread 0x7fffc1410700 (LWP 29889)]
[New Thread 0x7fffabd2d700 (LWP 29890)]
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
|1=-10| |2= -5| |3= -2| |4= -1| |5=  0| |6=  1| |7=  2| |8=  5| |9= 10|
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
+---------------------------------------------------------------------+
|               H = back 1 minute,  L = forward 1 minute              |
|                 h = previous frame,  l = next frame                 |
|           g = start of clip, j = next clip, k = previous clip       |
|                0 = restart, q = quit, space = play                  |
+---------------------------------------------------------------------+
[New Thread 0x7fffab52c700 (LWP 29891)]
[filter avcolor_space] Invalid format glsl
Couldn't open libEGL.so.1: /usr/lib/x86_64-linux-gnu/libmirclient.so.9: symbol xkb_compose_table_unref, version V_0.5.0 not defined in file libxkbcommon.so.0 with link time reference
[Thread 0x7fffc3fff700 (LWP 29885) exited]
Current Position:          0
Thread 1 "melt" received signal SIGSEGV, Segmentation fault.
0x00007fffe7173700 in ?? ()
(gdb) bt
#0  0x00007fffe7173700 in ?? ()
#1  0x00000000004031af in transport (consumer=0x22dd240, producer=0x7cf9b0)
    at melt.c:431
#2  main (argc=<optimized out>, argv=<optimized out>) at melt.c:996
(gdb) 

The 2 .ts files are about 5gig each, so I can make them available if I start uploading and let it run overnight.

**Comment by ddennedy** [comment]
> [filter avcolor_space] Invalid format glsl

That is a sign of a problem where you are using movit services without movit being initialized (because it failed automatic detection or opengl failed to initialize).
Your .mlt has lines such as the following:
```
    <property name="movit.convert.width">1280</property>
    <property name="movit.convert.height">720</property>
    <property name="movit.convert.format">2</property>
```
However, there are no movit filters or transitions. First of all. it is not clear how those lines got there. That is not normal. I just did some tests in Shotcut with GPU processing enabled, and I do not see them in my XML output. However, the xml producer will try to use initialize opengl when it saw those. Probably, you just need to search for all lines with movit in them and remove them.
