### ISSUE TITLE
More exactly rule to match animation property

### ISSUE THREAD

**Issue by 599316527** [mltframework/mlt#363]
https://github.com/mltframework/mlt/blob/f39609dfb03121ac62e5d5e84a7b02151e2406b9/src/framework/mlt_animation.c#L314-L331

I'm writing webvfx producers and I find that properties which contain `=` would be spilt in `mlt_animation_parse`. It shall be more exactly to match the animation property to avoid the case.

**Comment by 599316527** [comment]
Which escape character? backslash? 

* `"a=b"`     -> `"b"`
* `"a\=b"`    -> `"a=b"`
* `"a\\=b"`   -> `"a=b"`
* `"a\\\=b"`  -> `"a\=b"`
* `"a\\\\=b"` -> `"a\=b"`

It looks great.

**Comment by 599316527** [comment]
Offering an option for each effect to turn animation property off is another solution. 

```bash
melt --video-track webvfx resource="xxxx" title="xxxx=yyyy" noanimation="true"
```

I changed the call from `mlt_properties_anim_get` to `mlt_properties_get` in `getStringParameter` of webvfx  to work around temporarily.

**Comment by ddennedy** [comment]
Yes, backslash. I had to edit my comment and escape it in Markdown to make it show! In MLT, it would be like:

* `"a=b"`     -> `"b"`
* `"a\=b"`    -> `"a=b"`
* `"a\\=b"`   -> `"a\=b"`
* `"a\\\=b"`   -> `"a\\=b"`

One backslash before equal sign gets removed.

**Comment by 599316527** [comment]
> One backslash before equal sign gets removed.

👍👍👍

**Comment by 599316527** [comment]
Fine. Just let mlt know it's not an "animation value".
