### ISSUE TITLE
How To Keep Alpha Channel For Webm In Mlt

### ISSUE THREAD

**Issue by vvck** [mltframework/mlt#364]
when I used video and png with compsite transition, I  can get transparent effect, 
but  when I used webm file to be b_track in transition ,i found there is no transparent effect.
So how can i use mlt to keep alpha channel to get transparent effect in transition?

**Comment by vvck** [comment]
I found ffmpeg used native vp8 decoder to decode webm file ，so we only get yuv420p pixel format in video data, but if I set video codes to libvpx, the pixel format will be yuva420,that is well.
then I try to set vcodes to libvpx in producer of mlt  used the comand avformat:wemb:xxx.webm?vcodes=libvpx, but there is no effect. 
Is I used  a wrong way? please tell me  how can I do.

**Comment by ddennedy** [comment]
Do you mean `vcodec`? I do not believe if it will work, but I have not heard of `vcodes`. You probably need to convert the webm to something like Quicktime Animattion (qtrle), ffv1, or huffyuv.

**Comment by vvck** [comment]
@ddennedy Sorry , I spelt the wrong word , it should be vcodec.
Yes, quicktime format (mov) is good, it can make transparent effect, but I still want to use webm, beacuse of it' low size.
I found URL parse only set dict data in ffmpeg, if I want to change vcodec, i must use other way to make option work.

**Comment by ddennedy** [comment]
Now, it works with or without `?vcodec=___`

**Comment by ddennedy** [comment]
I am going to remove the query string handling because I do not want to break file names that contain '?' and do not want to require escaping or encoding them because there are too many legacy projects and scripts that will be broken.
