### ISSUE TITLE
Tempo and pitch

### ISSUE THREAD

**Issue by xjiangfan** [mltframework/mlt#366]
I tried to change audio's tempo or pitch by using sox module, but it was not work, could anyone tell me why?
code like this:
```
......
Producer producer(profile, audio_file);
Filter filter(profile, "sox.tempo");
filter.set("effect", "tempo 1.5");
producer.attach(tempo_filter)
......
```

**Comment by ddennedy** [comment]
Sox effects that have temporal side effects such as tempo are not supported. MLT is all about time, and things like that that affect time in ways that MLT does not know about do not work.
