### ISSUE TITLE
The encoder 'aac' is experimental but experimental codecs are not enabled

### ISSUE THREAD

**Issue by cooldog21** [mltframework/mlt#367]
[aac @ 0x7f336c002920] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
consumer_avformat.c: Unable to encode audio - disabling audio output.

FFmpeg  version release-3.2
mlt version 6.6

**Comment by bmatherly** [comment]
This is not an MLT problem. FFmpeg requires you to specify strict=-2 if you want to use experimental codecs. So add strict=-2 to your command.
