### ISSUE TITLE
A suggestion for commit 7a09644 to make more  efficiency when pause

### ISSUE THREAD

**Issue by vvck** [mltframework/mlt#368]
When I saw commit 7a09644，I think it‘s a good improve to consumer.
    But there is still high cpu processing when I set speed to 0 at pause state, 
I found the reason is in func [ melt_consumer_get_frame ], 
Every time  we call it, we will get new source image frome  producer and apply filters whatever the frame is the same.
    So I consider it's a good idea to use the same frame when the speed is 0; 
if we get the frame which is the same position with the last one , 
we should skip apply fitler to new frame and insert the last frame to deque.

**Comment by ddennedy** [comment]
> Every time we call it, we will get new source image frome producer and apply filters

mlt_consumer_get_frame() and related mlt_service.get_frame() virtual functions do NOT get an image and apply filters. They only get a mlt_frame, which does not yet have any media data. Rather, it only has function pointers pushed onto stacks for how to get image and audio data when requested by mlt_frame_get_image() or mlt_frame_get_audio(). 
If you think there is a misunderstanding please supply a patch even if not fully ready to help explain your point.
