### ISSUE TITLE
Random pixes when make affine transition with the video  of  9:16 aspect rate 

### ISSUE THREAD

**Issue by vvck** [mltframework/mlt#378]
when I make the affine transition with the two video, the a video' aspect  rate is 16:9 ,the b one' aspect rate is 9:16, there will be random pixes on the second video , it will be only show when I set the "rescale.interp" is "bilinear", the other interpolation is good. 
I think bilinear is useful, beacuse the  nearest interpolation will cost  loss of quality，but the bicubic interpolation is make low performance ，so the bilinear  is balance。

**Comment by ddennedy** [comment]
Please provide a command line or MLT XML that reproduces the issue.

**Comment by ddennedy** [comment]
Here I tried to reproduce it in Shotcut 18.10, but I do not"
![image](https://user-images.githubusercontent.com/1146683/47544022-ddf1b000-d899-11e8-8470-887512c59e1a.png)

And here is my XML.

[mlt_bug_378.mlt.txt](https://github.com/mltframework/mlt/files/2517642/mlt_bug_378.mlt.txt)

**Comment by vvck** [comment]
I don't know what the interpolation  to used in shutcut when making affine transition.
 I use sdl to play the video,  I changed consumer_sdl.c:118 
mlt_properties_set( self->properties, "rescale", "nearest" );  to 
mlt_properties_set( self->properties, "rescale", "bilinear" ); 
![good nearest](https://user-images.githubusercontent.com/13618946/47553042-9f5f0280-d938-11e8-945d-fc935d97f225.png)  good for nearest
![bad bilinear](https://user-images.githubusercontent.com/13618946/47553039-9f5f0280-d938-11e8-9f5c-a0aba8c807b8.png) bad for bilinear

my mlt file
[test.xml.txt](https://github.com/mltframework/mlt/files/2518311/test.xml.txt)

**Comment by vvck** [comment]
I try to the other 9:16 video, It's good,.
But I cant't understander why the video  proform like that.  
I upload the video as attachment， you can test it .  
[test1.zip](https://github.com/mltframework/mlt/files/2523385/test1.zip)

**Comment by ddennedy** [comment]
Not seeing it with your test1.mp4 either. The system I used tonight does not have SDL 1.2, so I used sdl2 consumer. Here is my XML based on yours. 
[mytest.xml.txt](https://github.com/mltframework/mlt/files/2523952/mytest.xml.txt)

I am closing this as unreproducible.
