### ISSUE TITLE
The encoder 'aac' is experimental but experimental codecs are not enabled

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#387]
Run into an issue:
```
[aac @ 0x7fe77c202980] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```
Added strict -2 but get another error:
`consumer_avformat.c: Unable to encode audio - disabling audio output.`

**Comment by bmatherly** [comment]
Your syntax is incorrect.
`strict=-2`
Example here:
https://github.com/mltframework/mlt-scripts/blob/master/test/test_avsync.sh#L36
