### ISSUE TITLE
(apply) How to get the root node of the top layer through the child node

### ISSUE THREAD

**Issue by sway913** [mltframework/mlt#391]
I want to get the top node tractor object through the get_image of a filter.

as the picture shows
![node](https://user-images.githubusercontent.com/9814915/50420903-dee09700-0874-11e9-831f-cd26066ebe9a.png)

**Comment by sway913** [comment]
Use 【mlt_frame_get_original_producer(frame)】to get only the upper node, how should I get the top node

**Comment by ddennedy** [comment]
We only use GitHub issues for bug tracking, and this is not a bug. What you ask for is not possible. A tractor is not required or always available. Also, a filter should not be interacting with a tractor.
