### ISSUE TITLE
Code issues and potential bugs

### ISSUE THREAD

**Issue by shlyakpavel** [mltframework/mlt#392]
Hello. I have some notes on the code here. Most of the issues are found by PVS studio static analyzer. I hope some experienced devs find time to check this out
1. Null pointer is freed here
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/linsys/consumer_SDIstream.c#L371
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/linsys/consumer_SDIstream.c#L381
2. Memory is used after being reallocated.
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/framework/mlt_multitrack.c#L434
3. Null pointer is freed here. I guess it should be better to refactor this code so it does not use `goto`
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/framework/mlt_playlist.c#L100
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/framework/mlt_playlist.c#L106-L107
4. `frame` is first used, then checked against null
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/framework/mlt_consumer.c#L805-L807
5. `decklink` is never null as the memory is allocated with 'new' operator. It can throw exception, but not return null https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/decklink/consumer_decklink.cpp#L988
6. Condition is obviously always true as we have already returned from the function otherwise
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/motion_est/producer_slowmotion.c#L286
7. Intention here does not represent the actual code behavior
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/plusgpl/cJSON.c#L166
In fact, `ptr2+=len;` is always executed, no matter what the condition result is.
8. This function does a real mess. It is dangerous to print a string into itself.
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/plusgpl/filter_telecide.c#L122
Refer https://www.viva64.com/en/w/v541/
9. The 'fullname' reference becomes invalid when temporary object returned by a function is destroyed.
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/qt/qimage_wrapper.cpp#L341
Refer http://doc.qt.io/qt-5/qstring.html#querying-string-data
10. This expression has the same condition `oheight <= 6` twice. It's suspicious and probably works not as expected
I guess someone forgot to change `oheight <= 6` into `iheight <= 6`
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/core/filter_resize.c#L78
11. Nonsense
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/plus/filter_affine.c#L40-L43
12. Null pointer dereference
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/plus/filter_spot_remover.c#L232
13. Getting size of a pointer... Wow
https://github.com/mltframework/mlt/blob/fafaa42e72cee6efb093d959829c756d52e067db/src/modules/frei0r/factory.c#L315
I'll try to leave some PRs later

**Comment by shlyakpavel** [comment]
@ddennedy thanks for working on this!
As for 7:
The problem is that code logic does not correspond to intending style (no new line). It is better to move 
`ptr2+=len;`
to a separate line so the code is easier to read and static analysis doesn't fail

**Comment by ddennedy** [comment]
> The problem is that code logic does not correspond to intending style

You mean "indent," but I literally thought you meant "intend" suggesting there was a logic error. :-) Again, since this is not our code, I decline to change it for this minor thing.
