### ISSUE TITLE
Processing with higher color depth?

### ISSUE THREAD

**Issue by unfa** [mltframework/mlt#399]
I've tried using the UM Map effect in Kdenlive, but I've realised that there's not enough color depth to make that useful.

I've rendered a 16-bit-per-pixel TIFF image from Blender, but Kdenlive still treats it like an 8-bit one, resulting in pixelated mapping.

![selection_671](https://user-images.githubusercontent.com/491704/51044536-a3a6cd80-15c1-11e9-90c7-e1c2b770c3e6.png)

Is there a way to fix this problem?

Other times I'd like to be able to use custom 16-bit grayscale bitmaps for compositing, but again - the extra dynamic range is being truncated in Kdenlive.

I assumed this is a MLT thing, am I right?

PS: I know there's "Corners" effect that I could use to achieve what is on that screenshot, but with UV Map I could do so much more than that - this was just the simplest project to learn how to use it.

**Comment by ddennedy** [comment]
MLT uses Qt or GDK Pixbuf to load images, and these are currently limited to 8-bit. Also, MLT has very limited support for >8-bit elsewhere. Of course, higher bit depth support is on almost every video developer's road map whether published or not. This is not a bug and feature requests are not accepted without the code (i.e. pull request).
