### ISSUE TITLE
Can't seek the end of frame in MPEG-4

### ISSUE THREAD

**Issue by vvck** [mltframework/mlt#405]
If a mp4 file 's length is 200, so it‘s in=0, out=199;
I try to seek to 199 frame after open the file, I can't get the image run the command like this:

melt xxx.mp4 in=199 out=199 -consumer sdl;

the picture show is black,but if I play the video from the head, the last frame is good . I know it used the cache, but how can I do make the same with play and seek;

Other crash can appear when seek directly to the the end of the file which the audio stream index =0, the video stream index =1 , and stream.rotate=90

**Comment by ddennedy** [comment]
> Other crash can appear when seek directly to the the end of the file which the audio stream index =0, the video stream index =1 , and stream.rotate=90

I do not reproduce this with my sample vertical video files, but they all have audio_index=1, video_index=0 including files produced by MLT consumer avformat. Open a separate issue if you can provide a sample file or preferably a pull request with the fix.

**Comment by ddennedy** [comment]
> Other crash can appear when seek directly to the the end of the file which the audio stream index =0, the video stream index =1 , and stream.rotate=90

It just so happens I got a file that matches this description yesterday!
https://github.com/mltframework/shotcut/issues/271

It does not crash for me on Linux, but it produces digital noise in the image. It does crash for me on Windows.

**Comment by ddennedy** [comment]
The crash you reported is fixed.

**Comment by vvck** [comment]
I think it' s not the real reason that the video is rotated, When I test the crash , I found the last self->video_frame is end with audio packet,  so I suggest the fix should be like this:

if ( self->video_frame && self->video_frame->linesize[0]
		 && (self->pkt.stream_index == self->video_index)
		 && ( paused || self->current_position >= req_position ) )


@ddennedy

**Comment by ddennedy** [comment]
Why? I do not see anything in this if block that concerns itself with self->pkt. In order to make a change I need a reproducible test case.

**Comment by ddennedy** [comment]
I found a major regression with my commit efe43e2!
After reverting it, I found your suggestion also fixes the crash.
