### ISSUE TITLE
webvfx progress is inconsistent between shotcut & melt

### ISSUE THREAD

**Issue by coolwanglu** [mltframework/mlt#419]
Consider the following mlt fraction
```xml
<producer id="producer0" in="0:0" out="10:0">
  <filter>
    <property name="mlt_service">webvfx</property>
  </filter>
</producer>
<playlist>
  <entry producer="producer0" in="5:0" out="10:0" />
</playlist>
```

What is the expected progress range within the webvfx plugin?

Here's what I tested
1. windows + shotcut 19.01.27: 0.0 - 1.0
2. linux + melt 6.6.0: 0.5 - 1.0

Somehow both makes sense. #1 is more intuitive in GUI, but #2 is more logical and friendly for programming.

**Comment by coolwanglu** [comment]
By progress range I mean the range of the "progress" argument for the webvfx render function.

**Comment by ddennedy** [comment]
There was a change in MLT between 2 & 1 to make 1 the intended result.
