### ISSUE TITLE
consumer deadlock fix

### ISSUE THREAD

**Issue by max-verem** [mltframework/mlt#421]
After taking some tests against head source i found that playback of my clips hangs.

This caused by commit https://github.com/mltframework/mlt/commit/7a09644e0560d4e5032421b7edbdb3dfef708f01#diff-1a56b0854c3579001ff234abcfe80217

In my case i have a empty playlist in paused state (speed == 0) that assigned to consumer.

So, at this code part:

https://github.com/mltframework/mlt/blob/4c5daf91522e304476853eabfd62b6f154f7a504/src/framework/mlt_consumer.c#L834-L851

it filling with ONE frame and awaits until it become lower...

in the same time, code part:

https://github.com/mltframework/mlt/blob/4c5daf91522e304476853eabfd62b6f154f7a504/src/framework/mlt_consumer.c#L1571-L1591

awaits for 10 frames to fill during preroll (property buffer is set 10).

as result we have two threads waiting for different buffer states and no broadcast event happens.

to resolve it, i would propose to drop prefilling in **mlt_consumer_rt_frame**:

```
diff --git a/src/framework/mlt_consumer.c b/src/framework/mlt_consumer.c
index 637f928..3076276 100644
--- a/src/framework/mlt_consumer.c
+++ b/src/framework/mlt_consumer.c
@@ -1570,13 +1570,9 @@ mlt_frame mlt_consumer_rt_frame( mlt_consumer self )

                if ( priv->preroll )
                {
-                       int buffer = mlt_properties_get_int( properties, "buffer" );
-                       int prefill = mlt_properties_get_int( properties, "prefill" );
 #ifndef _WIN32
                        consumer_read_ahead_start( self );
 #endif
-                       if ( buffer > 1 )
-                               size = prefill > 0 && prefill < buffer ? prefill : buffer;
                        priv->preroll = 0;
                }

```

**Comment by ddennedy** [comment]
> i would propose to drop prefilling in mlt_consumer_rt_frame

That is not an acceptable resolution. I need to find a way to reproduce it (melted?) or revert the offending commit. Or perhaps profiling should be skipped when speed == 0.

**Comment by ddennedy** [comment]
I was able to reproduce this in melted with the decklink consumer by:
```
uadd decklink
pause u0
load u0 ....
play u0
usta u0 (does not progress from 0)
stop u0 (deadlock)
```
Please test my change in 6ac737cf16f2e87fdbb818d5f7ff54bebf0b40c3

**Comment by max-verem** [comment]
> Please test my change in [6ac737c](https://github.com/mltframework/mlt/commit/6ac737cf16f2e87fdbb818d5f7ff54bebf0b40c3)

works for me
