### ISSUE TITLE
fatal error: gdk/gdk.h: No such file or directory  #include <gdk/gdk.h>

### ISSUE THREAD

**Issue by jerryshaw12** [mltframework/mlt#429]
factory.c:22:10: fatal error: gdk/gdk.h: No such file or directory
 #include <gdk/gdk.h>

**Comment by ddennedy** [comment]
Not enough information and it (configure and make) works fine on a bunch of operating systems for nightly builds:

- https://github.com/mltframework/mlt/blob/master/.travis.yml
- https://github.com/mltframework/mlt/blob/master/.gitlab-ci.yml
- http://build.mltframework.org
- https://github.com/macports/macports-ports/blob/master/multimedia/mlt/Portfile

The configure script checks for gtk+-2.0 and gdk-pixbuf-2.0 png-config files for development. If you have those installed, you should already have gdk-2.0 as well.
If you do not need the GTK+ 2 module/functionality you can use `--disable-gtk2` with configure.

**Comment by jerryshaw12** [comment]
Nvm, already install mlt from pacman

Pada tanggal Rab, 27 Mar 2019 04.52, Dan Dennedy <notifications@github.com>
menulis:
