### ISSUE TITLE
Faulty Playback

### ISSUE THREAD

**Issue by allanrps** [mltframework/mlt#441]
Playback for all files regardless of file type or resolution is consistently slow and choppy. This is not a typical lag problem due to processing, this is a bug in playback. There is no frame dropping and it is not load dependent. Rendering and all effects and filters seem to function properly. There were several times where the video played back full speed when first running melt from terminal, but after those times all playback has been very consistent and predictable: about 4x slowed down and a little choppy. This may have been after installing movit, or running kdenlive. Playback from within kdenlive has always been this way however. mlt 6.14.0-5 was configured with everything but opencv, ndi, and swfdec. The system is an Arch install with an armv8.2 chip 8x2GHz, no gpu support, and the only functioning video output is opengl. VLC and ffplay functioned properly with all the test files. Thanks for the help

**Comment by allanrps** [comment]
I just checked the verbose output of melt and it shows two counts of "[consumer sdl2] dropped video frame" for every frame. Kdenlive on the otherhand shows full fps playback 95% of the time. The rformance is the same in both applications.

I don't know if this is significant, but audio is not implemented on my system. After ending playback melt issues "[consumer sdl2] audio timed out"

**Comment by ddennedy** [comment]
> I don't know if this is significant, but audio is not implemented on my system.

Yes, that is very significant. Basically, all output on MLT is governed by the consumer, and the SDL consumers use the SDL audio callback to affect the timing. I am not exactly sure what happens when the audio is not working. An alternative consumer that is not available in kdenlive but provides a point of comparison is called xgl. Run `melt -query consumers` to see if it is in your build. It uses OpenGL, but I would have re-read the source code to understand how it regulates timing.

**Comment by allanrps** [comment]
Great, I will divert my attention to implementing audio and then check back. I appreciate the help.

For what its worth using xgl gives the followig error. I will just ignore it for now and get audio working.

X Error of failed request:  GLXBadContextTag
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Serial number of failed request:  40
  Current serial number in output stream:  41

**Comment by allanrps** [comment]
I lost my system trying to implement audio, it'll be some time before I can address this.... But now that I understand what is at play it shouldn't be a problem. Might as well close this, thanks for the help
