### ISSUE TITLE
Any plans to improve documentation and / or source code documentation?

### ISSUE THREAD

**Issue by ryno1234** [mltframework/mlt#448]
First off, fantastic library. Thank you for all the effort in creating this.

Are there any plans to improve the documentation? I feel there are some basic things still missing.

* There is documentation of the C library, but I'm not seeing any documentation around the C++ wrapper.
* Basic things like the string format expected when creating a new producer would be great. Apparently you can provide an argument to the mlt_factory_producer() such as "avformat:path/to/some/file", but I've yet to actually land on any documentation outlining how this works and when it is or isn't required.

There are many other aspects, but just curious if there is any plan to improve docs at all.

Thanks.

**Comment by ddennedy** [comment]
There are no concrete plans, but we are looking for volunteers. There is a [repo](https://github.com/mltframework/mlt_web) for the web site and docs outside of Doxygen.

The C++ wrapper is so thin, it easy to use the C docs and then just look at the C++ headers to see the corresponding methods and parameters.

Good point on the second bullet. The general advice here is to not supply an argument for the second/service parameter as that prevents using something called the `loader` producer (the default producer per [MLT_PRODUCER](https://www.mltframework.org/doxygen/envvars.html)). You almost always want to use the [`loader`](https://www.mltframework.org/plugins/ProducerLoader/) super-producer. One of the most important things it attaches are image and audio conversion filters that allow different services' that operate in different formats work together. Then, I guess you can figure that resource specifications can be prefixed by the name of a producer from the `melt` docs. This is actually handled again by the loader producer, but it is not required unless you are using a generator-style producer (e.g. color). `loader` consults a file named [`loader.dict`](https://github.com/mltframework/mlt/blob/master/src/modules/core/loader.dict) to determine what real producer to use based on wildcard against the resource string.
