### ISSUE TITLE
About error: Failed to load "luma"

### ISSUE THREAD

**Issue by mozgbrasil** [mltframework/mlt#450]
Hello

I am trying to reproduce the following example

https://stackoverflow.com/a/37798198

Using the following command

    melt *.MOV -mixer luma -mix 25 -track tmp.mp3 -consumer avformat:out.avi vcodec=libx264 b=5000k

But the error is being returned

    Invalid mixer ...
    Failed to load "luma"

Alert is also displayed

    [avi @ 0x7fd948000c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

My version

    $ shotcut.melt -version
    melt 6.15.0

Can you help me please

**Comment by ddennedy** [comment]
> *.MOV

You should not use a wildcard in conjunction with `-mix`. It is only going to work with the last two video files, not between everyone which might be what you are expecting.

> `-mixer luma -mix 25`

These two are out-of-order. You must specify `-mix` before `-mixer`.
