### ISSUE TITLE
Can mlt merge two videos that overlap into one video?

### ISSUE THREAD

**Issue by techsin** [mltframework/mlt#456]
Hi,

Nice project. I didn't know about this utility until just now. Looks really good. But I'm wondering, if it's possible to merge N clips into one video minus the parts that repeat.

Clips are saved in alphabetic order.
Clips may have overlapping identical frames. i.e. Video 1: 1-12.  Video 2: 7-25 = 7-12 are overlapping.

**Comment by ddennedy** [comment]
Yes but you must know how much overlap. MLT can not determine that for you. Something like: melt video1 in=0 out=11 video2 in=12 out=24 ...
