### ISSUE TITLE
Strange behaviour on new server

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#461]
On one server it works fine, on new i have issue:
```
melt 
-profile atsc_1080p_30 
"test.jpg" length=120 
-filter crop center=1 
-filter affine transition.geometry="0=-60,0:110%x110%;120=0,0:110%x110%" 
-consumer avformat:"out.mp4" vcodec=libx264 vb=5500k strict=-2
```
![image](https://user-images.githubusercontent.com/17032489/59945698-12d9f500-9471-11e9-9662-a5c5064b239e.png)

It outputs just one frame with image instead of 120 frames with animation..

P.S. When trying to process big project, it just crashes after around ~150 frames without any error, and output file is corrupted...

Any suggestions what can cause this?

**Comment by DangerD256** [comment]
Reinstalled ffmpeg from source, didn't helped also...

**Comment by ddennedy** [comment]
I did not reproduce your problem from the command line you provided, but we do not know your servers and the versions of MLT on them. You should compare them. As you can see here there have been a number of changes in the past few years in the affine transition that powers the filter:
https://github.com/mltframework/mlt/commits/master/src/modules/plus/transition_affine.c

Also, you should check the locale setting on your server. melt is sensitive to the locale for numeric parsing. Thus, the usage of commas in your transition.geometry property might be interpreted incorrectly. Instead of comma as a separator, use a slash:
`transition.geometry="0=-60/0:110%x110%;120=0/0:110%x110%" `
Alternatively, run melt as `LC_NUMERIC=C melt...`

**Comment by DangerD256** [comment]
` melt -profile atsc_1080p_30 "1567580072.jpg" length=120 -filter crop center=1 -filter affine transition.geometry="0=0/0:110%x110%;120=-60/0:110%x110%" -consumer avformat:"1567580072.mp4" vcodec=libx264 vb=5500k strict=-2 -verbose
`
`[mjpeg @ 0x22d1e60] Changeing bps to 8
[mjpeg @ 0x22d82c0] Changeing bps to 8
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
|1=-10| |2= -5| |3= -2| |4= -1| |5=  0| |6=  1| |7=  2| |8=  5| |9= 10|
+-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
+---------------------------------------------------------------------+
|               H = back 1 minute,  L = forward 1 minute              |
|                 h = previous frame,  l = next frame                 |
|           g = start of clip, j = next clip, k = previous clip       |
|                0 = restart, q = quit, space = play                  |
+---------------------------------------------------------------------+
[libx264 @ 0x7f7298201900] using SAR=1/1
[libx264 @ 0x7f7298201900] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x7f7298201900] profile High, level 4.0
[libx264 @ 0x7f7298201900] 264 - core 142 r2495 6a301b6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[mjpeg @ 0x7f726c0035c0] Changeing bps to 8
[mjpeg @ 0x7f726c004e20] Changeing bps to 8
[producer avformat] /home/us3d/tmp/test test, testOLOLO/1567580072.jpg
    checking VFR: pkt.duration 1
[libx264 @ 0x7f7298201900] frame I:1     Avg QP:25.60  size:218545
[libx264 @ 0x7f7298201900] mb I  I16..4:  3.7% 72.8% 23.5%
[libx264 @ 0x7f7298201900] final ratefactor: 33.11
[libx264 @ 0x7f7298201900] 8x8 transform intra:72.8%
[libx264 @ 0x7f7298201900] coded y,uvDC,uvAC intra: 89.8% 71.6% 45.9%
[libx264 @ 0x7f7298201900] i16 v,h,dc,p: 13% 56%  2% 30%
[libx264 @ 0x7f7298201900] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 13% 29% 12%  6%  7%  6%  9%  6% 12%
[libx264 @ 0x7f7298201900] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 44%  5%  4%  6%  5%  6%  4%  7%
[libx264 @ 0x7f7298201900] i8c dc,h,v,p: 42% 36% 14%  8%
[libx264 @ 0x7f7298201900] kb/s:52450.80
[libfdk_aac @ 0x7f7298205200] 1 frames left in the queue on closing
Current Position:          0
`

**Comment by DangerD256** [comment]
On another server all works fine:

> +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
> |1=-10| |2= -5| |3= -2| |4= -1| |5=  0| |6=  1| |7=  2| |8=  5| |9= 10|
> +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+ +-----+
> +---------------------------------------------------------------------+
> |               H = back 1 minute,  L = forward 1 minute              |
> |                 h = previous frame,  l = next frame                 |
> |           g = start of clip, j = next clip, k = previous clip       |
> |                0 = restart, q = quit, space = play                  |
> +---------------------------------------------------------------------+
> [libx264 @ 0x7ff1cc201900] using SAR=1/1
> [libx264 @ 0x7ff1cc201900] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
> [libx264 @ 0x7ff1cc201900] profile High, level 4.0
> [libx264 @ 0x7ff1cc201900] 264 - core 142 r2495 6a301b6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
> [libx264 @ 0x7ff1cc201900] frame I:1     Avg QP:15.47  size:524840
> [libx264 @ 0x7ff1cc201900] frame P:30    Avg QP:12.87  size: 23602
> [libx264 @ 0x7ff1cc201900] frame B:89    Avg QP:23.01  size:  5618
> [libx264 @ 0x7ff1cc201900] consecutive B-frames:  0.8%  0.0%  2.5% 96.7%
> [libx264 @ 0x7ff1cc201900] mb I  I16..4:  1.2% 62.0% 36.7%
> [libx264 @ 0x7ff1cc201900] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4: 26.7%  0.7%  1.8%  0.0%  0.0%    skip:70.7%
> [libx264 @ 0x7ff1cc201900] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8: 23.0%  0.4%  0.1%  direct: 0.7%  skip:75.8%  L0:39.2% L1:55.0% BI: 5.7%
> [libx264 @ 0x7ff1cc201900] final ratefactor: 11.00
> [libx264 @ 0x7ff1cc201900] 8x8 transform intra:61.9% inter:49.6%
> [libx264 @ 0x7ff1cc201900] coded y,uvDC,uvAC intra: 97.4% 80.6% 74.4% inter: 6.6% 3.8% 2.3%
> [libx264 @ 0x7ff1cc201900] i16 v,h,dc,p: 14% 30% 11% 45%
> [libx264 @ 0x7ff1cc201900] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 13% 32% 10%  5%  7%  6%  8%  6% 12%
> [libx264 @ 0x7ff1cc201900] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 17% 35%  6%  5%  8%  6%  8%  6% 10%
> [libx264 @ 0x7ff1cc201900] i8c dc,h,v,p: 36% 39% 16%  9%
> [libx264 @ 0x7ff1cc201900] Weighted P-Frames: Y:0.0% UV:0.0%
> [libx264 @ 0x7ff1cc201900] ref P L0: 95.6%  0.1%  4.1%  0.2%
> [libx264 @ 0x7ff1cc201900] ref B L0: 96.3%  3.6%  0.0%
> [libx264 @ 0x7ff1cc201900] ref B L1: 96.8%  3.2%
> [libx264 @ 0x7ff1cc201900] kb/s:3465.90
> [aac @ 0x7ff1cc205200] 1 frames left in the queue on closing
> Current Position:        119
>

**Comment by DangerD256** [comment]
Install configuration:

> [root@server mlt-6.16.0]# ./configure --enable-gpl --enable-gpl3
> Found gcc version 4.8.5
> Configuring framework:
> Configuring modules:
> Configuring modules/avformat:
> Configuring modules/core:
> Configuring modules/decklink:
> Configuring modules/feeds:
> Configuring modules/frei0r:
> Configuring modules/gtk2:
> - GTK2 components not found: disabling
> Configuring modules/jackrack:
> - jackrack not found: disabling
> - ladspa not found; disabling
> Configuring modules/kdenlive:
> Configuring modules/linsys:
> Configuring modules/lumas:
> Configuring modules/motion_est:
> Configuring modules/ndi:
> - NDI SDK not found: disabling
> Configuring modules/normalize:
> Configuring modules/oldfilm:
> Configuring modules/opencv:
> - not explicitly enabled: disabling
> Configuring modules/opengl:
> - movit not found: disabling
> Configuring modules/plus:
> - libebur128 not found: using internal libebur128
> Configuring modules/plusgpl:
> Configuring modules/qt:
> ./configure: line 43: qmake: command not found
> - Libexif not found, disabling exif features (auto rotate)
> - Qt not found - disabling
> Configuring modules/resample:
> Configuring modules/rtaudio:
> Configuring modules/sdl:
> - SDL development libs not found: disabling
> Configuring modules/sdl2:
> - SDL2 development libs not found: disabling
> Configuring modules/sox:
> - sox not found: disabling
> Configuring modules/swfdec:
> - swfdec not found: disabling
> Configuring modules/videostab:
> Configuring modules/vid.stab:
> - vid.stab not found: disabling
> Configuring modules/vmfx:
> Configuring modules/xine:
> Configuring modules/xml:
> Configuring mlt++:
> Configuring swig:
> GPLv3 license used
>

**Comment by ddennedy** [comment]
> Current Position: 0
...
> - GTK2 components not found: disabling
> - Qt not found - disabling

There is your problem. Since the frame counter does not advance beyond 0, the length of the image producer is 1 frame because it is using avformat to load the image instead of either GTK2 pixbuf or Qt. The image producers in pixbuf and qt modules make an image 15000 frames long by default but not avformat. You should build with one of the above dependencies. Otherwise if you add `length=15000 out=14999` after the name of the image, then it should work with avformat.
