### ISSUE TITLE
Soundtrack volume changes is using different source files

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#462]
A bit strange issue, i have all sound from videos muted (except first one) and soundtrack attached to whole video and issue that volume is changes to lower on mp4 files than backs on MOV files

https://youtu.be/nMkRVmThJ5E
0:33 (23.MOV) volume up
0:40 (25.mp4) volume down
0:44 (26.MOV) volume up

```
"21 mute.mov"
"22.mp4"   -attach-clip volume gain=0 -mix 7 -mixer luma
"23.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma
"24.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma
"25.mp4"   -attach-clip volume gain=0 -mix 7 -mixer luma
"26.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"27.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"28.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"29.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"30.MOV"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"31.mp4"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"32.mp4"   -attach-clip volume gain=0 -mix 7 -mixer luma  
"33.mp4"   -attach-clip volume gain=0 -mix 7 -mixer luma
...
-audio-track "tmp.mp3" out=4585 
-transition mix in=0 out=4585 a_track=0 b_track=1 
-filter volume level="0=-14;899=-14;914=0;4555=0;4585=-100;"  
-profile atsc_1080p_2997  -consumer avformat:"out.mp4" vcodec=libx264 vb=5500k ab=128k strict=-2
```

Any suggestion?

**Comment by ddennedy** [comment]
I am not completely sure, but quite likely this is due to the default mixing mode of the `mix` transition. There are 3 modes: default, combine, and sum. I recommend that you add `sum=1` after `-transition mix` and test it.
See https://mltframework.org/plugins/TransitionMix/

**Comment by DangerD256** [comment]
Tried `-attach-clip volume gain=0  -transition mix sum=1 -mix 7 -mixer luma` still same issue
also tried `-attach-clip volume gain=0  -mix 7 sum=1 -mixer luma`. Both has same issue...

**Comment by DangerD256** [comment]
Worked, thanks a lot =)
