### ISSUE TITLE
Explicit repository path doesn't work on Windows

### ISSUE THREAD

**Issue by ryno1234** [mltframework/mlt#463]
Related to #459. When calling melt.exe with the new `-repository` argument, the path used is incorrect. This should also address issues with invoking MLT from code as well which I've seen in tests.

I.e. 
```

C:\Clients\MyClient\Projects\VideoGenerator\Dev\ConsoleRunner\build\Debug - Windows\netcoreapp2.2>melt.exe -repository "c:\Clients\MyClient\Projects\VideoGenerator\Dev\ConsoleRunner\build\Debug - Windows\netcoreapp2.2\"
mlt_repository_init: no plugins found in "C:\Clients\MyClient\Projects\VideoGenerator\Dev\ConsoleRunner\build\Debug - Windows\netcoreapp2.2c:\Clients\MyClient\Projects\VideoGenerator\Dev\ConsoleRunner\build\Debug - Windows\netcoreapp2.2""
```

**Comment by ddennedy** [comment]
OK, but you might still have problems loading frei0r and ladspa plugins and movit shaders if you need those and continue to not follow the directory layout MLT wants on Windows. It expects those in subdirectories of the executable:
- lib/frei0r-1
- lib/ladspa
- share/movit
I may not be willing to fix those for you, and you'll have to submit a patch.

**Comment by ryno1234** [comment]
Thanks @ddennedy . Would you mind pointing me in the right direction regarding frei0r / movit where the code expects a certain directory? We may have to submit a patch for it if we find it's not working.

.Net Core specifically has its executable reside in the `c:\Program Files\dotnet\dotnet.exe`, so attempting to find the plugins and related shared objects relative to the executable simply won't work unless we were to create a self-contained deployment which I don't want to do unless I have to.

Thanks!

**Comment by ddennedy** [comment]
These use a global MLT property named `MLT_APPDIR`. This is currently determined from the exe directory. We can add an environment variable MLT_APPDIR to set this and skip its computation if it was set. This will still assume all of those subdirectories mentioned above - they are all relative to MLT_APPDIR. Otherwise, we need to add environment overrides for frei0r and movit (one already exists for LADSPA).
