### ISSUE TITLE
Random melt crashing (Windows)

### ISSUE THREAD

**Issue by ryno1234** [mltframework/mlt#466]
I'm experiencing random crashing of melt while generating a video (SDL2 or avformat output). The crash seems random in that I can adjust a part of the video graph and the crash will no longer happen. For example, 

* I can remove the transitions and the video will generate successfully. 
* I can remove one of the audio tracks and the video will generate successfully.
* I can remove the filter  and the  video will generate successfully. 

Further more, I've found that I can remove `libmltxine.dll` from the plugins and the crash will no longer happen regardless of graph changes. Because this seems random, I'm reluctant to say `libmltxine.dll` is the culprit however.

The melt.exe exit code is -1073741819 which appears to be a Windows "File System Error".

The errors in the Event Log differ depending upon the changes I mentioned above:

**Example 1**

> Faulting application name: melt.exe, version: 0.0.0.0, time stamp: 0x5d28b82d
> Faulting module name: libmltavformat.dll, version: 0.0.0.0, time stamp: 0x5d28b83c
> Exception code: 0xc0000005
> Fault offset: 0x000093a9
> Faulting process id: 0x9380
> Faulting application start time: 0x01d538d8dbaf7b3e
> Faulting application path: > c:\Project\build\melt.exe
> Faulting module path: c:\Project\build\lib\mlt\libmltavformat.dll
Report Id: c57a7257-7555-45f7-a767-82de122d221b
> Faulting package full name: 
> Faulting package-relative application ID: 

**Example 2**

> Faulting application name: melt.exe, version: 0.0.0.0, time stamp: 0x5d28b82d
> Faulting module name: ntdll.dll, version: 10.0.17134.799, time stamp: 0x636bcb43
> Exception code: 0xc0000005
> Fault offset: 0x0004446a
> Faulting process id: 0x5e28
> Faulting application start time: 0x01d538d73122b5a6
> Faulting application path:  c:\Project\build\melt.exe
> Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
> Report Id: 19362017-e30a-46d0-84e2-aa5ed5e83741
> Faulting package full name: 
> Faulting package-relative application ID: 

**Example 3**

> Faulting application name: melt.exe, version: 0.0.0.0, time stamp: 0x5d28b82d
> Faulting module name: avformat-58.dll, version: 58.20.100.0, time stamp: 0x00000000
> Exception code: 0xc0000005
> Fault offset: 0x0018f1c9
> Faulting process id: 0x88c0
> Faulting application start time: 0x01d538d6d2b3c15c
> Faulting application path: c:\Project\build\melt.exe
> Faulting module path: c:\Project\build\avformat-58.dll
> Report Id: 8f18c75f-94c5-473f-b0f2-e28e3e98fcb6
> Faulting package full name: 
> Faulting package-relative application ID: 

Here is an example of a graph that crashes

```XML
<?xml version="1.0" encoding="utf-8"?>
<mlt LC_NUMERIC="en_US" version="6.17.0" root="c:\Project\build" title="Anonymous Submission">
  <profile description="DV/DVD PAL" width="1920" height="1080" progressive="0" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="889" display_aspect_den="500" frame_rate_num="30" frame_rate_den="1" colorspace="601"/>
  <producer id="producer0" title="Music Producer" in="0" out="5569">
	<property name="length">5570</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\music.mp3</property>
	<property name="seekable">1</property>
	<property name="meta.media.sample_aspect_num">72</property>
	<property name="meta.media.sample_aspect_den">72</property>
	<property name="aspect_ratio">1</property>
	<property name="audio_index">0</property>
	<property name="video_index">-1</property>
	<property name="mute_on_pause">1</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <producer id="producer1" in="0" out="97">
	<property name="length">98</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\dialogue01.wav</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <producer id="producer2" in="0" out="90">
	<property name="length">91</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\dialogue02.wav</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <producer id="producer3" in="0" out="87">
	<property name="length">88</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\dialogue03.wav</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <producer id="producer4" in="0" out="95">
	<property name="length">96</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\dialogue04.wav</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <playlist id="playlist1">
	<blank length="31"/>
	<entry producer="producer1" in="0" out="97"/>
	<entry producer="producer2" in="0" out="90"/>
	<entry producer="producer3" in="0" out="87"/>
	<entry producer="producer4" in="0" out="95"/>
  </playlist>
  <producer id="producer5" in="0" out="127">
	<property name="length">128</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\PORTEST\PORTEST_1.mov</property>
	<property name="seekable">1</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <producer id="producer6" in="0" out="186">
	<property name="length">187</property>
	<property name="eof">pause</property>
	<property name="resource">C:\Project\TestingResources\PORTEST\PORTEST_10.mov</property>
	<property name="seekable">1</property>
	<property name="mlt_service">avformat</property>
  </producer>
  <tractor id="tractor0" in="0" out="29">
	<track producer="producer5" in="98" out="127"/>
	<track producer="producer6" in="0" out="29"/>
	<transition id="transition0" out="29">
	  <property name="a_track">0</property>
	  <property name="b_track">1</property>
	  <property name="factory">loader</property>
	  <property name="mlt_service">luma</property>
	</transition>
  </tractor>
  <playlist id="playlist2">
	<entry producer="producer5" in="0" out="97"/>
	<entry producer="tractor0" in="0" out="29"/>
	<entry producer="producer6" in="30" out="156"/>
	<filter id="filter0">
	  <property name="factory">loader</property>
	  <property name="resource">C:\Project\TestingResources\banner\640x360\banner_640x360_%03d.png</property>
	  <property name="mlt_service">watermark</property>
	  <property name="producer.begin">1</property>
	  <property name="producer.autolength">1</property>
	  <property name="composite.valign">bottom</property>
	</filter>
  </playlist>
  <tractor id="tractor10" title="Anonymous Submission" global_feed="1" in="0" out="1246">
	<track producer="producer0" in="0" out="1246"/>
	<track producer="playlist1"/>
	<track producer="playlist2"/>
	<transition id="transition10">
	  <property name="a_track">1</property>
	  <property name="b_track">0</property>
	  <property name="mlt_service">mix</property>
	  <property name="combine">True</property>
	</transition>
  </tractor>
</mlt>

```

**Comment by ddennedy** [comment]
I have not tried to reproduce this yet, but a couple of comments.

> `<profile description="DV/DVD PAL" width="1920" height="1080" progressive="0" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="889" display_aspect_den="500" frame_rate_num="30" frame_rate_den="1" colorspace="601"/>`

This combination of resolution and aspect ratios are a little off. DAR = RES * SAR
More than likely, you want to use `display_aspect_num=16 display_aspect_den=9`
Also, you probably want to use `colorspace=709` instead of 601. That is the standard for HD and non-HDR UHD.

> `<property name="combine">True</property>`

MLT only accepts 1 or 0 for boolean values. Properties passed through to a dependent lib such as  ffmpeg might be different, but that is not the case here. In any case, I have had the most success with `sum=1` instead of using `combine` or default mode.

> Further more, I've found that I can remove libmltxine.dll from the plugins and the crash will no longer happen regardless of graph changes.

Are any of your video clips interlaced? The xine module only provides a deinterlacer, and if you omit it then there is a second priority deinterlacer in the avformat module that MLT (via loader producer per its loader.ini) automatically falls back to using. Thus, you may find it acceptable to omit libmltxine.dll.

**Comment by ryno1234** [comment]
FYI, I made the changes to the profile as you mentioned with no effect on the stability. Interestingly, if I execute the same melt command from shotcut's root directory against my `.mlt` file it runs without issue. Perhaps a have created a corrupt build somehow? Incompatible shared object's? Not sure how that could happen but it is an interesting observation.

**Comment by ddennedy** [comment]
Shotcut is complied using gcc5 and MinGW. How about yours?
-- 
+-DRD-+

**Comment by ryno1234** [comment]
Here's what we're using.

> gcc.exe (Rev1, Built by MSYS2 project) 7.4.0
> Copyright (C) 2017 Free Software Foundation, Inc.

**Comment by ddennedy** [comment]
That compiler and version should be fine. It is what I use on my Linux development workstation.
FWIW here are how FFmpeg and MLT are configured in our build:

`./configure --prefix=/root/shotcut/shotcut/Shotcut --disable-static --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libmfx --cross-prefix=x86_64-w64-mingw32.shared- --arch=x86_64 --target-os=mingw32 --pkg-config=pkg-config`

`./configure --prefix=/root/shotcut/shotcut/Shotcut --enable-gpl --enable-gpl3 --without-kde --disable-sdl --disable-dv --disable-kino --disable-vorbis --gtk2-prefix="/root/shotcut/shotcut/Shotcut" --target-os=MinGW --target-arch=x86_64 --rename-melt=melt.exe`

**Comment by ryno1234** [comment]
This is ours:

> ./configure --enable-debug --arch='i686' --prefix=$HOME/build/mlt/ --target-os=MinGW --enable-gpl --enable-gpl3 --without-kde --disable-sdl --disable-decklink --disable-frei0r --disable-jackrack --disable-rtaudio

and the compilation error we get (unless we add `--disable-sse`) is:

> cc -c -I../.. -DARCH_X86_64 -Wall -DPIC -march=i686   -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I../../win32  -o transition_matte.o transition_matte.c
transition_matte.c: In function 'copy_Y_to_A_scaled_luma_sse':
transition_matte.c:50:2: error: 'asm' operand has impossible constraints
  __asm__ volatile
  ^~~~~~~
make[2]: *** [../../../config.mak:27: transition_matte.o] Error 1
make[2]: Leaving directory '/home/rgrif/mlt/src/modules/core'
make[1]: *** [Makefile:5: all] Error 1
make[1]: Leaving directory '/home/rgrif/mlt/src/modules'
make: *** [Makefile:9: all] Error 1

**Comment by faridosc** [comment]
Have found a crash in Kdenlive in: MLT src/modules/core/transition_matte.c that might be related?

<pre>
Thread 140 "RenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff71c95700 (LWP 15385)]
0x00007fffd436894e in copy_Y_to_A_scaled_luma_sse (
    alpha_a=0x7fff4f00f310 "QU\376\277\341E\032\v\037\355\377\340\344H*\357HG>\251^\n\001Hw\221\257ȽO\236\276\237\206pC\233\304\026\336\377\373\070\200\060\fݷ\267^\252/Xe\303f\aS~\232z\177\243\216\027\300v@\032\062\246/\337\327\350\300\034N\221Z\204\034;\254_\321a\214=\022_\377\267\243\370\v\020\064\r\210\340\362ȸ\270\246\253ˉ/_O\303\n", 
    image_b=0x7fff3d38f000 "", cnt=-489183) at transition_matte.c:50
50      transition_matte.c: No such file or directory.
(gdb) thread apply all bt


Thread 140 (Thread 0x7fff71c95700 (LWP 15385)):
#0  0x00007fffd436894e in copy_Y_to_A_scaled_luma_sse (alpha_a=0x7fff4f00f310 "QU\376\277\341E\032\v\037\355\377\340\344H*\357HG>\251^\n\001Hw\221\257ȽO\236\276\237\206pC\233\304\026\336\377\373\070\200\060\fݷ\267^\252/Xe\303f\aS~\232z\177\243\216\027\300v@\032\062\246/\337\327\350\300\034N\221Z\204\034;\254_\321a\214=\022_\377\267\243\370\v\020\064\r\210\340\362ȸ\270\246\253ˉ/_O\303\n", image_b=0x7fff3d38f000 "", cnt=-489183) at transition_matte.c:50
#1  0x00007fffd4368bed in copy_Y_to_A_scaled_luma (height=1080, width=1920, stride_b=3840, image_b=0x7fff3d38f000 "", stride_a=1920, alpha_a=0x7fff4f00f310 "QU\376\277\341E\032\v\037\355\377\340\344H*\357HG>\251^\n\001Hw\221\257ȽO\236\276\237\206pC\233\304\026\336\377\373\070\200\060\fݷ\267^\252/Xe\303f\aS~\232z\177\243\216\027\300v@\032\062\246/\337\327\350\300\034N\221Z\204\034;\254_\321a\214=\022_\377\267\243\370\v\020\064\r\210\340\362ȸ\270\246\253ˉ/_O\303\n") at transition_matte.c:129
#2  0x00007fffd4368bed in transition_get_image (a_frame=a_frame@entry=0x7fff4d820230, image=image@entry=0x7fff71c94a78, format=format@entry=0x555559da1dfc, width=width@entry=0x7fff71c94d04, height=height@entry=0x7fff71c94d08, writable=writable@entry=1) at transition_matte.c:185
#3  0x00007ffff6fbb9df in mlt_frame_get_image (self=0x7fff4d820230, buffer=0x7fff71c94a78, format=0x555559da1dfc, width=0x7fff71c94d04, height=0x7fff71c94d08, writable=1) at mlt_frame.c:620
#4  0x00007ffff6fbb9df in mlt_frame_get_image (self=0x7fff4d820230, buffer=0x7fff71c94a78, format=0x555559da1dfc, width=0x7fff71c94d04, height=0x7fff71c94d08, writable=1) at mlt_frame.c:620
#5  0x00007fffd3ccfc98 in get_image(mlt_frame, uint8_t**, mlt_image_format*, int*, int*, int) (a_frame=a_frame@entry=0x7fff4c001e00, image=image@entry=0x7fff71c94d18, format=format@entry=0x555559da1dfc, width=width@entry=0x7fff71c94d04, height=height@entry=0x7fff71c94d08, writable=writable@entry=0) at transition_qtblend.cpp:150
#6  0x00007ffff6fbb9df in mlt_frame_get_image (self=0x7fff4c001e00, buffer=0x7fff71c94d18, format=0x555559da1dfc, width=0x7fff71c94d04, height=0x7fff71c94d08, writable=0) at mlt_frame.c:620
#7  0x00007ffff6fd1f4c in producer_get_image (self=self@entry=0x7fff4c00ccf0, buffer=buffer@entry=0x7fff71c94d18, format=format@entry=0x555559da1dfc, width=width@entry=0x7fff71c94d04, height=height@entry=0x7fff71c94d08, writable=writable@entry=0) at mlt_tractor.c:371
#8  0x00007ffff6fbb9df in mlt_frame_get_image (self=0x7fff4c00ccf0, buffer=0x7fff71c94d18, format=0x555559da1dfc, width=0x7fff71c94d04, height=0x7fff71c94d08, writable=0) at mlt_frame.c:620
#9  0x00007ffff6fcf408 in consumer_read_ahead_thread (arg=) at mlt_consumer.c:828
#10 0x0000555555af4ece in RenderThread::run() (this=0x7fff3c0a5020) at /home/farid/kdenlive/src/monitor/glwidget.cpp:1470
#11 0x00007ffff1f82530 in  () at /usr/lib/libQt5Core.so.5
#12 0x00007ffff15484cf in start_thread () at /usr/lib/libpthread.so.0
#13 0x00007ffff1a9c2d3 in clone () at /usr/lib/libc.so.6
</pre>

More info:
https://invent.kde.org/kde/kdenlive/issues/409#note_18933

Hope that helps.
