### ISSUE TITLE
Pango producer works but dynamictext (using Pango fallback) does not.

### ISSUE THREAD

**Issue by ryno1234** [mltframework/mlt#467]
I'm able to use Pango as a producer and successfully render text, but when using the `text` or `dynamictext` filters I do not get text.

As a reminder, it appears these filters try to use QT first and if it cannot be found (which is the case on my system), it falls back to use Pango instead.

Furthermore, I realized while deleting my fontconfig cache directory it is regenerated with ~200 items when running a video generation using the Pango producer but when generating a video trying to use only the filter, I get ~90. Of the 90 items in that cache folder it looks like each of them reference directories which do not have any fonts in them. However, when running the Pango producer (not the filter) and I get the ~200 cache items, some of those items contain references to my actual font folder.

It appears there is something going on where the filter is not finding fonts but the producer is.

Any ideas?

**Comment by ddennedy** [comment]
Sorry, I do not know what is wrong with the fontconfig cache. I do not know much about fontconfig, but I think you should be using `fc-cache` command line utility instead of relying on just-in-time. I did not realize it would even do JIT.

**Comment by ryno1234** [comment]
@ddennedy, thanks for the fix.

**Comment by ryno1234** [comment]
Tested this. It is improved but still not working. I at least now get Pango text using the filter. However, I'm only getting the words "text" in the upper-left of my video despite setting the argument, etc.
I've tried changing:

- Font Size
- Font Face
- Argument
- Halign
- Valign

All with no affect. I tried looking at the source code but I'm not familiar enough with the pipeline to confidently make the fix here.

**Comment by ddennedy** [comment]
Fixed

**Comment by ryno1234** [comment]
Beat me to it. Thanks.

**Comment by ddennedy** [comment]
This is a rather complex area with composition of services and tricks to handle multiple render threads. No doubt it would have taken you a long time.
