### ISSUE TITLE
webvfx - frames per second issue

### ISSUE THREAD

**Issue by andchir** [mltframework/mlt#468]
Hello. Thank you for your excellent work!

I can not understand how I can avoid this problem. 
My command:
~~~
/path/to/Shotcut/Shotcut.app/qmelt \
-progress \
-track \
"/path/to/video.mp4" out=200 \
-track \
-producer webvfx:"plain:/path/to/animation.html" transparent=1 out=200 \
-transition frei0r.cairoblend automatic=1 mode=normal \
a_track=0 b_track=1 \
-profile atsc_720p_25 \
-consumer avformat:"/path/to/out.mp4" \
vcodec=libx264 vb=1228800 acodec=aac ab=128k
~~~
Result:
https://www.dropbox.com/s/jv1ubcukdo5pkl9/demo-anim3-25fps.mp4?dl=0
I get too fast animation (3.5 sec).

But if I change the video ("/path/to/video.mp4") to the image ("/path/to/image.jpg"), then the animation speed is normal (6 sec).
https://www.dropbox.com/s/4ni82ms6lk1xml8/demo-anim3-image-25fps.mp4?dl=0

I have not found a way to avoid this.
I also noticed that the speed of animation playback on a web page depends on the FPS of the video on another (background) track.

**Comment by ddennedy** [comment]
You must use the WebVfx JavaScript extension for animation timing to work correctly.
See this page for more explanation: https://shotcut.org/howtos/tumult-hype/
See this page for more official documentation: https://www.mltframework.org/doxygen/webvfx/effects_authoring.html
Shotcut include a Text: HTML filter template that includes a Web Animations API polyfill for WebVfx.
Lastly, a Shotcut user has created a helper script to use CSS animation with Web Animations and WebVfx: http://www.elusien.co.uk/shotcut/animations/index.html
