### ISSUE TITLE
Output format in avformat presets / Matroska output

### ISSUE THREAD

**Issue by logiclrd** [mltframework/mlt#477]
I wish to use Kdenlive and directly render output to MKV files. I am currently unable to do this. I believe the culprit is the line "f=mp4" at the top of each of the MLT avformat preset files involved (e.g. `x264-medium`). In my experimentation with a Kdenlive installation, simply removing "f=mp4" entirely from the MLT avformat preset files had the following effects:

1. Kdenlive can pass a value such as "f=mp4" or "f=mkv" to MLT when rendering based on the user's input, and it is respected by MLT and determines the output format.

2. If no value is supplied, the MLT consumer appears to autoselect a format based on the target filename supplied, e.g. in the absence of an `f=` option, if `Output.mp4` is supplied then it writes an MPEG-4 container, and if `Output.mkv` is supplied then it writes a Matroska container.

3. If no value is supplied and the filename doesn't have a recognized extension, then MLT seems to fall back on an MPEG-2 container.

Would it be reasonable to suggest/request that the preset files have the `f=mp4` removed from them for future releases? This would mean that Kdenlive versions based on those releases would no longer force all output to MP4 containers regardless of filename and in spite of `f=mkv` in a custom render format definition. I don't know if there is other significant fallout, I guess perhaps if someone is using MLT to produce files with non-standard/non-existent extensions, or even directly sending MLT's output to a device instead of a file, then they might be depending on `f=mp4` in the preset?

In my experimentation and personal use, MP4 containers don't seem to be playable prior to the completion of the render, whereas MKV output can be played as it is being written when the file is only partially complete. It is this flexibility that I am in search of. :-)

**Comment by ddennedy** [comment]
Any value in a preset can be overridden. Why is kdenlive forced to use the value in the preset? Maybe this is a kdenlive problem.
I am not going to remove these lines as Shotcut uses them to preload the container format selection when the user chooses a preset. I am not going to change Shotcut and leave it to chance based on hoping the user enters a known extension.

**Comment by logiclrd** [comment]
Okay, then I think it is a bug in the MLT code. If the preset file says `f=mp4` and the MLT script says `<consumer f="mkv" ...`, then it writes an MP4 file, not an MKV file.

**Comment by ddennedy** [comment]
It could be a bug in the xml producer. What is the rest of that consumer element? I am not a kdenlive developer.

**Comment by ddennedy** [comment]
The xml author should put the `properties` attribute before any overrides.

**Comment by logiclrd** [comment]
Ahh, that'll be it, then. Looks like Kdenlive reorders what's in the UI. Based on this:

![image](https://user-images.githubusercontent.com/2349379/65311446-fa53a680-db55-11e9-8c65-19acfea896b1.png)

It wrote this XML:
```
 <consumer f="mkv" g="120" properties="x264-medium" crf="9" global_quality="500" meta.preset.extension="mkv" target="OutputFileName.mkv" threads="1" real_time="-1" mlt_service="avformat" vcodec="libx264" ab="256000" preset="veryslow" acodec="aac" me_method="umh" in="0" out="3781"/>
```

At a guess, could be wrong, but I suspect it's throwing it into a dictionary and then enumerating it back out and getting a completely unpredictable order.

So, if Kdenlive learns to not put `f="mkv"` (or, indeed, anything) before `preset=...`, then the problem should go away?

**Comment by logiclrd** [comment]
Dug into it a bit further, Kdenlive is using `QDomDocument` to model the XML in-memory before writing it out, and I easily found tons of posts/issues/bug reports about Qt 5 introducing unpredictability into XML attributes. The Qt team's response seems to be "the XML standard says that attribute order doesn't matter, and we have our reasons for making our DOM objects behave this way, so you're just going to have to deal with it." I guess this means that `QDomDocument` is fundamentally unsuitable for creating MLT scripts, where the attribute order very much does matter.

**Comment by j-b-m** [comment]
in Kdenlive, main.cpp we have this:

    // Force QDomDocument to use a deterministic XML attribute order
    qSetGlobalQHashSeed(0);

Which is supposed to solve the attribute order...

**Comment by logiclrd** [comment]
From what I've read, this doesn't actually produce a predictable order, merely a _repeatable_ order. In practice, it seems that the randomization produced with a seed of 0 puts a couple of options including `f=mkv` _before_ `properties=x264_medium`. I suppose it might be possible to experimentally determine a specific `QHash` seed that gives `"properties"` a lower value (with its current implementation) than other attribute names, guaranteeing it goes first. But that seems fragile and unmaintainable, and it feels much more "correct" to rewrite that particular XML document generation to not use `QDomDocument` at all. I have proposed this in Kdenlive bug [411260](https://bugs.kde.org/show_bug.cgi?id=411260).

**Comment by ddennedy** [comment]
I will make a change in MLT to read the properties attribute first and then all the others.

**Comment by logiclrd** [comment]
Oh, nice! Yeah, that makes XML documents that are semantically identical as far as the XML standard is concerned produce the same behaviour within MLT. I like that :-) Thanks!
