### ISSUE TITLE
melt video playback not working

### ISSUE THREAD

**Issue by paperbenni** [mltframework/mlt#480]
Specifying a consumer like avformat works, but the default sdl one shows up as an empty window. audio playback works. 
WM is dwm
OS: Arch
GTX 1060 proprietary drivers
ryzen 1700
I tried killing the compositor, no difference. 
sdl is installed, melt from the arch repo.

**Comment by ddennedy** [comment]
duplicate of #449

**Comment by ddennedy** [comment]
Fixed in cb0ff75
