### ISSUE TITLE
WebVfx installation and usage

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#481]
Installed WebVfx with: (had to copy .pc files to /usr/share/pkgconfig, setting directory with variable didn't helped)
```
/usr/bin/qmake-qt5 -r PREFIX=/usr/local
make install
```
```
melt -query transition=webvfx
# No metadata for transition "webvfx"
```
```
xvfb-run -a qmelt -query filter=webvfx
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
# No metadata for filter "webvfx"
```

MLT installation:
```
./configure --enable-gpl3 --enable-opengl
Found gcc version 4.8.5
Configuring framework:
Configuring modules:
Configuring modules/avformat:
Configuring modules/core:
Configuring modules/decklink:
Configuring modules/feeds:
Configuring modules/frei0r:
Configuring modules/gtk2:
- Libexif found, enabling auto rotate
Configuring modules/jackrack:
- jackrack not found: disabling
Configuring modules/kdenlive:
Configuring modules/linsys:
Configuring modules/lumas:
Configuring modules/motion_est:
Configuring modules/ndi:
- NDI SDK not found: disabling
Configuring modules/normalize:
Configuring modules/oldfilm:
Configuring modules/opencv:
- not explicitly enabled: disabling
Configuring modules/opengl:
- movit not found: disabling
Configuring modules/plus:
- libebur128 found: using external libebur128
Configuring modules/plusgpl:
Configuring modules/qt:
- Libexif found, enabling auto rotate
- Qt version 5.x detected
- fftw found, enabling lightshow
Configuring modules/resample:
Configuring modules/rtaudio:
Configuring modules/sdl:
 - using SDL version 1.2.15
Configuring modules/sdl2:
 - using SDL version 2.0.10
Configuring modules/sox:
Configuring modules/swfdec:
- swfdec not found: disabling
Configuring modules/videostab:
Configuring modules/vid.stab:
- vid.stab not found: disabling
Configuring modules/vmfx:
Configuring modules/xine:
Configuring modules/xml:
Configuring mlt++:
Configuring swig:
GPLv3 license used
```

How can i use html transition between two movie clips in command line?
https://www.mltframework.org/doxygen/webvfx/examples_2transition-shader-crosszoom_8html-example.html

`melt 1.mp4 2.mp4 -mix 30 -mixer webvfx:transition.html`
or
`melt 1.mp4 2.mp4 -mix 30 -transition webvfx:transition.html`
can't find clear info about that...

And how to make webvfx overlay html as in shotcut to render html with text animation? `-filter watermark...` ?

(CentOS7)

**Comment by DangerD256** [comment]
Project is alive? No any answer within one month...(

**Comment by ddennedy** [comment]
We only use this for bug tracking, and not only is this not a bug, but there is a separate webvfx project. No one has volunteered to help you build. If you pay attention to the qmake output from webvfx, it provides a hint that you need to set a qmake variable to get the MLT components.

**Comment by ddennedy** [comment]
https://github.com/mltframework/webvfx

**Comment by DangerD256** [comment]
> https://github.com/mltframework/webvfx#building

Used this, installed, didn't show any error that mlt is not found as before, but still doesn't works...

Is there any precompiled package for ubuntu?
