### ISSUE TITLE
LV2 audio effects?

### ISSUE THREAD

**Issue by mxmilkb** [mltframework/mlt#486]
[LV2](http://lv2plug.in/) is an open multiplatform plugin format. Existing plugins cover various forms of EQ, compression, noise reduction, and other types of processing. Enabling the processing of audio tracks by LV2 plugins by MLT would allow for a great variety of creative opportunities. Related information on the [GH wiki](https://github.com/drobilla/lv2/wiki).

**Comment by ddennedy** [comment]
Thank you for your interest in MLT, but we do not accept feature requests without a pull request. LV2 is already on my long to do list, but not a high priority personally.

**Comment by faridosc** [comment]
Hi Dan,

Is there a roadmap somewhere?

Thanks

**Comment by richardpl** [comment]
avfilter supports lv2 already to some extent.
