### ISSUE TITLE
Lost alpha channel when synthesizing tracks?

### ISSUE THREAD

**Issue by 599316527** [mltframework/mlt#492]
I used `melt` to put a png image with alpha channel over a jpg image with following comand:

```
melt -track xxxx.jpg out=:5.0  -track -blank :1.0 xxxx.png out=:4.0 
```

<img width="739" alt="Screen Shot 2019-10-29 at 18 14 41" src="https://user-images.githubusercontent.com/1331413/67760814-f84a0500-fa7c-11e9-9aac-258dab9980f7.png">

It didn't work as expected. Any other parameter is required to apply alpha channel to the process of tracks synthesis?

**Comment by ddennedy** [comment]
You need to use a transition to blend video or mix audio. Some transitions that do basic video blending are composite, qtblend, and frei0r.cairoblend.
