### ISSUE TITLE
Build fails with --enable-lumas

### ISSUE THREAD

**Issue by luigino** [mltframework/mlt#502]
mlt 6.18.0 on openSUSE Tumbleweed, see [log](https://github.com/mltframework/mlt/files/3839762/mlt_6.18.0.txt).

**Comment by ddennedy** [comment]
I am not reproducing a problem locally. I do not know why it failed. You should `ls -aF src/modules/lumas` to diagnose. I suspect that the create_lumas script did not execute for some reason. Are you sure you need to `--enable-lumas`?

**Comment by luigino** [comment]
The luma executable could not find a shared linked library. I added:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../framework`
to create_lumas to fix this.

> Are you sure you need to --enable-lumas?

Not quite sure, but I kept them for continuity.
