### ISSUE TITLE
How to convert video edit friendly format? 

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#503]
The problem is that on some videos timewarp produces white screen.
Which codec or format I should use?

**Comment by ddennedy** [comment]
In Shotcut see Properties > menu > Convert to Edit-friendly.... It offers 3 choices: lossy high quality H.264, visually lossless ProRes, or lossless Ut Video. The code to generate ffmpeg command lines is
https://github.com/mltframework/shotcut/blob/master/src/widgets/avformatproducerwidget.cpp#L676

You can also view the Shotcut log after using this function to see the command line.
