### ISSUE TITLE
mlt shows no codecs on Fedora 30

### ISSUE THREAD

**Issue by ice0** [mltframework/mlt#504]
Hi!

I try to play sound using MLT on Fedora.

```
mlt-melt ./sound-48000.wav
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
Failed to load "./sound-48000.wav"
Failed to load "./sound-48000.wav"
```

This is a raw wav file without any compression.  ([sound-48000.wav.zip](https://github.com/synfig/synfig/files/3851090/sound-48000.wav.zip))

So i try to look on list of available codecs:
```
mlt-melt -query "audio_codecs"
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
# No audio codecs - failed to load avformat consumer
```

and next i found [this](https://bugzilla.redhat.com/show_bug.cgi?id=1394801)

As I understand it, the main problem is that the ffmpeg library is not available in Fedora.
Maybe this problem can be solved using other compilation options? We only need wav and ogg support.

**Comment by bmatherly** [comment]
We do not maintain the packages. You should talk to the packager for your distribution.

It looks like there are packages on RPM fusion:
https://admin.rpmfusion.org/pkgdb/package/free/ffmpeg/
https://admin.rpmfusion.org/pkgdb/package/free/mlt-freeworld/

Or, we provide a convenience script that makes it easy to build yourself:
https://github.com/mltframework/mlt-scripts/blob/master/build/build-melt.sh

**Comment by ice0** [comment]
Yes, I know that you do not maintain packages. The question was: is it possible to play sound using MLT if ffmpeg is not available? If yes, then I will ask the maintainer to change MLT build options, if not - then this does not make sense.

**Comment by ddennedy** [comment]
There is a vorbis module that relies upon libvorbis and libvorbisfile, but it is deprecated. Nothing built in for WAV.

**Comment by ice0** [comment]
Thanks, Dan!

**Comment by sergiomb2** [comment]
> We do not maintain the packages. You should talk to the packager for your distribution.
> 
> It looks like there are packages on RPM fusion:
> https://admin.rpmfusion.org/pkgdb/package/free/ffmpeg/
> https://admin.rpmfusion.org/pkgdb/package/free/mlt-freeworld/
> 
> Or, we provide a convenience script that makes it easy to build yourself:
> https://github.com/mltframework/mlt-scripts/blob/master/build/build-melt.sh

I'm Fedora / RPMFusion package maintainer , I will look for that script . 
Fedora Design suite ask me to add MLT to Fedora , but we can't add avformat (because depends on ffmpeg) on Fedora  , so we do, on RPMFusion mlt-freeworld, where remove all except avformat part .
So I enable libvorbis ? 
Thank you.
