### ISSUE TITLE
bug from Fedora: mlt-melt doesn't play sounds

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#505]
https://bugzilla.redhat.com/show_bug.cgi?id=1772924

Any idea what might be ? issue is not a regression, mlt-6.16.0 and mlt-6.18.0 have the same issue

**Comment by sergiomb2** [comment]
More links with information HTH 

https://bugzilla.redhat.com/show_bug.cgi?id=1724862
https://github.com/synfig/synfig/issues/863

**Comment by ddennedy** [comment]
Nothing in your bugs mention testing with mlt-melt command line utility. Did you test with that? Quite likely it is SDL integration problem. For instance sdl2 is preferred over sdl 1.x now, and MLT can be built for either or both. But if built for SDL 2 only and synfig requests “sdl” it will not be found as only “sdl2” is available. I have never touched synfig code to hello there.

**Comment by ddennedy** [comment]
FYI libmod_avcodec.so is not a part of MLT

**Comment by ice0** [comment]
Hi, Dan!
> Nothing in your bugs mention testing with mlt-melt command line utility.

I mention it [here](https://github.com/mltframework/mlt/issues/504)

**Comment by ddennedy** [comment]
The vorbis module has been deprecated since version 0.9.2 in June 2014. It was deprecated because I no longer want to maintain it, and it is redundant with the avformat module for vast majority of users who also need the libavformat. I have not removed it, but this means it no longer builds by default.  You can build it by adding dependencies libvorbis and libvorbisfile and by adding the step `make -C src/modules/vorbis` .

**Comment by sergiomb2** [comment]
Confirmed , mlt without ffmpeg doesn't play sounds .
So is not a issue

**Comment by ddennedy** [comment]
I am willing to take our vorbis module out of deprecation for the next release if it helps Fedora.

**Comment by ice0** [comment]
That will be awesome!

**Comment by sergiomb2** [comment]
> I am willing to take our vorbis module out of deprecation for the next release if it helps Fedora.

Thanks for the commit, I enabled vorbis now.
At least in some distros , ffmpeg is not consider complete free , so for the purists of open source it may be useful not just for Fedora , I think.
