### ISSUE TITLE
mkv not returned by consumer->get_data("f") after f=list

### ISSUE THREAD

**Issue by logiclrd** [mltframework/mlt#507]
I'm trying to figure out why Kdenlive reports that MKV is an invalid format, even though due to another bug it will still let you use it and it does actually work. I've come here because it looks like Kdenlive's behaviour is the result of MLT not reporting MKV as a supported format.

I took a peek into how Kdenlive determines that apparently MKV isn't supported, and the Kdenlive code is making the following calls to try to get a list of valid values for the "f" parameter:
```
    auto *consumer = new Mlt::Consumer(p, "avformat");

    consumer->set("f", "list");
...
        Mlt::Properties formats((mlt_properties)consumer->get_data("f"));
...
        for (int i = 0; i < formats.count(); ++i) {
            supportedFormats << QString(formats.get(i));
        }
```
Based on this, I infer that `consumer->get_data("f")` is not returning "mkv" as a supported value. Is this expected? Is Kdenlive doing the wrong thing here?

I tried to write a test app to do this sequence in isolation, using Ubuntu packages on Windows 10 WSL Ubuntu, but the resulting app gets zero formats back from `get_data("f")`. I'm not sure whether this means I'm doing it wrong, or Windows 10 WSL Ubuntu isn't doing a good enough of being a native Linux, or whether that's why Kdenlive thinks MKV isn't valid: because it doesn't think _anything_ is valid.

My test:
```
logiclrd@RESONATOR:~/testmlt$ cat test.cc
#include "mlt++/Mlt.h"

#include <iostream>

using namespace std;

int main()
{
    cout << "start of main" << endl;

    Mlt::Factory::init();

    cout << "factory initialized" << endl;

    Mlt::Profile p;

    cout << "profile created" << endl;

    auto *consumer = new Mlt::Consumer(p, "avformat");

    cout << "consumer created" << endl;

    consumer->set("f", "list");

    cout << "consumer f set to list" << endl;

    Mlt::Properties formats((mlt_properties)consumer->get_data("f"));

    cout << "formats properties object processed, count: " << formats.count() << endl;

    for (int i=0; i < formats.count(); i++)
        cout << i << ": " << formats.get(i) << endl;
}

logiclrd@RESONATOR:~/testmlt$ make
g++ -o test test.cc -I/usr/local/include/mlt -lmlt -lmlt++ -g
logiclrd@RESONATOR:~/testmlt$ ./test
start of main
factory initialized
profile created
consumer created
consumer f set to list
formats properties object processed, count: -1
logiclrd@RESONATOR:~/testmlt$
```

**Comment by ddennedy** [comment]
“mkv” is not valid per ffmpeg; it must be “matroska”. MKV is an optional file make extension.

**Comment by logiclrd** [comment]
Hmm, interesting, okay! Curious that setting `f=mkv` _still actually works_. This seems like a consistency bug. But, it's a consistency bug in ffmpeg, then? FFmpeg gives MLT a list of formats that doesn't include "mkv", but then still "does the right thing" if you say it anyway? I guess there isn't a lot MLT can do about that, if that's the case. :-P
