### ISSUE TITLE
cmake: cannot create ALIAS target "sdl2"

### ISSUE THREAD

**Issue by Chaz6** [mltframework/mlt#509]
When running cmake, the following output is produced:-

```
CMake Error at src/modules/sdl2/CMakeLists.txt:3 (add_library):
  add_library cannot create ALIAS target "sdl2" because target "SDL2::SDL2"
  is imported but not globally visible.
```

CMake version 3.4.16 provided by cmake3-3.14.6-2.el7.x86_64 on CentOS 7.7.1908 64-bit.

**Comment by vpinon** [comment]
Hello,
On my current machine SDL2::SDL2 is not even defined,
is this patch working for you?
Thanks for your report and tests,
Vincent

**Comment by Chaz6** [comment]
Hiya, sorry I have had not chance to test but the patch looks good.
