### ISSUE TITLE
Null pointer dereference in `mlt_filter_process()`

### ISSUE THREAD

**Issue by LebedevRI** [mltframework/mlt#514]
With mlt git master + shotcut git master, i'm hitting an immediate segfault upon first first project creation and first video file load.
```diff
diff --git a/src/framework/mlt_filter.c b/src/framework/mlt_filter.c
index aea134f9..bdc84678 100644
--- a/src/framework/mlt_filter.c
+++ b/src/framework/mlt_filter.c
@@ -309,7 +309,7 @@ mlt_frame mlt_filter_process( mlt_filter self, mlt_frame frame )
        // Save the position on the frame
        mlt_properties_set_position( MLT_FRAME_PROPERTIES( frame ), name, position );
 
-       if ( disable || self->process == NULL )
+       if ( disable || self == NULL || self->process == NULL )
        {
                return frame;
        }
```
As it is evident from the diff, the problem is null pointer deference in `self->process`:
```
(gdb) bt full
#0  0x00007ffff7f9390d in mlt_filter_process (self=0x0, frame=0x7fff881ac500) at mlt_filter.c:312
        properties = 0x0
        disable = 0
        unique_id = 0x0
        position = 0
        name = "pos.(null)\000\367\377\177\000\000\240\233\a\225\377\177\000\000?rUUU\000\000\300\233\a\225\377\177\000\000\000\000\000\000\377\177\000\000\340I\000\210\377\177\000\000t\032\370\367\000\000\000"
#1  0x000055555571d7ff in  ()
#2  0x0000555555718ffe in  ()
#3  0x00005555555ff3c1 in  ()
#4  0x00007ffff6087d52 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff60848d2 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff5aaffb7 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff5bc72df in clone () at /lib/x86_64-linux-gnu/libc.so.6
```
The rest of `thread apply all bt full`: [mlt-null-deref.txt](https://github.com/mltframework/mlt/files/4032075/mlt-null-deref.txt)

I don't know whether this is the bug itself, or the bug is elsewhere and that bug should not have been reached, thus i'm filing an issue and not submitting a pull request.

**Comment by ddennedy** [comment]
I am willing to accept that change, but this may be happening because your configuration of MLT does not include a filter that Shotcut is expecting. Shotcut is not written to support every possible configuration of MLT. The configuration it expects is that in [scripts/build-shotcut.sh](https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh) and in [flathub](https://github.com/flathub/org.shotcut.Shotcut/blob/master/org.shotcut.Shotcut.yaml).
