### ISSUE TITLE
Wrong filter scaling with nightly

### ISSUE THREAD

**Issue by Photosounder** [mltframework/mlt#517]
Michel Rouzic here, there's a new problem with the nightly, a problem that wasn't there with v19.12.31 but is there when opening my project in v20.01.27, in my video (https://www.youtube.com/watch?v=0uTAcJBhhZk) the first two scenes are PNGs, the first with "Rotate and Scale" applied and the second with "Size and Position" applied. In the 20.01.27 nightly both images appear much smaller, like roughly half the original size. If I disable the filter "Size and Position" the image fills the screen normally, but if it's turned on it becomes inexplicably much smaller without fitting the white selection rectangle. Compare with the YT video: https://www.mediafire.com/file/yxim08yy7p1vuil/shotcut_1_v20.01.27_cut.mp4/file

I tried posting this on the forum but the links tripped the spam detection and even hid my previous posts.

**Comment by ddennedy** [comment]
nightly build to test http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-200128.zip
