### ISSUE TITLE
Composite transition - unable to scale more than 100% and how to add transition for both clips

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#519]
1st issue i have that i'm unable to scale video more than 100%

```
melt \
21.mp4 \
-track \
-blank 60 \
22.mp4 \
-filter boxblur start=10 end=1 in=60 out=70 \
-transition \
composite in=60 out=70 a_track=0 b_track=1 \
start=50%/50%:0x0:100 \
end=0/0:200%x200%:100 \
-consumer avformat:out32.mp4
```

The effect i'm trying to achieve is too zoom in 1st track to 400% and than next track zoom out from 400% to 100%, is there any way i can achieve this with this transition?

**Comment by ddennedy** [comment]
By default, composite treats the geometry as a bounding rectangle and only downscales content to fit inside. You need to add `fill=1` if you want to upscale content. This is not documented [here](https://www.mltframework.org/plugins/TransitionComposite/). I just added it, but this part of the web site is not updated until the next release.

**Comment by DangerD256** [comment]
Is there any way to animate both tracks? as it only animates second track...
Or maybe some another tool (not transition) to move video tracks on viewport?

**Comment by DangerD256** [comment]
? :'(
