### ISSUE TITLE
3DL LUTs not supported

### ISSUE THREAD

**Issue by faridosc** [mltframework/mlt#525]
Trying to use a .3dl LUT (both in Shotcut and Kdenlive) doesn't work although it seems to be supported in ffmpeg:

https://ffmpeg.org/ffmpeg-filters.html#lut3d-1

**Comment by ddennedy** [comment]
It works for me on supported files, but not all LUTs as they are not all supported by FFmpeg. You need to test a specific LUT in ffmpeg alone first and then provide it here if not working. Reopen when you have done that.
