### ISSUE TITLE
eof=loop in command line application

### ISSUE THREAD

**Issue by andchir** [mltframework/mlt#526]
In the producer we have parameters "length" and "eof". We can repeat the source of the video ``eof=loop``. But in command line it doesn’t work for me.
~~~
melt clip1.mp4 length=400 eof=loop
~~~
Is it possible?

**Comment by ddennedy** [comment]
This is in the [FAQ](https://mltframework.org/faq/#how-do-i-loop-something-indefinitely-on-the-melt-command-line). You have to put `eof=loop` before anything else. The reason is because there is a tractor object created with a duration based on the graph before looping is considered, and the loop in your command line applies to the producer and not the tractor. Setting properties before anything else makes them apply to this hidden tractor.

**Comment by andchir** [comment]
Can you please give an example how to use?
I try to set the parameter to the creation of the track, but the video always stops (pause), but does not repeat.
~~~
melt \
eof=loop -video-track \
"/home/user/clip.mp4" out=527 length=528
~~~

**Comment by ddennedy** [comment]
Remove -video-track

**Comment by andchir** [comment]
~~~
melt \
eof=loop \
"/home/user/clip.mp4" out=527 length=528 \
-profile atsc_720p_25
~~~
Doesn't work, pause only. melt 6.19.0

**Comment by andchir** [comment]
It works if I remove "out".
~~~
melt \
eof=loop \
"/home/user/clip.mp4" length=528 \
-profile atsc_720p_25
~~~
That was the reason. Thanks!

**Comment by andchir** [comment]
But what should I do if I need tracks?
It works:
~~~
melt eof=loop -track \
"/path/to/clip.mp4" length=472 \
-profile atsc_720p_255
~~~
This does not work:
~~~
melt -track "colour:black" out=471 \
eof=loop -track \
"/path/to/clip.mp4" length=472 \
-transition "frei0r.cairoblend" automatic=1 mode="normal" a_track=0 b_track=1 \
-profile atsc_720p_25
~~~

**Comment by ddennedy** [comment]
melt starts out with one track, and `-track` adds a new track. So, if you put nothing before `-track` then you have a track with nothing in it below the new track introduced with `-track`. Also, you did not put `eof=loop` first as I previously instructed. Ultimately, I only use GitHub Issues for tracking hard defects, and I am not going to keep answering your questions. Good luck

**Comment by andchir** [comment]
If this is not a defect, please show me what I need to do? I tried pasting to the beginning and before the transaction. This does not work with multiple tracks.

**Comment by ddennedy** [comment]
Every time you post a new command line showing growing requirements. You have not defined what you need to do other than loop, and I am not here to serve your ever growing requirements. This works for me:
```
melt eof=loop color:red out=200 -track -blank 100 noise: out=200 -transition luma in=100 out=200 -profile atsc_720p_50
```
If you cannot get it to work, then you should consider to render the multitrack composition to a single file and then simply loop that with melt or any other player that supports it.

**Comment by andchir** [comment]
Sorry if I took your time and poorly formulated the question. In the first question, I mentioned the producer and the length parameter. I need to repeat only one video source. Like in this XML:
~~~
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<mlt>
    <producer id="producer0">
        <property name="resource">/path/to/picture.jpg</property>
    </producer>
    <producer id="producer1">
        <property name="resource">/path/to/video.mp4</property>
        <property name="length">400</property>
        <property name="eof">loop</property>
    </producer>
    <playlist id="playlist0">
        <entry producer="producer0" out="100"/>
        <entry producer="producer1" out="400"/>
        <entry producer="producer0" out="100"/>
    </playlist>
    <tractor id="tractor0" in="0" out="600">
        <track producer="playlist0"/>
    </tractor>
</mlt>
~~~
If the video is less than 400 frames, then it repeats. But I think this is not possible on the command line. I will use XML for this.
