### ISSUE TITLE
More flexible affine transform

### ISSUE THREAD

**Issue by cinoss** [mltframework/mlt#527]
I am trying to match 2 shapes in 2 clips by affine transform both of them and transition one to another. Due to strict sequence of applying affine transform matrix ( offset, rorate, scale ) and having screen center as origin for both rotation and scale, it's not trivial to match 2 shape.
I am asking if there is some way for me to change the sequence or pass in the transform matrix directly?

My current workflow is writing python script to generate `.mlt` file and use `melt` for debugging/outputting video file.

**Comment by ddennedy** [comment]
No
