### ISSUE TITLE
melt silent

### ISSUE THREAD

**Issue by Marcuzzz** [mltframework/mlt#530]
This is the command I use:
`['/Applications/Shotcut.app/Contents/MacOS/melt', '8aba6675-d160-4442-9e73-e92e964f9d6e.xml', 'out="761"', '-silent', '-consumer', 'avformat:test.mp4']`

I get a lot of warnings like: 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f9ad700bc00] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]

is there away to hide these warnings?

**Comment by ddennedy** [comment]
Not at the melt command line. `-silent` is not about the log level but about a banner and progress info. You can submit a pull request to make the logging level more configurable than `-debug` or `-verbose`.
