### ISSUE TITLE
Luma module produces rubbish or crashes

### ISSUE THREAD

**Issue by thelazy6** [mltframework/mlt#537]
There are some cases that rendering a luma transition either produces something like 
![vlcsnap-2020-03-28-07h49m17s585](https://user-images.githubusercontent.com/62787185/77817131-b32c0c80-70c8-11ea-8af5-7bfb8af8f56b.png) (it should be a red theatre curtain closing) or simply crashes with a segmentation fault. Kdenlive's preview rendering is subject to the same.
The strange thing is that the error occurs only in few cases even if the same luma transition was rendered successfully before in the same video; it is also unpredictable which of the described cases occur (sometimes it is even different when rendering the same playlist twice).
Tested releases 6.18.0, 6.20.0 and upstream, same problem in all three.

**Comment by faridosc** [comment]
Send me the luma files and the instructions so I can try to generate a crash log.

**Comment by faridosc** [comment]
Do you have Movit (GPU effects) enabled?

**Comment by faridosc** [comment]
Related to: https://github.com/mltframework/mlt/issues/608
