### ISSUE TITLE
Cmake is broken should be removed or fixed

### ISSUE THREAD

**Issue by llelectronics** [mltframework/mlt#538]
I foolishly tried to build 6.20 with cmake. It first ends up as version 6.19 and then kdenlive cannot be build against it. 
So cmake seems to be broken and should be either fixed or removed. 

./configure
make
make install 
worked perfectly fine though.

**Comment by ddennedy** [comment]
There were recent changes and fixes including version in got master. If it does not work for you submit a patch or use configure.

**Comment by vpinon** [comment]
Yes sorry I ran the checks for the commit before 6.20 on my system which was not clean and had another MLT installation that did hide the problem.
Last week I worked in a clean environment, now the CMake base should be better, yet really not deeply tested (only me, on only 2 systems)
