### ISSUE TITLE
[IDEA] Automated multitrack sync feature

### ISSUE THREAD

**Issue by forart** [mltframework/mlt#539]
Hi there, I recently discovered a very cool lib called [Aurio](https://github.com/protyposis/Aurio) "that focuses on audio processing, analysis, media synchronization and media retrieval and implements various audio fingerprinting methods".

As [this video](https://www.youtube.com/watch?v=QXQVPXjR3Lc) demonstrates, it's able - through its GUI called [AudioAlign](https://github.com/protyposis/AudioAlign) - to analyze and align audios from many video takes.

The only drawback is that it has been developed in C# for .NET, so it's Windows-only.

It would be really great to establish some kind of collaboration between projects in order to (finally) obtain a platform-indipendent open source a/v synchronizer.

Hope that inspires.

**Comment by bmatherly** [comment]
In the video they demonstrate how to export from AudioAlign to Sony Vegas. Maybe you could ask the author to add a feature to export to export to .mlt.

Thank you for sharing your idea, but we reserve this issue tracker for bugs. So I will close it.

**Comment by ddennedy** [comment]
I think it is more of a job for an application rather than this framework, and Kdenlive has code for this.

**Comment by forart** [comment]
> Maybe you could ask the author to add a feature to export to export to .mlt.
> 
Well, I believed that would be great if Aurio firgerprint algorithms could be integrated into some platform-indipendent library...

**Comment by bmatherly** [comment]
> Well, I believed that would be great if Aurio firgerprint algorithms could be integrated into some platform-indipendent library...

That is not necessary. In the tutorial the operator aligned the clips in AudioAlign and then exported a project to Vegas. Vegas does not have the Aurio fingerprint algorithm integrated.
