### ISSUE TITLE
mlt-6.20.0 does not install python bindings

### ISSUE THREAD

**Issue by juanitotc** [mltframework/mlt#540]
When compiling mlt-6.20.0 with "--swig-languages=python" the python bindings are not installed with "make install"

I guess the following are required, but are there any others?

site-packages/_mlt.so
site-packages/mlt.py

**Comment by ddennedy** [comment]
We have been through this before, and this is intentional because its locations varies so much by each system. It is job of the package or manual builder to install per the needs.

**Comment by juanitotc** [comment]
Could you at least state what needs to be installed?

**Comment by ddennedy** [comment]
Oh, sure. Copy `_mlt.so` and `mlt.py` to wherever. If you just need it for flowblade, you can copy it to the flowblade code folder:
https://github.com/mltframework/mlt-scripts/blob/master/build/build-flowblade.sh#L999
