### ISSUE TITLE
How to cross compile mlt for ARM based system?

### ISSUE THREAD

**Issue by wjhtinger** [mltframework/mlt#560]
Just armeabi-v7a cpu, is there any guide?

**Comment by ddennedy** [comment]
I am not aware of any, and I am cofounder of 15 years. I would start with a guide for ffmpeg and then bring lessons learned from that to MLT. It may require build and small changes.

**Comment by ddennedy** [comment]
Also the configure and makefiles build system is mature, but the newer CMake-based build might be more easily adapted if you find a guide in that direction. Please, if you make some progress, share the info and changes needed!

**Comment by wjhtinger** [comment]
If the mlt use the standard autotool configure system, the cross comcompile would be easy.
