### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tim-lukacik** [mltframework/mlt#561]
I am using kdenlive (kdenlive-20.04.0b-x86_64.appimage) on Kubuntu 20.04 to stitch some videos together and add a few basic effects.

The project -
1080p 29.97fps
~2.5gb input files, .mov format from iphone 11
~30 minutes final length

When choosing either WebM or MP4 presets (havent tried others) the render kicks off successfully but brings my system to a crawl/crash about halfway through. It starts out using around 1gb of ram and allocates about 20mb a second until it gets to about 22gb and everything gets unstable.

Any ideas?

**Comment by vpinon** [comment]
Hello,
Could you tell which effects & compositions you use? Are you using a language with comma as decimal separator?
Could you generate a "render script" (melt playlist) and share it?

**Comment by tim-lukacik** [comment]
English language. I think I only have used video speed adjustments and mute.

[melt.zip](https://github.com/mltframework/mlt/files/4631896/melt.zip)

I found today that when my system stops responding it actually recovers after waiting 10-15 minutes. Once it has recovered the ram usage of Melt is back at 1gb and counting up again.

**Comment by tim-lukacik** [comment]
I compiled latest kdenlive and the issue persisted. I then compiled melt from latest and now everything is working great.
