### ISSUE TITLE
portability issue: mlt and OpenBSD, mutex initialisation

### ISSUE THREAD

**Issue by marcespie** [mltframework/mlt#567]
The mutex code aborts.

most specifically, pthread_mutex_init does NOT guarantee any mutex type,
and on OpenBSD, the default mutex type is too strict (self-locking doesn't work).

explicitly setting the type to PTHREAD_MUTEX_RECURSIVE makes things work

[src1.txt](https://github.com/mltframework/mlt/files/4667786/src1.txt)
[src2.txt](https://github.com/mltframework/mlt/files/4667787/src2.txt)

**Comment by Ikke** [comment]
There is another instance, which causes kdenlive to hang on start:

```diff
diff -ruN mlt-6.22.1/src/framework/mlt_property.c src2/mlt-6.22.1/src/framework/mlt_property.c
--- mlt-6.22.1/src/framework/mlt_property.c     2020-08-01 20:23:06.000000000 +0200
+++ mlt-6.22.1/src/framework/mlt_property.c     2020-09-18 23:38:45.257937933 +0200
@@ -90,8 +90,11 @@
 mlt_property mlt_property_init( )
 {
        mlt_property self = calloc( 1, sizeof( *self ) );
-       if ( self )
-               pthread_mutex_init( &self->mutex, NULL );
+       if ( self ) {
+       pthread_mutexattr_t ma;
+       pthread_mutexattr_settype( &ma, PTHREAD_MUTEX_RECURSIVE );
+               pthread_mutex_init( &self->mutex, &ma );
+       }
        return self;
 }
```

**Comment by ddennedy** [comment]
Thank you both.
