### ISSUE TITLE
webvfx transition

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#574]
Tried to add transitions using webvfx from here:
http://www.elusien.co.uk/shotcut/gl-transitions/index.html (CrossZoom)

`qmelt 111.mp4 222.mp4 -mix 60 -mixer webvfx:crosszoom.html`

The problem is that transition ends before next video...
https://youtu.be/QuEecjKd5S8

[crosszoom.zip](https://github.com/mltframework/mlt/files/4710023/crosszoom.zip)

Is there any way to use webvfx transitions from command line. I have automated script that create videos.

**Comment by billensley** [comment]
DangerD256, this is a totally inappropriate place to message you however I have a question on a closed question you were asking about on another github project, FabricJS.

**Comment by DangerD1024** [comment]
> DangerD256, this is a totally inappropriate place to message you however I have a question on a closed question you were asking about on another github project, FabricJS.

You can message me to Hangouts (dangerd[at]dangerd.org)

**Comment by DangerD1024** [comment]
Tried several effects, but i have same issue with all of them...
https://dl.dropboxusercontent.com/s/1f6qqox2v8vjg3g/out2.mp4?dl=0

`>melt.exe 24.mp4 25.mp4 -mix 60 -mixer webvfx:gl-transitions-swirl.html`

**Comment by DangerD1024** [comment]
Can anyone help me with that? I can even pay for that =)
