### ISSUE TITLE
if the mlt API can be called in different threads?

### ISSUE THREAD

**Issue by wjhtinger** [mltframework/mlt#577]
Just like, call mlt_consumer_start() in thread A, and call mlt_consumer_stop() in thread B.

**Comment by ddennedy** [comment]
Yes, but in your example you need to add mutex locks around those calls to avoid a crash or an inconsistent state. There can be many things happening within those calls, and these calls do not provide the protections when called from multiple threads. The only API that has such builtin protection when called from multiple threads is mlt_properties.
