### ISSUE TITLE
how to use melt command line to livestream facebook use rtmps?

### ISSUE THREAD

**Issue by leehanse** [mltframework/mlt#584]

**Comment by ddennedy** [comment]
You need to first get it working in ffmpeg and then convert its muxing, encoding, and output protocol/URL specification to properties on the MLT `avformat` consumer: https://www.mltframework.org/plugins/ConsumerAvformat/#plugin-information

Alas, I do not have anything ready to give. I am merely dropping a hint or suggestion.
From [this](https://trac.ffmpeg.org/wiki/EncodingForStreamingSites) FFmpeg Wiki page,
`ffmpeg -f alsa -ac 2 -i hw:0,0 -f x11grab -framerate 30 -video_size 1280x720 \
-i :0.0+0,0 -c:v libx264 -preset veryfast -b:v 1984k -maxrate 1984k -bufsize 3968k \
-vf "format=yuv420p" -g 60 -c:a aac -b:a 128k -ar 44100 \
-f flv rtmp://live.twitch.tv/app/<stream key>`

to melt will be like:
`melt -verbose -profile atsc_720p_30 -consumer avformat:rtmp://live.twitch.tv/app/<stream key> vcodec=libx264 preset=veryfast vb=1984k maxrate=1984k bufsize=3968k g=60 acodec=aac ab=128k f=flv ...`
The remainder in `...` can be anything that MLT can produce like `my.mp4` will decode a video file and automatically scale, pad, and adjust frame rate to fit the `-profile`.
