### ISSUE TITLE
Compiling mlt on windows gives an error

### ISSUE THREAD

**Issue by oan-99** [mltframework/mlt#585]
Hi, I'm using msys2 on windows machine to compile mlt. When I execute `make`, I get this error.
>list='src/framework src/mlt++ src/melt src/modules src/swig profiles'; \
for subdir in $list; do \
        make -s -C $subdir depend || exit 1; \
        make -C $subdir all || exit 1; \
done
make[1]: Entering directory '/d/GithubPulls/mlt/src/framework'
cc -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -DUSE_MMX -mmmx -DUSE_SSE -msse -DUSE_SSE2 -msse2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -DPREFIX_DATA="\"/usr/local/share/mlt\"" -DPREFIX_LIB="\"/usr/local/lib/mlt\""   -c -o mlt_property.o mlt_property.c
In file included from mlt_property.c:28:
mlt_property.h:41:15: error: conflicting types for 'locale_t'
   41 | typedef char* locale_t;
      |               ^~~~~~~~
In file included from /usr/include/inttypes.h:25,
                 from mlt_types.h:34,
                 from mlt_property.h:26,
                 from mlt_property.c:28:
/usr/include/sys/_locale.h:10:28: note: previous declaration of 'locale_t' was here
   10 | typedef struct __locale_t *locale_t;
      |                            ^~~~~~~~
make[1]: *** [<builtin>: mlt_property.o] Error 1
make[1]: Leaving directory '/d/GithubPulls/mlt/src/framework'
make: *** [Makefile:9: all] Error 1

**Comment by a17r** [comment]
Indeed, the same error appears with musl libc on Gentoo Linux: https://bugs.gentoo.org/713938
Alpine Linux applies this patch over current codebase (the link was given to me as a fix for above downstream report):
https://git.alpinelinux.org/aports/patch/testing/mlt/musl-locale.patch?id=d02611584d4b2f693469c72272fe369413139394

Just for reference see previous musl support PR for mlt: https://github.com/mltframework/mlt/pull/298

**Comment by oan-99** [comment]
> 
> 
> Indeed, the same error appears with musl libc on Gentoo Linux: https://bugs.gentoo.org/713938
> Alpine Linux applies this patch over current codebase (the link was given to me as a fix for above downstream report):
> https://git.alpinelinux.org/aports/patch/testing/mlt/musl-locale.patch?id=d02611584d4b2f693469c72272fe369413139394
> 
> Just for reference see previous musl support PR for mlt: #298
Still could not do anything

**Comment by oan-99** [comment]
After lot of digging documentation and web surfing, I solved the problem at last. I am using msys2 for building mlt on windows. So the solution is following:

- Used gcc having 10.* version which is latest as of this(in msys2 repos)
- search for "dlfcn" in msys2 package repos and install that package
- use either msys2 64 bit or 32 bit console. Don't use the general one, the one with nothing mentioned. For me 64 bit worked.
