### ISSUE TITLE
 How to downsize the image before the process of Filters or Transitions?

### ISSUE THREAD

**Issue by wjhtinger** [mltframework/mlt#588]
I input the 1080P video, and do some Filters or Transitions, then display at 720P.
Now the Filters or Transitions are done at 1080P after video decode, the CPU payload is very high!  So, is there any way to control to  resize the image from 1080P to 720P before the Filters or Transitions?

Very thanks.

**Comment by ddennedy** [comment]
See mlt_profile

**Comment by wjhtinger** [comment]
> 
> 
> See mlt_profile

I have set the profile to 1280X720，but no effect on CPU payload changing. I looks like that profile config only affect the consumer，right？

**Comment by ddennedy** [comment]
Yes it uses the CPU. Use a lower resolution if your want to reduce CPU or use something else.

**Comment by wjhtinger** [comment]
> 
> 
> Yes it uses the CPU. Use a lower resolution if your want to reduce CPU or use something else.

If can downsize the resolution to 720P before do  Filters or Transitions?

**Comment by ddennedy** [comment]
That is already what it is doing based on the profile. Consumers do not scale their self.
