### ISSUE TITLE
Affine filter ignoring rescaling interpolation setting

### ISSUE THREAD

**Issue by jonpacker** [mltframework/mlt#590]
When resizing an imagine to fit within a rect using the `affine` filter, I cannot get interpolation to work. It always seems to use "nearest neighbour".

Here is the simple MLTXML file I'm using to test:

```
<mlt>
  <profile frame_rate_num="25" width="960" height="540" sample_aspect_den="1" sample_aspect_num="1" description="output profile" colorspace="709"/>
  <consumer preset="fast" rescale="bicubic" f="mp4" vcodec="libx264"  mlt_service="avformat" ar="48000" ab="384k" channels="2" codec="aac" target="/Users/jonpacker/Downloads/testout.mp4"/>

  <producer id="logo">
    <property name="resource">/Users/jonpacker/Downloads/mlttest/logo.png</property>
  </producer>
  <playlist id="playlist">
    <entry producer="logo" in=":0.00" out=":2.00">
      <filter>
        <property name="mlt_service">affine</property>
        <property name="transition.rect">35%/35%:30%x30%</property>
        <property name="transition.halign">center</property>
        <property name="transition.valign">middle</property>
        <property name="transition.scale">1</property>
        <property name="transition.fill">0</property>
        <property name="transition.rescale.interp">bicubic</property>
        <property name="rescale.interp">bicubic</property>
      </filter>
    </entry>
  </playlist>
</mlt>
```

This gives output which looks like this, which you can see is clearly using nearest neighbour:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/678101/86142760-d87b4d00-baf3-11ea-8d1e-4ff0afa04e31.png">

The closest I have come to solving this on my own is adding an `swscale` or `gtkrescaler` filter after the `affine` filter, which does apply the correct interpolation, however it also has a side affect of losing its aspect ratio and filling the affine filter's rect:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/678101/86143143-5b9ca300-baf4-11ea-98b5-5c69108f9744.png">

Tried to figure this out as much as I could on my own but I've come to a dead end here.

Running on MacOS with the `qmelt` binary from Shotcut.

**Comment by bmatherly** [comment]
Which version of MLT are you using? Maybe you are affected by this?
https://github.com/mltframework/mlt/commit/076b041010c19e62c653a7d96cfb2909369cf62f#diff-e756fe9fe7c174d21ae4b8879d580f63

**Comment by jonpacker** [comment]
That describes exactly my issue, yeah. So I'll assume this is fixed, but not released yet. I am using the `qmelt` binary that comes shipped with Shotcut 20.06.28.

**Comment by ddennedy** [comment]
Your version includes this change, and you are not using a transition. But your XML organization is a little unexpected. Since you have Shotcut you should use it to create the same thing, see if it works, and use its approach to XML.

**Comment by jonpacker** [comment]
Right, that XML was the result of a lot of fiddling to get it to try and produce the results I was expecting 😅.

It actually looks like this is still happening though in my specific situation. If I use `affine` with `scale_x` and `scale_y` set (as Shotcut does), then the interpolation is as expected. However, if I use the `rect` attribute, it goes back to nearest neighbour. Here a file from Shotcut which does much the same thing, but which has been altered to use `rect` in the `affine` filter (plus I've added a consumer that specifies interpolation): https://gist.github.com/jonpacker/9ef02c61f1960b5f564aad7ed7b34d29

**Comment by ddennedy** [comment]
The Size and Position filter in Shotcut uses rect but does not have this problem. Maybe someone will look into this particular combination of parameters some day, but if you want to move ahead now you might try that instead of modifying Rotate and Scale.

**Comment by jonpacker** [comment]
Ok I think I must be going crazy. I went back and fired up Shotcut again and I still can't seem to get it to be using the right interpolation. Here are the steps I took:

1. Add the same image to two video tracks in a new Shotcut project (I used 960x540 as it's easier to see the interpolation)
2. Resize one image to fit within a 300x200 box using the Size and Position filter
3. Resize the other image to be about the same size using the Rotate and Scale filter, and offset it to be next to the first image.
4. Export the file, making sure Interpolation is set to something like Bicubic (not nearest neighbour).

For me, this resulted in an output video with images that look like this, which both seem to be using nearest neighbour to my eye:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/678101/86410618-5fc6ed00-bcbb-11ea-956e-77b12e184f02.png">

Here are both the .mlt project file and the temp file that was passed to qmelt: https://gist.github.com/jonpacker/12109f9b2c8739babebfe020b317a38b

**Comment by ddennedy** [comment]
I agree the quality looks poor in your image even with bicubic. However, you are heavily downscaling each image to a height of 200 within a project/export of 960x540. You also exported with H.264 compression further degrading the image. Next, you cropped the resulting image and blew it up to 1322x960. Considering the black borders in this image, I estimate the cropped height about 240. This means you upscaled the result at roughly 4x (960x240=4). In summary, you severely degraded an image and look at it through a magnifying lens and surprise to find how bad it looks.

There are a few places in the code where interpolation and scaling are done. I added some extra logging in there to verify behavior and everything is working as expected and respecting the interpolation option, and it is. Still, sometimes, with your test case, it was difficult for me to see a difference between nearest neighbor and bicubic. So, I created a sample image with diagonal lines and curves using the text generator in Shotcut and exported it as PNG at 1920x1080:

![hello](https://user-images.githubusercontent.com/1146683/86417083-d09ce380-bc80-11ea-8986-e20b8e2df460.png)

I plugged that into your project, and exported it as PNG - once using nearest neighbor and again using bicubic. Still, they looked similar, and when you zoom in an image viewer, it becomes subject to its interpolation. Finally, I used ImageMaick compare to make an image difference: `compare nearest-00001.png bicubic-00001.png difference.png`
This shows there is a difference in red:
![difference](https://user-images.githubusercontent.com/1146683/86417204-34271100-bc81-11ea-936a-096023688fdf.png)

**Comment by jonpacker** [comment]
>  In summary, you severely degraded an image and look at it through a magnifying lens and surprise to find how bad it looks.

That isn't really fair, mate. I exported the video at 960x540 and took a cropped screenshot using the screenshot tool on MacOS, as simple as that. Here's what the exact same process looks like when bicubic interpolation is correctly applied:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/678101/86417873-a3772200-bcce-11ea-9d1f-4c8a4e09ea93.png">

Could you try that test again but use a photo, such that you can see how the details inside the picture are being resampled? In my example you can see it on the ridges of the mountain and the lines of the road: the nearest neighbour resolves into jagged pixels where the bicubic creates a smoother line.

**Comment by ddennedy** [comment]
I did admit the quality is more poor than even I  expected, and if downscale my sample image to 426x240, then it is better than what the affine filters are doing. Still, the interpolation setting is having some affect as proven by the image compare. However, I do not know the root cause of the poor interpolation and have a fix. Maybe someone else can figure it out.

**Comment by ddennedy** [comment]
Also, another observation is that when I ask for something to be upscaled using one of the affine filters, I can quickly and easily see a difference within Shotcut preview as I change Settings > Interpolation. Here is a screenshot of the Shotcut preview with bicubic on the left and GNOME Image Viewer on the right with the same source image.
![image](https://user-images.githubusercontent.com/1146683/86419621-91729080-bc88-11ea-897e-acf5f0198d98.png)
The quality is very comparable. But a similar test with down-scaling shows a much worse quality in Shotcut:
![image](https://user-images.githubusercontent.com/1146683/86419720-f3cb9100-bc88-11ea-81bd-accf04c4b3c3.png)

**Comment by ddennedy** [comment]
I thought of a couple of possible workarounds/improvements to try while we research further the interpolation kernel:

1. add `<property name="transition.b_scaled">1</property>` This will make it use the dedicated, better quality image scaler before affine. It scales first to the project resolution in this mode. I think that helps a little.

2. switch to a different implementation in Qt named [qtblend](https://mltframework.org/plugins/FilterQtblend/). It does not support nearly as many properties as you can see. Also, it is hard-coded to bilinear. Qt has a nearest neighbor option that the MLT plugin does not use, and Qt does not offer a bicubic. Change the `mlt_service` property to `qtblend` and change `transition.rect` to simply `rect`. I was surprised when this did not give me better results in my experiment!
