### ISSUE TITLE
pkgconfig .pc file shows 6.21.0 ?

### ISSUE THREAD

**Issue by rubyFeedback** [mltframework/mlt#600]
Hey guys,

Using this URL: https://github.com/mltframework/mlt/releases/download/v6.22.0/mlt-6.22.0.tar.gz

compiled from source, fine, without error. In the pkgconfig/ subdirectory
I look at the two .pc files and they have as content 6.21.0. Obviously the
content should instead be 6.22.0.

Perhaps the mistake is on my own computer system (could be some old .pc file
somewhere else for example), but perhaps something is  wrong upstream; I discovered
this indirectly as I have a ruby script that checks for
versions (and checks that e. g. the version such as 6.22.0 matches what pkgconfig
returns, that way I discovered this - but as said it may also be a user error no my
computer system. Either way I thought it best to report it; please feel free to close
this issue request at any moment in time).

**Comment by ddennedy** [comment]
I can confirm that the CMakeFiles.txt was not set correctly for the release tarball. I will make a 6.22.1 version that fixes it.

**Comment by ddennedy** [comment]
fixed in 2223ce7
tarball pending
