### ISSUE TITLE
Possible incorrect install path with "--disable-windeploy" option

### ISSUE THREAD

**Issue by ice0** [mltframework/mlt#605]
Hi guys!

I am currently working on [MSYS2 MLT](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-mlt) package. MSYS2 uses Linux-like directory structure (`/bin` `/lib` `/share`).
So, I have configured mlt with the following flags: `./configure --target-os=MinGW --disable-windeploy ...`

And this is how `bin` directory looks after `make install` command:
```
/bin
$ ls
libmlt++-3.dll  libmlt++.dll  libmlt-6.dll  libmlt.dll  melt.exe
```

As you can see `libmlt.dll` and `libmlt++.dll` is installed to `bin` directory. However, if I try to link with MLT, `ld` fails, because pkg-config is looking inside `lib` dir for libraries.

```
pkg-config --libs mlt++
-LC:/msys64/mingw64/lib -lmlt++ -lmlt
```

And if I understand correctly `libmlt.dll` and `libmlt++.dll` must be installed inside `lib` directory, and `libmlt++-3.dll` `libmlt-6.dll`  and `melt.exe` to `bin`.

Please correct me if i am wrong.

**Comment by vpinon** [comment]
Hello,

In MSYS context, I agree that dll's should be in lib/ except the versioned ones.

But --disable-windeploy is currently used in Kdenlive Windows builds (made with KDE Craft), in which context most dll's are put next to the exe, so we should check if it still works changing the layout. Unfortunately I don't have much time to work on this these days, maybe within 1 or 2 weeks.

Maybe building through CMake could allow more layout flexibility through various cmake options. But this is not heavily tested, and still missing some modules.

Note: we did build MLT in MSYS2 at some point:
https://invent.kde.org/multimedia/kdenlive/-/blob/master/packaging/kdenlive-msys2.sh

**Comment by ice0** [comment]
@vpinon I can make a patch for MSYS2 package, and make a PR later if all works fine. 
We also using MLT for Synfig Studio windows build, and just copying .dlls from `mingw/bin` to our `bin` folder when making installer.

**Comment by ice0** [comment]
Ok. I made changes to the CMake scripts so that MLT now can be built on MSYS2. (https://github.com/mltframework/mlt/pull/609)

Reasons to switch from Makefiles:
- `Make` doesn't generate `dll.a` files (they needed for `lld` linker, `ld` is VERY slow in Windows on large binaries);
- `Make` makes a little non-standard `.pc` files. As MSYS2 did some paths mangling (for ex. it converts `/opt` to `c:\msys64\opt` when builds, it expects `autoconf` produced files (here is my [patch](https://github.com/ice0/MINGW-packages/blob/2bef95022ad55427de57184435a11767277e63e2/mingw-w64-mlt/010-mlt-6.20.0-fix-configure-paths.patch) where I convert paths like `/usr/lib` to `${libdir}` so MSYS2 can make a path mangling). This problem is automatically fixed becuase CMake generates "standard" Makefiles;
