### ISSUE TITLE
mlt causes a system crash when rendering a .mlt file

### ISSUE THREAD

**Issue by evertvorster** [mltframework/mlt#617]
Hi there! It's been a while since I complained to the developers of mlt. That's probably a good thing. 

I am mostly a kdenlive user, but this issue is also present in shotcut, so I can only assume that it is due to mlt.
My system is Arch Linux, all nicely up to date. The issue is present in latest git master, as well as the latest released version of mlt. 

What I am doing is a lazy way of doing time-lapses with my Canon 5D Mk III. It's set to record FullHD 25fps, IPB frames. (It also has an all I frame option, and I don't recall this issue happening on it that type of footage)

Anyways, I let the camera record for 30 minutes or so, then speed up the footage 5,000 to 10,000 percent with kdenlive. This generates a .mlt file that crashes my system. In kdenlive, just loading it into the project manager causes the issue, as kdenlive tries to render a preview of the file for easy editing. 

In shotcut, I can import the clip, but once I try to export it as a video, it gets to about 30% through the file, and then my 20GB RAM is gobbled up in less than a minute without the progress bar progressing. 

Here is the offending .mlt file. The source file is nearly a gigabyte, would you like a copy as well? I can throw it on a gdrive, but it will take a while to upload. 
[UJ5A7082.zip](https://github.com/mltframework/mlt/files/5489724/UJ5A7082.zip)

**Comment by ddennedy** [comment]
I reproduced this problem (huge memory usage) with my own media. Turning off pitch compensation (set `warp_pitch` to 0 in the XML) avoids the problem. @bmatherly can you take a look at this please?

**Comment by evertvorster** [comment]
Wow, that was quick. You guys are superstars!

I can use the no pitch compensation workaround as I am not using the audio anyways.

Thanks for looking into this so quickly. 
Kind regards,
-Evert-

**Comment by ddennedy** [comment]
With no pitch compensation, on my test clip, with speed factor of 50, it uses 210 MB of RAM.
With pitch compensation on and speed factor of 10, it uses 193 MB.
With pitch compensation on and speed factor of 20, it uses 4 GB! So, simply limiting it to a certain range is needed to avoid memory usage issues on lower end systems is necessary.
With pitch compensation on and speed factor of 15, it uses 204 MB. That seems like a reasonable limit.

**Comment by evertvorster** [comment]
OK.. I have this reported as a bug on Kdenlive as well. 

Pitch compensation does not make sense after a certain speed factor, so we will probably end up just disabling it outside of a factor of 15.

**Comment by ddennedy** [comment]
We need to fix it in MLT as well perhaps with a limit. If we do (pending further investigation) it still makes sense to reflect the limit in the UI so that a user does not report a bug that it is turned on but not making an effect.

**Comment by evertvorster** [comment]
I was thinking of just simply greying out the pitch compensation button once the speed slider gets dragged past a certain point. Or at least that is how I would implement it if kdenlive was my project. 
Thanks again for the keen eye and superior help on this one.

**Comment by bmatherly** [comment]
Can anyone test this proposed fix: https://github.com/bmatherly/mlt/commit/c6d7ff55b0163655b13d83ea305cecea2a8383fa
It seems to work for me, but I do not have a test file that matches all the parameters of yours.

**Comment by ddennedy** [comment]
Yes, that option fixes it. Will it have any degradation of the sound quality in the most usable range of pitch change?

**Comment by bmatherly** [comment]
> Will it have any degradation of the sound quality in the most usable range of pitch change?

This is what the documentation says:

> - OptionTransientsCrisp - Reset component phases at the peak of each transient (the start of a significant note or percussive event). This, the default setting, usually results in a clear-sounding output; but it is not always consistent, and may cause interruptions in stable sounds present at the same time as transient events. 
> - OptionTransientsMixed - Reset component phases at the peak of each transient, outside a frequency range typical of musical fundamental frequencies. The results may be more regular for mixed stable and percussive notes than OptionTransientsCrisp, but with a "phasier" sound. The balance may sound very good for certain types of music and fairly bad for others.
> - **OptionTransientsSmooth - Do not reset component phases at any point. The results will be smoother and more regular but may be less clear than with either of the other transients flags.**

So it sounds like there is a tradeoff between smoothness and transient clarity. In my limited listening testing, I did not perceive a difference.

I added some debug messages so that I could monitor the samples being "held back" in the library. The "Crisp" and "Mixed" options result in delayed samples for all pitch factors. The "Smooth" option was almost rock solid with a constant delay through the library.

I think this is a good tradeoff so that we will be sure to have more consistent results and better lipsync.

**Comment by ddennedy** [comment]
Ok please submit PR

**Comment by ddennedy** [comment]
Fixed in #618
