### ISSUE TITLE
the timewarp producer doesn't correct change a xml resource. 

### ISSUE THREAD

**Issue by hpp0hpp** [mltframework/mlt#622]
D:\下载\Shotcut\melt.exe -track color:#000000 out=0 -track timewarp:0.2:c41c5f93-e2f5-4f5d-915a-b7db937b6aa9.xml in=":0.000000" out=":1635.000000" -transition mix a_track=0 b_track=1 -consumer xml

the out put still keep the same length with the original, not the length/time after speed adjust, as the play list still keep the out= as original, which loses some content. I think this is the bug, and I cannot easily fixed it. 

![image](https://user-images.githubusercontent.com/54829297/99871830-7ba23f80-2c18-11eb-8c85-d4e17ca00ebf.png)

**Comment by bmatherly** [comment]
The timewarp producer works by overriding the profile framerate on the encapsulated producer. The XML producer does not support profile framerates other than the rate that the XML was created with. Therefore, the XML producer is not compatible with the timewarp producer.

This is not a bug, but rather a feature that has not been implemented yet. I do not know of a current work-around or another way to speed up an XML file. But improved speed control is on our roadmap and is expected to be improved in the coming months.
