### ISSUE TITLE
Clip eof behavior when using mlt_playlist

### ISSUE THREAD

**Issue by gabrieljablonski** [mltframework/mlt#627]
As I understand, when a producer has it's `eof` property set to `pause`, playback speed is supposed to be set to 0 when the last frame of the clip is reached. When using an `mlt_playlist` producer, it seems that the playback speed is indeed set to 0, but only at the level of the playlist's child producer (an `avformat` producer for example), so playback is not paused at the end of the clip (if it's not the last in the playlist), since the playlist's speed is not set to 0.

Is this behavior expected and pausing at the end of a clip in an `mlt_playlist` is not possible directly?

**Comment by ddennedy** [comment]
This is expected. eof handling really only applies to whatever producer is directly connected to the consumer. When playing a playlist, only its eof applies and a clip's eof handing is subordinate. The playlist has an event ["playlist-next"](https://www.mltframework.org/doxygen/event.html) if you want to listen on it. In case that does not fire when reaching the end of the playlist, maybe there is some other way to detect that.

**Comment by gabrieljablonski** [comment]
> The playlist has an event ["playlist-next"](https://www.mltframework.org/doxygen/event.html) if you want to listen on it.

I had actually considered using this event, though I wanted to check first if there was something more straight forward. 
Thanks for the quick response.

**Comment by gabrieljablonski** [comment]
Just in case anyone runs into this issue in the future, in my specific use case, [these changes](https://github.com/gabrieljablonski/mlt/commit/395e5291159eb5d9ea9c772dd649c5679ed96be0) allow the use of a producer property `"pause"` for the playlist (slightly refactored on [this commit](https://github.com/gabrieljablonski/mlt/commit/2fe2b7d5deaf662206ad57345c4e03b9aaeb1a56)).

When it is set to `"end"`, when the playlist reaches the end of the current clip, it will set the speed to 0 at the last frame.
When set to `"start"`, the playback will pause at the first frame of the clip following the one currently playing. 

This idea could easily be expanded upon to allow for more complex controls, such as a list of clips indexes and specific behaviors at the end/start of each one.
