### ISSUE TITLE
Audio level filter mirroring channel value when using more than 8 channels

### ISSUE THREAD

**Issue by gabrieljablonski** [mltframework/mlt#629]
When applying the `audiolevel` filter, I've observed the following behavior, which I believe to be a bug.

When using a consumer with the property `channels` set to 8, the values are as expected.
But when using anything above 8 channels, the second channel after the last valid channel will mirror the value from the very first channel. 

For example, playing a media with a single stereo audio track (2 channels), will show the audio level for the 4th channel as the same from the 1st channel. Similar behavior happens with 5.1 audio.

Below I've put some of the values I've retrieved from a random audio sample from two different media, one single track, and the other 5.1 (ignore the absolute values, since I've normalized them in the [0, 255] range).

Single track:
```
// 8 channels
[
    { left: 72, right: 88 },
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 }
]
// 16 channels
[
    { left: 70, right: 81 }, # <--
    { left: 0, right: 70 },  # <--
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 }
]
```
5.1:
```
// 8 channels
[
    { left: 45, right: 35 },
    { left: 139, right: 4 },
    { left: 3, right: 2 },
    { left: 0, right: 0 }
 ]
// 16 channels
[
    { left: 47, right: 34 },  # <-- left = 47
    { left: 71, right: 10 },
    { left: 4, right: 6 },
    { left: 0, right: 47 },   # <-- right = 47
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 },
    { left: 0, right: 0 }
]
```

I believe this isn't an issue with the `audiolevel` filter, but with the frame audio samples. Before learning of the filter, I was calculating audio levels manually, retrieving the samples with `mlt_frame_get_audio()` (as seen [here](https://github.com/gabrieljablonski/mlt/commit/7c74eba5c4286f5472df8d0f84f66b7a3f142dc3#diff-2ac4f6724d2fc64934f77ba2d2927e00a8c0ab70dc1ee169c9e6763197e407cbR890)), and observed the same behavior.

**Comment by bmatherly** [comment]
It might be a bug, or it might not. But what you might not realize is that if you request channels from the consumer without specifying a channel layout, the framework will infer a channel layout. And the framework will attempt to remix the channel layout from the sources to match the inferred channel layout.

In most cases, the channel layout is assumed to be obvious. 1 channel is mono. 2 channels is stereo. But 8 channels is not 4 stereo pairs. MLT uses the ffmpeg swresample library to determine a default layout. And for 8 channels, I believe it will choose 7.1 surround for the channel layout. You may end up with sound in the center and LFE channels (maybe more, I am not sure what happens in the remix process).

You might receive the results you expect if you specify the "independent" channel layout - which will treat all the channels as independent and avoid remixing. Try adding this property to the consumer: "channel_layout=independent" and see if you get the results you expect.

**Comment by ddennedy** [comment]
Also, the `mix` transition only supports 6 channels. We can easily increase it to 8 or 16. It will make it consume more memory: 1500 KB  per channel per mix instance (typically one per track in a multitrack setup). For example, increased to 16 channels, with 10 mix instances the memory usage increases by 146.5 MB.

**Comment by gabrieljablonski** [comment]
Setting the channel layout to `"independent"` does not seem to have any effect.

> Also, the `mix` transition only supports 6 channels. We can easily increase it to 8 or 16.

I'm not explicitly using any transitions, so I'm pretty sure this wouldn't affect me in this case, correct?
Are there other parts of the audio management that have a limit on the number of channels supported? Even if the memory usage were to increase, that personally wouldn't be a problem.

**Comment by ddennedy** [comment]
The mix transition must be added explicitly and thus unlikely the cause.

**Comment by bmatherly** [comment]
I do not reproduce your problem with this command:

`melt -debug stereo.mp4 -filter audiolevel -consumer sdl2 channels=8`

> [filter audiolevel] channel 0 level 0.523460
> [filter audiolevel] channel 1 level 0.523515
> [filter audiolevel] channel 2 level 0.000000
> [filter audiolevel] channel 3 level 0.000000
> [filter audiolevel] channel 4 level 0.000000
> [filter audiolevel] channel 5 level 0.000000
> [filter audiolevel] channel 6 level 0.000000
> [filter audiolevel] channel 7 level 0.000000

Can you provide a melt command that demonstrates your issue?

**Comment by gabrieljablonski** [comment]
`melt -debug sample.mp4 -filter audiolevel -consumer sdl2 channels=16`

> [filter audiolevel] channel 0 level 0.349576
> [filter audiolevel] channel 1 level 0.378988
> [filter audiolevel] channel 2 level 0.000000
> [filter audiolevel] channel 3 level 0.000000
> [filter audiolevel] channel 4 level 0.000000
> [filter audiolevel] channel 5 level 0.000000
> [filter audiolevel] channel 6 level 0.000000
> [filter audiolevel] channel 7 level 0.000000
> [filter audiolevel] channel 8 level 0.000000
> [filter audiolevel] channel 9 level 0.349576
> [filter audiolevel] channel 10 level 0.000000
> [filter audiolevel] channel 11 level 0.000000
> [filter audiolevel] channel 12 level 0.000000
> [filter audiolevel] channel 13 level 0.000000
> [filter audiolevel] channel 14 level 0.000000
> [filter audiolevel] channel 15 level 0.000000

Increasing the number of channels should be enough to reproduce it. `sample.mp4` is this case has 4 stereo tracks (only first track has sound), so the last valid channel is channel 7. Following the behavior I described, the second channel after the last valid one (7 + 2 -> 9) mirrors the first channel.

**Comment by bmatherly** [comment]
See proposed fix here: https://github.com/mltframework/mlt/pull/632

**Comment by gabrieljablonski** [comment]
Working for me. Thanks for the help!
