### ISSUE TITLE
Confused position in framebuffer

### ISSUE THREAD

**Issue by zhangqianliang** [mltframework/mlt#65]
Dear,

I want to speed up specific clip of a movie([00:01:00, 00:02:00] of sample.mp4), for some movies command below works:
melt framebuffer:sample.mp4?2 in=00:00:30.000 out=00:01:00.00

but for some other movies, command like:
melt framebuffer:sample.mp4?2 in=00:01:00.000 out=00:01:30.00

It confused me.

PS: Could I do speed up operation in filter, like ffmpeg -vf setpts=0.5*PTS?

**Comment by ddennedy** [comment]
The framebuffer producer recently (Feb. 8, 2015) received some changes. Therefore, you need to test this with the latest version 0.9.4. You did not clearly state the problem. I am going to close this bug if you do not clearly demonstrate a defect.

**Comment by ddennedy** [comment]
If you are using version 0.9.4 or a git clone from the month of February, then maybe you are noticing this regression that I reverted today: 0c30d7d360ed389f20e385069557a6ba3ba77131

**Comment by zhangqianliang** [comment]
Please check this video: https://drive.google.com/file/d/0B0ILYfmAfQoyeHdQNUtQUVpDakk/view?usp=sharing

I just copy to mp4:
ffmpeg -i 001.flv -c copy 001.mp4

Speed up operation:
melt framebuffer:001.mp4?2 in=00:00:10.000 out=00:00:20.000
melt framebuffer:001.flv?2 in=00:00:10.000 out=00:00:20.000
comes out same video frames.

But, slow down operation:
melt framebuffer:001.mp4?0.25 in=00:00:10.000 out=00:00:20.000
melt framebuffer:001.flv?0.25 in=00:00:10.000 out=00:00:20.000
comes out different video frames.

**Comment by zhangqianliang** [comment]
Yes, I update melt to version 0.9.6, and yes, this bug not found in this version. And last question, Did melt officer offer melt static build?

**Comment by ddennedy** [comment]
Thank you for testing and confirming on the latest version. No, there is not a static build option. Even if it did offer that for the library and melt executable, most of the interesting work takes place in modules, which are only loaded dynamically like a plugin.
