### ISSUE TITLE
MinGW: melt build fails without SDL

### ISSUE THREAD

**Issue by eszlari** [mltframework/mlt#650]
Under MinGW, if neither SDL1 or SDL2 are installed, the build fails with:
```
melt.c:35:10: fatal error: SDL.h: No such file or directory
   35 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
```

**Comment by ddennedy** [comment]
You need to define macro `MELT_NOSDL` to build melt without SDL dependency. It is not automatically dropped.
