### ISSUE TITLE
Crash with autotrack_rectangle and selected zone outside frame boundaries

### ISSUE THREAD

**Issue by jlskuz** [mltframework/mlt#652]
**Description**
Rendering crashes with the autotrack_rectangle effect when selected zone goes outside frame boundaries.

**Reproduce**
Execute `melt -profile atsc_1080p_25 color:red out=20 -attach autotrack_rectangle geometry="463 769 960 540" -consumer avformat:result.mp4`

**Version:**
git (a51ace4861c82f6e2707ae893040089a445c56ad)

_I created this because of [this](https://invent.kde.org/multimedia/kdenlive/-/issues/580) issue for Kdenlive_

**Comment by ddennedy** [comment]
We are removing this effect and its motion_est module from the next major version of MLT due by the end of April.
