### ISSUE TITLE
mlt_image_format rgb colour shifts more than expected

### ISSUE THREAD

**Issue by CorrosiveTruths** [mltframework/mlt#657]
Hi, have been wanting to use mlt_image_format=rgb24a to preserve colour resolution when going from 1080 to 2160 and also for intermediate alpha transparency movies, but have noticed it shifting the colour more than expected.

You can see the difference by comparing the results of:

melt -producer frei0r.test_pat_B in=0 out=120 -profile atsc_1080p_30 -consumer avformat:testpatt_yuv422.mkv mlt_image_format=yuv422 vcodec=libx264 an=1 qp=0 real_time=-1
Colour bars: Fully saturated colours, off by 1-2.
![testpatt_yuv422](https://user-images.githubusercontent.com/18117943/107882964-04f9a300-6ee4-11eb-9b5d-2b1b498da24d.png)

melt -producer frei0r.test_pat_B in=0 out=120 -profile atsc_1080p_30 -consumer avformat:testpatt_rgb24a.mkv mlt_image_format=rgb24a vcodec=libx264 an=1 qp=0 real_time=-1
Colour bars: Fully saturated colours, off by 17-40 with orange-ish red, and the loss of 40 levels of green
![testpatt_rgb24a](https://user-images.githubusercontent.com/18117943/107882967-0925c080-6ee4-11eb-9199-dc19e99c8059.png)

And then comparing that to ffmpeg externally doing the same conversion to the mlt_image_format=yuv422 version.

ffmpeg -i /home/peter/kdenlive/testpatt_yuv420p.mkv -c:v libx264rgb -qp 0 testpatt_ffrgb.mkv
Colour bars: Fully saturated colours, off by 1-3.
![testpatt_ffrgb](https://user-images.githubusercontent.com/18117943/107882970-10e56500-6ee4-11eb-9680-b507a3842b9d.png)

**Comment by ddennedy** [comment]
What is your version? There was a very relevant change made in August 2020
https://github.com/mltframework/mlt/commit/9be412fdfe967a03fbc0460a7847fde829d146f3

**Comment by CorrosiveTruths** [comment]
Thanks for looking into that so quickly, Dan.

I was on 6.22, works fine in the latest version, sorry to bother you.

**Comment by ddennedy** [comment]
Great
