### ISSUE TITLE
[mlt_pool] out of memory

### ISSUE THREAD

**Issue by zhangqianliang** [mltframework/mlt#66]
I try to add background music to a video, and I got this error:

[mlt_pool] out of memory 0

And I find melt process %MEM up to 96.8%

And here is my command:
melt -track "http://netdisk.foream.cn:8080/netdisk/iface/downloadFile?fileId=74976&expire=1425987406247&hash=ab0609081cabea3755199519f3e36d3e&ext=.mp4" -audio-track "http://netdisk.foream.cn:8080/netdisk/iface/downloadOpen?fileId=75023" -transition mix:-1 a_track=0 b_track=1 -consumer avformat:c.mp4 vcodec=libx264 acodec=aac

**Comment by ddennedy** [comment]
Yes, I reproduced it. To workaround, add "combine=1" to the mix transition. There are 2 mixing algorithms, and the "combine" property selects the alternate. All MLT video editors use combine=1 since it is better, which is why this bug went unnoticed.

**Comment by ddennedy** [comment]
P.S. If you are trying to add a music track to a project, then you probably should not give the "-1" argument to the mix transition.

**Comment by zhangqianliang** [comment]
OK, let me try

**Comment by zhangqianliang** [comment]
I find that Shotcut also use "always_active=1", what does it do?

**Comment by ddennedy** [comment]
I do not believe always_active=1 is necessary in Shotcut. I forget now why I added it. On transitions, in general, it affects whether in and out will be used: http://www.mltframework.org/doxygen/properties.html

Some transitions like mix also interpret it to affect how mix level animation from the start property to the end property.
