### ISSUE TITLE
Image sequence does not seem to properly handle images of different sizes

### ISSUE THREAD

**Issue by carlonluca** [mltframework/mlt#663]
I reported this issue to kdenlive here: https://bugs.kde.org/show_bug.cgi?id=431376. When creating a sequence of images, it seems that an image is initially shown with the same size of the previous one, despite the fact that the size is different.

This is a test set I prepared to reproduce the issue: https://app.box.com/s/df55s9ldew4sj4nyk6t9h7k7u96fjtuw.
This is the video prepared by kdenlive:
* Video without dissolve transition: https://app.box.com/s/rcgtxwojmjxnleava475f7eehkogjagy
* Video without any animation: https://app.box.com/s/uaqlftg0sb6xwhc7meiqdu8boi0l123z

As you can see, I was told that the melt command also shows the same behavior. Is this the proper place to report the issue?
Thanks!

**Comment by jlskuz** [comment]
The melt command to reproduce with the files provided by @carlonluca  is `melt test_set/.all.jpg`
