### ISSUE TITLE
how to call atadenoise function in ffmpeg

### ISSUE THREAD

**Issue by xsy123xsy** [mltframework/mlt#666]
how to use atadenoise with source code by transplanting it to a video engine. Is there any example to call function "ff_atadenoise_init_x86" in "FFmpeg/libavfilter/atadenoise.h"

**Comment by ddennedy** [comment]
You cannot call it directly from MLT app. See
https://www.mltframework.org/plugins/FilterAvfilter-atadenoise/

**Comment by xsy123xsy** [comment]
Is there any example to call&nbsp;atadenoise in C++ code ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dan Dennedy"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 凌晨0:58
收件人: "mltframework/mlt"<mlt@noreply.github.com&gt;; 
抄送: "xsy_xsy"<366366235@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mltframework/mlt] how to call atadenoise function in ffmpeg (#666)





 
You cannot call it directly from MLT app. See
 https://www.mltframework.org/plugins/FilterAvfilter-atadenoise/

**Comment by ddennedy** [comment]
The best example without using MLT is in FFmpeg source code:
https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/filtering_video.c

You would have to change the `filter_descr` string. There is no similar example of filtering video for MLT.

**Comment by xsy123xsy** [comment]
Thx for your answer. I have read the example "FFmpeg/doc/examples/filtering_video.c",but I cannot really understand how it works. And I can't figure out how to configure const char *filter_descr in https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/filtering_video.c to use atadenoise to do video processing in ffmepg. What's more, I'd like to debug it on macOS/Ubuntu step by step to delve into the code and learn how the algorithm works.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dan Dennedy"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 中午1:48
收件人: "mltframework/mlt"<mlt@noreply.github.com&gt;; 
抄送: "xsy_xsy"<366366235@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mltframework/mlt] how to call atadenoise function in ffmpeg (#666)





 
The best example without using MLT is in FFmpeg source code:
 https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/filtering_video.c
 
You would have to change the filter_descr string. There is no similar example of filtering video for MLT.
