### ISSUE TITLE
why out = total_frames - 1 ?

### ISSUE THREAD

**Issue by zhangqianliang** [mltframework/mlt#67]
I do some editing in Shotcut, but I find something interesting: Shotcut sets out =  total_frames - 1, such as:

a.mp4, total frames length: 3200, then Shotcut melt xml like: in=0 out=3199

What does it do? THX

**Comment by pez4brian** [comment]
Frame positions are "0" based. So, in a stream with only one frame, the frame number is "0". The first frame is always zero and the last frame is always total_frames - 1.

For future reference, the issue tracker is not for support questions. Please use the mailing list or stackoverflow.
http://www.mltframework.org/bin/view/MLT/OnlineSupport
