### ISSUE TITLE
Mac mini OSX (arm64) Segmentation failed

### ISSUE THREAD

**Issue by DangerD1024** [mltframework/mlt#677]
MLT compiled from source:
```
./configure --enable-gpl
make
sudo make install
```
When i try to process any file i have `zsh: segmentation fault  melt`

![image](https://user-images.githubusercontent.com/4560434/111141028-b21b1600-858b-11eb-8529-9e003777268d.png)

Any solution for it?

P.S. Mac mini on ARM64

**Comment by ddennedy** [comment]
macOS ARM support is in development and fixed on the v7 branch. It will be merged and released in April.
