### ISSUE TITLE
Missing option to stream copy without re-encode?

### ISSUE THREAD

**Issue by dustball** [mltframework/mlt#678]
So, I've been using ffmpeg to slice up a video, to remove the ads before posting.  (I do this because it saves 1.5 hours instead of Adobe Premiere rendering another version without ads.)

The problem is that ffmpeg's time code or frame seeking (-ss and -t) are NOT frame accurate -- unless you reencode.  

Which defeats the whole purpose.

So I switched to melt:

```
melt input.mp4 in=610 out=1051 -consumer avformat:1.mp4 acodec=aac ar=44100 ab=317k vcodec=libx264 vb=30166k
melt input.mp4 in=1797 out=2050 -consumer avformat:2.mp4 acodec=aac ar=44100 ab=317k vcodec=libx264 vb=30166k
melt input.mp4 in=2428 -consumer avformat:3.mp4 acodec=aac ar=44100 ab=317k vcodec=libx264 vb=30166k
echo "file 'part1.mp4'\nfile 'part2.mp4'\nfile 'part3.mp4'\n" > inputs.txt
ffmpeg -f concat -i inputs.txt -c copy -y output.mp4
```

Which is working great .. except .. it's reencoding again!  I was hoping for a stream copy.  This takes just as long as Adobe Premiere rendering a new version for 1.5 hours...

(When ffmpeg does the stream copy, it processes the whole 20 minute video in less than 1 minute, at 2000+ fps on my very old machine..)

Can I cut up videos without doing a whole reencode?

Thanks!

**Comment by vpinon** [comment]
No you can't. Melt is always decoding-recoding, as it is a video processing (editing) tool. And stream copy can't be frame-accurate as most codecs don't encode every frame.
What you could do is stream copy, see what you miss, precisely create the missing chunks (re-encoding), then concat everything: this way you reencode only the minimum amount.
Maybe there are tools to do that (avidemux?) but I'm not sure.
