### ISSUE TITLE
confused mix length 

### ISSUE THREAD

**Issue by zhangqianliang** [mltframework/mlt#68]
This is "-mix" description:

-mix length                              Add a mix between the last two cuts

The length means frames?
But if the frame rates(fps) of these two cuts are not different, it may cause unexpected result?

And can "-mix" followed by time(00:00:05.000)?

**Comment by pez4brian** [comment]
The "-mix" parameter can only be specified in frames, not time.

The source frame rate is irrelevant because it applies based on the frame rate of the profile.

For future reference, the issue tracker should not be used for support queries:
http://www.mltframework.org/bin/view/MLT/OnlineSupport

**Comment by zhangqianliang** [comment]
OK, THX
