### ISSUE TITLE
How I can create advanced transition like in shotcut (webvfx) using command line player

### ISSUE THREAD

**Issue by DangerD1024** [mltframework/mlt#688]
Is there any way to use webvfx for command line player to create more advanced transition rather than Luma.
Or as Webvfx will be removed, what should I use to create transitions?

I'm using mlt for automated video creation.

**Comment by ddennedy** [comment]
Use your imagination. See the Shotcut forum and YouTube videos due examples. See the demo folder in MLT for more examples. This is not a bug and this area is for hard defect tracking only.

**Comment by ddennedy** [comment]
See this forum search https://forum.shotcut.org/search?q=transition%20%23tutorial
While the demos use the `composite` transition, that is low quality. Better ones today are `affine` and `qtblend`.
