### ISSUE TITLE
Negativ timewarp does not work for slideshows if value is >-1

### ISSUE THREAD

**Issue by jlskuz** [mltframework/mlt#693]
You can't reverse a slideshow if the speed is above `-1` reproduce e.g. with `melt timewarp:-0.9:/home/user/.all.jpg`.

`-1` and below works as expected (e.g. `melt timewarp:-2:/home/user/.all.jpg`)

Just as a side note: the speed has no effect for the slideshow, because the image duration is set via `ttl`

**Comment by frdbr** [comment]
Don't know if it is related but it doesn't work on .mlt clips either.

**Comment by jlskuz** [comment]
Oh, it seems it is something with local `melt timewarp:-0,9:/home/user/.all.jpg` works…
