### ISSUE TITLE
Deallocating memory from `mlt_pool`

### ISSUE THREAD

**Issue by gabrieljablonski** [mltframework/mlt#695]
I've been working with a large number of producers (100+) and ran into an undesirable behavior.

After opening all of the producers, the `melt` process has a certain amount of memory used (let's say 5% for 100 producers).
The problem is that after closing all producers, the process memory usage does not go back down. I'm quite certain it isn't due to a "traditional" memory leak since opening 100 producers again does not affect the memory at all, though opening an extra 100 (200 total) will raise the memory usage to about 10% in this example.

After profiling the process, I've narrowed it down to the usage of `mlt_pool`s (specifically the `mlt_pool_alloc()` function) when creating instances of the resample filter (`filter_resample_init()`). So my guess is the memory gets allocated to fit all of the filters, and doesn't get deallocated when closing them, staying available for other filters created in the future.

This is problematic since reducing the number of producers after working with a very large number doesn't reduce the memory footprint.

If this is expected behavior (which I wouldn't be surprised if it is, since this is only a problem for a very large number of producers), is there a way I could manually free up this memory after closing the producers? I've tried calling `mlt_pool_purge()` after closing them, but that didn't work.

**Comment by ddennedy** [comment]
Yes, I can concur that it does exhibit the behavior you describe, but I would expect `mlt_pool_purge()` to help. However, we do not have tests around this. I suppose it also possible there is a reference leak somewhere. In `mlt_pool.c` you can find a define to build without pooling. Please test with that.

**Comment by ddennedy** [comment]
Did you define `USE_MLT_POOL` to 0? I ask because you mention the resample filter as if you possibly changed only it to not use memory pool.

**Comment by gabrieljablonski** [comment]
> Did you define `USE_MLT_POOL` to 0? I ask because you mention the resample filter as if you possibly changed only it to not use memory pool.

Yes, I disabled it by setting the `USE_MLT_POOL` flag to 0.

**Comment by ddennedy** [comment]
You can also try with this commit c6334410 on this recent resample filter. But I think it would only possibly reduce the problem - perhaps to a tolerable level though. This was reverted on master branch and instead applied to v7 due to the heavy change. v7 has some major changes you may not be prepared to handle yet.

**Comment by gabrieljablonski** [comment]
> You can also try with this commit [c633441](https://github.com/mltframework/mlt/commit/c6334410799ba989868582fbbbd5d44936c6b62e) on this recent resample filter.

I believe this will be good enough for now. It doesn't seem to fix the issue, since closing the producers still doesn't free up the memory, but these changes significantly reduce the overall memory usage. I have to open about 3x as many producers to reach the same memory usage as before.

Hopefully this doesn't become an issue for me in the future, but if it happens I'll probably try merging with the v7 changes before anything else.

Thanks a lot for the help!
