### ISSUE TITLE
stop image looping when audio track finishes

### ISSUE THREAD

**Issue by scratchoo** [mltframework/mlt#700]
Sorry to post this here but after a long search and much fatigue I can't find any answer to my question so I thought maybe someone here can provide me with a direction

I have an image which I want to combine with an audio track like this

` melt image.png -audio-track audio_track.mp3 -consumer avformat:res.mp4
`

but this never stops on terminal until I give it an out={number}

however if I give it an out the image disapear before the audio finishes, I want the image to stay until the audio finish

your help is very appreciated

**Comment by ddennedy** [comment]
Image producers default to 15000 frames. If you want it shorter, you need to set an out point. If you want it longer you need to set `length` in addition to `out`. There is no way to say the length should be based on something else. You need to do that. Get the length of the audio file in frames by using `melt audio_track.mp3 -consumer xml` and viewing the length property.

**Comment by scratchoo** [comment]
@ddennedy got it, thank you very much <3 just curious, what's the role of "length" ?

**Comment by ddennedy** [comment]
length is simply another word for duration in the context of time. In the context of media that has a natural duration (audio and video), it needs to be known by the framework, and the user must be able to override a detected duration (in case the detection was wrong or simply to repeat the last frame of video).

**Comment by scratchoo** [comment]
@ddennedy thank you for the explanation, you would save me many hours if I came here the first minute I was stuck, but unfortunately I spent the whole day searching for a solution! thank you again :)

**Comment by tslater** [comment]
@ddennedy Do you mind helping me understand why the [example here](https://github.com/mltframework/mlt/blob/master/demo/mlt_slideshow) doesn't have an "out" and can just use a ttl? It seems like I have the same issue of defaulting to 15000 frames when I try and use ttl in the example and can only use "out".

**Comment by bmatherly** [comment]
[ttl](https://mltframework.org/plugins/ProducerQimage/#ttl) only affects the duration of each image, but not the overall duration of the producer. For that example, you would still need to set "out" if you want it to stop at a specific time.

**Comment by tslater** [comment]
Thanks @bmatherly. One thing I'm still confused about though, why does [this example](https://github.com/mltframework/mlt/blob/master/demo/mlt_slideshow) not need an `-out`?

```
melt \
photos/.all.jpg ttl=75 \
-filter luma:luma1.pgm luma.softness=0.1 luma.invert=0 \
$*
```

**Comment by ddennedy** [comment]
length = #pictures * ttl
Or, read [the source](https://github.com/mltframework/mlt/blob/master/src/modules/qt/producer_qimage.c#L37).
