### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by davidwongiiss1984** [mltframework/mlt#701]
// cut mlt_type is ‘’mlt_producer”
Mlt::Service* cut = p.cut(...);

// fail
Mlt::Producer ref(*cut);
    mlt_service_type type = producer.type( );  Will return unknown

**Comment by bmatherly** [comment]
I added a test case here that tries to reproduce your description.
https://github.com/mltframework/mlt/commit/4dfac8f01837b641fa03dc31a610381906268101
This test case passes.

Maybe you can provide a test case that fails for your scenario?

**Comment by davidwongiiss1984** [comment]
Thank you for your reply. I'm very sorry for the trouble. Our version is too low. This bug has been fixed in 6.18
