### ISSUE TITLE
Crash on ogg with album art

### ISSUE THREAD

**Issue by jlskuz** [mltframework/mlt#704]
I am not sure if this needs to be fixed in mlt or if it is an upstream issue with ffmpeg or something else, but I get a crash when I try to play an ogg file containing album art with `melt file.ogg`. This does not happen with my local installation, but with melt inside the kdenlive flatpak and it seems to be a problem on Manjaro as a user reported [here](https://bugs.kde.org/show_bug.cgi?id=435755).

The cmd output is this

```gdb
Assertion stream_index < ogg->nstreams failed at libavformat/oggdec.c:943

Thread 1 "melt" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
```

Here is a full gdb backtrace: [crash.txt](https://github.com/mltframework/mlt/files/6324993/crash.txt)

**Comment by jlskuz** [comment]
Seems to happen on openSUSE Tumbleweed as well. https://bugs.kde.org/show_bug.cgi?id=433992

**Comment by ddennedy** [comment]
I downloaded the ogg file from wikimedia in the kde bug 433992, and I do not reproduce a problem in melt, and it does not have cover art. So, that bug report is unrelated. Do you have a simple file or an ffmpeg command line to make one that reproduces the problem?

**Comment by jlskuz** [comment]
Here is one: [albumart.ogg.zip](https://github.com/mltframework/mlt/files/6326984/albumart.ogg.zip)

I followed this (simple) guide to create one: https://alexcabal.com/adding-album-art-to-ogg-files-from-the-command-line

**Comment by ddennedy** [comment]
In the debugger I can see MLT is using video index 1, and that is the correct and valid index according to ffprobe output
```
Input #0, ogg, from '/home/ddennedy/Downloads/albumart.ogg':f=0/0   
  Duration: 00:03:03.59, start: 0.000000, bitrate: 162 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      Artist          : Robin Alciatore
      Genre           : Other
    Stream #0:1: Video: png, rgba(pc), 1024x1024 [SAR 3779:3779 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```
I do not understand why it asserts then. In any case, I found that `melt albumart.ogg video_index=-1` does play the audio and skips the album art.

**Comment by ddennedy** [comment]
I also pushed the fix to the v6 branch. There are no current plans to make another version 6 release, but think it is likely if not soon.
