### ISSUE TITLE
quite stable  video quality degradation in some cases

### ISSUE THREAD

**Issue by ovoshlook** [mltframework/mlt#710]
Hello
I have an issue with quite systematic video quality degradation when mix more than one video to net.
The problem exists when problematic video is the biggest one ( has different (but still the original) resolution. Only smaller videos added.
Video before:
<img width="145" alt="Screenshot 2021-05-07 at 13 01 11" src="https://user-images.githubusercontent.com/8499399/117440687-abc66c00-af34-11eb-9a9e-575d0aaa23b4.png">
Video after:
<img width="145" alt="Screenshot 2021-05-07 at 13 02 08" src="https://user-images.githubusercontent.com/8499399/117440724-b8e35b00-af34-11eb-86d6-528969db70e0.png">

The input file is quite simple and has description:

` Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:58:36.80, start: 0.000000, bitrate: 156 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1152x720 [SAR 1:1 DAR 8:5], 155 kb/s, 10 fps, 10 tbr, 10240 tbn, 20 tbc (default)`

producer is also quite simple for that file

 `<producer id="producer9">
    <property name="resource">problematic_video.mp4</property>
    <property name="aspect_ratio">1</property>
    <property name="mlt_service">avformat</property>
  </producer>

  <playlist id="playlist_producer9">
    <blank length=":113.0"/>
    <entry producer="producer9" />
    
      <filter id="filter0" in=":113.0" out=":547.0" >
        <property name="background">colour:0</property>
        <property name="mlt_service">affine</property>
        <property name="transition.distort">0</property>
        <property name="transition.valign">middle</property>
        <property name="transition.halign">center</property>
        <property name="transition.fill">0</property>
        <property name="transition.rect">0/0:1280x605</property>
      </filter>
      <filter id="filter1" in=":547.0" out=":3631.0" >
        <property name="background">colour:0</property>
        <property name="mlt_service">affine</property>
        <property name="transition.distort">0</property>
        <property name="transition.valign">middle</property>
        <property name="transition.halign">center</property>
        <property name="transition.fill">0</property>
        <property name="transition.rect">0/0:1280x605</property>
      </filter>
  </playlist>`
  
  Once I remove all other videos from the track producer but leave the layout and problematic track - problem is gone.
  
  The thing is that I can't catch the pattern 
  for most of the videos I mix the quality is really good
  
  Maybe there is an additional steps how I can dig deeper?

**Comment by bmatherly** [comment]
It is unclear how to reproduce the problem from your description. But I see you are using the affine filter. Perhaps you would benefit to change the scaling method for the affine filter. There are some instructions here: https://github.com/mltframework/mlt/issues/290

If changing the scaling method does not help, I think you will need to provide a test example that shows the failure so someone can investigate.

**Comment by ovoshlook** [comment]
Hello 
sorry for the long response
I've tried "rescale=bicubic" as filter param and had no luck so far
I created 2 small video examples that show the problem
Config above produces this:
One of them is the source and the other one is the result after mixing with another video

https://user-images.githubusercontent.com/8499399/120300951-b1f9ff00-c2cc-11eb-9c08-da75c8ee042b.mp4

https://user-images.githubusercontent.com/8499399/120300975-b6261c80-c2cc-11eb-9691-fb7bde9a090f.mp4

Both are cut versions of the real output but they show the degradation
Not sure if it helps but I'll try to make  the shorter version of this video specifically with the cut fragments as well

**Comment by ovoshlook** [comment]
Hi there
Maybe I need to provide some more additional info regarding this one?
I'm happy just need to understand what particularly?

**Comment by bmatherly** [comment]
> Maybe I need to provide some more additional info regarding this one?

Yes. I do not reproduce your problem. Can you provide the mlt file and associated source clips? The best scenario would be a bare minimum example with a single source file and a single mlt file.

**Comment by ddennedy** [comment]
Try including basic information that belongs in a bug report such as operating system, version, command line, etc. Try creating something similar in Shotcut and compare it with what you are doing and using. Your problem seems similar to #590

**Comment by ovoshlook** [comment]
Thank you for the answers.
I will provide some examples 
I just need to not ruin the format of the file but at the same time to remove unneeded as well
Wil update on the start of the next week

**Comment by ovoshlook** [comment]
Hello. Sorry for the long-long response
Just an update
found the degradation happens only in Docker for Melt v6.22
With no docker works fine
Updated to v6.24 - degradation in tested video disappeared (tried in Docker )

I going to update production env and test there
If no issues anymore - I will close the ticket.
