### ISSUE TITLE
can we keep the same binary name and same location of devel files ? 

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#713]
in https://src.fedoraproject.org/rpms/mlt/pull-request/3 I was doing a binary and devel compatibility of mlt-7 with mlt-6 , I don't think we ever need maintain both versions, AFAIK the big change is cmake ( the way we compile it ) . 
So instead I do the compatibility downstream , can we done upstream and for all ? 

Thank you

**Comment by sergiomb2** [comment]
FTR https://src.fedoraproject.org/fork/sergiomb/rpms/mlt/c/d5aa549f1952ed8e616ba82705483860e72b526a

**Comment by sergiomb2** [comment]
why cmake: add major version to files/dirs  [1] ? this breaks builds of all packages (kdenlive, synfig , shotcut) 

[1]
https://github.com/mltframework/mlt/commit/d56f8e4567d132107fd9007802192ae07c607689

**Comment by sergiomb2** [comment]
with [1] I can build synfig , but kdenlive searches for mlt.so not for mlt-7.so , so I prefer rollback  "add major version to files/dirs" , also openshot which use python should not work since mlt.py also changed to mlt-7.py etc .  

[1]
```
ln -sr %{buildroot}%{_libdir}/pkgconfig/mlt-framework-7.pc %{buildroot}%{_libdir}/pkgconfig/mlt-framework.pc
ln -sr %{buildroot}%{_libdir}/pkgconfig/mlt++-7.pc %{buildroot}%{_libdir}/pkgconfig/mlt++.pc
ln -sr %{buildroot}%{_includedir}/mlt-7 %{buildroot}%{_includedir}/mlt
ln -sr %{buildroot}%{_includedir}/mlt-7/mlt++ %{buildroot}%{_includedir}/mlt++
```

**Comment by ddennedy** [comment]
It is intentional to break compatibility of the build until the app has migrate to this major new version. The whole idea of a major new version is API breakage. Lots of projects put their major version into things now to facilitate multiple major versions installed at the same time. Only Shotcut is currently compatible with MLT 7.

**Comment by ddennedy** [comment]
https://www.mltframework.org/blog/v7.0.0_released/

**Comment by vpinon** [comment]
Kdenlive has a work/mlt7 branch, that will land in 21.08 release.
Its embedded FindMLT.cmake got adapted and works (even if not perfect), ideally it could be shipped by MLT (it was on eszlari todo list, but has not happened yet).

**Comment by sergiomb2** [comment]
> It is intentional to break compatibility of the build until the app has migrate to this major new version. The whole idea of a major new version is API breakage. Lots of projects put their major version into things now to facilitate multiple major versions installed at the same time. Only Shotcut is currently compatible with MLT 7.

when you change /usr/lib64/libmlt.so.6 to /usr/lib64/libmlt.so.7 , soname bump .  We can deduce that we have an api breakage , it is enough , you don't need add major versions in all places , I think that how it works

**Comment by sergiomb2** [comment]
> Lots of projects put their major version into things now to facilitate multiple major versions installed at the same time

That is the point, I  don't want pack multiple versions of MLT ...
