### ISSUE TITLE
Progress Percentage as a floating point value?

### ISSUE THREAD

**Issue by MiguelGuthridge** [mltframework/mlt#714]
For rendering especially large projects, printing the progress percentage as an `int` doesn't give enough insight into the actual progress of the render. Changing the progress output to a `double` seems simple enough, to the point that I could make the change myself. My main question is whether this would be a desired, as it runs the risk of breaking apps that use melt as a dependency that parse the progress from this output (although the change could be better in the long run, as it would allow for those apps to display more fine-grained progress outputs as well.

Thoughts?

**Comment by vpinon** [comment]
Note: melt also outputs the current frame number, if you know the start and end frame you can better know where you are...

**Comment by ddennedy** [comment]
@vpinon How would adding some decimal digits affect kdenlive? I am not worried about Shotcut because I can manage that change, and new releases always require latest release of MLT or later. Frame counts are not always convenient, and I think Miguel makes a good point.

**Comment by vpinon** [comment]
We are not yet on MLT-7 (switch prepared for next release 21.08), and we (I) can handle that change.

**Comment by ddennedy** [comment]
Submit a pull request with the code change if you want this.

**Comment by MiguelGuthridge** [comment]
Ok so I'm looking to make the changes, but I can't get MLT (unmodified) to build. I'm pretty sure this is to do with me missing packages that are required modules. I don't have any experience with packages in C++, or with CMake, so I'm not entirely sure how to set myself up properly. A quick explanation would be awesome, since I can't find anything that makes much sense to me.
