### ISSUE TITLE
libvpx encoding regression

### ISSUE THREAD

**Issue by Jookia** [mltframework/mlt#718]
This was first reported in https://bugs.kde.org/show_bug.cgi?id=430093 but I think this is actually a bug in melt.

To reproduce:
- Create a video in Kdenlive 19.02 and nightly app images
- Export it instead of rendering it so you get an MLT file
- Render both with MLT
- See that they both have poor output

However, rendering with the 19.02 appimage's provided MLT works fine.

The only error I notice really is '[libvpx @ 0x7f7ef0001d00] Bitrate not specified for constrained quality mode, using default of 256kbit/sec', possibly related to https://github.com/FFmpeg/FFmpeg/commit/14941d386acd90b92aaaf75fbdac2c07d33f167a . Setting the bitrate higher helps, but it isn't ideal.

**Comment by ddennedy** [comment]
This looks more like a parameters (properties) issue than a code bug. With that said you should not echo kdenlive bugs here. Kdenlive developers are also responsible for MLT. This report has no melt command line or MLT XML and therefore invalid.

**Comment by Jookia** [comment]
What would you need for me to make a MLT bug report about this? There's no bug report guidelines so I couldn't know to add a melt command line of MLT XML, so please don't close this.

**Comment by bmatherly** [comment]
> What would you need for me to make a MLT bug report about this?

The best bug reports provide the simplest melt command line example that can demonstrate the problem.
