### ISSUE TITLE
MPEG-TS are not accurated 

### ISSUE THREAD

**Issue by remoover** [mltframework/mlt#724]
[https://we.tl/t-pfepC3SAhA](url)

here i added accurated mpeg-ts frame by frame file for testing, if you test well, u can see issues, ie if you click on frame 100 , 150 etc,.. there are bugs .. not moving anymore etc... u will see that. many thanks for fixing

**Comment by ddennedy** [comment]
This file does not support seeking within FFmpeg libavformat, and we depend on that. You can use `ffplay -seek_interval 1 25accuratedTS.ts`, press space to pause, and use left & right cursor keys to seek by one second. You will see it is broken there too. According to mediainfo it is variable frame rate, which is not supported for seeking.
