### ISSUE TITLE
frei0r.curves - limited points

### ISSUE THREAD

**Issue by atom-smasher** [mltframework/mlt#734]
I'm using kdenlive, and it seems like `frei0r.curves` is supposed to support 5 points, but in kdenlive it's only supporting 3 points. I played around with the XML (`/usr/share/kdenlive/effects/frei0r_curves.xml`) and I just couldn't get it working; it could be something the kdenlive team got wrong and I can't figure it out, or it may be a problem with `frei0r.curves`.

At the same time, I noticed that `frei0r.bezier_curves` seems to support some arbitrarily high (unlimited?) number of points, but with the Bézier handles, the kdenlive interface gets unusably cluttered if more than 3-4 points are used.

What I'd very much like to see is `frei0r.curves` support some arbitrarily high number (unlimited?) of points. I'm really trying to get more than 3-5 points on a curve, in kdenlive.

Ubuntu 20.04.3 LTS 
kdenlive_39.snap
kdenlive 21.08.0
MLT 7.0.0

**Comment by ddennedy** [comment]
This is not a bug in MLT; it is a limitation in frei0r API unless it is changed to use a string parameter with like JSON but then there is no systematic way to provide Keyframes.

**Comment by jaromil** [comment]
Hi Dan! I am trying to understand what can be improved. OK for the JSON string parameter to provide variadic structured inputs even as arrays of points. But I do not understand your remark about missing keyframes, do you mind to explain?

**Comment by ddennedy** [comment]
MLT provides Keyframes for animated property values with interpolation for numeric values. If the property value is a JSON string, it does not work. It can do keyframed text but with no interpolation and cannot interpolate something inside JSON.
