### ISSUE TITLE
avformat producer does not cache audio

### ISSUE THREAD

**Issue by Tjoppen** [mltframework/mlt#738]
While experimenting with running melt on HTTPS URLs I noticed single-stepping backwards would always result in a seek and a new HTTPS connection having to be set up, verified by watching apache2's access.log on my home server. When running melt with -hide-audio this issue goes away and single-stepping backward/forward works as expected.

Example commands:

    melt -producer avformat:https://samples.mplayerhq.hu/MXF/Quantel%20widescreen%20test.mxf

compared to

    melt -hide-audio -producer avformat:https://samples.mplayerhq.hu/MXF/Quantel%20widescreen%20test.mxf

This seems to happen with any container format, not just MXF. Looking at producer_avformat.c it indeed seems there's no caching for audio.

I may submit a patch for this, reporting it for now while I investigate some other stuff.

**Comment by ddennedy** [comment]
Not a bug.
