### ISSUE TITLE
Compile error in latest (2021-11-25) git in mltresample rtaudio consumer.

### ISSUE THREAD

**Issue by evertvorster** [mltframework/mlt#752]
Rtaudio was built from git as well, I don't know if that makes any difference?

Here is where it fails in the compilation phase:

[ 86%] Built target mltresample
[ 86%] Building CXX object src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/consumer_rtaudio.cpp.o
/ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp: In member function ‘bool RtAudioConsumer::create_rtaudio(RtAudio::Api, int, int)’:
/ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp:195:25: error: ‘RtAudioError’ does not name a type; did you mean ‘RtAudioErrorType’?
  195 |                 catch ( RtAudioError& e ) {
      |                         ^~~~~~~~~~~~
      |                         RtAudioErrorType
In file included from /ad/OS/aur/mlt-git/src/mlt/src/framework/../framework/mlt.h:58,
                 from /ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp:20:
/ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp:197:62: error: ‘e’ was not declared in this scope
  197 |                         mlt_log_info( getConsumer(), "%s\n", e.getMessage().c_str() );
      |                                                              ^
/ad/OS/aur/mlt-git/src/mlt/src/framework/../framework/mlt_log.h:86:94: note: in definition of macro ‘mlt_log_info’
   86 | #define mlt_log_info(service, format, args...) mlt_log((service), MLT_LOG_INFO, (format), ## args)
      |                                                                                              ^~~~
/ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp: In member function ‘int RtAudioConsumer::stop()’:
/ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp:351:33: error: ‘RtAudioError’ does not name a type; did you mean ‘RtAudioErrorType’?
  351 |                         catch ( RtAudioError& e ) {
      |                                 ^~~~~~~~~~~~
      |                                 RtAudioErrorType
In file included from /ad/OS/aur/mlt-git/src/mlt/src/framework/../framework/mlt.h:58,
                 from /ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp:20:
/ad/OS/aur/mlt-git/src/mlt/src/modules/rtaudio/consumer_rtaudio.cpp:353:71: error: ‘e’ was not declared in this scope
  353 |                                 mlt_log_error( getConsumer(), "%s\n", e.getMessage().c_str() );
      |                                                                       ^
/ad/OS/aur/mlt-git/src/mlt/src/framework/../framework/mlt_log.h:84:96: note: in definition of macro ‘mlt_log_error’
   84 | #define mlt_log_error(service, format, args...) mlt_log((service), MLT_LOG_ERROR, (format), ## args)
      |                                                                                                ^~~~
make[2]: *** [src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/build.make:76: src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/consumer_rtaudio.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1113: src/modules/rtaudio/CMakeFiles/mltrtaudio.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: mlt-git

**Comment by bmatherly** [comment]
RtAudio git is listed as "6.0.0beta1" and that project has not created a tag or release for that. It seems there are a lot of changes happening in RtAudio master that will require updates to MLT to be compatible.

MLT is tested with the 5.x series. I suggest to compile against RtAudio 5.2.0.

It seems that the MLT CMake files could benefit from better version checking for the RtAudio module.

**Comment by ddennedy** [comment]
Also we can consider deprecating this module. Another solution to the problem is to disable the module if not needed.

**Comment by evertvorster** [comment]
Wow, not a lot of love for this rtaudio stuff _at all_
Anyways, I got here because kdenlive requires mlt to be built with movit AND rtaudio before turning on GPU accells. 

My internet connection is terrible at the moment, and my Arch box requires an update before it will allow me to install a vanilla rtaudio. Of course the way around this is to build from git. :) I'll build the 5.2.0 tagged stuff and see if that works.

**Comment by ddennedy** [comment]
You can change kdenlive to use sdl2_audio instead of rtaudio, and I bet it will work. Also, I think there is a way to tell cmake not used the pkg-config for rtaudio and let MLT use its included RtAudio source, but I forget how to do that and need to look it up or you can.
