### ISSUE TITLE
Trying to watermark a video with an image 

### ISSUE THREAD

**Issue by MohammedZ666** [mltframework/mlt#754]
I have observed if I try to watermark a video with an image whose height/width is not divisible by 2 then the image does not scale correctly. Am I implementing it wrong or is it a feature of melt?  This is the [image](https://imgur.com/a/fKBa0Do).

Sorry to ask this here, it is more of a StackOverflow question but I quickly need some expert opinion.

EDIT: I am using melt command line tool of version 6.24.0
```
melt --version
melt 6.24.0
Copyright (C) 2002-2020 Meltytech, LLC
<https://www.mltframework.org/>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mlt SYSTEM "https://raw.githubusercontent.com/mltframework/mlt/master/src/modules/xml/mlt-xml.dtd">
<mlt>
	<producer id="producerisFeVg2kjuJVs6Thd48DT">
		<property name="resource">
	/home/abuobaidazishan/DevProjects/video_editor/WORKER/O3KrPflzPMV68gdCmPLqA_k_0FL2XiXa/isFeVg2kjuJVs6Thd48DT.png
		</property>
		<property name="musecut:mime_type">
			image/png
		</property>
		<property name="musecut:name">
			brainekt.png
		</property>
		<property name="meta.media.width">
			244
		</property>
		<property name="meta.media.height">
			207
		</property>
	</producer>
	<producer id="producerSo-jYoIV3kPqFYEo2KYQu">
		<property name="resource">
			/home/abuobaidazishan/DevProjects/video_editor/WORKER/O3KrPflzPMV68gdCmPLqA_k_0FL2XiXa/So-jYoIV3kPqFYEo2KYQu.mp4
		</property>
		<property name="musecut:mime_type">
			video/mp4
		</property>
		<property name="musecut:name">
			BANGLADESH _ Raw Beauty.mp4
		</property>
		<property name="meta.media.0.codec.width">
			1280
		</property>
		<property name="meta.media.0.codec.height">
			720
		</property>
		<property name="length">
			00:04:40,380
		</property>
	</producer>
	<playlist id="videotrack0">
		<entry producer="producerSo-jYoIV3kPqFYEo2KYQu" />
	</playlist>
	<playlist id="audiotrack0" />
	<playlist id="videotrack1">
		<blank length="00:00:40,000" />
		<entry producer="producerisFeVg2kjuJVs6Thd48DT" in="00:00:40,000" out="00:01:25,000" />
	</playlist>
	<playlist id="videotrack2" />
	<tractor id="main" out="00:04:40,380">
		<multitrack>
			<track producer="videotrack0" />
			<track producer="audiotrack0" />
			<track producer="videotrack1" />
			<track producer="videotrack2" />
		</multitrack>
		<transition id="transitionvideotrack1" in="00:00:40,000" out="00:01:25,000">
			<property name="a_track">
				0
			</property>
			<property name="b_track">
				2
			</property>
			<property name="mlt_service">
				composite
			</property>
			<property name="geometry">
				30%/12%:67%x57%
			</property>
		</transition>
	</tractor>
</mlt>

```

**Comment by ddennedy** [comment]
You should specify your version and MLT profile attributes. Not using a profile? Then are you using melt or something to auto establish profile from the input? Is it 1280x720 16:9?

This might be fixed in the latest version
https://github.com/mltframework/mlt/commit/ea5da3c33d1a88a93cf804e3ac6602e44ce04dc9#diff-0747ad4e55ce10a3469cc38898333613c4e904b16004e63790fe828a9bd63bf4

You can also try using the affine or qtblend transitions instead. The geometry property name might be different.

**Comment by ddennedy** [comment]
Also, please explain "does not scale correctly."  I tried your XML with my media against git master, and this is what I see with `melt your.xml`:
![image](https://user-images.githubusercontent.com/1146683/143960076-76e8d84e-bd58-4b9e-89d4-73075667bc93.png)

I opened the image in a window above the MLT video window below.

**Comment by MohammedZ666** [comment]
@ddennedy Thank you so much for replying.  I am using melt command line tool of 6.24.0

Now I have figured the **problem really is not the divisibility of the image width/height by 2 but the aspect ratio of the image**. If  the aspect ratio is less than or equal to 1 or greater than 16:9 (1.7) **(1>=aspect ratio<=16/9)** that image works correctly.  I will also update the issue after you reply.  The problem seems to be with the image aspect ratio but not the height/width being even.

We are trying to develop a video-editing app fully made with javascript for web. By **scaling correctly I meant there is no discrepancy between preview** (rendered using js in our frontend) and the video (we get from melt+mlt xml from the backend).  

## Here is the example of the image that scales correctly: ## 

The first screenshot is of the preview of the app, the second one is the actual video: 

1. ![image](https://user-images.githubusercontent.com/50874919/143979519-519db71f-36ec-467e-b174-3ed311e8584e.png)
2. ![image](https://user-images.githubusercontent.com/50874919/143979551-d981eab6-1dbf-4053-82d1-fb08e22c5cef.png)

The picture [here](https://user-images.githubusercontent.com/50874919/143980896-134eebfa-8f19-46a2-b388-8dfe14aab3f8.jpg) is of 9:16 resolution but surprisingly it has an width of 2339 pixels(odd) and a height of 4156 pixels. 
**And this one works.**

The [video](https://youtu.be/tvfl5gDJZAw) used here has the 16:9 aspect ratio and is of 1280 * 720 resolution. 

## Now the following contains the example of an image that does not scale correctly: ##

The first one is of the preview and the second one of the actual video:

1. ![image](https://user-images.githubusercontent.com/50874919/143980318-34c8cd0b-4fda-444e-8c17-74de64dd50ed.png)
2. ![image](https://user-images.githubusercontent.com/50874919/143980394-fede6bfd-2c10-44f8-bd76-9157e5d9ae62.png)

The  [image](https://imgur.com/a/fKBa0Do) used here has a resolution of 244 * 207 px and an aspect ratio of 1.17 (which does not satisfy 1>=aspectRatio<=16:9(1.7)) and hence does not work. 

We crunch the geometry of the image in the video from the following lines of code, this percentage is used with **"geometry" property** of the transition.

## Frontend ##
```
 { ....
  "width": (size.y * 100 / imageDim.parentDims.parentHeight) * aspectRatio,
  "height": (size.y * 100 / imageDim.parentDims.parentHeight),
...}
```
## XML ## 
```
<property name="geometry">30%/12%:67%(width goes here)x57%(height goes here) </property>
```
Here size.y is the height of the image on the preview window and size.x is the width. We scale the width with the aspect Ratio of the image. Also here parentHeight and parentWidth are of our preview window, which is of 480 * 270 px and has the 16:9 aspect ratio. 
**I don't know if the problem is from the implementation side or if it is a melt feature**  Any help would be appreciated.

**Comment by ddennedy** [comment]
I am sorry but I am unable to help you with this much. Maybe someone else will. I see you are using percentages in your geometry value. Maybe that is the problem. Ask yourself: percentages of what? In MLT, it is the [profile](https://mltframework.org/docs/profiles/) dimensions, but you did not specify the profile again. It is not a percentage of the image or video.

**Comment by MohammedZ666** [comment]
from [here](https://mltframework.org/docs/profiles/) I get, **"Profiles define the output video properties, which affects the image processing"**

I am not explcitly declaring a profile (through text or the melt command).

Therefore, my profile, in this case, **I assume** is this [video](https://youtu.be/tvfl5gDJZAw), whose width is 1280 and height is 720 which I am watermarking which also is the **a_track** of the transition. 

This is the command I am currently using to output the video:

`melt project.mlt -consumer avformat:output.mp4 acodec=aac vcodec=libx264
`

Can I declare the profile in this way?

`melt -profile input.mp4 project.mlt -consumer avformat:output.mp4 acodec=aac vcodec=libx264`

Here the input.mp4 is this [video](https://youtu.be/tvfl5gDJZAw) which is also referred to above.

Thanks.

**Comment by ddennedy** [comment]
> Can I declare the profile in this way?

No, see the output  of `melt -query profiles`. See also the output of a profile from `melt -query profile=atsc_1080p_25` if you want to make your own file that you can supply to this command line option, which takes the name of an installed profile or a path to your own profile text file.

**Comment by MohammedZ666** [comment]
**If I don't declare a profile, then does the video I am trying to watermark, become the profile**? In my code the percentages of geometry property of transition is based on the video width and height I am trying to watermark and it works for most images. Thanks for the reply!

**Comment by Naser4100** [comment]
> I have observed if I try to watermark a video with an image whose height/width is not divisible by 2 then the image does not scale correctly. Am I implementing it wrong or is it a feature of melt? This is the [image](https://imgur.com/a/fKBa0Do).
> 
> Sorry to ask this here, it is more of a StackOverflow question but I quickly need some expert opinion.
> 
> EDIT: I am using melt command line tool of version 6.24.0
> 
> ```
> melt --version
> melt 6.24.0
> Copyright (C) 2002-2020 Meltytech, LLC
> <https://www.mltframework.org/>
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE mlt SYSTEM "https://raw.githubusercontent.com/mltframework/mlt/master/src/modules/xml/mlt-xml.dtd">
> <mlt>
> 	<producer id="producerisFeVg2kjuJVs6Thd48DT">
> 		<property name="resource">
> 	/home/abuobaidazishan/DevProjects/video_editor/WORKER/O3KrPflzPMV68gdCmPLqA_k_0FL2XiXa/isFeVg2kjuJVs6Thd48DT.png
> 		</property>
> 		<property name="musecut:mime_type">
> 			image/png
> 		</property>
> 		<property name="musecut:name">
> 			brainekt.png
> 		</property>
> 		<property name="meta.media.width">
> 			244
> 		</property>
> 		<property name="meta.media.height">
> 			207
> 		</property>
> 	</producer>
> 	<producer id="producerSo-jYoIV3kPqFYEo2KYQu">
> 		<property name="resource">
> 			/home/abuobaidazishan/DevProjects/video_editor/WORKER/O3KrPflzPMV68gdCmPLqA_k_0FL2XiXa/So-jYoIV3kPqFYEo2KYQu.mp4
> 		</property>
> 		<property name="musecut:mime_type">
> 			video/mp4
> 		</property>
> 		<property name="musecut:name">
> 			BANGLADESH _ Raw Beauty.mp4
> 		</property>
> 		<property name="meta.media.0.codec.width">
> 			1280
> 		</property>
> 		<property name="meta.media.0.codec.height">
> 			720
> 		</property>
> 		<property name="length">
> 			00:04:40,380
> 		</property>
> 	</producer>
> 	<playlist id="videotrack0">
> 		<entry producer="producerSo-jYoIV3kPqFYEo2KYQu" />
> 	</playlist>
> 	<playlist id="audiotrack0" />
> 	<playlist id="videotrack1">
> 		<blank length="00:00:40,000" />
> 		<entry producer="producerisFeVg2kjuJVs6Thd48DT" in="00:00:40,000" out="00:01:25,000" />
> 	</playlist>
> 	<playlist id="videotrack2" />
> 	<tractor id="main" out="00:04:40,380">
> 		<multitrack>
> 			<track producer="videotrack0" />
> 			<track producer="audiotrack0" />
> 			<track producer="videotrack1" />
> 			<track producer="videotrack2" />
> 		</multitrack>
> 		<transition id="transitionvideotrack1" in="00:00:40,000" out="00:01:25,000">
> 			<property name="a_track">
> 				0
> 			</property>
> 			<property name="b_track">
> 				2
> 			</property>
> 			<property name="mlt_service">
> 				composite
> 			</property>
> 			<property name="geometry">
> 				30%/12%:67%x57%
> 			</property>
> 		</transition>
> 	</tractor>
> </mlt>
> ```

I'm also facing this issue.

**Comment by MohammedZ666** [comment]
Sorry it was an internal bug. I was not deleting the previous transition before adding another one with the image which created the problem. Thanks for all the help!
