### ISSUE TITLE
How can I uninstall melt, if I installed compiling from source (README.md)?

### ISSUE THREAD

**Issue by MohammedZ666** [mltframework/mlt#759]
This is the process i followed, from [README.md](https://github.com/mltframework/mlt/blob/master/README.md)

```
git clone https://github.com/mltframework/mlt.git
cd mlt
cmake .
cmake --build .
. setenv
cmake --install .
```
This is my os info:
`Linux pop-os 5.15.5-76051505-generic #202111250933~1638201579~21.04~09f1aa7-Ubuntu SMP Tue Nov 30 02: x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ddennedy** [comment]
CMake does not provide an uninstall target by default and neither do we add one. See the generated `install_manifest.txt` in your MLT build directory, and the following article:
https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall
