### ISSUE TITLE
Add Intel QSV acceleration support

### ISSUE THREAD

**Issue by TsingJyujing** [mltframework/mlt#767]
I'm using mlt by kdenlive, I compiled ffmpeg with QSV support and verified it's capable to use GPU to accelerate encoding, but the option `vcodec=h264_qsv` seems did not supported by mlt, is there any plan to support it?

Thank you very much!

**Comment by ddennedy** [comment]
It already works. You did something wrong when building or running to ensure the correct version of MLT or FFmpeg is used (library loading).

**Comment by TsingJyujing** [comment]
@ddennedy Thank you for your reply, I've already compiled ffmpeg with QSV support, how can I let mlt use my compiled version?

**Comment by ddennedy** [comment]
Try it in an existing Shotcut build where I made it work without doing anything special. I do not know why it is not working for you. It only works on Windows. On macOS you need to use videotoolbox, and on Linux vaapi. Maybe you need to set more parameters like a bitrate or quality level. Or maybe you are not using the correct build of FFmpeg when you build MLT.
