### ISSUE TITLE
Processing Shotcut jobs containing transitions results in frame jumps around transition

### ISSUE THREAD

**Issue by Headd2k** [mltframework/mlt#771]
Melt 7.5.0, Shotcut-Version 22.01.30, Windows 10

Hello,

i'm trying to utilize "melt.exe" to get video rendering jobs based on Shotcuts .mlt project xml done via CLI and came across a problem i'm not able to solve alone.

Workflow for testing:

- create a new project in Shotcut gui
- add a short video to the timeline
- cut the video at some point and move the right part -3 seconds in timeline to create a transition between the two segments
- save the project and render the video as mp4 with no options changed
- right click on the job process bar and display the generadted xml
- save the xml into a new file
- go to cli and start the video export using the saved xml with no additional settings
-- melt.exe "d:\savedjobfromshotcut.mlt" -progress -verbose -consumer avformat:"d:/output.mp4"

On my system the resulting mp4 from the Shotcut gui export applied the transition flawlessly while the result from the cli export has very strange frame "jumps" around the transition.

Is there something i'm missing or that i can do to make the cli export working more like the one from the gui? I'm not sure if this is a bug or related to some missing/wrong configuration?

Thank you in advance!

**Comment by ddennedy** [comment]
You need to set the environment variable LC_ALL=“C”

**Comment by Headd2k** [comment]
i will give it a try asap. thank you for your quick reply!
