### ISSUE TITLE
on macos 12: mlt_repository_init: no plugins found in "/usr/local/PlugIns/mlt"

### ISSUE THREAD

**Issue by peymanr** [mltframework/mlt#774]
On macOS 12.1; MLT 7.4.0
Using brew install formula. Melt gives this error:

`mlt_repository_init: no plugins found in "/usr/local/PlugIns/mlt"`

**Comment by ddennedy** [comment]
sorry but we do not maintain the homebrew build. It looks like they are building it with RELOCATABLE defined, which is not appropriate for system-wide distributions like that. That option is only to be used for making macOS .app bundles on macOS.

**Comment by ddennedy** [comment]
Oh, RELOCATABLE defaults to ON on macOS, and they need to turn it off.

**Comment by peymanr** [comment]
Thanks @ddennedy, I tried building from source also (had to use -i to ignore QT-related errors, and update libxml to use command line tools on macos 12.1)  -- but it gets to the same error.

**Comment by ddennedy** [comment]
Did you run cmake with `-DRELOCATABLE=OFF` ?

**Comment by peymanr** [comment]
looks like that's the problem. The default in cmake is on. setting to off fixes the missing plugins issue. but i couldn't finish the install due to not having qt. cmake has an issue with macos12 also probably because it resolves libxml-2 to cli-mac-os.10. 

Thanks for help.

**Comment by ddennedy** [comment]
If you do not need Qt run cmake with `-DMOD_QT=OFF`. If you read CMakeLists.txt you can see the options.

**Comment by peymanr** [comment]
worked
