### ISSUE TITLE
[question] ffmpeg-free vs ffmpeg full feature  

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#785]
Hi, 
recently Fedora have one ffmpeg-free i.e one ffmpeg without many codecs [1]  .
building MLT with ffmpeg free will have impact ? how big ? what do you suggest ? 

thank you for your time 

BTW
Fedora 36 will have MLT-7 https://fedoraproject.org/wiki/Changes/F36MLT-7

[1]
https://bugzilla.redhat.com/show_bug.cgi?id=2051008

**Comment by bmatherly** [comment]
I do not volunteer to read through all the details in the bugzilla thread. But at first glance, it looks like the free version removes support for these external libraries:
- decklink
- libfdk_aac
- libtls

**Comment by sergiomb2** [comment]
OK for the record , AFAIU , the ffmpeg-free removes H.264 and H.265 patents ,  which implies x264, x265, HEVC.

From devel Fedora Mailing list, I highlight these quotes 

"There will be great news when the H.264 and H.265 patents finally expire."

"Unless H.266 (VVC) takes off, and we get to start the cycle all over again until 2040 or so (rough estimate on patent expiration)."

"H.266 is not popular. Most video services (Youtube, Twitch, etc.) have started to switch to the royalty-free AV1 codec."

**Comment by Conan-Kudo** [comment]
We actually do have libfdk-aac-free enabled with ffmpeg-free. We use GnuTLS instead of libtls, but that shouldn't matter from MLT's point of view. We don't have the decklink library in Fedora or RPM Fusion, so this already doesn't apply to our builds of MLT.

**Comment by Conan-Kudo** [comment]
You can see the list of enabled codecs here:
* Decoders: https://src.fedoraproject.org/rpms/ffmpeg/blob/rawhide/f/enable_decoders
* Encoders: https://src.fedoraproject.org/rpms/ffmpeg/blob/rawhide/f/enable_encoders

**Comment by leigh123linux** [comment]
rpmfusion doesn't use fdk-aac as it breaches ffmpeg licensing.
