### ISSUE TITLE
File producer_glaxnimate.yml missing

### ISSUE THREAD

**Issue by jlskuz** [mltframework/mlt#789]
With 88636e0814d19927b7fd95ab63fd5e1845af02ab it is not possible to `make install` mlt with `cmake .. -DMOD_GLAXNIMATE=ON` because the file `src/modules/glaxnimate/producer_glaxnimate.yml` is missing even though it is required through the CMakeLists.txt. I guess @ddennedy you forgot to add it to the commit.

Full error 
```
CMake Error at src/modules/glaxnimate/cmake_install.cmake:66 (file):
  file INSTALL cannot find
  "/path/to/repos/mlt/src/modules/glaxnimate/producer_glaxnimate.yml":
  No such file or directory.
Call Stack (most recent call first):
  src/modules/cmake_install.cmake:72 (include)
  src/cmake_install.cmake:62 (include)
  cmake_install.cmake:62 (include)


make: *** [Makefile:100: install] Error 1
```

**Comment by ddennedy** [comment]
thanks. Please be aware this module depends on a git submodule.
