### ISSUE TITLE
How to fix discrepancy between Melt and FFmpeg on Windows?

### ISSUE THREAD

**Issue by s5bug** [mltframework/mlt#791]
My local installation of FFmpeg supports `h264_amf`:
```
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv h264_cuvid )
(encoders: libx264 libx264rgb h264_amf h264_mf h264_nvenc h264_qsv )
```

Yet calling the `melt` bundled with Kdenlive does not:
```
  - h264_mf
  - h264_nvenc
  - nvenc_h264
```

Most likely because the `ffmpeg` bundled with Kdenlive does not either:
```
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_cuvid ) (encoders: libx264
libx264rgb h264_mf h264_nvenc nvenc nvenc_h264 )
```

Setting Kdenlive to use my local `ffmpeg` doesn't let me use `h264_amf`, because Kdenlive asks `libmlt++` and not `ffmpeg`:

![kdenlive Environment settings](https://user-images.githubusercontent.com/7751296/168497575-d0f9bfdd-6669-40a8-83d3-e8d59e639b1a.png)

![kdenlive Render window showing "Unsupported video codec" error](https://user-images.githubusercontent.com/7751296/168497709-5d685e0a-a4f6-4fb3-ac3f-284e10976ae9.png)

What do I need to do to get MLT to recognize `h264_amf`? What are the proper steps to take here to prevent Kdenlive's `libmlt` from being out of sync with my `ffmpeg`?

Apologies for the weird question, nothing online seemed to apply to Windows (especially with how Kdenlive bundles MLT and FFmpeg).

**Comment by ddennedy** [comment]
You need to compile FFmpeg and MLT yourself or work with the Kdenlive team on their builds. You can only swap DLLs if they are on the same, but likely your other version of FFmpeg that supports amf was built statically and a different version.

**Comment by s5bug** [comment]
If I compile FFmpeg and MLT myself, I would also have to compile Kdenlive myself, right?
