### ISSUE TITLE
Building MLT with FFmpeg-git

### ISSUE THREAD

**Issue by babam86** [mltframework/mlt#793]
MLT 7.6.0

Unable to build MLT with FFmpeg-git
How to build MLT with FFmpeg-git

Thanks.

**Comment by ddennedy** [comment]
You need to use the latest release branch or tag of FFmpeg or submit the code changes to fix it.

**Comment by babam86** [comment]
Is it due to FFmpeg switching to the new FIFO API?

**Comment by ddennedy** [comment]
fixed in 14aa2ec0
