### ISSUE TITLE
melt uses libavcodec internals and will break in the next FFmpeg release

### ISSUE THREAD

**Issue by Tjoppen** [mltframework/mlt#794]
20f972701806be20a77f808db332d9489343bb78 hides many fields behind the FFCodec struct.

Steps to reproduce on current master (b5c62c06e6ac2b67c0008a75b5e4ebaf4099f91b):

1. Check out FFmpeg commit 20f972701806be20a77f808db332d9489343bb78
2. ```./configure --enable-shared --prefix=$HOME/local && make -j && make install```
4. Check out latest melt
5. ```cmake -DCMAKE_PREFIX_PATH=$HOME/local -DCMAKE_INCLUDE_PATH=$HOME/include/ .```
6. ```make -j```

So far the only no-no field is codec->decode, but there are also other fields and functions that are deprecated.

**Comment by Tjoppen** [comment]
I see priv_data_size is also being used. consumer_avformat.c sets properties on priv_data, which is not the way to do things. From IRC:

```
10:06 <@nevcairiel> you are supposed to apply those to AVCodecContext, and if you set the child flag it'll then forward them to the underlying codec private settings
10:07 < durandal_1707> there is function in FFmpeg that allows to modify opt values from priv context, useful for runtime options modification
```

The specific thing the code seems to be doing is setting presets (-vpre and -apre), which are an ffmpeg_opt.c thing, not something that can be done via the lavc API. Some codecs have an internal "preset" option but that does not seem to be the purpose of this apre and vpre stuff.

**Comment by ddennedy** [comment]
> The specific thing the code seems to be doing is setting presets (-vpre and -apre), which are an ffmpeg_opt.c thing, not something that can be done via the lavc API.

Sure it can, by parsing that preset file and setting AVOptions as that is what these files contain. When I fix this, I will remove access to `priv_data_size` and use the `AV_OPT_SEARCH_CHILDREN` flag.

**Comment by ddennedy** [comment]
Deprecations are out-of-scope for this bug report and fix.
