### ISSUE TITLE
Redefinition of filter_swresample_init() causes a LTO issue with a modern toolchain

### ISSUE THREAD

**Issue by frispete** [mltframework/mlt#797]
Attempting to update the package from 7.4.0 to 7.6.0 with openSUSE Tumbleweed (GCC 12) reveals a new issue:

[   12s] cd /home/abuild/rpmbuild/BUILD/mlt-7.6.0/build/src/modules/avformat && /usr/bin/cmake -E cmake_link_script CMakeFiles/mltavformat.dir/link.txt --verbose=1
[   12s] /usr/bin/cc -fPIC -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -O2 -g -DNDEBUG -flto=auto -ffat-lto-objects -Wl,--as-needed -shared  -o ../../../out/lib/mlt/libmltavformat.so CMakeFiles/mltavformat.dir/common.c.o CMakeFiles/mltavformat.dir/factory.c.o CMakeFiles/mltavformat.dir/filter_avcolour_space.c.o CMakeFiles/mltavformat.dir/filter_avdeinterlace.c.o CMakeFiles/mltavformat.dir/filter_swscale.c.o CMakeFiles/mltavformat.dir/producer_avformat.c.o CMakeFiles/mltavformat.dir/consumer_avformat.c.o CMakeFiles/mltavformat.dir/filter_avfilter.c.o CMakeFiles/mltavformat.dir/filter_swresample.c.o  ../../../out/lib/libmlt-7.so.7.6.0 -lm /usr/lib64/libavformat.so /usr/lib64/libswscale.so /usr/lib64/libavutil.so /usr/lib64/libavcodec.so /usr/lib64/libavfilter.so /usr/lib64/libavdevice.so /usr/lib64/libswresample.so 
[   12s] /home/abuild/rpmbuild/BUILD/mlt-7.6.0/src/modules/avformat/factory.c:30:19: warning: type of 'filter_swresample_init' does not match original declaration [-Wlto-type-mismatch]
[   12s]    30 | extern mlt_filter filter_swresample_init( mlt_profile profile, char *arg );
[   12s]       |                   ^
[   12s] /home/abuild/rpmbuild/BUILD/mlt-7.6.0/src/modules/avformat/filter_swresample.c:265:12: note: type mismatch in parameter 2
[   12s]   265 | mlt_filter filter_swresample_init( mlt_profile profile, mlt_service_type type, const char *id, char *arg )
[   12s]       |            ^
[   12s] /home/abuild/rpmbuild/BUILD/mlt-7.6.0/src/modules/avformat/filter_swresample.c:265:12: note: 'filter_swresample_init' was previously declared here
[   12s] /home/abuild/rpmbuild/BUILD/mlt-7.6.0/src/modules/avformat/filter_swresample.c:265:12: note: code may be misoptimized unless '-fno-strict-aliasing' is used

**Comment by ddennedy** [comment]
Thanks. You can add this commit diff as a patch to your package until the next release.

**Comment by frispete** [comment]
Dan - I'm impressed! Since I started to contribute to Open-Source projects, I never encountered such a quick feedback with a fix. 

You made my day!

**Comment by ddennedy** [comment]
Heh, well, not always. I am working at the moment, waiting for a result, and these are simple, obvious problems and fixes. :-)
