### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by oberon2007** [mltframework/mlt#81]
Currently we are not able to build cerain software without depending on mlt-git. See https://github.com/nfnty/pkgbuilds/issues/3 Would it be possible for you to release a new version of mlt?

**Comment by ddennedy** [comment]
I do plan to release a new version of MLT this week. I don't know why are trying to build Shotcut yourself when a binary is readily available.

**Comment by ddennedy** [comment]
Version 0.9.8 is released.
