### ISSUE TITLE
msys2 builds fails on windows (no include directory)

### ISSUE THREAD

**Issue by yeahitsjan** [mltframework/mlt#814]
I use the latest MLT from git (``git clone``, https://github.com/mltframework/mlt/commit/99f437de1a669893e28db34012115e902a446ca0) on Windows 10 64-bit.

I try to link MLT to my Qt project. For that I created a folder ``libs`` and cloned MLT into it. Then I tried to build it using msys like this:

```
$ cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:/Qt/5/14_2/5.14.2/mingw73_64 -DCMAKE_INSTALL_PREFIX=$PWD/ibuild
$ cmake --build .
```

This generates some stuff in the ``out`` directory.
```
27.07.2022  21:43    <DIR>          .
27.07.2022  21:43    <DIR>          ..
27.07.2022  21:43    <DIR>          lib
27.07.2022  21:43           448.587 libmlt++-7.dll
27.07.2022  21:42           704.175 libmlt-7.dll
27.07.2022  21:43           310.294 melt.exe
27.07.2022  21:42    <DIR>          share
```

The ``lib`` folder contains the ``.a`` and a subfolder ``mlt`` with other DLLs like ``libmltcore.dll`` and others.

When using
```
$ cmake --install .
```
it installs that stuff into the directory I specified but erroring out with:
```
-- Installing: Z:/_Projects/_tests/qt-msys/libs/mlt/ibuild/lib/libmlt.dll
CMake Error at src/framework/cmake_install.cmake:45 (file):
  file INSTALL cannot find "Z:/_Projects/_tests/qt-msys/libs/mlt/libmlt.def":
  No error.
Call Stack (most recent call first):
  src/cmake_install.cmake:42 (include)
  cmake_install.cmake:49 (include)
```

What I think is kinda strange is that, not in the ``out`` dir nor in the install directory there is some kind of ``include/`` I can pass to my project file. How does that come?

I installed all necessary dependencies and followed along all build guides & tips that are provided. Any help would be really appreciated!

- Jan

**Comment by ddennedy** [comment]
Not sure. I build MLT with msys2 regularly here: https://github.com/mltframework/shotcut/actions/workflows/build-windows.yml
I can see from build log that it successfully installs a `libmlt.def`. One difference is that I am using `-G Ninja` instead and then calling ninja to build and install. There is nothing to build for an include dir, and it fails to install because the install failed.

**Comment by yeahitsjan** [comment]
@ddennedy it worked with Ninja.. interesting. I now also got an ``include`` directory I now can pass as ``INCLUDEPATH`` to my ``.pro`` file. Many thanks!
