### ISSUE TITLE
Missing MLT module: glaxnimate required to load Lottie animations

### ISSUE THREAD

**Issue by Sarthak77tiwari** [mltframework/mlt#825]
I have install **Kdenlive**  22.08.1 where it show me that `Missing MLT module: glaxnimate required to load Lottie animations` after that I am install **glaxnimate 0.5.1+deb-3a75daf1** but this not solve the issue 

my Ubuntu 
`Distributor ID:   Ubuntu
Description:  Ubuntu 22.04.1 LTS
Release:   22.04
Codename:  jammy`
 hardware is 
`Terminal: gnome-terminal 
Intel CPU: Intel i5-8250U (8) @ 3.400GHz 
GPU: Intel UHD Graphics 620 
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 
530/535 / 620/625 Mobile`
if I download the **mlt** code from here then how execute it in my system

**Comment by ddennedy** [comment]
It does not work by simply installing Glaxnimate. You need a build of MLT that includes this module.  How you get that is outside the scope of a bug report. It depends on your package system or app bundling. This is not a kdenlive support area, and we do not provide one-on-one guidance to build MLT. I suggest you look for a build of kdenlive that bundles this such as AppImage.
