### ISSUE TITLE
Crop has no effect on images

### ISSUE THREAD

**Issue by tslater** [mltframework/mlt#831]
I can't seem to get cropping working for images, although there is an example that uses cropping on images:  https://github.com/mltframework/mlt/blob/master/demo/mlt_slideshow2

I've tried many things, but here is a simple case: 
```
melt \
"https://files.wordscenes.com/phraseImages/11ed3c8be63fe060af5ab91c2d0996a4-vD1ujRcEdkNsrv2h7.jpeg?p=workaround" out=157 -attach crop active=1 center=1  \
"https://files.wordscenes.com/phraseImages/11ed3c8be63fe062af5ab91c2d0996a4-vK5d2J_uYUR7okdrP.jpeg?p=workaround" out=543 -attach crop active=1 center=1 \
-consumer avformat:/tmp/center-1.mp4 \
frame_rate_num=25 width=960 height=480 sample_aspect_num=1 sample_aspect_den=1\
-progress
```

I'm on melt 7.8.0, MacOS 12.5 (I've also had the same issue on an Alpine Linux docker container)

**Comment by ddennedy** [comment]
See how Shotcut does it and learn instead of guessing.
