### ISSUE TITLE
transparent .webm video overlay not working on 7.8.0

### ISSUE THREAD

**Issue by orlandozeta** [mltframework/mlt#834]
I have a mp4 video  and a webm transparent video, the rendering run fine on v 7.7.0, with the correct overlay, meanwhile in v 7.8.0 the webm video loose his transparency and the background is all black.

with v7.7.0:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/11095509/198290441-1e56626c-c6cb-433c-bbd3-a7f7e538c818.png">

with v7.8.0:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/11095509/198290722-3fe173be-6571-4592-8290-7ea80eb563ab.png">

**Comment by ddennedy** [comment]
I do not reproduce it with master branch and new version 7.10.0, and there is not enough information. Maybe your build is bad or doing something wrong. Try using Shotcut (that is what I used to make the vp9 with alpha and test this). Reopen only if you can provide complete details including an example webm and command line or simple MLT XML.
