### ISSUE TITLE
 Audio and video out of sync in avformat producer.

### ISSUE THREAD

**Issue by Adonis-Song** [mltframework/mlt#835]
Hi. 
I met some trouble when I use melt to export video.

My mlt version is v7.8.0. System version is Mac Big Sur 11.5.1 .

My melt command is
```
melt ~/Downloads/test.mp4 -consumer avformat:./result.mp4
```

But `result.mp4`  is out of sync.  

After using ffprobe to print info of the source video, I find the start time of video stream is not 0 and the start time of audio stream is 0.

And then I debug source code, find this code in function  `decode_audio`
```
	// If we're behind, ignore this packet
	// Skip this on non-seekable, audio-only inputs.
	if ( !discarded && pkt->pts >= 0 && ( self->seekable || self->video_format ) && *ignore == 0 && audio_used > samples / 2 )
	{
		int64_t pts = pkt->pts;
		if ( self->first_pts != AV_NOPTS_VALUE )
			pts -= self->first_pts;
		else if ( context->start_time != AV_NOPTS_VALUE && self->video_index != -1 )
			pts -= context->start_time;
		double timebase = av_q2d( context->streams[ index ]->time_base );
		int64_t int_position = llrint( timebase * pts * fps );
		int64_t req_position = llrint( timecode * fps );
		int64_t req_pts =      llrint( timecode / timebase );

```

but the timebase of `self->first_pts` is video stream's timebase , the timebase of `context->start_time` is AV_TIME_BASE_Q. So it should be as follows
 ```
	// If we're behind, ignore this packet
	// Skip this on non-seekable, audio-only inputs.
	if ( !discarded && pkt->pts >= 0 && ( self->seekable || self->video_format ) && *ignore == 0 && audio_used > samples / 2 )
	{
        double timebase = av_q2d( context->streams[ index ]->time_base );
        int64_t pts = pkt->pts;
		if ( self->first_pts != AV_NOPTS_VALUE )
			pts -= av_rescale_q(self->first_pts,
                                context->streams[self->video_index]->time_base,
                                context->streams[ index ]->time_base);
		else if ( context->start_time != AV_NOPTS_VALUE && self->video_index != -1 )
			pts -= av_rescale_q(context->start_time,
                                context->streams[self->video_index]->time_base,
                                AV_TIME_BASE_Q);
```
 
After changing to this code ,  my exported video is sync

**Comment by Adonis-Song** [comment]
Does anyone know if my modification is correct? Should I make a PR? 
@bmatherly Do you have any advice?

**Comment by bmatherly** [comment]
I was going to wait for Dan to come back on line since he is the expert in the avformat producer. It would be good if you could provide a diff and a link to an example file that demonstrates the problem. You would also do a PR for that. If the change is good, it will require quite a bit of testing to avoid regression.

**Comment by ddennedy** [comment]
> the timebase of context->start_time is AV_TIME_BASE_Q

See the [`AVFormatContext`](http://ffmpeg.org/doxygen/5.1/structAVFormatContext.html#a2590129e00adfa726ab2033a10e905e9) API docs, which says:

> Position of the first frame of the component, in AV_TIME_BASE fractional seconds. 

Your change is probably correct, but I need to do more analysis and testing, of course. Please do make a PR! But it will not be included in the next release, which is due in a day or two.

**Comment by ddennedy** [comment]
Here is a new sample file that has a video start time > 0 that demonstrates this bug and confirms the fix:
https://user-images.githubusercontent.com/1146683/213943766-e1878e6a-3e62-454b-b0b5-e8d1f594592a.mp4
