### ISSUE TITLE
Memory leak with affine filter

### ISSUE THREAD

**Issue by bmatherly** [mltframework/mlt#837]
The purpose of this issue is to collect evidence while debugging this issue:
https://forum.shotcut.org/t/size-position-and-rotate-doesnt-release-memory-when-scaling/36259/

Use the test jpg from the user report found here:
https://drive.google.com/file/d/1oNVIUCZeLkdbgSQcfSCwCrQtplVGWsQK/view?usp=sharing

This command line demonstrates the problem:
`melt -profile atsc_1080p_25 qimage:/home/brian/Downloads/shotcut_resize_problem/shotcut_resize_problem.jpg ttl=1 -filter frei0r.c0rners -filter affine transition.rect="00:00:00.000=-9 -2 1958 1102 1;00:00:23.967=-898.959 -2 3798.72 2138 1" -consumer null mlt_image_format=rgba real_time=-1`

Upon running this command, memory will leak immediately until system resources are exhausted

I added mlt_pool_stat( ); after each frame and found that the memory pool stays static - the size does not grow

Valgrind output does not show any obvious leaks on this order of magnitude: 
[valgrind-out.txt](https://github.com/mltframework/mlt/files/9906660/valgrind-out.txt)

**Comment by ddennedy** [comment]
When animating the affine rect the image dimensions to upstream services changes. The MLT frei0r filter adapter needs to reconstruct the frei0r plugin instance in this case. However, it was not destroying the old one (effectively like an unlimited cache in case that size was requested again). And some frei0r plugins such as c0rners allocate quite a bit of memory.
