### ISSUE TITLE
libmltrtaudio.so: undefined symbol: pa_simple_drain

### ISSUE THREAD

**Issue by godoppl** [mltframework/mlt#839]
Hi,
Running the latest version of melt-7 on Ubuntu 22.04
```
➜  ~ melt-7 --version
melt-7 7.10.0
Copyright (C) 2002-2022 Meltytech, LLC
<https://www.mltframework.org/>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  ~ uname -s -r -v -i
Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64
➜  ~ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

I am getting an error when executing the binary:
```
mlt_repository_init: failed to dlopen /usr/lib/x86_64-linux-gnu/mlt-7/libmltrtaudio.so
  (/usr/lib/x86_64-linux-gnu/mlt-7/libmltrtaudio.so: undefined symbol: pa_simple_drain)
```

It was running fine with the previous version (7.8.0), and there does not seem to be any recent updates to pulse audio, so I can not figure out what else could have triggered the issue.

Pulse audio version:
```
➜  ~ apt list -a pulseaudio
Listing... Done
pulseaudio/jammy-updates,now 1:15.99.1+dfsg1-1ubuntu2 amd64 [installed,automatic]
```

**Comment by neod123** [comment]
Same problem on my side when rendering with Kdenlive

**Comment by Findus23** [comment]
While hunting down another issue, I tried https://github.com/eszlari/mlt/commit/0663b26a6cbd8dd06de54f1fb7f8cfa789554aa7 and can confirm when applying it to melt 7.10.0-1 in Debian testing fixes the `undefined symbol: pa_simple_drain` message

**Comment by zaemiel** [comment]
> 

Could you explain what we have to do to fix the issue?

**Comment by godoppl** [comment]
@zaemiel I guess we need to either wait for the PR to be merged, and a new release, or build mlt from @eszlari's branch
