### ISSUE TITLE
 Automatic full screen video synthesis for more than ten minutes

### ISSUE THREAD

**Issue by exceptiondc** [mltframework/mlt#846]
melt \
-profile hdv_720_25p \
colour:black out=00:23:29.000 \
-track -blank 0 D:\eyinhe\record\img\img\bg.png out=00:23:29.000 \
-track \
 -blank 00:00:01.000 /eyinhe/record/temp/282ff4ba-9263-4173-82e6-98611b63644b.mp4 out=00:23:27.999 \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/f2d72fe2-52c2-4ff8-9501-3c7d3ce5abf0.mp4 out=00:22:03.999 \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/e68844a2-ef6d-4831-907f-894788ddcb96.mp4 out=00:23:28.999 \
-transition composite geometry=0%/0%:100%x100% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:00:00.000 out=00:23:29.999 \
-transition composite geometry=0%/0%:33.33%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:00:00.000 out=00:22:03.999 \
-transition composite geometry=33.33%/0%:33.33%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:00:00.000 out=00:23:28.999 \
-transition composite geometry=66.66%/0%:33.33%x33.33% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:00:01.000 out=00:23:27.999 \
-consumer avformat:/eyinhe/record/pbvideo/13cf6f21-e0ce-4069-8b36-7658bd27c275.mp4 acodec=aac vcodec=libx264

![image](https://user-images.githubusercontent.com/25631107/203745368-19692e20-c3c9-432f-ab05-d81087313f12.png)

**Comment by ddennedy** [comment]
You need to also set the “length” property on producers that have no inherent duration such as color and images.
