### ISSUE TITLE
The video was successfully clipped to a picture, but the audio was not mixed

### ISSUE THREAD

**Issue by exceptiondc** [mltframework/mlt#847]
melt \
-profile hdv_720_25p \
colour:black out=00:00:47.000length=00:00:47.000 \
-track \
 -blank 00:00:01.000 /temp/631eb451-89b1-4d70-bcb8-e4002346fe4a.mp4 length=00:00:45.000 out=00:00:46.999 \
-track \
 -blank 00:00:00.000 /temp/1751aff0-8917-4c23-8d1f-2c052599ab49.mp4 length=00:00:44.000 out=00:00:44.999 \
-track -blank 0 /temp/img/bg.png out=00:00:47.000  length=00:00:47.000 \
-transition composite geometry=0%/0%:100%x100% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:00:00.000 out=00:00:47.000 \
-transition composite geometry=0%/0%:33.33%x33.33% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:00:00.000 out=00:00:44.999 \
-transition composite geometry=33.33%/0%:33.33%x33.33% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:00:01.000 out=00:00:46.999 \
-consumer avformat:/temp/003.mp4 acodec=aac vcodec=libx264

![image](https://user-images.githubusercontent.com/25631107/204500239-75923309-f070-4e90-a59d-90e563afbb57.png)

**Comment by ddennedy** [comment]
You did not add any “mix” transitions. This is not a space for help. Help yourself by studying the XML that Kdenlive or Shotcut generates.
