### ISSUE TITLE
Building MLT on Clang/LLVM/libc++/MinGW (locale_t redefinition on libc++/Win32)

### ISSUE THREAD

**Issue by driver1998** [mltframework/mlt#852]
I am trying to build MLT 7.12.0 on a Clang/LLVM/libc++/MinGW environment, more specifically, MSYS2 CLANG64 and CLANGARM64 environments, in order to port it over to Windows ARM64. And I hit a very nasty issue.

MLT doesn't seem to use any locale support on Windows (all code that uses `locale_t` are ifdef'd out), and in `mlt_property.h`, `locale_t` is typedef'd as a `char *`, basically as a stub.

```
typedef char* locale_t;
```

It works reasonably well on GCC/libstdc++/MinGW, but on Clang/libc++, they defined a `locale_t` in their standard C++ locale implementation for win32. And it is a C++ class (see include/c++/v1/__support/win32/locale_win32.h). 

So any C++ code that depend on locale or iostream and such will fail hard on redefinition of `locale_t`.

And since that is a C++ class, I can't just use that in `mlt_property.h`, even though the whole purpose of `locale_t` on MLT on Windows seems to be just a stub.

So far I can come up with a hard fix: replace any usage of `locale_t` in MLT to `mlt_locale_t` and typedef it back to `locale_t` on non-Windows platforms. But I wonder if this will be accepted upstream.

**Comment by driver1998** [comment]
cc @Biswa96

**Comment by ddennedy** [comment]
While locale is being used on Windows (via `setlocale`), usage of locale in MLT is loosely deprecated. However, I will accept something that does not break ABI at this time and does not actually do anything. The plan for the next major version is to actually remove locale or possibly add an option to build it as noop: https://www.mltframework.org/changes/todo/

**Comment by driver1998** [comment]
`mlt_property.h` is a public header so shuffling types around is a API break. But I think it won't break the ABI since the underlying type would be the same.

Also it would be perfectly fine if clang or Windows ARM support won't happen until the next major release. I just want to point out the current state of things.

**Comment by driver1998** [comment]
With #856 merged, I guess we can close this issue now.

**Comment by ddennedy** [comment]
Thank you for your contribution!
