### ISSUE TITLE
melt, transport, keyboard, sdl window

### ISSUE THREAD

**Issue by GerryHickman** [mltframework/mlt#854]
mlt built from v7.12.0.tar.gz

The melt program has a "transport", and using the keyboard, you can press 'l' to go forward one frame, or 'h' to go back one frame.

The keyboard events can come from the terminal, or from the SDL window, depending on which one is active.

When the keyboard events come from the terminal, it sees the difference between upper case and lower case letters, but when the keyboard events come from the SDL window it only sees lower case letters, so capital 'L' will end up as small 'l'. This means the one minute seek does not work.

It looks like it needs to check the 'mod' member of 'SDL_Keysym', somthing like

if (keymod & KMOD_SHIFT)

**Comment by bmatherly** [comment]
> The keyboard events can come from the terminal, or from the SDL window, depending on which one is active.

Just FYI, this feature only exists in the SDL module. The SDL2 consumer does not have any key handling implemented.

**Comment by GerryHickman** [comment]
I'm using the SDL2 consumer. I get an error if I try to use the SDL1 consumer:
```
Error: This program was linked against SDL2, which is incompatible with
SDL1 consumers. Aborting.
```
I can also see [consumer sdl2] if I enable -debug output.

I think the keyboard handling code is in 'src/melt/melt.c', as opposed to in the consumer. The function called 'void event_handling(...)' sets up 'SDL_PollEvent', so receives events from the SDL2 window when it's active.
