### ISSUE TITLE
Frei0r transitions not detected after upgrade to 7.12.0

### ISSUE THREAD

**Issue by SpacemanPaul** [mltframework/mlt#855]
System: Debian testing (bookworm) with melt-7 and frei0r installed via deb-multimedia, v7.12.0

After upgrading to 7.12.0, no frei0r transitions are being detected by melt:

```
$ melt-7 -query transitions
---
transitions:
  - qtblend
  - vqm
  - movit.luma_mix
  - movit.mix
  - movit.overlay
  - affine
  - composite
  - luma
  - mix
  - matte
...
```

**Comment by ddennedy** [comment]
Where are the frei0r plugins installed? We did not change where they are looked for in this version. Seems like a packaging problem. Look at installed MLT files for a libmltfrei0r.so.

**Comment by SpacemanPaul** [comment]
Mine are at: `/usr/lib/x86_64-linux-gnu/frei0r-1/`

Yep, I've got a libmltfrei0r.so:

```
$ ls -l /usr/lib/x86_64-linux-gnu/mlt-7/libmltfrei0r.so
-rw-r--r-- 1 root root 35608 Dec  1 01:40 /usr/lib/x86_64-linux-gnu/mlt-7/libmltfrei0r.so
```

**Comment by ddennedy** [comment]
That is not a standard, accepted path. You can read about that [here](https://frei0r.dyne.org/codedoc/html/group__pluglocations.html) as well as an environment variable you can use to override it. See also in MLT code https://github.com/mltframework/mlt/blob/1a91df9c2209eaeddd3f4b864a69497f5ef8b4e4/src/modules/frei0r/factory.c#L48

**Comment by SpacemanPaul** [comment]
Awesome, thanks for you help.

**Comment by SpacemanPaul** [comment]
Confirming that works. I'll try to send a message upstream to the packagers.
