### ISSUE TITLE
Glaxnimate as an external dependency

### ISSUE THREAD

**Issue by tobiasBora** [mltframework/mlt#857]
I am helping packaging Mlt+glaxnimate for NixOs, but we are surprised to see that there is no way to re-use the glaxnimate package as MLT downloads and compiles glaxnimate in a submodule. This does not seem really elegant for multiple reasons, leading to this conversation https://github.com/NixOS/nixpkgs/pull/209941:
- we need to compile glaxnimate twice
- the options/versions betweeen MLT's glaxnimate and the package glaxnimate might differ… potentially creating weird bugs (but I don't know enough about how MLT uses glaxnimate to say more)
- any patch (security, NixOs specific…) potentially applied to glaxnimate will not propagate to MLT, leading to maintenance headache.

It would be great to provide a way to use glaxnimate's package instead, even if I don't know much if it's something that must be done on your side or on both glaxnimate and MLT.

**Comment by tobiasBora** [comment]
I just filled a bug also on glaxnimate as they don't seem to provide a way to install the library here https://gitlab.com/mattbas/glaxnimate/-/issues/545, let me know if it's actually stopping you from using glaxnimate directly.

**Comment by ddennedy** [comment]
What I created is sufficient for my needs. If you want to do it differently make the change yourself and submit a pull request.
