### ISSUE TITLE
Facing issues while configuring MLT

### ISSUE THREAD

**Issue by 09mayurM** [mltframework/mlt#863]
Hi,
I was trying to configure MLT in my local. I am following this following document (https://www.mltframework.org/docs/buildscripts/). While running ./melted-build.sh command which is under Melted/Run the Script section I am getting the following error, Unable to configure mlt. Does anyone here has faced the same issue or if anyone has any solution for this please let me know I am stuck and not able to make any further progress.

Thanks!!

**Comment by ddennedy** [comment]
That script is very old, and melted no longer maintained supported. It is based on an older build system for MLT.

**Comment by 09mayurM** [comment]
> That script is very old, and melted no longer maintained supported. It is based on an older build system for MLT.

Hi ddennedy, Thanks for your answer. Is there any alternative that I can use?
