### ISSUE TITLE
Add new Shader filter

### ISSUE THREAD

**Issue by manojmmewara** [mltframework/mlt#867]
Hi There @ddennedy 
I need to integrate one gl-transition effect as a transition in MLT. 
I found Webvfx can do the job but there is not much documentation out there and its deprecated. 
Can you please suggest the best possible solution here or if you have any reference or sample by following that I can add this transition?
Thanks in advance !!!

**Comment by ddennedy** [comment]
This is not a defect, and this issue tracker is for bugs only. Movit is like your only option right now, but it is not a normal 8-bit RGB framework; so, most shader code cannot be simply dropped into a template. Good luck
