### ISSUE TITLE
FFmpeg avfilter

### ISSUE THREAD

**Issue by Augadh1** [mltframework/mlt#868]
Hi @ddennedy
I created one custom filter under av filter and added it into ffmpeg.
I build the ffmpeg and in ffmpeg its working fine and visible in ffmpeg filter list.
Now I tried to build mlt with this custom ffmpeg. mlt build successfully.
I checked in mlt filters but it is not available.
On investigating I found in mlt there is no avfilter available which can take 2 videos as input.
As my filter also takes 2 videos as input and apply some filter and output one video.

Can you please tell me why you are not supporting multiple input av filter ?
Also where you restricted it.

**Comment by bmatherly** [comment]
> Can you please tell me why you are not supporting multiple input av filter ?

MLT Filter objects only support input from one source. So using an AV filter with multiple inputs can not work. This is fundamental to the design of MLT.

> Also where you restricted it.

https://github.com/mltframework/mlt/blob/master/src/modules/avformat/factory.c#L448

MLT transitions can mix two frames from different sources. It would be possible to make an MLT transition similar to MLT filter that provides access to AV filters with two inputs. Nobody has volunteered to implement this yet.

**Comment by Augadh1** [comment]
@bmatherly, Thanks for quick reply. I just had one more query. 
I have seen fragment shader implementation in couple of transition effect (luma_mix) in movit library.
will it be feasible to add new transition effect supporting gl transition ?
