### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [mltframework/mlt#872]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [ClipInfo](https://github.com/mltframework/mlt/blob/9c3bb7d997a78fed3142c2ef95988623d21dce15/src/mlt%2B%2B/MltPlaylist.cpp#L43)
- [PushConsumer](https://github.com/mltframework/mlt/blob/493fa4b642099d295ea5b2b78f85a366a3d8c9ad/src/mlt%2B%2B/MltPushConsumer.cpp#L55)

**Comment by ddennedy** [comment]
Not needed
