### ISSUE TITLE
using deprecated function of ffmpeg avfilter

### ISSUE THREAD

**Issue by Augadh1** [mltframework/mlt#875]
Hi
I am building mlt. It build successfully. When I am running **_melt -query_** I am not seeing any avfilters in the output.

On debugging I found that **_avfilter_pad_count_** function is removed from **_avfilter.h_**. I found that ffmpeg has removed this function and instead of this they are recommending to use **_avfilter_filter_pad_count_**.

One more function also removed from ffmpeg **_av_mallocz_array_**. Alternative for this is **_av_calloc_**.

I replaced both the function in mlt and tried to build it but its giving me the error.
(replaced avfilter_pad_count to avfilter_filter_pad_count in avformat/factory.c)
(replaced av_mallocz_array to av_calloc in avformat/common_swr.c)

**Comment by ddennedy** [comment]
If you are using ffmpeg git master that might be a problem. We don’t update MLT every day as ffmpeg changes. Best to stick to release 5.1 at this time.

**Comment by tgurr** [comment]
This now appears to be an issue with the recently released ffmpeg 6, while it still compiles without errors there are runtime issues like op stated:

```
$ melt -query
mlt_repository_init: failed to dlopen /usr/x86_64-pc-linux-gnu/lib/mlt-7/libmltavformat.so
  (/usr/x86_64-pc-linux-gnu/lib/mlt-7/libmltavformat.so: undefined symbol: avfilter_pad_count)
```
Woule be nice to see this updated for ffmpeg 6 compatibility, having had a quick look at git master I could not spot any relevant commits we could already backport.
