### ISSUE TITLE
Make build work with -Wall -Werror

### ISSUE THREAD

**Issue by Tjoppen** [mltframework/mlt#877]
Currently the build spews warnings, which makes it difficult to catch new warnings. On gcc (and maybe clang?) -Wall and -Werror should be added and all warnings fixed, and any exceptions to this should be explicitly marked in C(XX)FLAGS.

The following addition to CMakeLists.txt improves the situation and makes explicit what warnings currently exist, some of which are quite serious, for example -Wno-restrict:

```cmake
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set(GCC_FLAGS "-Wall -Werror -Wno-unused-variable -Wno-unused-function -Wno-switch -Wno-parentheses -Wno-sequence-point -Wno-deprecated-declarations -Wno-return-type -Wno-restrict -Wno-unused-but-set-variable -Wno-format -Wno-format-truncation")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GCC_FLAGS}")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${GCC_FLAGS} -Wno-discarded-qualifiers")
endif ()
```

**Comment by bmatherly** [comment]
Using your proposal as an inspiration, I have a proposed resolution here: https://github.com/mltframework/mlt/pull/893

Please test it and comment.

**Comment by bmatherly** [comment]
A version of this is committed now.
