### ISSUE TITLE
Artifacts with images

### ISSUE THREAD

**Issue by frdbr** [mltframework/mlt#888]
On MLT master when adding JPG images to a project causes some artifacts in monitors.  Also when working with PNGs this didn't happen but the project did not render. (Can't tell if it is related.)

This is what I get in the terminal:

```
MLT: "[filter swscale] sws_scale_frame failed with -22 (Invalid argument)"
MLT: "[link avdeinterlace ] Failed to get image"
[swscaler @ 0x7f8967a153c0] Value 0.000000 for parameter 'srcw' out of range [1 - 2.14748e+09]
[swscaler @ 0x7f8967a153c0] Value 0.000000 for parameter 'srch' out of range [1 - 2.14748e+09]
[IMGUTILS @ 0x7f8989ffa6c0] Picture size 0x0 is invalid
MLT: "[filter swscale] sws_scale_frame failed with -22 (Invalid argument)"
```

![image](https://user-images.githubusercontent.com/77309092/225918963-588cb0c2-e2a1-4902-93b9-38454ac5104f.png)

**Comment by bmatherly** [comment]
Thanks for your report. Can you provide a melt command that reproduces this? I think that the MLT framework does not expect a PNG file to be in a chain.  It would be better if KDENLIVE did not put image files in chains. But I can fix it so it works.

**Comment by j-b-m** [comment]
Oh, you're right. Kdenlive incorrectly puts images in chains. I will fix it for the upcoming release.

**Comment by bmatherly** [comment]
I didn't mean to imply that it is "incorrect". Just unexpected and untested. I have fixed it now. It is up to you if you want to put images in chains. Maybe that will be useful for time/speed effects on image sequences. If you test that out, let me know.
