### ISSUE TITLE
enable webvfx in mlt framework

### ISSUE THREAD

**Issue by Augadh1** [mltframework/mlt#892]
Hi I am trying to enable webvfx in mlt. I updated buid_melt script and set ENABLE_WEBVFX flag.
When I am building mlt, It is giving me the error.
![webvfx_error](https://user-images.githubusercontent.com/39818153/227426541-aeb96c99-b7b3-4c26-97bb-b3eb26d5d54d.png)

I tried enabling webvfx in docker container of mlt also. there also it is giving error.

**Comment by ddennedy** [comment]
melted and webvfx are no longer maintained or supported.
