### ISSUE TITLE
One Definition Rule violation

### ISSUE THREAD

**Issue by jlskuz** [mltframework/mlt#905]
```
./src/modules/qt/filter_audiolevelgraph.cpp:35:3: error: type ‘struct private_data’ violates the C++ One Definition Rule [-Werror=odr]
./src/modules/qt/filter_audiowaveform.cpp:39:3: note: a different type is defined in another translation unit
./src/modules/qt/filter_audiolevelgraph.cpp:33:16: note: the first difference of corresponding definitions is field ‘levels_filter’
./src/modules/qt/filter_audiowaveform.cpp:33:11: note: a field with different name is defined in another translation unit
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

I am not sure how to fix this best. Something like 
```c
namespace audiolevelgraph {
    // Private Types
    typedef struct
    {
        mlt_filter levels_filter;
        int preprocess_warned;
    } private_data;
}
```
and hence `audiolevelgraph::private_data` should work, but maybe there is a better solution?

**Comment by ddennedy** [comment]
I do not know the answer as I have never run into it, but does not using `typedef` work?
```
struct private_data
{
...
}
```

**Comment by bmatherly** [comment]
@jlskuz, I suggest to wrap the struct in an anonymous namespace so the struct will have internal linkage.
https://www.learncpp.com/cpp-tutorial/unnamed-and-inline-namespaces/
Would you  be willing to test this for us and submit a patch if it works?
If you are not able to do that, I can propose a patch for you to test.

Also, why does your compiler flag errors that our automated builds to not detect? I would prefer that our automated workflows find these problems (or even our developer tools).

**Comment by jlskuz** [comment]
Thanks for the suggestion @bmatherly , I wrote a patch with anonymous namespaces and that made it build again. I will open a PR soon.

I have no idea why the build of PPA build fails, but the mlt pipeline and local builds not. I toke maintainer ship of the PPA over recently and I am lucky I some how mange to keep it alive, but don't have further expertise or knowledge on insides of launchpad and build options etc. it might set.

However one thing interesting to mention: on the PPA the build only fails on Ubuntu Kinetic and Jammy. Focal builds fine also without the patch.
