### ISSUE TITLE
Render dynamic animated editable text

### ISSUE THREAD

**Issue by Augadh1** [mltframework/mlt#908]
I am working on one web application development where i need to render glsl which can support editable animated text. Whereas User can edit the animated text which can be rendered through webgl.

Can you please provide me and reference link or if there any working GLSL code where i can pass editable text as input?

eg. I want to have same animation as provided in the below link using glsl https://tobiasahlin.com/moving-letters/#1

**Comment by ddennedy** [comment]
invalid bug report
