### ISSUE TITLE
mlt-7.14.9999 adds 9 video filters to all clips on project load in shotcut

### ISSUE THREAD

**Issue by Yamakuzure** [mltframework/mlt#910]
Hey everybody,

As there was a memory issue with the latest 7.14.0 release, I built mlt from github last night, as the memory issue got fixed.
Before I used mlt-7.12.0, because 7.14.0 also makes rendering take a lot longer than with 7.12.0, but I wanted to give it a shot again.

So today I open a project in shotcut where a lot of flac files have two filters: Stereo Enhancer and Normalize 2-Pass.

And both filters are there on all audio files placed on an audio track.

Additionally, 9 (ô.O) video filters that make absolutely no sense were also present.

As I normally do one setup of my voice-overs and then copy-pasta the filters to all files, I pasted it into a text editor, and it only shows two filters:

- `<property name="mlt_service">loudness</property>`
- `<property name="mlt_service">avfilter.haas</property>`

The two filters I have set up.

But why does Shotcut now also display:

- avdeinterlace
- fieldorder
- Crop: Source
- swscale
- resize
- avcolor_space
- swresample
- audiochannels

as Video filters on an audio-channel?

So I checked the video clips, and they all have these filters, too.
None of these are needed. 

To make sure this is not a Shotcut-issue, I downgraded mlt to 7.12.0.
The results were that:

1. The project loaded in 3 seconds instead of 15, and
2. all "fake" filters were gone.

This implies that mlt somehow adds these filters on its own.
Why?

**Comment by ddennedy** [comment]
You are building an unsupported combination of versions. Old versions of Shotcut are not compatible with new versions of MLT. MLT has always added these filters but Shotcut hides them. Use the latest git master version of Shotcut with that version (invalid number) of MLT.

**Comment by Yamakuzure** [comment]
> version (invalid number) of MLT.

The addition `.9999` means "live-build from repository".

**Comment by bmatherly** [comment]
mlt-7.14.9999 is the MLT version. You need to use the latest version of Shotcut.
