### ISSUE TITLE
Unknown build error

### ISSUE THREAD

**Issue by laszloatoth** [mltframework/mlt#911]
This tracker is for defects only! For feature requests, you can submit a pull
request with the changes.

If you’re reporting a defect, make it as detailed as possible, and include both your operating system and MLT versions (e.g. `macOS 10.16; MLT v7.4.0`).
Hi All,
I have an Ubuntu 22.04 running PC and trying to install latest 7.14.0 MLT version. I gathered and installed all of the SW dependencies and dev libraries that needs .Until the following command usage everything is fine:
**sudo cmake --build .**
then when libmltplus.so system object started to be assembled the error message:

laci@Sanyika:/mlt$ sudo cmake --build .
Consolidate compiler generated dependencies of target mlt
[ 10%] Built target mlt
Consolidate compiler generated dependencies of target melt
[ 11%] Built target melt
Consolidate compiler generated dependencies of target mlt++
[ 21%] Built target mlt++
Consolidate compiler generated dependencies of target mltcore
[ 36%] Built target mltcore
Consolidate compiler generated dependencies of target mltavformat
[ 40%] Built target mltavformat
Consolidate compiler generated dependencies of target mltdecklink
[ 42%] Built target mltdecklink
Consolidate compiler generated dependencies of target mltfrei0r
[ 44%] Built target mltfrei0r
Consolidate compiler generated dependencies of target mltgdk
[ 46%] Built target mltgdk
Consolidate compiler generated dependencies of target mltjackrack
[ 47%] Built target mltjackrack
Consolidate compiler generated dependencies of target mltkdenlive
[ 50%] Built target mltkdenlive
Consolidate compiler generated dependencies of target mltnormalize
[ 51%] Built target mltnormalize
Consolidate compiler generated dependencies of target mltoldfilm
[ 54%] Built target mltoldfilm
Consolidate compiler generated dependencies of target mltmovit
[ 62%] Built target mltmovit
Consolidate compiler generated dependencies of target mltplus
[ 63%] Linking C shared module ../../../out/lib/mlt/libmltplus.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(lt7-conf.o): warning: relocation against `fftw_solvtab_rdft_r2r' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/modules/plus/CMakeFiles/mltplus.dir/build.make:516: out/lib/mlt/libmltplus.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1327: src/modules/plus/CMakeFiles/mltplus.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
laci@Sanyika:~/mlt$ ^C

**the initial config file is:**
laci@Sanyika:~/mlt$ sudo cmake .
[sudo] password for laci: 
-- The following features have been enabled:

 * GPLv2
 * GPLv3
 * Clang Format
 * Module: avformat
 * Module: DeckLink
 * Module: Frei0r
 * Module: GDK
 * Module: JACKRack
 * Module: Kdenlive
 * Module: Normalize
 * Module: Oldfilm
 * Module: Movit
 * Module: Plus
 * Module: PlusGPL
 * Module: Qt (Qt5)
 * Module: Resample
 * Module: RtAudio
 * Module: Rubberband
 * Module: SDL1
 * Module: SDL2
 * Module: SoX
 * Module: vid.stab
 * Module: Vorbis
 * Module: XINE
 * Module: XML

-- The following OPTIONAL packages have been found:

 * JACK
 * OpenGL
 * Freetype
 * Fontconfig
 * Qt5Core
 * Qt5Xml
 * Qt5Gui
 * Qt5Svg
 * Qt5Widgets
 * Qt5
 * SWIG
 * ClangFormat (required version == 14)

-- The following REQUIRED packages have been found:

 * Threads
 * PkgConfig
 * X11

-- The following features have been disabled:

 * Tests
 * Doxygen
 * Module: Glaxnimate (Qt5)
 * Module: Glaxnimate (Qt6)
 * Module: NDI
 * Module: OpenCV
 * Module: Qt6
 * SWIG: C#
 * SWIG: Java
 * SWIG: Lua
 * SWIG: Node.js
 * SWIG: Perl
 * SWIG: PHP
 * SWIG: Python
 * SWIG: Ruby
 * SWIG: Tcl

-- Configuring done
-- Generating done
-- Build files have been written to: /home/laci/mlt
laci@Sanyika:~/mlt$ 

What went wrong? How can I repair it? Thanks.
BR,
  Laci.

**Comment by ddennedy** [comment]
`/usr/local/lib/libfftw3.a` was built incorrectly and should be removed. I recommend using the fftw -dev package via apt instead of building it yourself. This is not a bug in our build system. Building MLT is not easy. If you do not have a lot of experience, I do not recommend it.

**Comment by laszloatoth** [comment]
Ok, thanks for the quick answer. I never thought it is  a compile/build process fault. I need MLT only for Kdenlive app. purposes. Is it available somewhere that does not need compile?
I have already removed 
libfftw3.a file
and re-installed via apt-get fftw-dev_2.1.5-6_amd64.deb package. So actually no such file on my PC. But the build script needs the mentioned file.
_[ 62%] Built target mltmovit
Consolidate compiler generated dependencies of target mltplus
gmake[2]: *** No rule to make target '/usr/local/lib/libfftw3.a', needed by 'out/lib/mlt/libmltplus.so'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:1327: src/modules/plus/CMakeFiles/mltplus.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2_


How can I have the appropriate libfftw3.a file in my /usr/local/lib directory? Should I put it here manually?
__laci@Sanyika:~$ sudo apt-get reinstall fftw-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done_
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 256 kB of archives._
Thanks.
L.

**Comment by ddennedy** [comment]
The build files generated by cmake assume the fftw library is still in the old location. It is not smart and adapative. You would need to remove all the mlt build files and start over by running cmake. I suggest you to use https://kdenlive.org/en/download/ to get the latest version of Kdenlive with the latest version of MLT.
