### ISSUE TITLE
autorotate property not working on chains (except using the xml producer)

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#913]
the avformat `autorotate` property is not correctly passed on chains  (using melt and also when building a chain producer using Mlt::Chain). This only works using the xml_producer since the properties are passed on the producer before opening it.

Using a vertical clip (typically from a phone) that has a rotate flag, trying to disable rotation works using producer, but not using chain:

`melt -profile atsc_1080p_25 vertical.mp4 autorotate=0`
Works correctly, the video rotation is disabled and clip has an horizontal orientation.

`melt -profile atsc_1080p_25 -chain vertical.mp4 autorotate=0`
Fails, the clip is still playing vertically.

From my understanding, problem is that when creating a Chain (mlt_chain_set_source), the producer is opened. Changing the "autorotate" property after the producer has already been opened does not work. This could potentially affect other properties.

In producer_melt.c, mlt_chain_set_source is called first[1], then the arguments are passed in a later stage [2]

[1] https://github.com/mltframework/mlt/blob/master/src/modules/core/producer_melt.c#L441
[2] https://github.com/mltframework/mlt/blob/master/src/modules/core/producer_melt.c#L425

Not sure what would be the best way to solve this...

Using latest MLT git

**Comment by ddennedy** [comment]
I recently fixed something along this line for color_range and force_full_range. Fix is similar.
