### ISSUE TITLE
mix Sound decreases

### ISSUE THREAD

**Issue by exceptiondc** [mltframework/mlt#919]
I used mix, but the synthesized video has a smaller sound compared to the source video. May I ask what the problem is

melt \
-profile hdv_720_25p \
colour:black out=00:03:31.000 length=00:03:31.000 \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/2d3beb8d-b5c6-4ca8-8230-1d67b7632f53.mp4 length=00:11:31.000 in=00:07:53.000 out=00:11:23.999 -attach watermark:+2015.txt  \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/89a690b6-6dc5-4ac7-8cbd-967a443bee60.mp4 length=00:09:47.000 in=00:06:41.000 out=00:09:46.999 -attach watermark:+2001.txt  \
 -blank 00:00:00.000 /eyinhe/record/temp/4448df07-389f-485d-b879-b1d98800372e.mp4 length=00:00:29.000 in=00:00:00.000 out=00:00:24.999 -attach watermark:+2001.txt  \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/c6be010d-010f-40bd-b61f-b8bd9f68fc4b.mp4 length=00:10:15.000 in=00:06:37.000 out=00:10:07.999 -attach watermark:+2037.txt  \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/d3ab98a2-4d08-4639-8a3e-b183e6731360.mp4 length=00:09:45.000 in=00:06:06.000 out=00:09:36.999 -attach watermark:+2022.txt  \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/4b15ca01-b1a0-4c71-95b8-16d804c24ad3.mp4 length=00:08:31.000 in=00:04:53.000 out=00:08:23.999 -attach watermark:+2020.txt  \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/6444b3ca-62ec-4939-9d89-9c47b1ad40ac.mp4 length=00:08:23.000 in=00:04:45.000 out=00:08:15.999 -attach watermark:+2009.txt  \
-track \
 -blank 00:00:00.000 /eyinhe/record/temp/eb0e8557-daac-47b4-962c-ab2ccf964122.mp4 length=00:07:52.000 in=00:04:14.000 out=00:07:44.999 -attach watermark:+2046.txt  \
-track -blank 0 /eyinhe/record/img/bg.png out=00:03:31.000  length=00:03:31.000 \
-transition composite geometry=0%/0%:100%x100% a_track=0 b_track=8 sliced_composite=1 distort=1 in=00:00:00.000 out=00:03:31.000 \
-transition composite geometry=0%/0%:33.33%x33.33% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:43.999 \
-transition mix  a_track=0 b_track=2  in=00:00:00.000 out=00:02:43.999 \
-transition composite geometry=66.66%/0%:33.33%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:40.999 \
-transition mix  a_track=0 b_track=4  in=00:00:00.000 out=00:02:40.999 \
-transition composite geometry=0%/33.33%:33.33%x33.33% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:40.999 \
-transition mix  a_track=0 b_track=1  in=00:00:00.000 out=00:02:40.999 \
-transition composite geometry=33.33%/33.33%:33.33%x33.33% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:40.999 \
-transition mix  a_track=0 b_track=5  in=00:00:00.000 out=00:02:40.999 \
-transition composite geometry=66.66%/33.33%:33.33%x33.33% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:40.999 \
-transition mix  a_track=0 b_track=6  in=00:00:00.000 out=00:02:40.999 \
-transition composite geometry=0%/66.66%:33.33%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:40.999 \
-transition mix  a_track=0 b_track=3  in=00:00:00.000 out=00:02:40.999 \
-transition composite geometry=66.66%/66.66%:33.33%x33.33% a_track=0 b_track=7 sliced_composite=1 distort=1 in=00:00:00.000 out=00:02:40.999 \
-transition mix  a_track=0 b_track=7  in=00:00:00.000 out=00:02:40.999 \
-transition composite geometry=0%/0%:50%x100% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:02:44.000 out=00:02:47.999 \
-transition mix  a_track=0 b_track=2  in=00:02:44.000 out=00:02:47.999 \
-transition composite geometry=50%/0%:50%x100% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:02:44.000 out=00:02:47.999 \
-transition mix  a_track=0 b_track=1  in=00:02:44.000 out=00:02:47.999 \
-transition composite geometry=25%/0%:75%x100% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:02:48.000 out=00:02:50.999 \
-transition mix  a_track=0 b_track=2  in=00:02:48.000 out=00:02:50.999 \
-transition composite geometry=0%/0%:25%x33.33% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:02:48.000 out=00:02:50.999 \
-transition mix  a_track=0 b_track=1  in=00:02:48.000 out=00:02:50.999 \
-transition composite geometry=0%/33.33%:25%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:02:48.000 out=00:02:50.999 \
-transition mix  a_track=0 b_track=3  in=00:02:48.000 out=00:02:50.999 \
-transition composite geometry=0%/66.66%:25%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:02:48.000 out=00:02:50.999 \
-transition mix  a_track=0 b_track=4  in=00:02:48.000 out=00:02:50.999 \
-transition composite geometry=0%/0%:50%x66.66% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:02:51.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=2  in=00:02:51.000 out=00:02:54.999 \
-transition composite geometry=50%/0%:50%x66.66% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:02:51.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=1  in=00:02:51.000 out=00:02:54.999 \
-transition composite geometry=0%/66.66%:25%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:02:51.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=3  in=00:02:51.000 out=00:02:54.999 \
-transition composite geometry=25%/66.66%:25%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:02:51.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=4  in=00:02:51.000 out=00:02:54.999 \
-transition composite geometry=50%/66.66%:25%x33.33% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:02:51.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=5  in=00:02:51.000 out=00:02:54.999 \
-transition composite geometry=75%/66.66%:25%x33.33% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:02:51.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=6  in=00:02:51.000 out=00:02:54.999 \
-transition composite geometry=0%/0%:33.33%x33.33% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=2  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=33.33%/0%:33.33%x33.33% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=1  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=66.66%/0%:33.33%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=3  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=0%/33.33%:33.33%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=4  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=33.33%/33.33%:33.33%x33.33% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=5  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=66.66%/33.33%:33.33%x33.33% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=6  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=0%/66.66%:33.33%x33.33% a_track=0 b_track=7 sliced_composite=1 distort=1 in=00:02:55.000 out=00:03:16.999 \
-transition mix  a_track=0 b_track=7  in=00:02:55.000 out=00:03:16.999 \
-transition composite geometry=0%/0%:100%x100% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:19.999 \
-transition mix  a_track=0 b_track=2  in=00:03:17.000 out=00:03:19.999 \
-transition composite geometry=0%/0%:50%x100% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:03:20.000 out=00:03:22.999 \
-transition mix  a_track=0 b_track=2  in=00:03:20.000 out=00:03:22.999 \
-transition composite geometry=50%/0%:50%x100% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:03:20.000 out=00:03:22.999 \
-transition mix  a_track=0 b_track=1  in=00:03:20.000 out=00:03:22.999 \
-transition composite geometry=25%/0%:75%x100% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:03:23.000 out=00:03:25.999 \
-transition mix  a_track=0 b_track=2  in=00:03:23.000 out=00:03:25.999 \
-transition composite geometry=0%/0%:25%x33.33% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:03:23.000 out=00:03:25.999 \
-transition mix  a_track=0 b_track=1  in=00:03:23.000 out=00:03:25.999 \
-transition composite geometry=0%/33.33%:25%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:03:23.000 out=00:03:25.999 \
-transition mix  a_track=0 b_track=3  in=00:03:23.000 out=00:03:25.999 \
-transition composite geometry=0%/66.66%:25%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:03:23.000 out=00:03:25.999 \
-transition mix  a_track=0 b_track=4  in=00:03:23.000 out=00:03:25.999 \
-transition composite geometry=0%/0%:50%x66.66% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:03:26.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=2  in=00:03:26.000 out=00:03:27.999 \
-transition composite geometry=50%/0%:50%x66.66% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:03:26.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=1  in=00:03:26.000 out=00:03:27.999 \
-transition composite geometry=0%/66.66%:25%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:03:26.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=3  in=00:03:26.000 out=00:03:27.999 \
-transition composite geometry=25%/66.66%:25%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:03:26.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=4  in=00:03:26.000 out=00:03:27.999 \
-transition composite geometry=50%/66.66%:25%x33.33% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:03:26.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=5  in=00:03:26.000 out=00:03:27.999 \
-transition composite geometry=75%/66.66%:25%x33.33% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:03:26.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=6  in=00:03:26.000 out=00:03:27.999 \
-transition composite geometry=0%/0%:33.33%x33.33% a_track=0 b_track=2 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=2  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=33.33%/0%:33.33%x33.33% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=1  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=66.66%/0%:33.33%x33.33% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=3  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=0%/33.33%:33.33%x33.33% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=4  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=33.33%/33.33%:33.33%x33.33% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=5  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=66.66%/33.33%:33.33%x33.33% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=6  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=0%/66.66%:33.33%x33.33% a_track=0 b_track=7 sliced_composite=1 distort=1 in=00:03:28.000 out=00:03:30.999 \
-transition mix  a_track=0 b_track=7  in=00:03:28.000 out=00:03:30.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:02:41.000 out=00:02:43.999 \
-transition mix  a_track=0 b_track=1  in=00:02:41.000 out=00:02:43.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=1 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:19.999 \
-transition mix  a_track=0 b_track=1  in=00:03:17.000 out=00:03:19.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:02:41.000 out=00:02:47.999 \
-transition mix  a_track=0 b_track=3  in=00:02:41.000 out=00:02:47.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=3 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:22.999 \
-transition mix  a_track=0 b_track=3  in=00:03:17.000 out=00:03:22.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:02:41.000 out=00:02:47.999 \
-transition mix  a_track=0 b_track=4  in=00:02:41.000 out=00:02:47.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=4 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:22.999 \
-transition mix  a_track=0 b_track=4  in=00:03:17.000 out=00:03:22.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:02:41.000 out=00:02:50.999 \
-transition mix  a_track=0 b_track=5  in=00:02:41.000 out=00:02:50.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=5 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:25.999 \
-transition mix  a_track=0 b_track=5  in=00:03:17.000 out=00:03:25.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:02:41.000 out=00:02:50.999 \
-transition mix  a_track=0 b_track=6  in=00:02:41.000 out=00:02:50.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=6 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:25.999 \
-transition mix  a_track=0 b_track=6  in=00:03:17.000 out=00:03:25.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=7 sliced_composite=1 distort=1 in=00:02:41.000 out=00:02:54.999 \
-transition mix  a_track=0 b_track=7  in=00:02:41.000 out=00:02:54.999 \
-transition composite geometry=0%/0%:0%x0% a_track=0 b_track=7 sliced_composite=1 distort=1 in=00:03:17.000 out=00:03:27.999 \
-transition mix  a_track=0 b_track=7  in=00:03:17.000 out=00:03:27.999 \
-consumer avformat:/eyinhe/record/pbvideo/af5335dd-e14c-4265-9611-5075fc559bf9.mp4 acodec=aac vcodec=libx264

**Comment by exceptiondc** [comment]
Where can I see the relevant documents“ https://www.mltframework.org/docs/melt/ I didn't find it in this link

**Comment by bmatherly** [comment]
https://www.mltframework.org/plugins/TransitionMix/

**Comment by exceptiondc** [comment]
thanks
