### ISSUE TITLE
mlt-7.16.0, melt, horrible audio while paused?

### ISSUE THREAD

**Issue by GerryHickman** [mltframework/mlt#924]
Simple playback using melt  
```
bin/melt avformat:/path/to/BBC_TWO_2020-08-03_1441.ts in=10 out=40
```
in mlt-7.12.0, it gets to the out point, the video stays on the last frame and the audio is silent  

in mlt-7.16.0, it gets to the out point, the video stays on the last frame and the audio makes a horrible noise, probably continuously playing the sample from the last frame?

**Comment by bmatherly** [comment]
The new behavior is a result of this change: https://github.com/mltframework/mlt/issues/906

You  can use terminate_on_pause=1

**Comment by GerryHickman** [comment]
Thanks for the update.
I don't want terminate_on_pause=1 in this case.
melt is one of the few players with meaningful frame stepping (forward and back).
I need to pause on frame 100 and then 150 to do a cut.

**Comment by bmatherly** [comment]
You can also disable audio scrubbing on the sdl2 consumer or disable audio altogether
https://mltframework.org/plugins/ConsumerSdl2/#scrub_audio
https://mltframework.org/plugins/ConsumerSdl2/#audio_off

**Comment by GerryHickman** [comment]
I had actually tried 'scrub_audio=0', and for simple playback it does fix the problem of the continuous audio when paused, but I want audio scrubbing to work, e.g. when frame stepping in 7.12.0, it plays the audio of just that one frame and stops, but in 7.16.0, it plays the audio of that one frame and keeps playing it...
