### ISSUE TITLE
Please help me,  I encountered issues while updating the version inside Docker

### ISSUE THREAD

**Issue by gebiWangshushu** [mltframework/mlt#926]
My program is running inside a Docker container. Here is the system information of my Docker:

```
Linux function-video-clip-5dbc799ddf-smn66 5.4.0-1107-azure #113~18.04.1-Ubuntu SMP Tue Apr 25 13:58:29 UTC 2023 x86_64 GNU/Linux

（ubuntu 18.04）
```

The latest version I can currently install is :  `6.24.0-1`.
![image](https://github.com/mltframework/mlt/assets/27838829/f8a40c56-d4ac-4ce2-81be-6414a631042a)

I would like to know how I can install version` 7.8 `or a newer version. 
Thank you.

**Comment by ddennedy** [comment]
You can use our docker image mltframework/melt in docker hub or GitHub. Or build it yourself using our Dockerfile.

**Comment by gebiWangshushu** [comment]
@ddennedy  That inspired me. Thank you very much.

**Comment by gebiWangshushu** [comment]
> You can use our docker image mltframework/melt in docker hub or GitHub. Or build it yourself using our Dockerfile.

That inspired me. Thank you very much.
