### ISSUE TITLE
MLT Chains break mlt_filter_get_length2

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#927]
We recently received several reports of effects not working anymore. After some investigation, I found the cause to be the switch from MLT producers to chains. Affected effects are those using the `mlt_filter_get_length2` function that is supposed to return the playtime of the producer the effect is applied on.

When the filter is attached to a producer, it works correctly, but when attached to a chain, it returns 2147483646, breaking the effects. And the list of effects using this function is quite long...

This can be reproduced by this command line:

`melt -producer test.mp4 in=100 out=300 -attach brightness start=0 end=1`

This fill fade from black to normal. But when used on a chain:

`melt -chain test.mp4 in=100 out=300 -attach brightness start=0 end=1`

It stays black. I had a look at the mlt_filter_get_length2 function:
https://github.com/mltframework/mlt/blob/master/src/framework/mlt_filter.c#L212

But I am not familiar enough with chains to understand how to fix. Let me know if I can help in any way

**Comment by ddennedy** [comment]
The timing on chains is different than producers:
a) You need to set in and out points
b) The in and out points are relative to the beginning of the clip, not the chain's in point
c) start and end properties are deprecated
