### ISSUE TITLE
Opencv tracking seems broke

### ISSUE THREAD

**Issue by guiodic** [mltframework/mlt#928]
MLT version: 
7.16.0

OpenCv version 4.8.0

MLT frontend: kdenlive 23.04.3

OS: Manjaro Linux unstable (so, basically Arch)

Da diverse vesioni di MLT/OpenCV/Kdenlive il tracciatore di movimento non funziona. Arriva al 99% e poi fallisce. In passato, per puro caso, mi sono accorto che usando opencv dal repository di CachyOS (compilato per x86_64_v3 e con flag -O3) funzionava. Questo però sembrava non bastare per la OpenCV 4.7. Inoltre ora CachyOS non riesce a compilare OpenCV, così ho provato a compilarla manualmente per v3 e con il flag -O3, ma non ha funzionato.

**Comment by ddennedy** [comment]
It works fine in Shotcut builds. This is a build problem, and not a MLT code one.
