### ISSUE TITLE
How to achieve audio loop playback

### ISSUE THREAD

**Issue by w-wj-07** [mltframework/mlt#937]
Assuming there are two tracks, one of which plays video and the other plays audio, I want to achieve a loop of audio playback until the video ends. How can I achieve this

**Comment by ddennedy** [comment]
Repeat the audio producer as many times as needed.

**Comment by w-wj-07** [comment]
Hi, when using MLT to overlay two videos and play them simultaneously, I referred to the "frei0r. cairoblend" used in the. mlt file exported by shotcut software. It looks like this.
    <transition id="transition">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="version">0.1</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="threads">0</property>
      <property name="disable">0</property>
    </transition>
Therefore, I wrote the following code, but the second line of code always reported an error. Would you like to know if the usage of this frei0r. cairoblend is correct, or if there are any other methods I would like to achieve video overlay and playback at the same time? Thank you very much～

Auto * transition_ V=new Mlt:: Transition (profile, "frei0r. cairoblend");
Field ->plant_ Transition (* transition_v, 0, 1);

**Comment by w-wj-07** [comment]
Thank you very much~,there is another problem , when using MLT to overlay two videos and play them simultaneously, I referred to the "frei0r. cairoblend" used in the. mlt file exported by shotcut software. It looks like this.
transition id="transition"
property name="a_track">1</property
property name="b_track">2</property
property name="version">0.1</property
property name="mlt_service">frei0r.cairoblend</property
property name="threads">0</property
property name="disable">0</property

Therefore, I wrote the following code, but the second line of code always reported an error. Would you like to know if the usage of this frei0r. cairoblend is correct, or if there are any other methods I would like to achieve video overlay and playback at the same time? Thank you very much～

Auto * transition_ V=new Mlt:: Transition (profile, "frei0r. cairoblend");
Field ->plant_ Transition (* transition_v, 0, 1);

**Comment by ddennedy** [comment]
Invalid bug report
