### ISSUE TITLE
MLT::Chain leaking memory

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#945]
Hi all,

While debugging an important memory usage in Kdenlive, I came upon a strange behavior and I think MLT::Chain is not properly closing the producer's data. I tested with the simple code below.

This is a simple loop, creating a producer, asks for an image then closing the producer. If I run this app, I get a rather stable memory usage between 380-410M.

But if I replace Mlt::Producer and instead use Mlt::Chain to build the producer, the app quickly consumes several Gigabytes of RAM. I am not sure exactly how to fix this, but any help is welcome as this issue prevents users to open recent project files because of the memory usage.

```
std::unique_ptr<Mlt::Repository> repository(Mlt::Factory::
Mlt::Profile profile("atsc_1080p_25");
int ow = 320;
int oh = 240;
mlt_image_format format = mlt_image_rgba;
for (int i = 0; i < 100; i++) {
    Mlt::Producer prod(profile, "avformat", "/media/video/4kSample.MP4");
    Mlt::Frame *frame = prod.get_frame();
    const uchar *imagedata = frame->get_image(format, ow, oh);
    delete frame;
}
```

**Comment by ddennedy** [comment]
```
--- src/framework/mlt_chain.c
+++ src/framework/mlt_chain.c
@@ -395,4 +395,6 @@ void mlt_chain_close(mlt_chain self)
             mlt_link_close(base->links[i]);
         free(base->links);
+        mlt_producer_close(base->source);
+        mlt_properties_close(base->source_parameters);
         mlt_profile_close(base->source_profile);
         free(base);
```
?

**Comment by bmatherly** [comment]
Proposed fix here with some tweaks above Dan's patch.
https://github.com/mltframework/mlt/pull/947

@j-b-m , can you test with your program?
