### ISSUE TITLE
On the issue of implementing video overlay

### ISSUE THREAD

**Issue by w-wj-07** [mltframework/mlt#946]
Hi, when using MLT to overlay two videos and play them simultaneously, I referred to the "frei0r. cairoblend" used in the. mlt file exported by shotcut software. It looks like this.
transition id="transition"
property name="a_track">1</property
property name="b_track">2</property
property name="version">0.1</property
property name="mlt_service">frei0r.cairoblend</property
property name="threads">0</property
property name="disable">0</property

Therefore, I wrote the following code, but the second line of code always reported an error. Would you like to know if the usage of this frei0r. cairoblend is correct, or if there are any other methods I would like to achieve video overlay and playback at the same time? Thank you very much～

Auto * transition_ V=new Mlt:: Transition (profile, "frei0r. cairoblend");
Field ->plant_ Transition (* transition_v, 0, 1);

**Comment by ddennedy** [comment]
Invalid bug report
