### ISSUE TITLE
Crash when avformat producer properties change

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#948]
SInce the last change to avformat probe (https://github.com/mltframework/mlt/commit/2266e5c8e06efb18f3f13f26f0e7b6147ba5a840), I now get a crash playing some MLT xml files. See backtrace below.
The problem happens on xml files where the aStream/vStream properties have not yet been set on producers.

in producer_avformat, producer_set_up_video calls pick_video_stream. The "vstream" property is missing, so it is set here:
https://github.com/mltframework/mlt/blob/master/src/modules/avformat/producer_avformat.c#L2853

And this triggers a property-change event, asking for a probe:
https://github.com/mltframework/mlt/blob/master/src/modules/avformat/producer_avformat.c#L1538
Crash happens here.

However in this special case, the video index didn't change. We want to define the vStream for future use, but a probe is not necessary.

My initial idea was to block the property-changed with something like this around line 2853:

`mlt_events_block(properties, self);`

Around the code setting the "vStream" property, but for some reason it didn't stop the call to property_changed.

Any thoughts ?
The crashing playlist I have contains some copyrighted content from a user, but if necessary I can probably prepare another MLT playlist reproducing the crash with my own material.

Crash log:

```
Thread 16 "melt" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa3fff6c0 (LWP 18589)]
___pthread_mutex_lock (mutex=0x348) at ./nptl/pthread_mutex_lock.c:80
80      ./nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt full
#0  ___pthread_mutex_lock (mutex=0x348) at ./nptl/pthread_mutex_lock.c:80
        type = <optimized out>
        __PRETTY_FUNCTION__ = "___pthread_mutex_lock"
        id = <optimized out>
#1  0x00007ffff7fa7416 in mlt_properties_lock (self=0x555555905600)
    at /home/six/git/mlt/src/framework/mlt_properties.c:2187
#2  0x00007ffff7fa3a47 in mlt_properties_find (self=0x555555905600, name=0x7ffff3ab85dd "_probe_complete")
    at /home/six/git/mlt/src/framework/mlt_properties.c:542
        list = 0x0
        value = 0x0
        key = 10
        i = -2144064000
#3  0x00007ffff7fa49b2 in mlt_properties_get_int
    (self=0x555555905600, name=0x7ffff3ab85dd "_probe_complete")
    at /home/six/git/mlt/src/framework/mlt_properties.c:1028
        result = 0
        value = 0x555555ea6880
#4  0x00007ffff3a9c991 in property_changed
    (owner=0x555555eea380, self=0x555555ee9c70, name=0x7ffff3ab7dd3 "vstream")
    at /home/six/git/mlt/src/modules/avformat/producer_avformat.c:1539
        properties = 0x555555905600
#5  0x00007ffff7f8fd40 in mlt_events_fire
    (self=0x555555eea380, id=0x7ffff7fb5c52 "property-changed", event_data=...)
    at /home/six/git/mlt/src/framework/mlt_events.c:211
        event = 0x555555d76540
        i = 1
--Type <RET> for more, q to quit, c to continue without paging--
        list = 0x555555eea7d0
        listeners = 0x555555eeb3d0
        temp = "list:property-changed\000\377\377Ft\372\367\377\177\000\000\000\000\000\000\001\000\000\000\200\243\356UUU\000\000з\377\243\377\177\000\000\035=\372\367\377\177\000\000\323}\253\363\377\177\000\000\200\243\356UUU\000\000\323}\253\363\377\177\000\000\000\000\000\000\000\000\000\000\020\244\356UUU\000\000\000\000\000\000\000\000\000\000\340\267\377\243\377\177\000\000\323}\253\363\377\177\000"
        result = 1
        events = 0x555555eea7b0
#6  0x00007ffff7fa3daf in fire_property_changed (self=0x555555eea380, name=0x7ffff3ab7dd3 "vstream")
    at /home/six/git/mlt/src/framework/mlt_properties.c:622
#7  0x00007ffff7fa4ab1 in mlt_properties_set_int (self=0x555555eea380, name=0x7ffff3ab7dd3 "vstream", value=0)
    at /home/six/git/mlt/src/framework/mlt_properties.c:1063
        error = 0
        property = 0x7fff9800f630
#8  0x00007ffff3aa0ebf in pick_video_stream (self=0x7fff557beee0) at /home/six/git/mlt/src/modules/avformat/producer_avformat.c:2853
        properties = 0x555555eea380
        absolute_index = 0
#9  0x00007ffff3aa100c in producer_set_up_video (self=0x7fff557beee0, frame=0x7fff55631e00)
    at /home/six/git/mlt/src/modules/avformat/producer_avformat.c:2900
        producer = 0x555555eea380
        properties = 0x555555eea380
        context = 0x7fff555b9f80
        index = 0
        unlock_needed = 1
        frame_properties = 0x7fff55631e00
#10 0x00007ffff3aa42f1 in producer_get_frame (producer=0x555555eea380, frame=0x7fff9800ba40, index=0)
    at /home/six/git/mlt/src/modules/avformat/producer_avformat.c:3776
        service = 0x555555eea380
        cache_item = 0x555555d763b0

```

**Comment by bmatherly** [comment]
It looks like memory corruption since some of the variables have non-sensical values. Can you provide a minimal project to reproduce the problem? Also, can you reproduce it in melt? I do not have a KDENLIVE development environment.

**Comment by j-b-m** [comment]
Yes it is reproducible in melt. I will prepare a reproducible playlist with sources for testing.

**Comment by j-b-m** [comment]
The original playlist was rather complex so it took me some time to get a reduced project for testing.
The MLT playlist is crash-test.mlt (renamed to .txt allow attaching it here)
It is not as simple as I wished, but removing any clip in it fixes the crash. It consists of 5 instances of the same test.mp4 clip (also attached here, that is a simple color clip rendered with an audio track). Source clip does not really seem to matter.
The 5 instances of the clip are dispatched on several tracks, some with only audio, some with only video.
Simply trying to play the file through melt crashes on startup with the same log as pasted above:

melt crash-test.mlt

The crash appears with this commit: https://github.com/mltframework/mlt/commit/2266e5c8e06efb18f3f13f26f0e7b6147ba5a840

Reverting to an MLT version before this commit doesn't crash...
Hope it helps.

https://github.com/mltframework/mlt/assets/108252/b862d6f1-fe21-421d-97f3-7821865b1387

[crash-test.txt](https://github.com/mltframework/mlt/files/12545889/crash-test.txt)

**Comment by bmatherly** [comment]
Thanks for the test project. Can you please test this proposed fix: https://github.com/mltframework/mlt/pull/950
