### ISSUE TITLE
MLT geometric shape support

### ISSUE THREAD

**Issue by Augadh1** [mltframework/mlt#949]
Hi,

I am looking how to create shapes (rectangle, triangle, polygon) using mlt.
The requirement is shape can have fill colour, stroke properties, shadow properties.
I tried mask filter but it does not support stroke and shadow.

Can you help me if there is anything in mlt which can help me?
is it possible to have these shape generated by shader code or any mlt support any paint tool?

What is the best way to achieve this?

**Comment by ddennedy** [comment]
This tracker is for bug reports only. 
You can create shapes using the glaxnimate module and any of the formats it supports. See Shotcut official builds that includes Glaxnimate.
