### ISSUE TITLE
How to solve the aliasing problem in video mixing process？

### ISSUE THREAD

**Issue by w-wj-07** [mltframework/mlt#952]
Hi all～，when I am using frei0r. cairoblend to overlay two videos, for example, the size defined in the profile is 1920x1080. I found that If I adjust the size of the video to be inconsistent with the size defined in the profile, for example, if I crop the video to 1280x720, the edges of the video will appear jagged when playing. When the other video is played, the jagged shape of the video disappears and returns to normal. Similarly, if I rotate the video, it will also have jagged shapes during playback. I understand that the rotation also causes the video size and profile. Here are the video renderings，You can see jagged edges on the character, and when another video is played, the jagged shape disappears
<img width="536" alt="pic" src="https://github.com/mltframework/mlt/assets/75413574/4ad08bd2-c177-4651-8d25-6a45864bc36d">
. How can I solve this problem?Looking forward to receiving your reply～

https://github.com/mltframework/mlt/assets/75413574/ec087170-d7ff-4cf1-9078-ea4a6176cd38

https://github.com/mltframework/mlt/assets/75413574/5143c820-dc72-4478-97c6-7fddc9f7215c

**Comment by ddennedy** [comment]
Set the `rescale` [property](https://www.mltframework.org/doxygen/properties.html) for interpolation algorithm on your consumer to "bilinear" or "nearest". Some of the consumers override the MLT framework base default value of "bilinear" with its own default value of "nearest", which means no interpolation.
