### ISSUE TITLE
Watermark Chinese garbled code

### ISSUE THREAD

**Issue by exceptiondc** [mltframework/mlt#953]
How can I solve the problem of using the watermark function of the following script to generate Chinese garbled code?
melt \
-profile hdv_720_25p \
colour:black out=349 length=349 \
-track  \
test.mp4 in=0 out=249 -blank 0 -attach watermark:"+中文d中文的-1001.txt" \
test1.mp4 in=0 out=100 -blank 0 -attach watermark:"+中文d测试-1002.txt" \
-transition composite:25%/25%:50%x50% in=0 out=349 a_track=0 b_track=1 sliced_composite=1 \
-consumer avformat:/home/eyinhe/playback/temp/001.mp4 acodec=aac vcodec=libx264

![image](https://github.com/mltframework/mlt/assets/25631107/729cbf54-a4bf-4db9-854b-2b3813f7718a)

**Comment by ddennedy** [comment]
Not a valid bug report, and image added is useless. This is not a question and  answer forum.

**Comment by exceptiondc** [comment]
@ddennedy Can't you see my picture? I have re uploaded the image, which is generated through the script watermark function of Melt. The content generated after including Chinese is garbled，In the upper left corner area。
![image](https://github.com/mltframework/mlt/assets/25631107/83aedbc4-e2e8-47ae-a25f-6d07e81dad3a)
