### ISSUE TITLE
Video cannot be played on IOS phones

### ISSUE THREAD

**Issue by w-wj-07** [mltframework/mlt#954]
Hi～，why do some of the videos I create using MLT not play on certain mobile phones, especially for Apple iOS phones. The video format is MP4, I would like to know if the default output of MLT for. MP4 videos is profile high level 4.0? I checked and found that Apple iOS only supports video playback with profile high level 4.2.What parameters do I need to configure to make the video play on the IOS phone.Thank you very much!

**Comment by ddennedy** [comment]
Not a bug and not a bug report. This is not a question and answer forum.
