### ISSUE TITLE
Can't build on MSVC 2019

### ISSUE THREAD

**Issue by TyrasNistru** [mltframework/mlt#955]
Hi!

I'm trying to build MLT for MSVC 2019. The CMAKE part runs OK, but building the sln generated fails with a lot of errors. Even trying to build the "mlt" project fails:

The errors persist even if I enable C11 on the project settings.

What to do?

OS: Windows 11 Pro 22H2 build 22621.2283
Compiler: MSVC 2019 (Latest updaste)
MLT Version: 7.18.0,

[buildlog.txt](https://github.com/mltframework/mlt/files/12701997/buildlog.txt)

**Comment by ddennedy** [comment]
This is not a bug. This compiler is not targeted or tested. Not every CPU architecture and compiler in existence is simply going to work. If you want to use this compiler, figure out the changes yourself, and submit a pull request.
