### ISSUE TITLE
rtsp_transport ignored in avformat producer

### ISSUE THREAD

**Issue by matiaspl** [mltframework/mlt#96]
I've a problem with rtmp camera stream ingest - it seems that whatever the rtsp_transport value I set, it always uses UDP (at least from what I can tell from the logs). This doesn't work with some cameras not implementing ie, PAUSE command, and the auto fallback doesn't seem to work either (neither does setting the flag prefer_tcp in rtsp_flags). Is there something to double check?

Edit: tested under Ubuntu LTS 14.04, melt from the main repository.

**Comment by ddennedy** [comment]
MLT uses libavformat for this. It all depends on who provided your libavformat, its version, and how it was built. Also, you may need to supply parameters on the URL query string instead of on the producer. Also none of MLT maintainers have convenient access to RTSP let alone a TCP variant of it to provide much assistance or debugging. If you want to get anywhere with this you should provide info on how to create such a stream and exactly how you are trying to read it with melt. If it is not convenient or obvious, I doubt anyone wants to address this bug report.

**Comment by ddennedy** [comment]
Some tips:
Run `melt -query producer=avformat` to see if that libavformat parameter exists in your version.

Try to preface the URL with 'avformat-novalidate'. By default, MLT avformat producer opens the resource upon construction of the object to verify it can actually be used and gather basic info such as duration, default stream indexes, and seekable. If it is not seekable, then the resource is kept open, which likely means MLT properties after construction might not have any effect. "avformat-novalidate" skips that step, and you ought to be able to then set additional MLT properties needed prior to the actual stream open.

**Comment by matiaspl** [comment]
The parameter existed in my version and unfortunately avformat-novalidate tended to segfault with the versions I used. Now I'm experimenting with main git branch and haven't tried yet. While I have your attention - is there any way to make melt+avcodec send frames as soon as they are processed? I'm sending the data (sample clip) to a rtmp server and the data arrives only after the whole clip is processed or the process is interrupted by pressing 'q' or 'ctrl-c'.

**Comment by matiaspl** [comment]
As you said it's all in the ffmpeg version. To sum up what I've learned - with the latest git version some streaming inputs work (i.e. UDP, HTTP), some don't (RTMP) and I couldn't find any key to what doesn't work and why. And avformat-novalidate doesn't work with with UDP at all. All the streams I tested work fine with the standalone ffmpeg executable built alongside with melt.

**Comment by ddennedy** [comment]
No one is going to fix this for you. Submit patches, but this is a horrible bug report as written; so, I am closing it. For example, what is an "rtmp camera" and what does it have to do with RTSP? It is not even clear if this is about streaming input or output.
