### ISSUE TITLE
[SVT-AV1] MLT does not seem to support any configuration done via Kdenlive interface except "preset".

### ISSUE THREAD

**Issue by EligoQuodVideo** [mltframework/mlt#969]
This message has been translated into English automatically, so I'm sorry for any errors.

As I say in the header, MLT does not take into consideration the parameters entered when using the SVT-AV1 (libsvtav1 from FFMPEG) encoding. "preset=X", do seem to be "obeyed", but adding any other such as "film-grain-denoise=X", "pix_fmt=yuv420p10le", etc, causes everything entered by the user to be ignored, even "preset=X", which works if it is the only thing entered, and the file is encoded with the default values.

I'm using mlt-7.22.0 on Linux 6.6.4, QT 5.15.11, KDE 5.27.10 and Kdenlive 23.08.4.

Best regards.

**Comment by ddennedy** [comment]
This is not a MLT bug. It might be a build problem, but I guarantee you that pix_fmt works as I use it all the time in Shotcut.  You need to prove it is a MLT problem by using a melt command line and showing that SVT-AV1 is included in your build and with 10-bit support. Then, you can reopen this.
