### ISSUE TITLE
sdl consumer may require SDL12COMPAT_NO_QUIT_VIDEO 

### ISSUE THREAD

**Issue by schauveau** [mltframework/mlt#971]
SDL1 is often being replaced by https://github.com/libsdl-org/sdl12-compat , a compatibility wrapper around SDL2. 

Applications using the sdl consumer may experience some problems as shown in this Flowblade bug report https://github.com/jliljebl/flowblade/issues/1134

The solution appears to be SDL12COMPAT_NO_QUIT_VIDEO=1, a currently undocumented environment variable of sdl12-compat.  https://github.com/libsdl-org/sdl12-compat/issues/329

**Comment by ddennedy** [comment]
The `sdl` consumer is going to be deprecated. That does not mean immediate removal, but the writing is on the wall... that some day.

@jliljebl  It does not like it would be very difficult for you to make and test a simple change to move `SDL_Quit()` from `consumer_stop()` to `consumer_close()`. Alternatively, it looks like you can set the consumer property `sdl_started`=1 before calling `stop()` on it from python to avoid the error. I am not in a position to do this. Someone who cares about `sdl` should.

**Comment by jliljebl** [comment]
Ok, I'll work on this in October and see how this goes. I'm moving to a new place in a few weeks and that will probably eat up a lot of my time until maybe second week of October.

**Comment by ddennedy** [comment]
Fixed in a53c4fc1c6dbc837a90a8dbcead4706245e1af22
