### ISSUE TITLE
How to change the spacing of wrapped text?

### ISSUE THREAD

**Issue by wfd2022** [mltframework/mlt#977]
Hey guys,
We are using the dynamictext filter to display text provided by users on the video. If the text wraps to a new line, the spacing becomes very large. Is it possible to adjust or reduce this spacing?

Thanks in advance
![image](https://github.com/mltframework/mlt/assets/91302457/68227d1a-c890-4c6a-aa1f-b7e6745d2ad8)

**Comment by ddennedy** [comment]
This is not a bug.

**Comment by wfd2022** [comment]
> This is not a bug.

The line spacing seems to be fixed. Is it possible to change it?

**Comment by wfd2022** [comment]
> We are using the dynamictext filter to display text provided by users on the video. If the text wraps to a new line, the spacing becomes very large. Is it possible to adjust or reduce this spacing?

By the way, we encountered a bug while using the dynamictext filter to display text on the video. The weight attribute of the font doesn't work; changing its value has no effect. This has been tested in both the melt command line and the code.
