### ISSUE TITLE
[producer_xml] failed to load filter "affine"

### ISSUE THREAD

**Issue by laimouren** [mltframework/mlt#987]
When I was parsing the MLT file, I encountered a problem where I couldn't import the filter affine. 
I'm not sure if it's because my MLT is missing some dependency libraries. 
How can I troubleshoot and solve this problem? Thank you for your answer.

**Comment by laimouren** [comment]
<img width="575" alt="image" src="https://github.com/mltframework/mlt/assets/59273681/e457a997-f96f-44b8-bd60-61c85cec6185">

**Comment by bmatherly** [comment]
If you run

`melt -query filters | grep affine`

You should see a result:

`- affine`

If you do not see that result, then you have not built the affine filter or you are not linking to it for some reason.
